### ISSUE TITLE
TF1 is not working anymore

### ISSUE THREAD

**Issue by MartinDelille** [ytdl-org/youtube-dl#30997] opened 2022-06-02 19:05 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl "https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-le-totem-maudit-du-31-mai-2022-episode-14-31800896.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-le-totem-maudit-du-31-mai-2022-episode-14-31800896.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] koh-lanta-le-totem-maudit-du-31-mai-2022-episode-14-31800896: Downloading JSON metadata
[wat.tv] 13885430: Downloading JSON metadata
[wat.tv] 13885430: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[wat.tv] 13885430: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Unauthorized access.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/wat.py", line 96, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

This used to work but since a few days it seems that something change on the service and I have the error displayed in the log.

**Comment by ivunchata** [comment] 2022-07-20 20:57
This is not duplicate of https://github.com/ytdl-org/youtube-dl/issues/30959 which is for attempting to download the livestream.
TF1 have recently closed their replays and require the user to log in in order to watch them hence the 403 from above.

**Comment by dirkf** [comment] 2022-07-21 10:30
The report may not be the same, but the underlying issue was.

**Comment by dirkf** [comment] 2022-07-21 10:31
Resolved in https://github.com/dirkf/youtube-dl/commit/d2d90874d4008238c79e09b3967309809cec037a.

**Closed by dirkf** 2022-07-21 10:31 UTC
Labels: duplicate
