### ISSUE TITLE
Downloading webpage ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by vrysa** [ytdl-org/youtube-dl#32052] opened 2023-04-17 12:22 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

youtube-dl https://www.youtube.com/watch?v=JYNyQcblzgI
[youtube] JYNyQcblzgI: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tevaum** [comment] 2023-04-17 12:43
This is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by szabgab** [comment] 2023-04-17 12:54
This seems to be solved in the most recent source code.

* Install python
* Install this package: `pip install git+https://github.com/ytdl-org/youtube-dl`
* This way it worked for me.

**Comment by vrysa** [comment] 2023-04-17 14:52
but i was able to use it.

**Comment by vrysa** [comment] 2023-04-17 14:54
When I did the following:
1.    Install python
2.   Install this package: pip install git+https://github.com/ytdl-org/youtube-dl
2.2 It was complaining about pip3.8 file not available in usr/bin location , then I moved the file pip3.8 from usr/local/bin/ to usr/bin and it worked fine.

**Comment by ujjwal-45** [comment] 2023-04-17 16:55
@szabgab  I am also having same issue.

**Comment by ryjones** [comment] 2023-04-17 17:57
```youtube-dl --verbose "11Yr3YhdUrE"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '11Yr3YhdUrE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ac0663ae5
[debug] Python version 3.10.11 (CPython) - macOS-13.3.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] 11Yr3YhdUrE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Closed** 2023-04-17 19:01 UTC
