### ISSUE TITLE
Unable to download Udemy paid lectures offline 

### ISSUE THREAD

**Issue by siddhesh180401** [ytdl-org/youtube-dl#31482] opened 2023-01-21 10:28 UTC
## Checklist

- [✓] I'm reporting a broken site support issue
- [✓] I've verified that I'm running youtube-dl version **2021.12.17**
- [✓] I've checked that all provided URLs are alive and playable in a browser
- [✓] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✓] I've searched the bugtracker for similar bug reports including closed ones
- [✓] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
When i try to download the udemy lecture's it says 
```
  C:\Users\Siddhesh\Music\youtube-dl>youtube-dl -U
  youtube-dl is up-to-date (2021.12.17)

  C:\Users\Siddhesh\Music\youtube-dl>youtube-dl.exe https://www.udemy.com/course/qlik-sense-certification-the-complete- 
  practical-course/learn/lecture/23277012#overview
  [udemy:course] course: Downloading webpage
  ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt- 
  dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose 
  flag and include its complete output.
```

**Comment by dirkf** [comment] 2023-01-21 17:45
Use `--cookies ...` with cookies exported from your logged-in browser session that can show the course videos.

If that fails, duplicate of #29915.

See [why failure is likely](https://github.com/ytdl-org/youtube-dl/issues/29705#issuecomment-1110932428).

**Comment by dirkf** [comment] 2023-01-28 16:36
Closing for lack of response.

**Closed by dirkf** 2023-01-28 16:36 UTC

**Comment by siddhesh180401** [comment] 2023-01-29 17:38
Where can i find the cookies

**Comment by siddhesh180401** [comment] 2023-01-29 17:39
Please make a video for how to download Udemy DRM-protected content. Please

**Comment by dirkf** [comment] 2023-01-29 21:31
>Where can i find the cookies

Read the Manual regarding cookies.

>Please make a video for how to download Udemy DRM-protected content. ...

You can make it yourself.

Scene: some Udemy user sitting in front of a computer.

The anxious Udemy user looks at the screen and turns off the computer with a sad shake of the head, turns to camera, and says "I give up -- it's impossible."

Ends.
