### ISSUE TITLE
💰 How can I donate to support developers?

### ISSUE THREAD

**Issue by TerrorJacktyl** [ytdl-org/youtube-dl#32980] opened 2024-11-24 04:23 UTC
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

How can I donate to support this project?

youtube-dl has done wonders for me. Notably, I can intentionally download videos for times where I'm offline (or being a scab living off low data) and avoid getting sucked into doomwatching. While I take a break from software, it's a great motivator to keep up command-line usage.

I was really surprised not to see any mentions of a donate link anywhere. Is there something in the license that forbids donation to this project?

If donations are not allowed officially, surely there's some *other* way to support the project?

Thank you for all your hard work!

**Comment by dirkf** [comment] 2024-11-24 19:30
You can donate to _yt-dlp_ where a lot of new development is done that's reused here. Or, if you enjoy drudgery, help out with issues and PRs here.

**Comment by dirkf** [comment] 2024-11-24 19:39
Also, basically duplicate of #5945, with historical comments.

**Closed by dirkf** 2024-11-24 19:39 UTC
Labels: question

**Comment by TerrorJacktyl** [comment] 2024-11-25 02:50
Sorry, I should have scrolled more on the first issues page.

I tried the donation link [listed here](https://github.com/ytdl-org/youtube-dl/issues/10510#issuecomment-243806489), but it's 404 now. Is there a new donation link?

> Or, if you enjoy drudgery, help out with issues and PRs here.

I'm currently taking a break from programming (especially untyped languages) for my sanity. I'll opt to wait for a donation link instead. Thank you for your services 🫡
