### ISSUE TITLE
403 error while downloading from pluralsight

### ISSUE THREAD

**Issue by ukreddy-erwin** [ytdl-org/youtube-dl#29895] opened 2021-09-01 06:16 UTC
From windows powershell/cmd

youtube-dl --username "*******@gmail.com" --password "******" --verbose --sleep-interval 200 "https://app.pluralsight.com/library/courses/building-custom-github-actions"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '--sleep-interval', '200', 'https://app.pluralsight.com/library/courses/building-custom-github-actions']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] building-custom-github-actions: Downloading JSON metadata
[download] Downloading playlist: Building Custom GitHub Actions
[pluralsight:course] playlist Building Custom GitHub Actions: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\program files\python39\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\program files\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\program files\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\program files\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dirkf** [comment] 2022-01-18 23:42
Duplicate of #29776.

**Closed** 2022-02-07 12:55 UTC
Labels: duplicate
