### ISSUE TITLE
Download speed is extremely slow

### ISSUE THREAD

**Issue by erickulcyk** [ytdl-org/youtube-dl#31374] opened 2022-11-21 18:39 UTC
Running on Windows 11, I get about 14fps trying to download a sample video.  Not sure if there is some option I need to pass to make it go faster?  I would expect at least the 30fps that the video is encoded in, and hopefully a lot more.

youtube-dl https://youtu.be/1AbfRENy3OQ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/1AbfRENy3OQ', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 1AbfRENy3OQ: Downloading webpage
[youtube] 1AbfRENy3OQ: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://rr4---sn-nx5s7n7d.googlevideo.com/videoplayback?expire=1669077364&ei=FMV7Y7akLdXJkwbsoo4w&ip=73.225.60.28&id=o-AJkeMcD0yURgRRSPjIGhzAbQWx04_Pf9I-NO0jcDoThZ&itag=22&source=youtube&requiressl=yes&mh=SX&mm=31%2C29&mn=sn-nx5s7n7d%2Csn-nx57ynse&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1968750&vprv=1&mime=video%2Fmp4&ns=Ye84WySQUjzwgyTy4DMhuv4J&cnr=14&ratebypass=yes&dur=186.734&lmt=1547283352258659&mt=1669055386&fvip=2&fexp=24001373%2C24007246&c=WEB&txp=2211222&n=IlqwFyz6AFFPumIDn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKSuSEegyke_NxqLFIuh-ItLSm_3vS5V9WrSPx8ep4XLAiBJaoMmHWMYgkCUBsIiRsYXtyB6vrBHqsJPwo_mk8NxMA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAN8ZVtVD0zoe8XwNXUnjuzUTm6lrHTlxouZqG3nC2bZ2AiB0ma4OU-9IYUAVCIInuHF1AJBfXbZ82q75YFnO88CRSQ%3D%3D'
[download] Resuming download at byte 14938229
[download] Destination: stereo inertial based autonomous UAV navigation in challenging sunlight-1AbfRENy3OQ.mp4
[download]  71.1% of 24.90MiB at 76.73KiB/s ETA 01:36

**Comment by dirkf** [comment] 2022-11-21 19:43
Duplicate of #29326 (etc).

For now, you need to install the program from the git master branch, as discussed in the links from the above, or there are forks with a Windows .exe.

**Closed by dirkf** 2022-11-21 19:43 UTC

**Comment by erickulcyk** [comment] 2022-11-22 19:56
@dirkf thanks.  How often are the pip/conda repos updated?  Seems odd that this was marked fixed almost a year ago and the default versions still have the bug.

**Comment by dirkf** [comment] 2022-11-22 22:28
They get updated when a new release is made (well, TBH I only assume that wrt Conda, having not done it yet). https://github.com/ytdl-org/youtube-dl/issues/28859#issuecomment-1158188788 applies.
