### ISSUE TITLE
[YouTube] default search fails with URL encoding

### ISSUE THREAD

**Issue by harvey100** [ytdl-org/youtube-dl#31561] opened 2023-02-17 23:06 UTC
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by kim3k** [comment] 2023-02-17 23:14
its not working with age restricted videos, at least not on youtube.. tried with cookies. im using python. YDL_OPTION { 'cookiefile' : 'cookies.txt' }.. at least not for me. I used Get cookies.txt to extract cookies.

**Comment by yanquan2020** [comment] 2023-02-18 00:04
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Vangelis66** [comment] 2023-02-18 00:38
@yanquan2020: See #31530 😉

**Comment by dirkf** [comment] 2023-02-18 03:28
OK, duplicate of that issue.

**Comment by kim3k** [comment] 2023-02-19 01:35
i updated to latest Youtube-dl-master and it fixed the age restriction. (Thank you) 
BUT, now the search results from YTsearch is REALLY bad. if i YTsearch miley cyrus flowers, i get miley cyrus - flowers 10Hour version etc.. 
One more is if i YTsearch for "værsågod", what i except getting is this: 
"https://www.youtube.com/watch?v=3Ougb9F0Bd4" <-- correct one as i got with the older version
And what i get is this:
"https://www.youtube.com/watch?v=upAuXLjTORw" <-- no idea what this is.
I did not have this problem with the older version of 2021.12.17. Any ideas? :)
I'm using this for a private discord music-bot :)

**Comment by dirkf** [comment] 2023-02-19 01:57
This is what I get, matching what you expect:
```console
 $ python -m youtube_dl --get-filename 'ytsearch5:værsågod'
Værsågod-3Ougb9F0Bd4.webm
Televerket Værsågod--sG6YcITRIg.mp4
Hotell Smarty, værsågod.... - Harald Heide-Steen Jr. (1985)-YSX85hI7xRg.mp4
Værsågod øvelser-eoXTyfgEF4Y.mp4
Værsågod, ferdig tråkka-fRUP-jv2WUo.webm
```
But with 2021.12.17:
```
$ youtube-dl --get-filename 'ytsearch5:værsågod'
ERROR: Signature extraction failed: Traceback (most recent call last):
...
```

**Comment by dirkf** [comment] 2023-02-19 01:58
Your unwanted video is:
```
Vinyl Værsågod - Teaser 1-upAuXLjTORw.mp4
```

**Comment by JohnTRL** [comment] 2023-02-19 11:16
Y'all, go /youtube_dl/extractor/common.py.
Line 983, change: `fatal=True` to `fatal=False`

**Comment by kim3k** [comment] 2023-02-19 12:03
Yes. when i do the same command i get the correct video in console. but that is not the song that starts to play.. hmm, only happen with the newest youtube-dl..
here is verbose:

python -m youtube_dl --verbose --get-filename 'ytsearch5:værsågod'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--get-filename', 'ytsearch5:værsågod']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
Værsågod-3Ougb9F0Bd4.webm
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
Televerket Værsågod--sG6YcITRIg.mp4
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
Hotell Smarty, værsågod.... - Harald Heide-Steen Jr. (1985)-YSX85hI7xRg.mp4
[debug] Default format spec: bestvideo+bestaudio/best
Værsågod-5UpTGHUjc0s.webm
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
Oslo Nye Centralteatret - Jacobsen, værsågod!--6gPZORjk1o.mp

**Comment by dirkf** [comment] 2023-02-19 12:07
How does it "start to play"?

Eg, `python -m youtube_dl -o - 'ytsearch5:værsågod' | mpv -` ?

**Comment by kim3k** [comment] 2023-02-19 12:23
u mean like this?:

    url = query if query.startswith("http") else None
    if not url:
        YDL_OPTIONS = {
            'format': "bestaudio",
            'noplaylist': True,
            'default_search': 'ytsearch',
            'quiet': True,
            'cachedir': False,
            'nocheckcertificate': True,
            'force-ipv4': True
        }
        with youtube_dl.YoutubeDL(YDL_OPTIONS) as ydl:
            result = ydl.extract_info(query, download=False) ?

**Comment by kim3k** [comment] 2023-02-19 13:19
`[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[download] Downloading playlist: v%C3%A6rs%C3%A5god
[youtube:search] query "v%C3%A6rs%C3%A5god": Downloading page 1
[youtube:search] playlist v%C3%A6rs%C3%A5god: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] upAuXLjTORw: Downloading webpage
[youtube] Downloading just video upAuXLjTORw because of --no-playlist
[youtube] upAuXLjTORw: Downloading player 11e3a4ec
[debug] [youtube] Decrypted nsig bmJ9b08pz8oLbzu4 => 8UCMq4Hkcx2s3g
[debug] [youtube] Decrypted nsig eMRz851GeDs7ynXj => nctpjSgfD7FHTA
[download] Finished downloading playlist: v%C3%A6rs%C3%A5god
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Connecting to voice...
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Starting voice handshake... (connection attempt 1)
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Voice handshake complete. Endpoint found stockholm8901.discord.media
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] upAuXLjTORw: Downloading webpage
[youtube] Downloading just video upAuXLjTORw because of --no-playlist
[youtube] upAuXLjTORw: Downloading player 11e3a4ec
[debug] [youtube] Decrypted nsig B_QfIQnZqzPGDyBK => Ob58VCtGTs_F9g
[debug] [youtube] Decrypted nsig coF5BwCoyHCffTa6 => -QBLwyxn3soi4Q
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] videoplayback?expire=1676834262&ei=diHyY4XRAYSB7QSbp6LoDw&ip=109.247.185.206&id=o-ACvFrJAeJpeEc9ze8dU0jQjQTlLlZsApvdQYO8CYhyZF&itag=249&source=youtube&requiressl=yes&mh=pn&mm=31,29&mn=sn-5aupcvm-n8bz,sn-5goeenes&ms=au,rdu&mv=m&mvi=3&pcm2cms=yes&pl=20&initcwndbps=3070000&vprv=1&mime=audio/webm&ns=1I3uw9cM1bhPKmKaFyF-_aEL&gir=yes&clen=764263&dur=124: Requesting header`

**Comment by kim3k** [comment] 2023-02-19 13:19
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[download] Downloading playlist: v%C3%A6rs%C3%A5god
[youtube:search] query "v%C3%A6rs%C3%A5god": Downloading page 1
[youtube:search] playlist v%C3%A6rs%C3%A5god: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] upAuXLjTORw: Downloading webpage
[youtube] Downloading just video upAuXLjTORw because of --no-playlist
[youtube] upAuXLjTORw: Downloading player 11e3a4ec
[debug] [youtube] Decrypted nsig bmJ9b08pz8oLbzu4 => 8UCMq4Hkcx2s3g
[debug] [youtube] Decrypted nsig eMRz851GeDs7ynXj => nctpjSgfD7FHTA
[download] Finished downloading playlist: v%C3%A6rs%C3%A5god
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Connecting to voice...
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Starting voice handshake... (connection attempt 1)
[2023-02-19 14:17:40] [INFO    ] discord.voice_client: Voice handshake complete. Endpoint found stockholm8901.discord.media
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] upAuXLjTORw: Downloading webpage
[youtube] Downloading just video upAuXLjTORw because of --no-playlist
[youtube] upAuXLjTORw: Downloading player 11e3a4ec
[debug] [youtube] Decrypted nsig B_QfIQnZqzPGDyBK => Ob58VCtGTs_F9g
[debug] [youtube] Decrypted nsig coF5BwCoyHCffTa6 => -QBLwyxn3soi4Q
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg 2023-01-16-git-01f46f18db-full_build-www.gyan.dev, ffprobe 2023-01-16-git-01f46f18db-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] videoplayback?expire=1676834262&ei=diHyY4XRAYSB7QSbp6LoDw&ip=109.247.185.206&id=o-ACvFrJAeJpeEc9ze8dU0jQjQTlLlZsApvdQYO8CYhyZF&itag=249&source=youtube&requiressl=yes&mh=pn&mm=31,29&mn=sn-5aupcvm-n8bz,sn-5goeenes&ms=au,rdu&mv=m&mvi=3&pcm2cms=yes&pl=20&initcwndbps=3070000&vprv=1&mime=audio/webm&ns=1I3uw9cM1bhPKmKaFyF-_aEL&gir=yes&clen=764263&dur=124: Requesting header

**Comment by dirkf** [comment] 2023-02-19 13:36
This doesn't reveal with what command-line/parameter dict yt-dl was invoked? In particular the `URL`.

**Comment by kim3k** [comment] 2023-02-19 16:11
When I use youtube_dl to search for a song without a URL, it will use the default_search option to search YouTube for the query im provide (in this case "værsågod". The query can be a string representing the name of the song, artist, or any relevant keywords.

Here's an example command-line that youtube-dl uses when performing a default search:


youtube-dl "ytsearch:my search query"
So, in the code, the youtube_dl command will use the options specified in the YDL_OPTIONS dictionary and the query parameter. If the query starts with "http", it will use the URL directly. Otherwise, it will use default_search to search for the query on YouTube.

**Comment by dirkf** [comment] 2023-02-20 04:52
With (roughly) your code and also with `--default-search ...` on the command line I also get this file:
```
Audi RS6 v Tesla Model 3 Performance  - DRAG RACE _ICE vs EV-gKT-x1wJpTY.webm
```
This is because the actual search being performed is `ytsearch:v%C3%A6rs%C3%A5god`. The query term is getting URL-encoded as it's passed through yt-dl. Now of course if everyone would stick to ASCII alphanumeric searches that would fine, but then there are people who insist on using `æ` and `å` and such-like, not mention the whole of China, etc.

The default search "URL" is constructed in the generic extractor and redirected through an `info_dict` with `'_type': 'url'`. yt-dl calls `sanitize_url()` on the `info_dict['url']` when processing this type of extractor result. This causes the URL encoding.

A solution could be to pass the search terms using the `smuggle_url()/unsmuggle_url()` mechanism. I'll check this further.

**Comment by dirkf** [comment] 2023-02-20 05:21
Fixed in yt-dlp with commit bc6b9bcd6554c10aa321cbfe151272e0df1a869b, so we should pull that.

**Comment by kim3k** [comment] 2023-02-20 19:15
is there a way for me to get it to my youtube-dl or is bigger changes that need to be done? :)
tried to change those lines alone, but did break core.py

**Comment by dirkf** [comment] 2023-02-20 20:30
This is the working fix that I made out of the yt-dlp commit. You don't need to modify `test/test_utils.py` or `youtube_dl/extractor/generic.py` for the fix: they're just extra tests.
```diff
commit 1d3751c3fe50b203d3e2bff71d866c8c500f8288 (HEAD -> newmaster)
Author: pukkandan <pukkandan.ytdlp@gmail.com>
Date:   Tue Jun 1 18:05:41 2021 +0530

    Escape URLs in `sanitized_Request`, not `sanitize_url` d2558234cf5dd12d6896eed5427b7dcdb3ab7b5a added escaping of URLs while sanitizing. However, `sanitize_url` may not always receive an actual URL. Eg: When using `youtube-dl "search query" --default-search ytsearch`, `search query` gets escaped to `search%20query` before being prefixed with `ytsearch:` which is not the intended behavior. So the escaping is moved to `sanitized_Request` instead.

diff --git a/test/test_utils.py b/test/test_utils.py
index 9d364c863..ea2b96ed2 100644
--- a/test/test_utils.py
+++ b/test/test_utils.py
@@ -250,6 +250,7 @@ class TestUtil(unittest.TestCase):
         self.assertEqual(sanitize_url('httpss://foo.bar'), 'https://foo.bar')
         self.assertEqual(sanitize_url('rmtps://foo.bar'), 'rtmps://foo.bar')
         self.assertEqual(sanitize_url('https://foo.bar'), 'https://foo.bar')
+        self.assertEqual(sanitize_url('foo bar'), 'foo bar')
 
     def test_expand_path(self):
         def env(var):
diff --git a/youtube_dl/extractor/generic.py b/youtube_dl/extractor/generic.py
index 0e473e952..b01900afa 100644
--- a/youtube_dl/extractor/generic.py
+++ b/youtube_dl/extractor/generic.py
@@ -2320,6 +2320,25 @@ class GenericIE(InfoExtractor):
                 'height': 720,
                 'age_limit': 18,
             },
+        }, {
+            # would like to use the yt-dl test video but searching for
+            # '"\'/\\ä↭𝕐' fails, so using an old vid from YouTube Korea
+            'note': 'Test default search',
+            'url': 'Shorts로 허락 필요없이 놀자! (BTS편)',
+            'info_dict': {
+                'id': 'usDGO4Zb-dc',
+                'ext': 'mp4',
+                'title': 'YouTube Shorts로 허락 필요없이 놀자! (BTS편)',
+                'description': 'md5:96e31607eba81ab441567b5e289f4716',
+                'upload_date': '20211107',
+                'uploader': 'YouTube Korea',
+                'location': '대한민국',
+            },
+            'params': {
+                'default_search': 'ytsearch',
+                'skip_download': True,
+            },
+            'expected_warnings': ['uploader id'],
         },
     ]
 
diff --git a/youtube_dl/utils.py b/youtube_dl/utils.py
index 4edbfa27b..761edcd49 100644
--- a/youtube_dl/utils.py
+++ b/youtube_dl/utils.py
@@ -2176,11 +2176,11 @@ def sanitize_url(url):
     for mistake, fixup in COMMON_TYPOS:
         if re.match(mistake, url):
             return re.sub(mistake, fixup, url)
-    return escape_url(url)
+    return url
 
 
 def sanitized_Request(url, *args, **kwargs):
-    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
+    return compat_urllib_request.Request(escape_url(sanitize_url(url)), *args, **kwargs)
 
 
 def expand_path(s):

```

**Comment by kim3k** [comment] 2023-02-20 20:46
Can confirm it works. 👍  
other bugs got fixed as well, were a few videos that didnt play at all (even with direct URL). But now that works too.
Thank you sir! 100% chad! 🥇

**Comment by dirkf** [comment] 2023-02-22 17:32
Fixed in https://github.com/ytdl-org/youtube-dl/commit/1d3751c3fe50b203d3e2bff71d866c8c500f8288.

**Closed by dirkf** 2023-02-22 17:32 UTC
Labels: bug, patch-available
