### ISSUE TITLE
Udemy bug while downloading course

### ISSUE THREAD

**Issue by elijunior01** [ytdl-org/youtube-dl#31193] opened 2022-08-22 17:12 UTC
./youtube-dl.exe --cookies .\udemy.com_cookies.txt -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' https://www.udemy.com/cientista-de-dados/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '.\\udemy.com_cookies.txt', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', 'https://www.udemy.com/cientista-de-dados/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] cientista-de-dados: Downloading webpage
[udemy:course] 1225734: Downloading course curriculum
[download] Downloading playlist: 1225734
[udemy:course] playlist 1225734: Collected 346 video ids (downloading 346 of them)
[download] Downloading video 1 of 346
[udemy] 22093950: Downloading webpage
[udemy] 22093950: Downloading lecture JSON
[udemy] 41475852: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://www.udemy.com/assets/41475852/files/2022-05-22_20-59-39-e49e5a53bf6278d16db31cf442d90c93/2/hls/AVC_1920x1080_1600k_AAC-HE_64k/aa003bbb530922981761057f38208d3d3424.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMi0wNS0yMl8yMC01OS0zOS1lNDllNWE1M2JmNjI3OGQxNmRiMzFjZjQ0MmQ5MGM5My8yLyIsImV4cCI6MTY2MTIwNDM4NX0.1cTjZLCloiZJ5YIbV77xdkBRRSsk3a2XrQHHI-E3yq4&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 19
[download] Destination: 1225734\1 - Apresentação\001. Instruções Gerais.mp4
[download] 100% of 19.77MiB in 00:05
WARNING: 41475852: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 2 of 346
[udemy] 21169554: Downloading webpage
[udemy] 21169554: Downloading lecture JSON
[udemy] 37614993: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://www.udemy.com/assets/37614993/files/2021-11-18_20-33-49-558d88d6075d7b2eefdb924653aedc8c/2/hls/AVC_1920x1080_4800k_AAC-HE_64k/aa002a0c55e7098828d5695e2d493d9227d5.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMS0xMS0xOF8yMC0zMy00OS01NThkODhkNjA3NWQ3YjJlZWZkYjkyNDY1M2FlZGM4Yy8yLyIsImV4cCI6MTY2MTIwNDM5M30.4kQhctcHL7da7qrSWbssbfiqVzjEM7q77OefqggL680&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 171
[download] Destination: 1225734\1 - Apresentação\002. Apresentação.mp4
[download] 100% of 214.57MiB in 00:52
WARNING: 37614993: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
[download] Downloading video 3 of 346
[udemy] 22285484: Downloading webpage
[udemy] 22285484: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\udemy.py", line 408, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-08-22 22:37
Duplicate of #29925.

**Closed by dirkf** 2022-08-22 22:37 UTC
