### ISSUE TITLE
youtube url unexpected caused crash

### ISSUE THREAD

**Issue by jimlynnjulian** [ytdl-org/youtube-dl#30380] opened 2021-12-15 22:23 UTC
-Using latest version.
-URL is a functioning YouTube site.
-Verbose output submitted as requested by software:
C:\ytdl>ytdl --verbose https://www.youtube.com/watch?v=SQadcm_dwEM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=SQadcm_dwEM']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg N-86129-g1e8daf3, ffprobe N-86129-g1e8daf3
[debug] Proxy map: {}
[youtube] SQadcm_dwEM: Downloading webpage
[youtube] SQadcm_dwEM: Downloading player 204bfffb
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1623, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1359, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1349, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1262, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1331, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Lukieer** [comment] 2021-12-16 00:16
Fixed in my fork: https://github.com/Lukieer/youtube-dl

**Comment by jimlynnjulian** [comment] 2021-12-16 00:30
> Fixed in my fork: https://github.com/Lukieer/youtube-dl

Thanks, but I'm using Windows 11. 
I'm curremtly downloading on FireFox, with a "SaveFrom" extension.

**Comment by MaskDuck** [comment] 2021-12-16 00:49
I am getting this error too.

**Comment by audyviii** [comment] 2021-12-16 01:01
I am getting this error as well on Windows 11

**Comment by dirkf** [comment] 2021-12-16 03:42
Duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), with fix.

Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, @jimlynnjulian, kindly close this issue.

**Comment by jimlynnjulian** [comment] 2021-12-16 04:08
Why would I submit a Broken Site support issue. Speak some sense please.
I complied with a request in the error printout of the app to post a bug. Doing YTDL a favor, or so I thought. 
I'm still interested in a viable answer. If the bug was fixed, why am I getting errors? 
Until the problem is fixed in the field, there is a bug and no fix.

**Comment by jimlynnjulian** [comment] 2021-12-16 04:13
When will the Windows binary reflect the change?

**Comment by dirkf** [comment] 2021-12-16 04:33
If you read issue #30363 and linked material, this would become clear, but no-one is going to copy that information into your duplicate issue.

What you were seeing was yt-dl failing to handle a site (YT) that you expected it to handle. That's what "Broken site support" means. If you follow the template as linked, you see
> WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

and later

>- Search the bugtracker for similar issues: http://yt-dl.org/search-issues. DO NOT post duplicates.

The templates were set up by the project to help resolve people's problems efficiently, and this is all the more relevant when as at present no maintainers are active.

**Comment by jimlynnjulian** [comment] 2021-12-16 05:19
I thought the 'Broken Site' thing concerned youtube-dl.org. Given that, how would I have worded a search? 
Include search terms in the error messages supplied by the software, or would that be too 'tedious'?

**Closed** 2021-12-16 22:19 UTC

**Comment by jimlynnjulian** [comment] 2021-12-16 22:20
Congratulations. Happy Holidays. I've closed this report.
