### ISSUE TITLE
[FranceTV] ERROR: Unable to download JSON metadata

### ISSUE THREAD

**Issue by calixus06** [ytdl-org/youtube-dl#30284] opened 2021-11-28 19:51 UTC
"youtube-dl https://www.france.tv/france-5/echappees-belles/echappees-belles-saison-16/2894331-suede-la-force-de-la-nature.html
[FranceTVSite] 2894331-suede-la-force-de-la-nature: Downloading webpage
[FranceTV] 84a0767d-bb61-44e3-afab-9a02a7452951: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Thanks for your help !!

Nico

**Comment by dirkf** [comment] 2021-11-28 22:45
Duplicate of #29956

**Closed** 2022-05-09 14:33 UTC
Labels: duplicate
