### ISSUE TITLE
youtube-dl no longer working on xvideos.com

### ISSUE THREAD

**Issue by snorkack71** [ytdl-org/youtube-dl#30401] opened 2021-12-19 00:53 UTC
Firefox works ok.  youtube-dl stopped working in last three weeks or so.
Script started on 2021-12-18 09:12:18-07:00 [TERM="xterm" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.xvideos.com/video25243383/18yo_teen_flat_chested_cum_on_cam_freecamgirls.club']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-12-686-pae-i686-with-debian-10.0
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 25243383: Downloading webpage
[0;31mERROR:[0m Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Script done on 2021-12-18 09:12:24-07:00 [COMMAND_EXIT_CODE="1"]

**Comment by kikuyan** [comment] 2021-12-19 01:39
Duplicate of #30276.
There's a PR #30278.

**Comment by bifa2** [comment] 2021-12-20 20:50
@snorkack71 this issue can be closed if it's a dupe

**Closed** 2022-02-05 02:24 UTC
Labels: duplicate
