### ISSUE TITLE
ERROR: Unable to extract uploader id; ...

### ISSUE THREAD

**Issue by Sollidottingen** [ytdl-org/youtube-dl#31689] opened 2023-02-25 05:18 UTC
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by pavel-cernohorsky** [comment] 2023-02-25 05:55
Hello, similar problem here...
Detailed printout:
```
$ /opt/youtube-dl.2021.12.17/youtube-dl --verbose 'https://www.youtube.com/watch?v=cMNv7arGNcM'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=cMNv7arGNcM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-5.15.88-gentoo-x86_64-AMD_Ryzen_7_4700U_with_Radeon_Graphics-with-glibc2.36
[debug] exe versions: ffmpeg 4.4.3, ffprobe 4.4.3
[debug] Proxy map: {}
[youtube] cMNv7arGNcM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/youtube-dl.2021.12.17/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/youtube-dl.2021.12.17/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/youtube-dl.2021.12.17/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/youtube-dl.2021.12.17/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/youtube-dl.2021.12.17/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by pavel-cernohorsky** [comment] 2023-02-25 06:02
Looks like a duplicate of #31530.

**Closed** 2023-02-25 11:43 UTC
Labels: duplicate, incomplete

**Comment by dirkf** [comment] 2023-02-25 11:50
#30839
