### ISSUE TITLE
[bravo] Unable to extract drupal settings

### ISSUE THREAD

**Issue by StevenDTX** [ytdl-org/youtube-dl#19213] opened 2019-02-13 02:00 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---

---

```
E:\>youtube-dl --verbose https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-10-so-vain-in-solvang: Downloading webpage
ERROR: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\bravotv.py", line 35, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---
### Description of your *issue*, suggested solution and other information

Something has apparently changed with Bravo within the last week. All videos produce this error: "Unable to extract drupal settings."

I get the same result with or without MSO credentials.

**Comment by NGTmeaty** [comment] 2019-02-13 02:36
It seems to have switched to drupal-settings-json, but doesn't contain the information. Someone else will have to take a look at this :)

**Comment by NGTmeaty** [comment] 2019-02-13 03:08
Just made a little fix. Will try to get it in a PR tonight.

**Comment by StevenDTX** [comment] 2019-02-13 12:45
Thanks a lot @ngtmeaty!

**Comment by jeeribaldi** [comment] 2019-02-15 21:29
New user. Still receiving the following:

~$ youtube-dl --verbose https://www.bravotv.com/top-chef/season-16/episode-11/videos/lck-ep-12-the-final-knockout
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bravotv.com/top-chef/season-16/episode-11/videos/lck-ep-12-the-final-knockout']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.08
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[BravoTV] lck-ep-12-the-final-knockout: Downloading webpage
ERROR: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bravotv.py", line 35, in _real_extract
    r'jQuery\.extend\(Drupal\.settings\s*,\s*({.+?})\);', webpage, 'drupal settings'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by StevenDTX** [comment] 2019-02-15 23:27
@jeeribaldi 

If you will notice, this issue is still open.  @NGTmeaty  was kind enough to fix the issue, but until one of the youtube-dl maintainers merges his fixes into a new build, then it will continue to fail.

This issue will get closed once its merged.

**Comment by nevafuse** [comment] 2019-02-18 02:19
@NGTmeaty I'm getting the following error when using your branch.  I noticed your test was using a different show.  You mind trying this show and see if you get the same error?  

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--download-archive', u'/home/pi/ytdl.arc', u'https://www.bravotv.com/last-chance-kitchen/season-7/videos/lck-ep-8-speed-round']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Git HEAD: ca1dc4a8a
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[BravoTV] lck-ep-8-speed-round: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'3651766',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/opt/youtube-dl/youtube_dl/extractor/bravotv.py", line 57, in _real_extract
    metadata = ls_playlist['video_metadata'][ls_playlist['default_clip']]
KeyError: u'3651766'
Traceback (most recent call last):
  File "/opt/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/opt/youtube-dl/youtube_dl/extractor/common.py", line 521, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'3651766',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by roadzy** [comment] 2019-02-28 03:34
Any idea how long it will take this to get merged by the maintainers?  How often do bugs get merged?  I just came here since I had the same error as above.

**Comment by roadzy** [comment] 2019-03-01 00:06
Ok new version pushed and downloaded. Same Error

youtube-dl --version
2019.03.01

youtube-dl --verbose  --cookies=bev.txt https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-3-sun-and-shade-in-the-bahamas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies=bev.txt', 'https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-3-sun-and-shade-in-the-bahamas']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.6.1 (CPython) - Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: ffmpeg 3.4.5, ffprobe 3.4.5
[debug] Proxy map: {}
[BravoTV] ep-3-sun-and-shade-in-the-bahamas: Downloading webpage
ERROR: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/bravotv.py", line 35, in _real_extract
    r'jQuery\.extend\(Drupal\.settings\s*,\s*({.+?})\);', webpage, 'drupal settings'),
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Closed** 2019-04-16 18:08 UTC
