### ISSUE TITLE
Netflix Request

### ISSUE THREAD

**Issue by peterpt** [ytdl-org/youtube-dl#21234] opened 2019-05-27 23:42 UTC
Is there any chance to implement netflix stream decoders/extraction to youtube-dl ?
I can provide a login for denvelopers to test it out .
Eventually posting here some movie link will not work at all without a login to the service .
I did not saw any related request for this movie stream website , this is why i am writting it here .
Btw , i will not post a netflix account here on plain view , provide some email so i can send it , and i send only to denvelopers .

Cheers

**Comment by remitamine** [comment] 2019-05-28 02:34
Duplicate of #1564.

**Closed by remitamine** 2019-05-28 02:34 UTC
Labels: site-support-request

**Comment by msaad99** [comment] 2020-03-01 19:49
There seems to be no update on #1564. Any idea if there has been any progress?
