### ISSUE TITLE
[france.tv] Error 503 while downloading

### ISSUE THREAD

**Issue by ytrezq** [ytdl-org/youtube-dl#30956] opened 2022-05-17 11:26 UTC
Error 503 while downloading https://www.france.tv/france-2/meurtres-au-paradis/meurtres-au-paradis-saison-11/3352060-dans-le-noir.html json (to be fixed soon as the video is available only during 7 days)

Just performed `curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl` today and tried to download the video.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-subs', '--embed-thumbnail', 'https://www.france.tv/france-2/meurtres-au-paradis/meurtres-au-paradis-saison-11/3352060-dans-le-noir.html', '--all-subs', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.12 (PyPy version 7.3.9) - Linux-3.18.115-17011592-aarch64-with-glibc2.35.9000
[debug] exe versions: none
[debug] Proxy map: {}
[FranceTVSite] 3352060-dans-le-noir: Downloading webpage
[FranceTV] 698392b7-ae1d-40b6-876d-d5fb5d40da54: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/pypy3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/pypy3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/pypy3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/pypy3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/pypy3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
Please note the video is available for download for free when using the official Android app. But the feature requires non rooted devices.

**Comment by dirkf** [comment] 2022-05-18 11:29
Duplicate of #29956.

Try [yt-dlp](https://github.com/yt-dlp/yt-dlp) for your immediate needs. The necessary fix needs to be back-ported but this is not completely trivial.

**Closed** 2022-06-01 12:26 UTC
Labels: duplicate
