### ISSUE TITLE
[XVideos] HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by BeachBush** [ytdl-org/youtube-dl#30707] opened 2022-03-02 16:17 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', '--restrict-filenames', 'https://www.xvideos.com/video46439753/porn-de/0/premiere_fahrrad_in_der_offentlichkeit_geil_abgefickt_']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-100-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[XVideos] 46439753: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2022-03-02 23:51
Duplicate of #30271, fixed in git master.

**Comment by brbergami** [comment] 2022-03-16 04:40
Latest build for windows as referenced in [https://github.com/ytdl-org/youtube-dl#installation](https://github.com/ytdl-org/youtube-dl#installation) still has this issue. This shouldn't be considered as "fixed" until releases _actually work_ for end user (link redirects to [https://yt-dl.org/latest/youtube-dl.exe](https://yt-dl.org/latest/youtube-dl.exe))

**Comment by brbergami** [comment] 2022-03-16 14:22
@dirkf Any chance to update the windows builds on yt-dl.org with the latest changes from master?

**Comment by barbertoclean21** [comment] 2022-03-16 14:54
Begging ant u no man no woman wth

**Comment by barbertoclean21** [comment] 2022-03-16 14:55
Beegin who iam begging u need to get away me whit Fabricating

**Comment by dirkf** [comment] 2022-03-16 15:44
The Windows build will appear, with an actual release, as soon as the new maintainer can concentrate for the necessary period on making it happen.

Meanwhile don't feel bad about the workaround. The self-extracting Windows build has to unpack all the files each time it runs, not just for yt-dl but the minimal Python build too. Whereas the other way, you end up with Python properly installed as well as yt-dl.

**Comment by 89z** [comment] 2022-03-16 16:30
> @garoto I was running youtube-dl from a single windows binary the whole time without using Python, aside with ffmpeg. No batteries required.

@brbergami this is a free project, so you get what you pay for.

You can install the master branch via pip, like thousands of other people do every day. Otherwise, you can wait for a release, when the maintainer feels like it, not when you demand it.

**Comment by brbergami** [comment] 2022-03-16 16:37
@89z I can build the windows binaries if someone can get me in touch with the one who did the previous ones. Upload them, and contribute with the project for the people that find that binaries more useful than doing a python, pip and ytb-dl installs. Just a download and you're good to go.

Dude, your comments are not helpful by any mean, why you keep commenting if you're not going to help?

**Comment by 89z** [comment] 2022-03-16 16:41
> I can build the windows binaries if someone can get me in touch with the one who did the previous ones. Upload them regularly, and contribute with the project for the people that find that binaries more useful than doing a python, pip and ytb-dl installs. Just a download and you're good to go.

That is already what happens now:

http://ytdl-org.github.io/youtube-dl/download.html

So I dont think anyone needs you to do that. Some projects do "snapshots", where a release a made on every commit. YouTube-DL is not one of those projects. YouTube-DL, like many other projects, make periodic releases, when the maintainer feels its the right time to do so.

If you wish to get a version past the latest release, youll need to use pip from the master branch, as previously discussed.

**Comment by brbergami** [comment] 2022-03-16 16:46
> If you wish to get a version past the latest release, youll need to use pip from the master branch, as previously discussed.

https://github.com/ytdl-org/youtube-dl/issues/30707#issuecomment-1069318509

**Comment by garoto** [comment] 2022-03-16 17:09
> Funny part is that tried the pip install on win, which gives me the 2021.12.17 version [...]

version information isn't updated till a release is made. You can edit `version.py` manually.

> that version still has the issue

Tried with master, and xvideos works for me.

**Comment by brbergami** [comment] 2022-03-17 00:29
@garoto

https://user-images.githubusercontent.com/37002893/158713106-6efb5b7d-061b-4d02-a3d7-3b191953a40f.mp4

**Comment by brbergami** [comment] 2022-03-17 00:58
@garoto 
https://user-images.githubusercontent.com/37002893/158715460-87cc6122-6055-4ca1-ab00-a38f111de15e.mp4

**Comment by garoto** [comment] 2022-03-17 01:17
Like dirkf already mentioned, `pip install youtube-dl` won't do it. Try the command that was posted: `pip install https://github.com/ytdl-org/youtube-dl/archive/master.zip`.

Failing that:
```
C:\>pip instal pyinstaller
C:\>curl --location --remote-name https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
C:\>7z x master.zip 
C:\>cd youtube-dl-master\
C:\>pyinstaller.exe youtube_dl\__main__.py --onefile --upx-exclude=vcruntime140.dll --icon "NONE"
```

And then find the newly generated .exe inside `.\youtube-dl-master\dist\`.

**Comment by afterdelight** [comment] 2022-03-19 03:47
does downloading xvidoes channel works? mine doesnt

**Closed** 2022-04-18 03:48 UTC
Labels: duplicate, fixed
