### ISSUE TITLE
ERROR : Unable to extract uploader id. have been using latest version

### ISSUE THREAD

**Issue by RexsyBima** [ytdl-org/youtube-dl#32064] opened 2023-04-20 00:29 UTC
when i try to download a playlist from

https://www.youtube.com/playlist?list=PLZS-MHyEIRo59lUBwU-XHH7Ymmb04ffOY

It gets that error message. my command was simple. it's youtube-dl https://www.youtube.com/playlist?list=PLZS-MHyEIRo59lUBwU-XHH7Ymmb04ffOY

Am i doing something wrong? im using the latest version btw

**Comment by RexsyBima** [comment] 2023-04-20 00:34
Sorry im dumb, please ignor this bug, and even delete it pls. im very new into github and stuffs. i apologize

**Comment by gosuto-inzasheru** [comment] 2023-04-20 02:30
it would help me (and others!) to expand on how your issue was resolved.

**Comment by gosuto-inzasheru** [comment] 2023-04-20 02:31
dupe of #31530

**Comment by spkahle1243** [comment] 2023-04-20 02:57
I have the most recent version of youtube-dl as can be seen here:
C:\Users\usr\AppData\Local\FoundryVTT\Data\my information\DM Images\Youtube Audio Downloader>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

Then using the following command, I get the following error:
C:\Users\usr\AppData\Local\FoundryVTT\Data\my information\DM Images\Youtube Audio Downloader>youtube-dl -f ogg https://www.youtube.com/watch?v=kUESqvDzEr0&list=PLumzb_XznlTGfzCqgG86xdOS7ayMgOSzx&index=4
[youtube] kUESqvDzEr0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gosuto-inzasheru** [comment] 2023-04-20 03:03
@spkahle1243 please report in #31530

**Closed** 2023-04-20 03:08 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-04-20 03:16
Or rather, review the issue and report if the recommended solution is not working.

In general: follow #30839; use the checklist; avoid creating a duplicate issue; done.
