### ISSUE TITLE
Can't download facebook videos

### ISSUE THREAD

**Issue by sondre1868** [ytdl-org/youtube-dl#20716] opened 2019-04-19 14:41 UTC
youtube-dl --verbose "https://www.facebook.com/laurent.jockschies/videos/1740767422629341/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/laurent.jockschies/videos/1740767422629341/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-47-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[facebook] 1740767422629341: Downloading webpage
[facebook] 1740767422629341: Downloading webpage
[facebook] 1740767422629341: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 471, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by copperfield42** [comment] 2019-04-19 14:44
same here, but with python 3.7.2

**Comment by ealgase** [comment] 2019-04-19 14:48
Duplicate of #20711.

**Closed** 2019-04-19 15:08 UTC
