### ISSUE TITLE
podcasts.apple.com doesn't work with youtube-dl

### ISSUE THREAD

**Issue by phelanm** [ytdl-org/youtube-dl#30250] opened 2021-11-19 22:19 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O ./youtube-dl
$ sudo chmod a+rx youtube-dl 
$ ./youtube-dl --version
2021.06.06
$ ./youtube-dl --verbose "https://podcasts.apple.com/us/podcast/the-joy-of-basketball-cookies-hoops-x-pdl/id1471240409?i=1000542112826"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://podcasts.apple.com/us/podcast/the-joy-of-basketball-cookies-hoops-x-pdl/id1471240409?i=1000542112826']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-0.slh.2-aptosid-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.1-1, avprobe 3.4.1-1, ffmpeg 3.4.1-1, ffprobe 3.4.1-1
[debug] Proxy map: {}
[ApplePodcasts] 1000542112826: Downloading webpage
ERROR: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/applepodcasts.py", line 44, in _real_extract
    webpage, 'ember data'), episode_id)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

doesn't work: https://podcasts.apple.com/us/podcast/the-joy-of-basketball-cookies-hoops-x-pdl/id1471240409?i=1000542112826

**Comment by kikuyan** [comment] 2021-11-19 23:21
Duplicate of #30216, read comment there.

**Comment by 89z** [comment] 2021-11-20 05:34
I have an alternative tool that works:

~~~
PS C:\> apple -i https://podcasts.apple.com/us/podcast/the-joy-of-basketball-cookies-hoops-x-pdl/id1471240409?i=1000542112826
{ArtistName:Sam and Stav
AssetURL:https://traffic.libsyn.com/secure/poddontlie/PDL_11-16_REG_-_AUDIO.mp3
Duration:1h22m13s Name:THE JOY OF BASKETBALL // Cookies Hoops x PDL
ReleaseDateTime:2021-11-16T15:41:19Z}
~~~

https://github.com/89z/mech

**Closed** 2022-02-05 02:32 UTC
Labels: duplicate
