### ISSUE TITLE
README and other files need to be updated in light of Hamburg court ruling

### ISSUE THREAD

**Issue by jrbray1** [ytdl-org/youtube-dl#32569] opened 2023-09-23 11:35 UTC
The README here, (and I guess many other files) refers to site https://yt-dl.org/ which has been blocked due to a court ruling. If there is an alternative site, can it be used instead

**Comment by nicolaasjan** [comment] 2023-09-23 17:35
See also:
https://github.com/ytdl-org/youtube-dl/issues/32495

**Comment by dirkf** [comment] 2023-09-23 18:08
In fact, duplicate of that. If the Germans can't control themselves, the next actual release will be fully hosted on GH.

**Closed by dirkf** 2023-09-23 18:08 UTC

**Comment by jrbray1** [comment] 2023-09-23 18:19
I really think you need to explain what's going on, and why software which is getting regular commits only mentions a formal release 2 years ago.

**Comment by dirkf** [comment] 2023-09-23 18:23
#31585.
