### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by xiaose** [ytdl-org/youtube-dl#23458] opened 2019-12-19 22:20 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl.exe https://cdn.vidyard.com/hls-videos/uOnFGlfrMECrVyZW-IC3vQ/stream_master_n9HYXx8RhD56f2z7vMEdQQ.m3u8?bkzlhYmEJ9O_HhZrvISndjxgx4ZmhNQOMiv8iFzv5oVE0h7mwHFI7l8v6z6vnal7d7YKB0isXG2grsxLMi_1O8dWbktYQyYdKBbQJQkwKVGWr6NbZQhQGMrT6vJdFV6ZkxB4vo3gljaQhuyACEAnwxhHUeKhbQp2bRorJGJZcdq3CCcJzO6yPdpKVz_HoKtc7JXc -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://cdn.vidyard.com/hls-videos/uOnFGlfrMECrVyZW-IC3vQ/stream_master_n9HYXx8RhD56f2z7vMEdQQ.m3u8?bkzlhYmEJ9O_HhZrvISndjxgx4ZmhNQOMiv8iFzv5oVE0h7mwHFI7l8v6z6vnal7d7YKB0isXG2grsxLMi_1O8dWbktYQyYdKBbQJQkwKVGWr6NbZQhQGMrT6vJdFV6ZkxB4vo3gljaQhuyACEAnwxhHUeKhbQp2bRorJGJZcdq3CCcJzO6yPdpKVz_HoKtc7JXc', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2
[debug] Proxy map: {}
[generic] stream_master_n9HYXx8RhD56f2z7vMEdQQ: Requesting header
WARNING: Could not send HEAD request to https://cdn.vidyard.com/hls-videos/uOnFGlfrMECrVyZW-IC3vQ/stream_master_n9HYXx8RhD56f2z7vMEdQQ.m3u8?bkzlhYmEJ9O_HhZrvISndjxgx4ZmhNQOMiv8iFzv5oVE0h7mwHFI7l8v6z6vnal7d7YKB0isXG2grsxLMi_1O8dWbktYQyYdKBbQJQkwKVGWr6NbZQhQGMrT6vJdFV6ZkxB4vo3gljaQhuyACEAnwxhHUeKhbQp2bRorJGJZcdq3CCcJzO6yPdpKVz_HoKtc7JXc: HTTP Error 403: Forbidden
[generic] stream_master_n9HYXx8RhD56f2z7vMEdQQ: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 2237, in urlopen     File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I try to get videos from https://www.jazzguitarlessons.net/blog/all-the-things-you-are 
I fund video link as: https://cdn.vidyard.com/hls-videos/uOnFGlfrMECrVyZW-IC3vQ/stream_master_n9HYXx8RhD56f2z7vMEdQQ.m3u8?bkzlhYmEJ9O_HhZrvISndjxgx4ZmhNQOMiv8iFzv5oVE0h7mwHFI7l8v6z6vnal7d7YKB0isXG2grsxLMi_1O8dWbktYQyYdKBbQJQkwKVGWr6NbZQhQGMrT6vJdFV6ZkxB4vo3gljaQhuyACEAnwxhHUeKhbQp2bRorJGJZcdq3CCcJzO6yPdpKVz_HoKtc7JXc and try to download it using youtube-dl.exe and have got **HTTP Error 403: Forbidden**

**Comment by remitamine** [comment] 2019-12-19 23:12
duplicate of #11338.
for now, you can download by adding the referer header:
`youtube-dl --add-header 'Referer: https://play.vidyard.com/ [HLS_URL]`

**Closed by remitamine** 2019-12-19 23:12 UTC

**Comment by xiaose** [comment] 2019-12-20 12:37
> duplicate of #11338.
> for now, you can download by adding the referer header:
> `youtube-dl --add-header 'Referer: https://play.vidyard.com/ [HLS_URL]`

Thank you, @remitamine  Now it works! )))

**Comment by salmanwaheed** [comment] 2020-01-20 04:30
> duplicate of #11338.
> for now, you can download by adding the referer header:
> `youtube-dl --add-header 'Referer: https://play.vidyard.com/ [HLS_URL]`

worked for me, Thanks @remitamine

**Comment by goniluka** [comment] 2020-04-05 16:31
Hi can you help me what [HLS_URL] can i put there for this link  
youtube-dl --add-header 'Referer: https://play.vidyard.com/ [https://cdn.vidyard.com/hls-videos/Xee6RMgC-QtFNtiEMpmEUg/full_hd_segmented/full_hd_segmented_V0dtqy4pTRMvStN0dbvA7w.m3u8]
can you help me i am a beginner. Thank you

**Comment by sabuncu** [comment] 2020-04-12 20:10
@goniluka Please see the first answer in the following page: 
https://www.quora.com/Tutorials-How-can-I-download-PluralSight-training-videos
Construct the batch-file.txt.  Add to the batch file:
--add-header 'Referer: https://play.vidyard.com/'
The HLS refers to the URL being downloaded.  You should specify your own URL(s) in the batch-file.

**Comment by sabuncu** [comment] 2020-04-12 20:11
@remitamine Thank you, worked for me.

**Comment by javaHelper** [comment] 2020-04-18 19:17
I used below but its not working for me

```javayoutube-dl -o "%(playlist_index)s.%(title)s.%(ext)s" --add-header "Referer: https://play.vidyard.com/" --username "abc@gmail.com" --password "abc@123" --verbose --sleep-interval 80 "https://app.pluralsight.com/library/courses/spring-integration-message-system-design-patterns/table-of-contents"```
