### ISSUE TITLE
Can not download 4K video

### ISSUE THREAD

**Issue by Diamond9** [ytdl-org/youtube-dl#28117] opened 2021-02-08 13:44 UTC
- [x] I've verified that I'm running youtube-dl version **2021.02.04.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
g:\youtube-dl>youtube-dl -F -v https://www.youtube.com/watch?v=QOjmvL3e7Lc
[debug] System config: []
[debug] User config: ['--no-mtime', '-o', '%(title)s__%(id)s__(%(tbr)dk)_%(height)s@%(fps)s_%(vcodec)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.youtube.com/watch?v=QOjmvL3e7Lc']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.02.04.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.3.1
[debug] Proxy map: {}
[youtube] QOjmvL3e7Lc: Downloading webpage
[youtube] QOjmvL3e7Lc: Downloading m3u8 information
[youtube] QOjmvL3e7Lc: Downloading MPD manifest
[info] Available formats for QOjmvL3e7Lc:
format code  extension  resolution note
91           mp4        256x144     197k , avc1.42c00b, 30.0fps, mp4a.40.5
92           mp4        426x240     338k , avc1.4d4015, 30.0fps, mp4a.40.5
93           mp4        640x360     829k , avc1.4d401e, 30.0fps, mp4a.40.2
94           mp4        854x480    1380k , avc1.4d401f, 30.0fps, mp4a.40.2
300          mp4        1280x720   3806k , avc1.4d4020, 60.0fps, mp4a.40.2
301          mp4        1920x1080  6231k , avc1.64002a, 60.0fps, mp4a.40.2 (best)

```

## Description

I can watch 4K (2160p 60 fps) video in a browser, but the youtube-dl does not list any formats higher 1080p.

**Comment by october262** [comment] 2021-02-08 19:12
retry with youtube-dl -f 301 https://www.youtube.com/watch?v=QOjmvL3e7Lc

**Comment by dstftw** [comment] 2021-02-08 19:20
Duplicate of #10787.

**Closed by dstftw** 2021-02-08 19:20 UTC
