### ISSUE TITLE
ERROR: Go said: 1025:Unable to retrieve required files for playback. (how to fix?)

### ISSUE THREAD

**Issue by FredThompsonII** [ytdl-org/youtube-dl#25640] opened 2020-06-12 18:44 UTC
I'm running the 2020.06.06 build for Windows. Wondering how to prevent this error:

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE',
 '--ap-password', 'PRIVATE', '-o', 'Schooled 0220 CB Saves the Planet 720p AAC 2
.0 x264.mp4', 'https://abc.com/shows/schooled/episode-guide/season-02/20-cb-save
s-the-planet']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.29
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-05-27-8b5f
fae
[debug] Proxy map: {}
[Go] 20-cb-saves-the-planet: Downloading webpage
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
[Go] VDKA0_uixgx8ru: Retrieving Media Token
[Go] VDKA0_uixgx8ru: Downloading JSON metadata
ERROR: Go said: 1025:Unable to retrieve required files for playback. Please try
again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx
45\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx
45\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpxtvjzx
45\build\youtube_dl\extractor\go.py", line 205, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 1025:Unable to retrieve required files
 for playback. Please try again in a few minutes.`

**Comment by gxam** [comment] 2020-06-25 17:35
Dupe of #25207

**Comment by magnum32** [comment] 2020-07-13 13:26
Its been over a month, and the issue with ABC.com still has not been fixed. When will it be implemented in the next version of YouTube-DL?

**Closed** 2020-07-14 12:56 UTC
