### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id;

### ISSUE THREAD

**Issue by QGB** [ytdl-org/youtube-dl#31636] opened 2023-02-21 02:06 UTC
```
In [240]: !youtube-dl -v --write-info-json --skip-download --write-auto-sub --convert-subs srt   --sub-lang en,zh-Hans  --proxy socks5://127.0.0.1:21080 {yu}
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--write-info-json', '--skip-download', '--write-auto-sub', '--convert-subs', 'srt', '--sub-lang', 'en,zh-Hans', '--proxy', 'socks5://127.0.0.1:21080', 'https://www.youtube.com/watch?v=5K27dJqGpf8']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.7.4 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {'http': 'socks5://127.0.0.1:21080', 'https': 'socks5://127.0.0.1:21080'}
[youtube] 5K27dJqGpf8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\qgb\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\qgb\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\qgb\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\qgb\anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1776, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "c:\qgb\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by QGB** [comment] 2023-02-21 02:12
```
In [242]: !yt-dlp.exe -v --write-info-json --skip-download --write-auto-sub --convert-subs srt   --sub-lang en,zh-Hans  --proxy socks5://127.0.0.1:21080 {yu}
[debug] Command-line config: ['-v', '--write-info-json', '--skip-download', '--write-auto-sub', '--convert-subs', 'srt', '--sub-lang', 'en,zh-Hans', '--proxy', 'socks5://127.0.0.1:21080', 'https://www.youtube.com/watch?v=5K27dJqGpf8']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'socks5://127.0.0.1:21080', 'https': 'socks5://127.0.0.1:21080'}
[debug] Loaded 1782 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=5K27dJqGpf8
[youtube] 5K27dJqGpf8: Downloading webpage
[youtube] 5K27dJqGpf8: Downloading android player API JSON
[info] 5K27dJqGpf8: Downloading subtitles: en, zh-Hans
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 5K27dJqGpf8: Downloading 1 format(s): 22
[info] Writing video subtitles to: Beams ｜ Bending Moment and Shear Force Diagram [5K27dJqGpf8].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=5K27dJqGpf8&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1676970612&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=E886BECF74EBA8E1CF8B02BD7E728BCF0A13C6F5.84727D2D6AB8F291388F77BFF4473DDE5AA5625F&key=yt8&kind=asr&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Beams ｜ Bending Moment and Shear Force Diagram [5K27dJqGpf8].en.vtt
[download] 100% of   40.18KiB in 00:00:00 at 83.98KiB/s
[info] Writing video subtitles to: Beams ｜ Bending Moment and Shear Force Diagram [5K27dJqGpf8].zh-Hans.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=5K27dJqGpf8&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1676970612&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=E886BECF74EBA8E1CF8B02BD7E728BCF0A13C6F5.84727D2D6AB8F291388F77BFF4473DDE5AA5625F&key=yt8&kind=asr&lang=en&tlang=zh-Hans&fmt=vtt"
[download] Destination: Beams ｜ Bending Moment and Shear Force Diagram [5K27dJqGpf8].zh-Hans.vtt
[download] 100% of   37.00KiB in 00:00:00 at 55.66KiB/s
[info] Writing video metadata as JSON to: Beams ｜ Bending Moment and Shear Force Diagram [5K27dJqGpf8].info.json
[SubtitlesConvertor] Converting subtitles
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3475, in pre_process
  File "yt_dlp\YoutubeDL.py", line 3468, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3446, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 999, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 369, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 324, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in real_run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 232, in check_version
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: ffmpeg not found. Please install or provide the path using --ffmpeg-location

ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
```

**Comment by rubykat** [comment] 2023-02-21 02:20
This is a duplicate of issue https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by jake380** [comment] 2023-02-21 03:17
[youtube] 2Vv-BfVoq4g: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2023-02-21 04:22
@QGB, in addition the second log is from yt-dlp.
See #30839.

**Closed by dirkf** 2023-02-21 04:23 UTC
