### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by b1tr4t** [ytdl-org/youtube-dl#32021] opened 2023-04-09 21:02 UTC
$ youtube-dl --verbose https://www.tiktok.com/@chicago.dietitian/video/7199800704016633134?_r=1&_t=8adskK6j9P0
[1] 17936
$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@chicago.dietitian/video/7199800704016633134?_r=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.16 (CPython) - Linux-4.15.0-208-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7199800704016633134: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/zzz/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 816, in wrapper
    return func(self, *args, **kwargs)
  File "/home/zzz/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 837, in __extract_info
    ie_result = ie.extract(url)
  File "/home/zzz/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
  File "/home/zzz/.local/lib/python3.7/site-packages/youtube_dl/extractor/tiktok.py", line 112, in _real_extract
    webpage, 'data'), video_id)['props']['pageProps']
  File "/home/zzz/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[1]+  Exit 1                  youtube-dl --verbose https://www.tiktok.com/@chicago.dietitian/video/7199800704016633134?_r=1

**Comment by 5-30** [comment] 2023-04-09 21:13
This tool is called "Youtube"-dl for a reason, it's not made for tiktok videos.

**Comment by b1tr4t** [comment] 2023-04-09 21:26
Works for Vimeo...

-- 
  Jono
  ***@***.***

**Comment by dirkf** [comment] 2023-04-09 23:26
Vimeo is a completely different target, and more straightforward.

>[1]+ Exit 1 youtube-dl --verbose https://www.tiktok.com/@chicago.dietitian/video/7199800704016633134?_r=1

You didn't quote the URL, so the command you ran omitted the `&_t=8adskK6j9P0` (the shell tried to run `_t=8adskK6j9P0` as a command, which just set the variable `_t`, and ran the rest of the command as background job 1, hence `[1]`).

If you had issued the correct command, it would probably have failed too, as a duplicate of #30251. Try PR #30479.

_yt-dlp_ succeeds with this URL, correctly quoted.

**Closed** 2023-04-19 18:17 UTC
Labels: duplicate
