### ISSUE TITLE
brew not getting any new updates

### ISSUE THREAD

**Issue by jamiedaniel** [ytdl-org/youtube-dl#31592] opened 2023-02-19 04:45 UTC
## Checklist

- [ x] I'm asking a question
- [ x] I've looked through the README and FAQ for similar questions
- [ x] I've searched the bugtracker for similar questions including closed ones

## Question

I have an older version installed by Brew ( 2021.12.17 ), any execution of brew upgrade YouTube-dl results in no changes. execution of YouTube-dl reinstall YouTube-dl also reflects no changes. Is there a new release being cut OR is there an installation that will keep us updated to "beta" so that we can use brew to manage the testing?

**Comment by dirkf** [comment] 2023-02-19 12:54
See #31530. What version is served by Brew is up to them.

**Comment by dirkf** [comment] 2023-02-19 12:56
Regarding an official release here, duplicate of #31585.

**Closed by dirkf** 2023-02-19 12:56 UTC
Labels: question
