### ISSUE TITLE
Pluralsight : HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by locatedk** [ytdl-org/youtube-dl#25383] opened 2020-05-23 22:37 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.05.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
WARNING: Unable to download JSON metadata: HTTP Error 429: Too Many Requests
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-4: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by locatedk** [comment] 2020-05-23 22:37
https://app.pluralsight.com/library/courses/overview-enterprise-it-architecture-9-2/table-of-contents

**Comment by locatedk** [comment] 2020-05-23 22:40
Verbose Log

D:\>youtube-dl.exe --verbose https://app.pluralsight.com/library/courses/overview-enterprise-it-architecture-9-2/table-of-contents
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://app.pluralsight.com/library/courses/overview-enterprise-it-architecture-9-2/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] overview-enterprise-it-architecture-9-2: Downloading JSON metadata
[download] Downloading playlist: An Overview of Enterprise and IT Architecture 9.2
[pluralsight:course] playlist An Overview of Enterprise and IT Architecture 9.2: Collected 43 video ids (downloading 43 of them)
[download] Downloading video 1 of 43
[pluralsight] 6f167144-238f-4e4a-95cc-8589e3a71955-0: Downloading JSON metadata
[pluralsight] 6f167144-238f-4e4a-95cc-8589e3a71955-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 6f167144-238f-4e4a-95cc-8589e3a71955-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 6f167144-238f-4e4a-95cc-8589e3a71955-0: Waiting for 5 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/d1706dba-922b-41c3-a4f1-d955ff20bcb5/current/mp4/1280x720.mp4?tUt0-cHVJUzErPgIf9OAZHLmXwVKLQgjmpzFgC5za0L2uvf5X1FdKz8wPW8ZLqUlRDJC_UU1luhAbUuUpLd2tR2euFCxoPaqD4JV1D6C8vKzuxvpL-isu1zRp-VA5fBuidcL6V4Em-bYTT3w2o42Yj3tTUBF7c_3IAsPNhzO_f29NkP5VUxSGiv_6r2y'
[download] Course Overview-d1706dba-922b-41c3-a4f1-d955ff20bcb5.mp4 has already been downloaded
[download] 100% of 2.72MiB
[download] Downloading video 2 of 43
[pluralsight] 74b29c60-7fc4-4d02-9e07-3a3c9546a564-0: Downloading JSON metadata
[pluralsight] 74b29c60-7fc4-4d02-9e07-3a3c9546a564-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 74b29c60-7fc4-4d02-9e07-3a3c9546a564-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 74b29c60-7fc4-4d02-9e07-3a3c9546a564-0: Waiting for 5 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277118/dd811fd647242054a57a30d6adcb648a/clips/resolution/dd3f51f9-eb86-4dc6-bdc4-3d88cbb1509c/current/mp4/1280x720.mp4'
[download] Introduction to an Overview of Enterprise and IT Architecture 9.2 -dd3f51f9-eb86-4dc6-bdc4-3d88cbb1509c.mp4 has already been downloaded
[download] 100% of 11.89MiB
[download] Downloading video 3 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-0: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-0: Waiting for 3 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/f9bb2d2a-6266-440a-94cb-4e15e440eaf6/current/mp4/1280x720.mp4?04FG-vsPW_yKOFpFrT2W4fcbFVsEXJFPGxCuH8ocxfPL5o3qh-7PsQIDq7I8rUoGdd0qkmEHU3aqTgQ4Z-v2C7bszSskcovuL8Gh1pPN1o3JbSu8w1dMcxHGIvCmM79I0Z2punRQUGN6M8II3U97TlPjg4EUv4N3_cFeuCNwjOlBRgkL2AxMt1tAQJQ2'
[download] Introduction to Enterprise Architecture-f9bb2d2a-6266-440a-94cb-4e15e440eaf6.mp4 has already been downloaded
[download] 100% of 7.55MiB
[download] Downloading video 4 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-1: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-1: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-1: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-1: Waiting for 4 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/cda75730-fd90-436d-81e7-42e53d657a5f/current/mp4/1280x720.mp4?HPF7Fg5G9R_3YIzoMPYMtTflgHMG7XarVDRK55fo9Yz2AzGd6y4dzOQ3dIY-XaRs8FKDsqE5IMv9HPxwTWKvma36-_2WEloC559x6-mHH3xKnCTVA1uzxj8aFg3iCf8AFyFqCZe858kXMvX-JKFzqME47HiO7933pUYZYYZ2byh_Bfr3n3WqfcxkKhKv'
[download] What Is an Enterprise-cda75730-fd90-436d-81e7-42e53d657a5f.mp4 has already been downloaded
[download] 100% of 2.88MiB
[download] Downloading video 5 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-2: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-2: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-2: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-2: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/1e5d543b-d9c4-46db-93c0-528d95ce592f/current/mp4/1280x720.mp4?vgmsYKjdiWkfiz_2mAxCS1JEZZ-F0YUJZzvP-npjd_e2MppV-8HGTT4hG91UlLWw1YWzBFtv0N3C27HijjcAi3EygKUEJN922EKhlAI-Mk3zZ9hCojmpk3HrsY0YCw-Spoa572t0xOUxk-ij8Ziea2jiXhyKGADN6VBSTcyC4m3HIT6hn3c-3nIYxsyz'
[download] What Is Architecture-1e5d543b-d9c4-46db-93c0-528d95ce592f.mp4 has already been downloaded
[download] 100% of 4.27MiB
[download] Downloading video 6 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-3: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-3: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-3: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-3: Waiting for 4 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277140/8d7af3082100680f215ab22fcf9f9991/clips/resolution/3de29b4c-df2d-4634-829f-a4f99965e78d/current/mp4/1280x720.mp4'
[download] What Is Enterprise Architecture-3de29b4c-df2d-4634-829f-a4f99965e78d.mp4 has already been downloaded
[download] 100% of 5.35MiB
[download] Downloading video 7 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-4: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-4: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-4: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-4: Waiting for 3 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/47bcf3b5-a904-4573-8b3b-e8b798dcc7bb/current/mp4/1280x720.mp4?V2CivVODexRW34b16jfZ92k_n45MGzy9W_eecibBbKEXCvNPbVXsoDCph5rUXwy7qbmYPPqMhWCYkQYqyWq8I2fVlzfMyifsPQo8Mh8CjNztrSMA9bmRAFbvYNECuF8p61om9vt-DedCsoLLne59x1-aqFYShpYWOQ5a4zUbUPvBP1V8LCzCoGHVrrv-'
[download] Enterprise Architecture Frameworks-47bcf3b5-a904-4573-8b3b-e8b798dcc7bb.mp4 has already been downloaded
[download] 100% of 7.68MiB
[download] Downloading video 8 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-5: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-5: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-5: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-5: Waiting for 3 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/4fb2cd9b-971d-4506-b237-96756640420c/current/mp4/1280x720.mp4?oNVGM5qfODbwzRd2C6RlvPA3_F3FOAs7kQVljdbOMqVSgfZVhX68CMM31pMefzJuRUCS3TwRFHm-KUH6S6WS4exEM0PipdYxNObTRPpOoJ91Td0jXAUu4MCMB4IYa6TNCEnfhOMs14RtD4owUdSfrJhV8SGc4rDL4zRW_KVp4skSRtepMRgwuJt2rFYx'
[download] The Basic Parts of TOGAF-4fb2cd9b-971d-4506-b237-96756640420c.mp4 has already been downloaded
[download] 100% of 4.80MiB
[download] Downloading video 9 of 43
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-6: Downloading JSON metadata
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-6: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-6: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e1f7b693-62d7-49ee-8d0a-2d5dd062bf2b-6: Waiting for 5 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277155/a7002e7a268e4d84ccb55ae4de868ac1/clips/resolution/4b6ef46c-5643-4c9e-980b-334fd4ffa6df/current/mp4/1280x720.mp4'
[download] TOGAF Foundational Concepts-4b6ef46c-5643-4c9e-980b-334fd4ffa6df.mp4 has already been downloaded
[download] 100% of 14.54MiB
[download] Downloading video 10 of 43
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-0: Downloading JSON metadata
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-0: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277162/db3991fdf058fac8e8914ce8d1880cf6/clips/resolution/15717a8d-90cc-42ee-8f0b-c7b3bca5b97a/current/mp4/1280x720.mp4'
[download] Introducing the Architecture Development Method (ADM)-15717a8d-90cc-42ee-8f0b-c7b3bca5b97a.mp4 has already been downloaded
[download] 100% of 7.44MiB
[download] Downloading video 11 of 43
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-1: Downloading JSON metadata
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-1: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-1: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-1: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277165/47a4865168aeff731ddaa5467a5c2f2f/clips/resolution/a15b9fc1-b7b9-493e-904a-acee0ff0846f/current/mp4/1280x720.mp4'
[download] ADM Basics-a15b9fc1-b7b9-493e-904a-acee0ff0846f.mp4 has already been downloaded
[download] 100% of 8.87MiB
[download] Downloading video 12 of 43
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-2: Downloading JSON metadata
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-2: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-2: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-2: Waiting for 4 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid5.pluralsight.com/expiretime=1590277170/44b723468039667d091f288fb1fd049b/clips/resolution/008589f1-b4f3-49d6-bf65-a203e68a82e4/current/mp4/1280x720.mp4'
[download] The Architecture Development Method-008589f1-b4f3-49d6-bf65-a203e68a82e4.mp4 has already been downloaded
[download] 100% of 3.99MiB
[download] Downloading video 13 of 43
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-3: Downloading JSON metadata
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-3: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-3: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 429: Too Many Requests
[pluralsight] 1fc0ee4b-ff84-42f1-9e2b-cbbe45bd72ff-3: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp4z7swgz7\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hiddejager** [comment] 2020-05-24 00:40
@dstftw  Why did you close my issue, can you please help me out? That question isn't answered anywhere

**Comment by dirkf** [comment] 2022-02-07 12:35
Duplicate of #27991, now.

See #29234.

**Closed by dirkf** 2022-02-07 12:35 UTC
