### ISSUE TITLE
yt shorts links are easy to rewrite to download

### ISSUE THREAD

**Issue by gwpl** [ytdl-org/youtube-dl#30911] opened 2022-05-02 17:48 UTC
Short's links e.g.  https://youtube.com/shorts/pFGnq_5fdwk?feature=share

does not work:

```
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

but rewriting this link to : https://youtu.be/pFGnq_5fdwk

Makes youtube-dl work!

Request: please recognize shorts links as they are easy to rewrite to normal yt links and then downloading works!

**Comment by 89z** [comment] 2022-05-02 18:07
> - [ ] I've searched the bugtracker for similar issues including closed ones

**Comment by dirkf** [comment] 2022-05-03 00:32
Duplicate of #30269; fixed in git master, as you would have found by [following the template](https://github.com/ytdl-org/youtube-dl/issues/30839).

**Closed by dirkf** 2022-05-03 00:32 UTC
