### ISSUE TITLE
Downloads from ARD Mediathek no longer work

### ISSUE THREAD

**Issue by ranzeyer** [ytdl-org/youtube-dl#28988] opened 2021-05-06 11:56 UTC
Video Downloads from ARD Mediathek no longer work since today.

youtube-dl  --verbose -F https://www.ardmediathek.de/video/serien/die-bergpolizei-wo-ist-pietro/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzU0NDU/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.ardmediathek.de/video/serien/die-bergpolizei-wo-ist-pietro/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzU0NDU/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[debug] Using fake IP 53.181.126.96 (DE) as X-Forwarded-For.
[ARDBetaMediathek] Y3JpZDovL2hyLW9ubGluZS8xMzU0NDU: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpeav8wi2f\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

youtube-dl --version
2021.04.26

**Comment by burk-castlehard** [comment] 2021-05-06 15:26
ACK - same on linux. (until 17:20 GMT+2)  
BUT that error stopped as i was typing this message. So for me now everything seems okay again.

**Comment by burk-castlehard** [comment] 2021-05-06 15:30
okay - seems like a "flapping bug" as its happening again:
`youtube-dl -F https://www.ardmediathek.de/video/agatha-christie-moerderische-spiele/folge-16-albert-major-redete-zu-viel-s02-e16/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTZkNTE3MjRiLTNhZjUtNDBlOC1hMDIzLWZjNmQwMDE4MDcwMA/
[ARDBetaMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTZkNTE3MjRiLTNhZjUtNDBlOC1hMDIzLWZjNmQwMDE4MDcwMA: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
burk@M4800:~/Downloads$ youtube-dl -F --verbose https://www.ardmediathek.de/video/agatha-christie-moerderische-spiele/folge-16-albert-major-redete-zu-viel-s02-e16/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTZkNTE3MjRiLTNhZjUtNDBlOC1hMDIzLWZjNmQwMDE4MDcwMA/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--verbose', u'https://www.ardmediathek.de/video/agatha-christie-moerderische-spiele/folge-16-albert-major-redete-zu-viel-s02-e16/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTZkNTE3MjRiLTNhZjUtNDBlOC1hMDIzLWZjNmQwMDE4MDcwMA/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.10.59.151 (DE) as X-Forwarded-For.
[ARDBetaMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTZkNTE3MjRiLTNhZjUtNDBlOC1hMDIzLWZjNmQwMDE4MDcwMA: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2279, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by Velofil** [comment] 2021-05-06 16:29
Similar problem still

![Screenshot from 2021-05-06 18:29:19](https://user-images.githubusercontent.com/55458327/117333252-0611ef00-ae99-11eb-99fd-ca08cf47d341.png)

**Comment by october262** [comment] 2021-05-06 17:05
this link - https://www.ardmediathek.de/video/serien/die-bergpolizei-wo-ist-pietro/hr-fernsehen/Y3JpZDovL2hyLW9ubGluZS8xMzU0NDU/ works ok here on my end.

**Comment by burk-castlehard** [comment] 2021-05-06 21:46
@october262 - that link works for me as well. Seems they are restructuring the "mediathek" and moving to another kind of pre-download system. As i wrote in my comment - seems to be a "flapping" bug. The link i posted still gives me an error, right now, while the other one is working fine. The video i wanted to download can be found by navigating through the series entry page: https://www.ardmediathek.de/sendung/agatha-christie-moerderische-spiele/staffel-2/Y3JpZDovL3dkci5kZS9vbmUvYWdhdGhhY2hyaXN0aWUtbW9lcmRlcmlzY2hlc3BpZWxl/2/

**Comment by wieland-s** [comment] 2021-05-07 14:04
Same problem here: https://github.com/ytdl-org/youtube-dl/issues/28960 (incomprehensibly closed)

Also: https://github.com/ytdl-org/youtube-dl/issues/28982 https://github.com/ytdl-org/youtube-dl/issues/28971 and https://github.com/ytdl-org/youtube-dl/issues/28965

**Comment by nklamann** [comment] 2021-05-08 17:23
Seems in some way related to the own IP . It failde under linux at my Hetzner Bokx but worked from home.

**Comment by Marrin** [comment] 2021-05-08 20:22
So maybe it's the fake IP from the log here:
```
[debug] Using fake IP 53.10.59.151 (DE) as X-Forwarded-For.
```

**Comment by SalocinHB** [comment] 2021-05-11 13:37
> So maybe it's the fake IP 

No, the error also occurs with `--no-geo-bypass` from a German IP

**Comment by SalocinHB** [comment] 2021-05-17 23:08
I'm pretty certain it's not related to your IP address. The episode I was trying to download last week worked yesterday, although my (fixed) IP hasn't changed since.

**Comment by 89z** [comment] 2022-04-24 02:18
Issue should be closed, URL is dead

**Comment by ranzeyer** [comment] 2022-07-28 23:30
Close old issue. ARD Mediathek is working correctly.

**Comment by nFec** [comment] 2022-11-03 12:42
Fails for me with and without --no-geo-bypass. Using my own IP or through a german VPN. Doesnt matter. Error is different though. Gateway timeout:

```
$ youtube-dl --no-geo-bypass --verbose https://www.ardmediathek.de/video/dokus-im-ersten/die-story-im-ersten-kampf-ums-klima-hoerfassung/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL3JlcG9ydGFnZSBfIGRva3VtZW50YXRpb24gaW0gZXJzdGVuL2U0NGMyZDdmLTM4MDEtNGNiMy1iZDU3LWU0NWYxZDFiNTBlYy9hdWRpb2Rlc2tyaXB0aW9u
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-geo-bypass', '--verbose', 'https://www.ardmediathek.de/video/dokus-im-ersten/die-story-im-ersten-kampf-ums-klima-hoerfassung/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL3JlcG9ydGFnZSBfIGRva3VtZW50YXRpb24gaW0gZXJzdGVuL2U0NGMyZDdmLTM4MDEtNGNiMy1iZDU3LWU0NWYxZDFiNTBlYy9hdWRpb2Rlc2tyaXB0aW9u']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - macOS-12.6-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[ARDBetaMediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL3JlcG9ydGFnZSBfIGRva3VtZW50YXRpb24gaW0gZXJzdGVuL2U0NGMyZDdmLTM4MDEtNGNiMy1iZDU3LWU0NWYxZDFiNTBlYy9hdWRpb2Rlc2tyaXB0aW9u: Downloading JSON metadata
[ARDBetaMediathek] 12059517: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 504: Gateway Time-out
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/ard.py", line 434, in _real_extract
    info = self._parse_media_info(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/ard.py", line 46, in _parse_media_info
    self._sort_formats(formats)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Closed** 2023-07-31 18:24 UTC
