### ISSUE TITLE
RTBF Auvio

### ISSUE THREAD

**Issue by ktz-on** [ytdl-org/youtube-dl#31266] opened 2022-09-30 13:09 UTC
youtube-dl -F https://www.rtbf.be/auvio/detail_le-grand-bain?id=2942673
[RTBF] 2942673: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-09-30 20:27
Duplicate of #31114.

**Closed by dirkf** 2022-09-30 20:27 UTC
