### ISSUE TITLE
Unable to extract ember data from Apple Podcast

### ISSUE THREAD

**Issue by martin-ward** [ytdl-org/youtube-dl#30413] opened 2021-12-22 14:00 UTC
youtube-dl --verbose 'https://podcasts.apple.com/gb/podcast/theology-in-the-raw/id1018952191?i=1000544808500'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://podcasts.apple.com/gb/podcast/theology-in-the-raw/id1018952191?i=1000544808500']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.12 (CPython) - Linux-5.15.6-desktop-2.mga8-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.3, ffprobe 4.3.3
[debug] Proxy map: {}
[ApplePodcasts] 1000544808500: Downloading webpage
ERROR: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/applepodcasts.py", line 42, in _real_extract
    ember_data = self._parse_json(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ember data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 89z** [comment] 2021-12-22 15:52
I have an alternate tool that works:

~~~
PS C:\> apple -i https://podcasts.apple.com/gb/podcast/theology-in-the-raw/id1018952191?i=1000544808500
GET https://podcasts.apple.com/gb/podcast/theology-in-the-raw/id1018952191?i=1000544808500
{ArtistName:Theology in the Raw Name:The Scandal of Christmas, Part 1: Dr.
Craig Keener ReleaseDateTime:2021-12-13T13:00:00Z Duration:0s
AssetURL:https://static1.squarespace.com/static/56f9adfa2b8dde80022de4f2/t/61b6a4daf3c0e91347f34acf/1639600378294/927-theology-in-the-rawCraig-Keener.mp3}
~~~

https://github.com/89z/mech

**Comment by martin-ward** [comment] 2021-12-22 16:32
I downloaded the web page and found a link to the mp3 file embedded in it which I could download directly. So this particular problem is solved, but it would be nice if youtube-dl could pick out these links and download the mp3 file.

**Comment by kikuyan** [comment] 2021-12-22 23:59
Duplicate of #30250, #30216.
There's a PR #30340.

**Comment by duivesteyn** [comment] 2022-01-27 05:38
whats the update on this?

**Closed** 2022-02-05 02:32 UTC
Labels: duplicate
