### ISSUE TITLE
Can't get Entire Video description

### ISSUE THREAD

**Issue by kurty83** [ytdl-org/youtube-dl#26053] opened 2020-07-19 01:04 UTC
When using 

youtube-dl.exe --write-info-json https://www.youtube.com/watch?v=xxxxxxxx 
or
youtube-dl.exe --write-description https://www.youtube.com/watch?v=xxxxxxxx 

I'm getting partial description, each time a part of description is cutted with "..." at 161 characters.
I can't get why ?! real bug or do i something wrong ? i'm the only one ?

**Comment by detritophage** [comment] 2020-07-19 05:00
The last two videos I downloaded (one on 7/13 and one on 7/16) are like that—description gets cut off at exactly 161 characters (same with JSON info). Descriptions from 7/11 and earlier seem to be fine. I didn't change the version of youtube-dl I was using between those dates, so maybe something changes server-side.

**Comment by michealespinola** [comment] 2020-07-21 07:44
Duplicate of #25937

**Comment by joeschmoe40** [comment] 2020-07-21 11:53
Note: The last (and, therefore, "current") version is 2020.06.16.1, which is over a month old.

Is there any indication when a new version will be out, incorporating this fix (the problem of the description being truncated)?

Given that we used to get new versions like every few days or so, this seems long overdue.

**Comment by michealespinola** [comment] 2020-07-21 13:11
Replying because I got CC'd, but I'm not particularly knowledgable here:

Sergey - who has been handling releases since as long as I have been using youtube-dl - has been inactive for 10+ days now. I don't otherwise know what the dev/mod hierarchy is for this project.  But given the current pandemic, I can only hope that he and his loved ones are well and in good health.

**Closed** 2020-07-22 11:33 UTC
