### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by EvilSupahFly** [ytdl-org/youtube-dl#32185] opened 2023-05-13 21:58 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
evilsupahfly on Black-Beast at Sat 13 May 2023 17:02:31 EDT
[~/Videos] youtube-dl --verbose -f 'bestvideo+bestaudio' "https://www.youtube.com/watch?v=IFwFDZDQWAA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'bestvideo+bestaudio', 'https://www.youtube.com/watch?v=IFwFDZDQWAA']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.2.7-060207-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] IFwFDZDQWAA: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Well, the problem started yesterday when I started getting a strange error:
```
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1673, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[download] Destination: Chalk Warfare-G1LEFtWk-08.mp4
[download] 100% of 10.35MiB in 12:38
```

Despite the initial error, it still downloaded the videos, albeit more slowly than previously. So, I forced `pip` to update it, even though it reported no update was required (`Requirement already satisfied: youtube-dl in /usr/local/lib/python3.10/dist-packages/youtube_dl-2021.12.17-py3.10.egg (2021.12.17)`),  and THEN it wouldn't download at all.

So I completely removed it, and rebuilt it from the same source I used last time (the `MASTER` branch here on GIT), tried again, but I still got `ERROR: Unable to extract uploader id` and the download fails.

After poking around, I found a Windows user who was getting a similar error but resolved it with a nightly build. I figured if it worked for him, it would work for me, so now I've gone and picked up the latest (at time of writing) Nightly Build from https://github.com/ytdl-patched/youtube-dl/releases/tag/2023.05.13.1919.

The good news is that the nightly build works, but if I remove it and go back to `Official Build 2021.12.17` everything falls apart again. Did YouTube change something on their end, or did I screw something up?

EDIT:
I'll also note that with the nightly build, the original error is also gone, and the speed has dramatically improved:
```
evilsupahfly on Black-Beast at Sat 13 May 2023 18:17:13 EDT
[~/Videos] youtube-dl -f 'bestvideo+bestaudio' --verbose "https://www.youtube.com/watch?v=6zCH13oxlPc"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '-f', 'bestvideo+bestaudio', '--verbose', 'https://www.youtube.com/watch?v=6zCH13oxlPc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python 3.10.6 (CPython 64bit) - Linux-6.2.7-060207-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] 6zCH13oxlPc: Downloading webpage
[debug] [youtube] Decrypted nsig QU6kUEO_TvHHxnkGA3 => RRfg9NqGm93q9g
[debug] [youtube] Decrypted nsig ALk2QxIDZF3RuEuowp => jJl1MJ4E8owYNg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr2---sn-nu5gu-tt1e.googlevideo.com/videoplayback?expire=1684037989&ei=BQ1gZJWDNIONjQT05q6gCA&ip=108.170.152.124&id=o-AJ0cFUuFUEfFYroovYFoj_mgH83OUCAIr0_n0E9GwQ-C&itag=299&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=Cn&mm=31%2C29&mn=sn-nu5gu-tt1e%2Csn-tt1e7nls&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=23&initcwndbps=1765000&vprv=1&svpuc=1&mime=video%2Fmp4&ns=rB3fQ5CyFqWQ89J5unLE910N&gir=yes&clen=374527444&dur=728.149&lmt=1682477059043846&mt=1684015997&fvip=2&keepalive=yes&fexp=24007246%2C24362688&c=WEB&txp=5535434&n=RRfg9NqGm93q9g&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgI5N7qLw6MBxmQgq4WvDw6aowbN-xw6vlRG1f4z3sU0sCIFJEynETfG_KUDBUOOHUnOwidAQTeyOL2Rv3YOxGk3x3&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGZRS_D5pHxBsjZxotXYR4VUjRcN_BBqUExlEdXWUq7ECIQCeY6KCJejruVjIbbQ_ALaqi_IXv453WFpFJMISW1yC2w%3D%3D'
[dashsegments] Total fragments: 36
[download] Destination: Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f299.mp4
[download] 100% of 357.18MiB in 00:37
[debug] Invoking downloader on 'https://rr2---sn-nu5gu-tt1e.googlevideo.com/videoplayback?expire=1684037989&ei=BQ1gZJWDNIONjQT05q6gCA&ip=108.170.152.124&id=o-AJ0cFUuFUEfFYroovYFoj_mgH83OUCAIr0_n0E9GwQ-C&itag=251&source=youtube&requiressl=yes&mh=Cn&mm=31%2C29&mn=sn-nu5gu-tt1e%2Csn-tt1e7nls&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=23&initcwndbps=1765000&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=rB3fQ5CyFqWQ89J5unLE910N&gir=yes&clen=12455510&dur=728.181&lmt=1682472910417233&mt=1684015997&fvip=2&keepalive=yes&fexp=24007246%2C24362688&c=WEB&txp=5532434&n=RRfg9NqGm93q9g&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMZ-aq8zVvNW2qCR5Pmv1E2EVuydEVpjWctgaO1A6CA8AiEAikAPN6yfnGcD0hD_MSrvHzLt20W1Z8-WvTJerKcCHwU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGZRS_D5pHxBsjZxotXYR4VUjRcN_BBqUExlEdXWUq7ECIQCeY6KCJejruVjIbbQ_ALaqi_IXv453WFpFJMISW1yC2w%3D%3D'
[dashsegments] Total fragments: 2
[download] Destination: Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f251.webm
[download] 100% of 11.88MiB in 00:01
[ffmpeg] Merging formats into "Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f299.mp4' -i 'file:Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.temp.mkv'
Deleting original file Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f299.mp4 (pass -k to keep)
Deleting original file Antimatter Weapons - Threat or Ridiculous Pipe Dream-6zCH13oxlPc.f251.webm (pass -k to keep)
```

**Comment by dirkf** [comment] 2023-05-13 23:15
If you did something to fix #31530 before (which would also have fixed the download speed), do the same again to fix the return of #32066 (that's your "strange error"). If not, you can't have been using yt-dl for YouTube since February, but you can read #31530 to learn about the problem.

Or just stick with the unofficial nightly build, which has the same effect.

**Comment by EvilSupahFly** [comment] 2023-05-13 23:22
Yesterday was the first time since December that I used YTDL, and since the nightly build seems to fix the issue, I'm just going to stick with the nightly build for now, rather than messing around with it anymore, because I don't want to break everything again.

**Comment by dirkf** [comment] 2023-05-13 23:35
In that case, your issue is a slightly complicated duplicate of #31530, and you've found one of the suggested solutions. For now keep using and updating, if necessary, the unofficial nightly build, but do report issues here rather than in the repo from which you downloaded it.

**Closed by dirkf** 2023-05-13 23:35 UTC
