### ISSUE TITLE
vimeo.com ERROR: Unable to extract info section;

### ISSUE THREAD

**Issue by cirhosis** [ytdl-org/youtube-dl#31376] opened 2022-11-23 14:27 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://player.vimeo.com/video/774163794
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.vimeo.com/video/774163794']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[vimeo] 774163794: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\vimeo.py", line 652, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
I have tried a number of videos from this vimeo account that I successfully downloaded in the past and all of them provide the same error message as above now.

**Comment by dirkf** [comment] 2022-11-23 16:08
> I've searched the bugtracker for similar issues including closed ones

Really?
Duplicate of #31311.

**Closed by dirkf** 2022-11-23 16:08 UTC

**Comment by cirhosis** [comment] 2022-11-23 21:36
The default search is apparently only for open issues so this doesn't show up.

**Comment by dirkf** [comment] 2022-11-23 21:48
The search is for open issues, unsurprisingly, if `is:open` is a word in the search text, but not otherwise. You have to delete it from the search, or paste the search text over it.

Some other issue management tools actually do this search for you, so that when make a new issue you get prompted with a list of existing issues that might be the same problem. GH doesn't have that built-in. There's a new structure for new issues and it might be possible to add the existing issue search to that workflow.

**Comment by cirhosis** [comment] 2022-11-24 02:48
I've seen projects that maintain a list of "fixed" but not in production bugs in a single open bug to deal with this sort of thing. 
I mean the checkbox text is clear but it's an honest mistake.
