### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by YoupuZhang** [ytdl-org/youtube-dl#31667] opened 2023-02-23 18:38 UTC
I have used youtube-dl for 2 years. It worked very well. Thank you. Unfortunately, since 3 days ago, all Youtube video has given me same error message as follows. My email address is wahaha_us@yahoo.com. Thank you for all your help in advance.  

[youtube] RGrs1hX2YPE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by YoupuZhang** [comment] 2023-02-23 18:39
I have used youtube-dl for 2 years. It worked very well. Thank you. Unfortunately, since 3 days ago, all Youtube video has given me same error message as follows. My email address is wahaha_us@yahoo.com. Thank you for all your help in advance.  

[youtube] RGrs1hX2YPE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Basit2121** [comment] 2023-02-23 19:05
getting the same error , worked fine a week ago

**Comment by flomnes** [comment] 2023-02-23 19:06
> getting the same error , worked fine a week ago



> I have used youtube-dl for 2 years. It worked very well. Thank you. Unfortunately, since 3 days ago, all Youtube video has given me same error message as follows. My email address is XXX. Thank you for all your help in advance.
> 
> [youtube] RGrs1hX2YPE: Downloading webpage ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

_off-topic_
@YoupuZhang you shouldn't leave your e-mail address or you'll get a lot of spam. Crawlers will save your e-mail address and send you spam/scam/phishing/etc.

**Comment by flomnes** [comment] 2023-02-23 19:08
Possible duplicate : https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by gnat42** [comment] 2023-02-23 19:39
Looks like a duplicate of #31530
Changing /usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py similar to ytb-dl did fixes it for me locally..

**Closed** 2023-02-23 21:00 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-02-23 21:03
> [ ]  I've searched the bugtracker for similar bug reports including closed ones

Why not? #30839
