### ISSUE TITLE
svtplay.se issues

### ISSUE THREAD

**Issue by bolinder** [ytdl-org/youtube-dl#26469] opened 2020-08-29 20:24 UTC
Since a couple of days, downloads from svtplay.se (for example https://www.svtplay.se/video/27050573/mississippi-grind?start=auto) fails with the error message "Unable to extract video id".

**Comment by Surkal** [comment] 2020-08-29 20:29
Duplicate of #26428

**Closed** 2020-08-31 20:30 UTC
