### ISSUE TITLE
Dropout HTTPError 403: 'Forbidden'

### ISSUE THREAD

**Issue by adudenamedjeff** [ytdl-org/youtube-dl#31198] opened 2022-08-23 21:42 UTC
Hi there-

Been trying to download videos from dropout.tv but have been getting the following error:

```
youtube-dl "https://www.dropout.tv/hardly-working/season:1/videos/ace-ventura" --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.dropout.tv/hardly-working/season:1/videos/ace-ventura', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1, ffprobe 5.1
[debug] Proxy map: {}
[generic] ace-ventura: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ace-ventura: Downloading webpage
[generic] ace-ventura: Extracting information
[vhx:embed] 449825: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

I get a different error when I try using my login credentials ('Unsupported URL') and from what I can tell I'm using the proper cookies, however every method I've seen online and tried to follow has proven unsuccessful (opening the frame in a new tab, inspecting and digging thru the network tab, etc).

Even if no one offers any solutions to this issue, I'd sure appreciate knowing that whatever is wrong, it's something within the code/website and it's not just a user error on my part.

Thanks!

**Comment by dirkf** [comment] 2022-08-23 22:14
Dropout.tv needs its own extractor as in PR #30680 to pass the necessary authentication parameters down to the VHX:embed extractor.

**Comment by dirkf** [comment] 2022-08-23 22:19
Duplicate of #30663.

**Closed by dirkf** 2022-08-23 22:19 UTC
