### ISSUE TITLE
download from arte-tv failing

### ISSUE THREAD

**Issue by PeterSchwalm** [ytdl-org/youtube-dl#30927] opened 2022-05-08 23:57 UTC
## Checklist

- [ x] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\w1\video\mahler>youtube-dl -v https://www.arte.tv/de/videos/108664-002-A/maria-joao-pires-spielt-mozart/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.arte.tv/de/videos/108664-002-A/maria-joao-pires-spielt-mozart/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg N-104925-ga8a7c5d502-20211218
[debug] Proxy map: {}
[ArteTV] 108664-002-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


D:\w1\video\mahler>
```

## Description

WRITE DESCRIPTION HERE
I have tried some downloads from arte.tv.de, all with the same result (for instance: "https://www.arte.tv/de/videos/105085-000-A/gustav-mahler-symphonie-nr-3-d-moll/".

**Comment by dirkf** [comment] 2022-05-09 14:25
1. Use the [template](https://github.com/ytdl-org/youtube-dl/issues/30839)
2. Using the template, find that your issue is a duplicate of #30919.
3. Read the issue to understand that the site has at least partially switched to a new API for which a fix is available.
4. Help to back-port that or wait for someone else to do it.

**Closed by dirkf** 2022-05-09 14:25 UTC
