### ISSUE TITLE
Output filename broken. Cannot predict the output filename

### ISSUE THREAD

**Issue by eriktjacobsen** [ytdl-org/youtube-dl#6506] opened 2015-08-09 07:50 UTC
Running the command: 
`youtube-dl -o 77d8f26f-3685-4c87-898f-2f4d98d3532b --get-filename -- 70wDodLb-m8`

Give the following output: `77d8f26f-3685-4c87-898f-2f4d98d3532b` which is of course correct, since that is the output filename I gave it. And this often works fine.

However, sometimes the following happens:

```
$ youtube-dl -o 77d8f26f-3685-4c87-898f-2f4d98d3532b -- 70wDodLb-m8
[youtube] 70wDodLb-m8: Downloading webpage
[youtube] 70wDodLb-m8: Downloading video info webpage
[youtube] 70wDodLb-m8: Extracting video information
[youtube] 70wDodLb-m8: Downloading DASH manifest
[youtube] 70wDodLb-m8: Downloading DASH manifest
[download] Destination: 77d8f26f-3685-4c87-898f-2f4d98d3532b.f248
[download] 100% of 152.24MiB in 00:43
[download] Destination: 77d8f26f-3685-4c87-898f-2f4d98d3532b.f171
[download] 100% of 7.41MiB in 00:01
[ffmpeg] Merging formats into "77d8f26f-3685-4c87-898f-2f4d98d3532b.webm"
Deleting original file 77d8f26f-3685-4c87-898f-2f4d98d3532b.f248 (pass -k to keep)
Deleting original file 77d8f26f-3685-4c87-898f-2f4d98d3532b.f171 (pass -k to keep)
```

So the resulting filename is the argument passed to -o with a ".webm" attached. Sometimes this appears to result in a ".mkv" attached as well.

I feel like this behavior is in error, and at the very least should come back with the correct filename when "--get-filename" is used.

This is currently breaking a software chain as the resulting file cannot be found.

**Comment by dstftw** [comment] 2015-08-09 10:20
Duplicate of #5710.

**Closed by dstftw** 2015-08-09 10:20 UTC

**Comment by eriktjacobsen** [comment] 2015-08-09 20:24
Hey @dstftw, I feel this is not a duplicate because that issue has to do with the `%(ext)s` template not being correct, he expects `%(ext)s` to be filled with .webm and it gets .mkv instead.

My issue is that I have no extension in the output filename, so I feel regardless of what internal merging needs to happen, there should be no extension on the output.

I think the final stage of saving the file should respect the -o argument, especially if no extension template is given. 

Can this issue be re-opened and marked as different than that issue?

**Comment by dirkf** [comment] 2024-05-17 23:54
Use `--exec ...`.
