### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'items' with --cookies

### ISSUE THREAD

**Issue by diamondsw** [ytdl-org/youtube-dl#28652] opened 2021-04-03 22:09 UTC
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
me@kelvin.local ~ % youtube-dl -v --cookies=/Users/jochs/Sync/Dante/Development/Cookies/youtube.txt "https://www.youtube.com/watch?v=Rtsu4Wvr4Ys"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies=/Users/jochs/Sync/Dante/Development/Cookies/youtube.txt', u'https://www.youtube.com/watch?v=Rtsu4Wvr4Ys']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.16 (CPython) - Darwin-20.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-99816-g3da35b7
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2060, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 533, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 268, in _real_initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 253, in _initialize_consent
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2902, in _get_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
me@kelvin.local ~ % 
```

## Description

In the last few days (I believe starting with 2021.04.01) I've been getting the semi-generic error above from Python when attempting to use a cookies file with youtube-dl. The cookies file hasn't changed, and removing the cookies file works as expected (except of course, I can't download videos that require being logged in).

Same error occurs on Linux x64 (Synology DSM with Python 2.7.12) and with M1/ARM MacOS 11.2.3 (Python 2.7.16). I can add additional systems to test on if helpful.

**Comment by vonmillhausen** [comment] 2021-04-03 22:11
Dupe of: https://github.com/ytdl-org/youtube-dl/issues/28640

**Closed** 2021-04-03 22:43 UTC

**Comment by diamondsw** [comment] 2021-04-04 00:44
I swear-to-god I searched beforehand! Apologies!
