### ISSUE TITLE
Error 410: Gone (VRT.BE)

### ISSUE THREAD

**Issue by Glooteph** [ytdl-org/youtube-dl#26957] opened 2020-10-21 17:14 UTC
Hello, can you help to download that ? :)
With the subtitles it would be perfect.
Thank you in advance.

> C:\Users\hehe\Downloads>youtube-dl https://www.vrt.be/vrtnu/a-z/belpop/10/belpop-s10a1
> [VrtNU] belpop-s10a1: Downloading webpage
> [VrtNU] belpop-s10a1: Downloading JSON metadata
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading asset JSON
> WARNING: Unable to download asset JSON: HTTP Error 410: Gone
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading token
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading video JSON
> ERROR: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Janbong** [comment] 2020-11-16 16:10
Same problem here

**Comment by Rudu-be** [comment] 2020-11-16 18:01
Also not working here, 

```
youtube-dl is up-to-date (2020.11.12)

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vrt.be/vrtnu/a-z/corona-talks/1/corona-talks-s1a1/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.12
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg git-2020-05-10-fc99a24
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] corona-talks-s1a1: Downloading webpage
[VrtNU] corona-talks-s1a1: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwrmvn5tt\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwrmvn5tt\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by Odenorde** [comment] 2020-11-16 18:09
Still not working with latest version. Is there an alternative to download the clips provided from vrtnu.be ?

**Comment by Jan-PieterBaert** [comment] 2020-11-16 22:43
There's a thing you can do to download clips from vrtnu.be, you open the inspector and look for a file ending in `.mpd` which will come when the video is playing, so you can play the video for a few seconds and download the clip with that mpd file

**Comment by Glooteph** [comment] 2020-11-17 07:35
Hello everyone,
Actually I found just a few days ago a website which does the job.
It downloads in SD but anyways, I did not find anything else. I can give you later the URL as I am at work right now.
If you ever find a solution to grab the subtitles I'll always be interested.

See you later!

**Comment by Odenorde** [comment] 2020-11-17 07:48
> Hello everyone,
> Actually I found just a few days ago a website which does the job.
> It downloads in SD but anyways, I did not find anything else. I can give you later the URL as I am at work right now.
> If you ever find a solution to grab the subtitles I'll always be interested.
> 
> See you later!

Happy to hear there are other solutions. Can you provide the link to the website which does the job?

About the subtitles: aren't these hard coded in the video on vrtnu? I've downloaded with youtubedl in the past with vrtnu.be and the subs are always hard coded in the movie. (if applicable)

**Comment by Rudu-be** [comment] 2020-11-17 11:01
Just updated to new version
`youtube-dl is up-to-date (2020.11.17)`

Error stays

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vrt.be/vrtnu/a-z/corona-talks/1/corona-talks-s1a1/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg git-2020-05-10-fc99a24
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] corona-talks-s1a1: Downloading webpage
[VrtNU] corona-talks-s1a1: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpa0zbt1ts\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by Rudu-be** [comment] 2020-11-19 11:28
The merge/commit has failed. Cam you retry?

**Comment by blackrum** [comment] 2020-11-19 17:22
Same error here as well, youtube-dl is up-to-date (2020.11.19). Any idea how to fix it?

**Comment by Odenorde** [comment] 2020-11-19 17:23
Problem still exists in version (2020.11.19)
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug ...

**Comment by Glooteph** [comment] 2020-11-19 19:02
Well, should I retry or it won't work ?

**Comment by Jan-PieterBaert** [comment] 2020-11-19 19:23
The fix provided in #27053 seems to work for me, so I guess the fix is either compiling your own version with those additions or waiting for it to be merged

**Comment by janvankerckhoven** [comment] 2020-11-20 19:34
> Still not working with latest version. Is there an alternative to download the clips provided from vrtnu.be ?

downloadgemist.nl

**Comment by Rudu-be** [comment] 2020-11-24 14:09
Hello, updated to 2020.11.24, not working.

What is the normal delay for a merge to be incoroporated in the official build?

**Comment by blackrum** [comment] 2020-12-01 18:46
Updated to version 29.11, unfortunately not working.

**Comment by Jan-PieterBaert** [comment] 2020-12-01 20:16
#26957 hasn't been merged yet, so it's logical that it's not working

**Comment by sharethewisdom** [comment] 2020-12-02 10:26
> What is the normal delay for a merge to be incoroporated in the official build?

It will probably take some time. Clone the repo, enter the directory, and run something like (assuming your user/passwd is in .netrc):

```
python -m youtube_dl -n https://www.vrt.be/vrtnu/a-z/terzake.relevant/
```

**Comment by vdmkenny** [comment] 2020-12-11 17:00
+1, broken for me as well.

**Comment by BelgianNoise** [comment] 2020-12-31 16:29
2020.12.31 still not working

**Closed** 2021-01-05 20:20 UTC

**Comment by Odenorde** [comment] 2021-01-07 09:08
With version 2021.01.03 still not working, I guess the fix hasn't merged yet?
```
C:\YoutubeDL> .\youtube-dl.exe --update
youtube-dl is up-to-date (2021.01.03)
C:\YoutubeDL> .\youtube-dl.exe -F https://www.vrt.be/vrtnu/a-z/spookuil/2018/spookuil/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.vrt.be/vrtnu/a-z/spookuil/2018/spookuil/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.01.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-03-24-e5d25d1
[debug] Proxy map: {}
[VrtNU] spookuil: Downloading webpage
[VrtNU] spookuil: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7n_m4vnl\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by remitamine** [comment] 2021-01-07 09:17
the fix will be included in the next release.
