### ISSUE TITLE
Receiving ExtractorError when using youtube-dl in python discord bot

### ISSUE THREAD

**Issue by benwornes** [ytdl-org/youtube-dl#26137] opened 2020-07-27 21:42 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\ben>youtube-dl https://www.youtube.com/watch?v=dQw4w9WgXcQ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] {18} signature length 104, html5 player f82a8c37
[youtube] dQw4w9WgXcQ: Downloading player https://www.youtube.com/s/player/f82a8c37/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 2106, in _real_extract
    signature = self._decrypt_signature(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1435, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1425, in _decrypt_signature
    func = self._extract_signature_function(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 91, in interpret_expression
    right_val = self.interpret_expression(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 188, in interpret_expression
    x, abort = self.interpret_statement(
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\ben\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I came back to my python discord bot earlier today, but youtube-dl seems to have broken.

My youtube-dl is fully updated to the newest version yet I am receiving errors when trying to download videos.

I honestly have no clue why this is happening, this is the exact same version I was using a couple of weeks ago and it worked, yet now it does not.

At first I thought it was an issue with the youtube-dl python interface, but I tried it in the regular command prompt and the exact same error still occurs.

(Please note, whilst the youtube URL given in my verbose log is indeed the "Rick Roll" link, this is only because I was testing this particular link in my discord server. This error still occurs no matter what link I type into console)

I would appreciate help.

Thanks, Ben

**Comment by splattadat** [comment] 2020-07-27 21:46
Duplicate of ...
https://github.com/ytdl-org/youtube-dl/issues/26136
https://github.com/ytdl-org/youtube-dl/issues/26135
https://github.com/ytdl-org/youtube-dl/issues/26134

**Closed** 2020-07-27 22:06 UTC
