### ISSUE TITLE
[VK] Publicly available video require user creds

### ISSUE THREAD

**Issue by betterthanever2** [ytdl-org/youtube-dl#31044] opened 2022-06-21 16:05 UTC
I'm using the latest version of the app.
The output is:
```[vk] -52620949_456247126: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\***\YoutubeDL.py", line 815, in wrapper
  File "C:\***\YoutubeDL.py", line 836, in __extract_info
  File "C:\***\common.py", line 534, in extract
  File "C:\***\vk.py", line 325, in _real_extract
  File "C:\***\vk.py", line 72, in _download_payload
  File "C:\***\common.py", line 943, in raise_login_required
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials. ```

[Video](https://vk.com/video-52620949_456247126) in the example is available without registration. Haven't used the app in the last few days; apparently VK's auth mechanism has changed - perhaps, this affects the public vids, too, somehow.

**Comment by rautamiekka** [comment] 2022-06-21 16:28
Give the full but censored verbose log.

**Comment by betterthanever2** [comment] 2022-06-21 16:33
> Give the full but censored verbose log.

Removed the paths. I hope this is what you meant.

**Comment by dirkf** [comment] 2022-06-22 11:00
Duplicate of #30135, unless OP can show any reason why not.

The problem is explained in the original issue.

**Comment by betterthanever2** [comment] 2022-06-22 11:13
> The problem is explained in the original issue.

Found the issue by manually putting its number in the URL. You are right, it is explained there. I got confused by the title, which has to do with private videos and not public ones. Thank you.

**Comment by dirkf** [comment] 2022-06-22 11:20
Typo fixed!

**Closed** 2022-06-22 11:21 UTC
Labels: duplicate
