### ISSUE TITLE
[pluralsight.com] Second video cannot be downloaded due to ExtractorError: No video formats found

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [ytdl-org/youtube-dl#24592] opened 2020-04-03 09:31 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'/nas_share/Multimedia/pluralsight/scripts/cookies.txt', u'--limit-rate', u'500K', u'--verbose', u'--sleep-interval', u'120', u'--max-sleep-interval', u'360', u'--playlist-start', u'1', u'--autonumber-start', u'1', u'https://www.pluralsight.com/courses/electron-fundamentals', u'-o', u'/nas_share/Multimedia/pluralsight/multi_download/electron-01-electron-fundamentals/%(autonumber)s-%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-50-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] electron-fundamentals: Downloading JSON metadata
[download] Downloading playlist: Electron Fundamentals
[pluralsight:course] playlist Electron Fundamentals: Collected 33 video ids (downloading 33 of them)
[download] Downloading video 1 of 33
[pluralsight] electron-fundamentals-m0-0: Downloading JSON metadata
[pluralsight] electron-fundamentals-m0-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] electron-fundamentals-m0-0: Waiting for 5 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://vid.pluralsight.com/clips/resolution/d9e2b424-8909-40fd-be61-804db1d992e8/current/mp4/1280x720.mp4?-ij9PdeK0IRTZJ4YFE73HyaktnLd1p9_Y10KrtmfyzBpe1pvdDZXaxEWW0wXtjrQEiy0IFxkMz5dTZF0sZmJLZgSFopVMi5nfoPdDXf_i-wn1NNopuhApj7WXu1BXVnm-ZThB6h8okIbfCuNfTfBBxQ7JtQUiWFuc4oiw-I6ytZar2rNbA52fsrTTx9l'
[download] Sleeping 250.78 seconds...
[download] Destination: /nas_share/Multimedia/pluralsight/multi_download/electron-01-electron-fundamentals/00001-Course Overview.mp4
[download] 100% of 3.06MiB in 00:06
[download] Downloading video 2 of 33
[pluralsight] electron-fundamentals-m1-0: Downloading JSON metadata
[pluralsight] electron-fundamentals-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] electron-fundamentals-m1-0: Waiting for 4 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

While trying to download pluralsight course `https://www.pluralsight.com/courses/electron-fundamentals'` application successfully downloads only first video, although from the logs it says that it found 33 videos. Second video download fails with error `ERROR: No video formats found; `

I've checked similar issues but could not find any other with the same reason.

**Comment by bonfy** [comment] 2020-04-03 11:28
I met the same problem and solved with `--cookies cookie.txt`

1. use a tool to export cookies from your browser(if using chrome tool cookies.txt).  Must be a Netscape HTTP Cookie File (txt style)
2. Add `--cookies cookie.txt`
3. Notice the txt file must use tab not space

**Comment by objque** [comment] 2020-04-03 11:34
@bonfy did you try to download more than one video in the course? i pass the cookies and got error while tried to download second video

**Comment by bonfy** [comment] 2020-04-03 11:38
I found I downloaded 9/21 videos and finally failed....

**Comment by dstftw** [comment] 2020-04-03 14:08
You must provide account credentials for any work on this.

**Comment by grzegorz-wolszczak** [comment] 2020-04-03 14:17
@dstftw Why did you close this issue ? I know it needs account and I will provide it. Will you reopen the ticket then ?

**Comment by grzegorz-wolszczak** [comment] 2020-04-03 14:40
@bonfy I used chrome with plugin cookies.txt. I've saved the cookies and used it as the parameter for the ytdl app. It allowed me to successfully login and start downloading first video. But the second immediately failed. I see two options here:
  1. There is a bug (more probable possibility) in ytdl, bug because pluralsight had updated some api etc. and ytdl did not caught up with the changes. 
  2. Some important cookies expired during the downloading process (more probable possibility). This seems less probable because I used the same cookies.txt file with three consequitive attempts and each time ytdl successfully downloaded first video. If the cookie really expiered, I would not be able to download event the first one (or ytdl would not be able to login at all)

**Comment by objque** [comment] 2020-04-03 17:55
it will be great to save this recommended flags in the driver as comment or something like that

**Comment by kimsagro1** [comment] 2020-04-04 23:24
@dstftw I have provided account credentials below:

```
username: tipigo3006@ualmail.com
password: Monday1!
```

**Comment by iamcoming94** [comment] 2020-04-05 00:52
I am having the same issue also. Managed to download first video only and getting error "No video formats found" in the following video.
my command was "youtube-dl --batch-file batch-file.txt" where I have put courses inside the batch-file.txt

**Comment by grzegorz-wolszczak** [comment] 2020-04-05 06:52
@dstftw will you reopen the issue ? kimsagro1 provided the account you needed.

**Comment by dirkf** [comment] 2022-02-07 12:36
Duplicate of #27991, now.

See #29234.

**Closed by dirkf** 2022-02-07 12:36 UTC
Labels: account-needed
