### ISSUE TITLE
Please add support for france.tv

### ISSUE THREAD

**Issue by soig** [ytdl-org/youtube-dl#31233] opened 2022-09-12 19:51 UTC
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

youtube-dl doesn't support downloading replay videos from france.tv.
Here's an example with full up to date youtube-dl

$ youtube-dl https://www.france.tv/france-4/il-etait-une-fois-la-vie/saison-1/1388031-la-moelle-osseuse.html[FranceTVSite] 1388031-la-moelle-osseuse: Downloading webpage
[FranceTV] cf6701dc-5493-4173-a6f0-8bb4efb87597: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

It should be pretty straightforward to add support for it, it looks like standard chunks of video.

Please add support for that website.
Thanks

**Comment by dirkf** [comment] 2022-09-12 20:11
> I've searched the bugtracker for similar site feature requests including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+france.tv:
```
10 Open 28 Closed
```
Duplicate of #29956, unless you can argue otherwise

**Closed by dirkf** 2022-09-12 20:11 UTC

**Comment by soig** [comment] 2022-11-17 15:18
OK no problem, I've switched to yt-dlp and we're considering dropping youtube-dl from the distribution…
