### ISSUE TITLE
Unable to extract nsig function code with 2024.07.25

### ISSUE THREAD

**Issue by yanmiao2** [ytdl-org/youtube-dl#32888] opened 2024-07-31 21:47 UTC
## Checklist

- [X] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**. No, using **2024.07.25**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=ab8EQZSWQOk', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2024.07.25 [e1b3fa242]
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-44-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] ab8EQZSWQOk: Downloading webpage
[youtube] ab8EQZSWQOk: Downloading player 20dfca59
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1690, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1690, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 879, in wrapper
    return func(self, *args, **kwargs)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 975, in __extract_info
    ie_result = ie.extract(url)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1725, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
  File "/home/cps/.local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig function code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
```

## Description

Using the latest 2024.07.25 version and already checked https://github.com/ytdl-org/youtube-dl/issues/30839, still having issue with simple command like `youtube-dl https://www.youtube.com/watch?v=ab8EQZSWQOk `

**Comment by SamDDBS** [comment] 2024-07-31 23:32
Will ditto that i have this same issue, also version 2024.07.25. Tried downloading a playlist and got the same errors for every video it tried
[bugreport.txt](https://github.com/user-attachments/files/16448059/bugreport.txt)

**Comment by Haifen** [comment] 2024-08-01 00:36
Confirming the same issue, commit [e1b3fa2 (AKA 2024.07.25 I guess :shrug:)](https://github.com/ytdl-org/youtube-dl/commit/e1b3fa242cb94eb9dc949ab3f2cace91c46f11bf).  Output of `youtube-dl --verbose -F https://youtu.be/tSMR2Lf40X4` is attached.
[youtube-dl_--verbose_-F_https___youtu.be_tSMR2Lf40X4-output-2024073101.txt](https://github.com/user-attachments/files/16448280/youtube-dl_--verbose_-F_https___youtu.be_tSMR2Lf40X4-output-2024073101.txt)
Also confirming this is a likely duplicate of #32885 (@dirkf references [yt-dlt/yt-dlp#10608](https://github.com/yt-dlp/yt-dlp/issues/10608), which in turn references [yt-dlt/yt-dlp#10611](https://github.com/yt-dlp/yt-dlp/pull/10611), which may be possible to merge into youtube-dl (not tried to merge from yt-dlp's extractor into youtube-dl's).

**Comment by ShantanuNair** [comment] 2024-08-01 02:18
The [fix](https://github.com/yt-dlp/yt-dlp/pull/10611) is in the [2024.08.01.000109 master release](https://github.com/yt-dlp/yt-dlp-master-builds/releases/tag/2024.08.01.000109#changelog).

**Comment by yanmiao2** [comment] 2024-08-01 02:45
> The [fix](https://github.com/yt-dlp/yt-dlp/pull/10611) is in the [2024.08.01.000109 master release](https://github.com/yt-dlp/yt-dlp-master-builds/releases/tag/2024.08.01.000109#changelog).

I'm quite confused, the link you gave points a different repo `yt-dpl`, isn't that a different library this (`youtube-dl`)?

**Comment by rasterfarm** [comment] 2024-08-01 04:40
diff --git a/test/test_youtube_signature.py b/test/test_youtube_signature.py
index 5b4aa3a..ecb2ee9 100644
--- a/test/test_youtube_signature.py
+++ b/test/test_youtube_signature.py
@@ -168,7 +168,7 @@ _NSIG_TESTS = [
     ),
     (
         'https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js',
-        'lL46g3XifCKUZn1Xfw', 'z767lhet6V2Skl',
+        '-fLCxedkAk4LUTK2', 'O8kfRq1y1eyHGw',
     ),
     (
         'https://www.youtube.com/s/player/5604538d/player_ias.vflset/en_US/base.js',
diff --git a/youtube_dl/extractor/youtube.py b/youtube_dl/extractor/youtube.py
index 84371ff..e994b2e 100644
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -1657,26 +1657,38 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
         return ret
 
     def _extract_n_function_name(self, jscode):
-        func_name, idx = self._search_regex(
-            # new: (b=String.fromCharCode(110),c=a.get(b))&&c=nfunc[idx](c)
-            # or:  (b="nn"[+a.D],c=a.get(b))&&(c=nfunc[idx](c)s
-            # old: .get("n"))&&(b=nfunc[idx](b)
-            # older: .get("n"))&&(b=nfunc(b)
+        # Examples (with placeholders nfunc, narray, idx):
+        # *  .get("n"))&&(b=nfunc(b)
+        # *  .get("n"))&&(b=narray[idx](b)
+        # *  b=String.fromCharCode(110),c=a.get(b))&&c=narray[idx](c)
+        # *  a.D&&(b="nn"[+a.D],c=a.get(b))&&(c=narray[idx](c),a.set(b,c),narray.length||nfunc("")
+        # *  a.D&&(PL(a),b=a.j.n||null)&&(b=narray[0](b),a.set("n",b),narray.length||nfunc("")
+        funcname, idx = self._search_regex(
             r'''(?x)
-                (?:\(\s*(?P<b>[a-z])\s*=\s*(?:
-                    String\s*\.\s*fromCharCode\s*\(\s*110\s*\)|
-                    "n+"\[\s*\+?s*[\w$.]+\s*]
-                )\s*,(?P<c>[a-z])\s*=\s*[a-z]\s*)?
-                \.\s*get\s*\(\s*(?(b)(?P=b)|"n{1,2}")(?:\s*\)){2}\s*&&\s*\(\s*(?(c)(?P=c)|b)\s*=\s*
-                (?P<nfunc>[a-zA-Z_$][\w$]*)(?:\s*\[(?P<idx>\d+)\])?\s*\(\s*[\w$]+\s*\)
-            ''', jscode, 'Initial JS player n function name', group=('nfunc', 'idx'))
-        if not idx:
-            return func_name
+            (?:
+                \.get\("n"\)\)&&\(b=|
+                (?:
+                    b=String\.fromCharCode\(110\)|
+                    (?P<str_idx>[a-zA-Z0-9_$.]+)&&\(b="nn"\[\+(?P=str_idx)\]
+                ),c=a\.get\(b\)\)&&\(c=|
+                \b(?P<var>[a-zA-Z0-9_$]+)=
+            )(?P<nfunc>[a-zA-Z0-9_$]+)(?:\[(?P<idx>\d+)\])?\([a-zA-Z]\)
+            (?(var),[a-zA-Z0-9_$]+\.set\("n"\,(?P=var)\),(?P=nfunc)\.length)''',
+            jscode, 'n function name', group=('nfunc', 'idx'), default=(None, None))
+        if not funcname:
+            self.report_warning('Falling back to generic n function search')
+            return self._search_regex(
+                r'''(?xs)
+                \b(?P<name>[a-zA-Z0-9_$]+)\s*=\s*function\([a-zA-Z0-9_$]+\)
+                \s*\{(?:(?!\};).)+?["\']enhanced_except_''',
+                jscode, 'Initial JS player n function name', group='name')
+        elif not idx:
+            return funcname
 
         return self._parse_json(self._search_regex(
-            r'var\s+{0}\s*=\s*(\[.+?\])\s*[,;]'.format(re.escape(func_name)), jscode,
-            'Initial JS player n function list ({0}.{1})'.format(func_name, idx)),
-            func_name, transform_source=js_to_json)[int(idx)]
+            r'var\s+{0}\s*=\s*(\[.+?\])\s*[,;]'.format(re.escape(funcname)), jscode,
+            'Initial JS player n function list ({0}.{1})'.format(funcname, idx)),
+            funcname, transform_source=js_to_json)[int(idx)]
 
     def _extract_n_function_code(self, video_id, player_url):
         player_id = self._extract_player_info(player_url)

**Comment by Haifen** [comment] 2024-08-01 07:09
Did a quick & dirty cherry-pick of upstream, and was about to make a git-am patch of it, but [@rasterfarm](https://github.com/rasterfarm) was quicker on the draw, and did a better merge of upstream's changes.  Patch applies, merges (using Gentoo to test), and fixes the issue.  Would make a pull, but don't want to take credit for @bashonly and [@rasterfarm](https://github.com/rasterfarm)'s work.  Will do it if no-one else does, with full attribution.

**Comment by robybeen** [comment] 2024-08-01 08:47
which release is the newest without this issue ?

**Comment by dirkf** [comment] 2024-08-01 09:09
#32885

**Closed by dirkf** 2024-08-01 09:09 UTC

**Comment by michelcrypt4d4mus** [comment] 2024-08-24 19:49
still consistently seeing this issue on `youtube-dl` master. debug output:

```
$ youtube-dl --verbose https://www.youtube.com/watch?v=ektquhrxjAM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ektquhrxjAM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: c5098961b
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-13.6.7-arm64-arm-64bit - OpenSSL 3.3.1 4 Jun 2024
[debug] exe versions: ffmpeg 7.0.1, ffprobe 7.0.1
[debug] Proxy map: {}
[youtube] ektquhrxjAM: Downloading webpage
[youtube] ektquhrxjAM: Downloading player a87a9450
ERROR: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1680, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1660, in _extract_n_function_name
    func_name, idx = self._search_regex(
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 2108, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1725, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/repos/youtube-dl/.venv/lib/python3.12/site-packages/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig jsi, player_id, func_codefunction code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig jsi, player_id, func_codefunction code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
```

**Comment by dirkf** [comment] 2024-08-24 21:25
Please don't post in closed duplicate issues unless there is an enormouskUpdate zly good reason
