### ISSUE TITLE
Not working youtube-dl any help

### ISSUE THREAD

**Issue by 0KRISZ0** [ytdl-org/youtube-dl#28724] opened 2021-04-10 13:14 UTC
Hello Guys! Not working youtube-dl. (Version 2021.01.16 https://github.com/ytdl-org/youtube-dl/releases/tag/2021.01.16)

LOG;
2021/04/10 15:01:31 11827baa INFO Loading instances
2021/04/10 15:01:31 11827baa INFO Loading instance://9291f716-2e22-4a7a-bbca-cb61cb8dc563
2021/04/10 15:01:31 11827baa 9291f716 INFO Initialization complete
2021/04/10 15:01:31 11827baa 9291f716 INFO Auto-Starting 11827baa-02af-4cc1-8204-a7ae9b222ab8/9291f716-2e22-4a7a-bbca-cb61cb8dc563 in 500 ms...
2021/04/10 15:01:31 11827baa INFO Loading instance://611e6c66-a3fd-4100-bc82-72b7dd7033dd
2021/04/10 15:01:31 11827baa 9291f716 PLUGIN [sinusbot-commands:113:12] Loaded SinusBot Commands v1.1.2 by Jonas Bögle (@irgendwr).
2021/04/10 15:01:31 11827baa 9291f716 PLUGIN [sinusbot-commands:114:12] SinusBot v1.0.0-beta.13-dc94a7c on windows
2021/04/10 15:01:31 11827baa 9291f716 INFO script sinusbot-commands loaded
2021/04/10 15:01:31 11827baa 9291f716 PLUGIN [sinusbot-commands:221:24] command.js library not found! Please download command.js to your scripts folder and restart the SinusBot, otherwise this script will not work.
2021/04/10 15:01:31 11827baa 9291f716 PLUGIN [sinusbot-commands:222:24] command.js can be found here: https://github.com/Multivit4min/Sinusbot-Command/blob/master/command.js
2021/04/10 15:01:32 11827baa 611e6c66 INFO Initialization complete
2021/04/10 15:01:32 11827baa 611e6c66 INFO Auto-Starting 11827baa-02af-4cc1-8204-a7ae9b222ab8/611e6c66-a3fd-4100-bc82-72b7dd7033dd in 1000 ms...
2021/04/10 15:01:32 [GENERAL/FFMPEG ] INFO FFmpeg/avcodec v3747941; license: LGPL version 3 or later; 572 codecs
2021/04/10 15:01:32 [GENERAL/FFMPEG ] INFO FFmpeg/avformat v3746148; license: LGPL version 3 or later; 146 formats
2021/04/10 15:01:32 [GENERAL/YTDL ] INFO youtube-dl checking...
2021/04/10 15:01:32 11827baa 611e6c66 PLUGIN [sinusbot-commands:113:12] Loaded SinusBot Commands v1.1.2 by Jonas Bögle (@irgendwr).
2021/04/10 15:01:32 11827baa 611e6c66 PLUGIN [sinusbot-commands:114:12] SinusBot v1.0.0-beta.13-dc94a7c on windows
2021/04/10 15:01:32 11827baa 611e6c66 INFO script sinusbot-commands loaded
2021/04/10 15:01:32 11827baa 611e6c66 PLUGIN [sinusbot-commands:221:24] command.js library not found! Please download command.js to your scripts folder and restart the SinusBot, otherwise this script will not work.
2021/04/10 15:01:32 11827baa 611e6c66 PLUGIN [sinusbot-commands:222:24] command.js can be found here: https://github.com/Multivit4min/Sinusbot-Command/blob/master/command.js
2021/04/10 15:01:32 11827baa 9291f716 WARN Could not create Chat-Tabletable Chat already exists
2021/04/10 15:01:32 11827baa 9291f716 WARN Could not create WhisperReceive-Tabletable WhisperReceive already exists
2021/04/10 15:01:32 11827baa 9291f716 WARN Could not create Notifications-Tabletable Notifications already exists
2021/04/10 15:01:33 11827baa 611e6c66 WARN Could not create Chat-Tabletable Chat already exists
2021/04/10 15:01:33 11827baa 611e6c66 WARN Could not create WhisperReceive-Tabletable WhisperReceive already exists
2021/04/10 15:01:33 11827baa 611e6c66 WARN Could not create Notifications-Tabletable Notifications already exists
2021/04/10 15:01:33 [GENERAL/YTDL ] INFO youtube-dl version compatible, support enabled
2021/04/10 15:01:33 [GENERAL/!!!!!!!] NOTICE You may now configure and launch the bots from the webinterface. http://0.0.0.0:8087
2021/04/10 15:01:33 11827baa 9291f716 INFO Starting instance ts3server://127.0.0.1?port=9987&nickname=KRISZ%20BOT&password=&channel=&channelpassword=
2021/04/10 15:01:34 11827baa 611e6c66 INFO Starting instance ts3server://95.138.193.24?port=9987&nickname=KRISZ%20BOT&password=&channel=&channelpassword=
2021/04/10 15:01:35 [GENERAL/RADIO ] INFO RadioStation data loaded
2021/04/10 15:01:35 11827baa 9291f716 INFO New connection status 1; Error 0
2021/04/10 15:01:35 11827baa 9291f716 INFO New connection status 2; Error 0
2021/04/10 15:01:35 11827baa 9291f716 INFO New connection status 3; Error 0
2021/04/10 15:01:35 11827baa 9291f716 INFO New connection status 4; Error 0
2021/04/10 15:01:36 [GENERAL/RADIO ] INFO Imported radio stations
2021/04/10 15:01:36 11827baa 611e6c66 INFO New connection status 1; Error 0
2021/04/10 15:01:37 11827baa 611e6c66 INFO New connection status 2; Error 0
2021/04/10 15:01:37 11827baa 611e6c66 INFO New connection status 3; Error 0
2021/04/10 15:01:37 11827baa 611e6c66 INFO New connection status 4; Error 0
2021/04/10 15:02:16 11827baa INFO JOBS-ADD [admin] https://www.youtube.com/watch?v=XXYlFuWEuKI OK
2021/04/10 15:04:05 [GENERAL ] Shutting down... Hold on...
2021/04/10 15:04:05 11827baa 9291f716 INFO New connection status 0; Error 0
2021/04/10 15:04:05 11827baa 611e6c66 INFO New connection status 0; Error 0
2021/04/10 15:04:06 11827baa 9291f716 INFO TSClient quit.
2021/04/10 15:04:06 11827baa 611e6c66 INFO TSClient quit.
2021/04/10 15:04:08 11827baa INFO Loading instances
2021/04/10 15:04:08 11827baa INFO Loading instance://9291f716-2e22-4a7a-bbca-cb61cb8dc563
2021/04/10 15:04:08 11827baa 9291f716 INFO Initialization complete
2021/04/10 15:04:08 11827baa 9291f716 INFO Auto-Starting 11827baa-02af-4cc1-8204-a7ae9b222ab8/9291f716-2e22-4a7a-bbca-cb61cb8dc563 in 500 ms...
2021/04/10 15:04:08 11827baa INFO Loading instance://611e6c66-a3fd-4100-bc82-72b7dd7033dd
2021/04/10 15:04:08 11827baa 9291f716 PLUGIN [sinusbot-commands:113:12] Loaded SinusBot Commands v1.1.2 by Jonas Bögle (@irgendwr).
2021/04/10 15:04:08 11827baa 9291f716 PLUGIN [sinusbot-commands:114:12] SinusBot v1.0.0-beta.13-dc94a7c on windows
2021/04/10 15:04:08 11827baa 9291f716 INFO script sinusbot-commands loaded
2021/04/10 15:04:08 11827baa 9291f716 PLUGIN [sinusbot-commands:221:24] command.js library not found! Please download command.js to your scripts folder and restart the SinusBot, otherwise this script will not work.
2021/04/10 15:04:08 11827baa 9291f716 PLUGIN [sinusbot-commands:222:24] command.js can be found here: https://github.com/Multivit4min/Sinusbot-Command/blob/master/command.js
2021/04/10 15:04:08 11827baa 611e6c66 INFO Initialization complete
2021/04/10 15:04:08 11827baa 611e6c66 INFO Auto-Starting 11827baa-02af-4cc1-8204-a7ae9b222ab8/611e6c66-a3fd-4100-bc82-72b7dd7033dd in 1000 ms...
2021/04/10 15:04:08 [GENERAL/FFMPEG ] INFO FFmpeg/avcodec v3747941; license: LGPL version 3 or later; 572 codecs
2021/04/10 15:04:08 [GENERAL/FFMPEG ] INFO FFmpeg/avformat v3746148; license: LGPL version 3 or later; 146 formats
2021/04/10 15:04:08 [GENERAL/YTDL ] INFO youtube-dl checking...
2021/04/10 15:04:08 11827baa 611e6c66 PLUGIN [sinusbot-commands:113:12] Loaded SinusBot Commands v1.1.2 by Jonas Bögle (@irgendwr).
2021/04/10 15:04:08 11827baa 611e6c66 PLUGIN [sinusbot-commands:114:12] SinusBot v1.0.0-beta.13-dc94a7c on windows
2021/04/10 15:04:08 11827baa 611e6c66 INFO script sinusbot-commands loaded
2021/04/10 15:04:08 11827baa 611e6c66 PLUGIN [sinusbot-commands:221:24] command.js library not found! Please download command.js to your scripts folder and restart the SinusBot, otherwise this script will not work.
2021/04/10 15:04:08 11827baa 611e6c66 PLUGIN [sinusbot-commands:222:24] command.js can be found here: https://github.com/Multivit4min/Sinusbot-Command/blob/master/command.js
2021/04/10 15:04:08 11827baa 9291f716 WARN Could not create Chat-Tabletable Chat already exists
2021/04/10 15:04:08 11827baa 9291f716 WARN Could not create WhisperReceive-Tabletable WhisperReceive already exists
2021/04/10 15:04:08 11827baa 9291f716 WARN Could not create Notifications-Tabletable Notifications already exists
2021/04/10 15:04:09 11827baa 9291f716 INFO Starting instance ts3server://127.0.0.1?port=9987&nickname=KRISZ%20BOT&password=&channel=&channelpassword=
2021/04/10 15:04:09 [GENERAL/YTDL ] INFO youtube-dl version compatible, support enabled
2021/04/10 15:04:09 [GENERAL/!!!!!!!] NOTICE You may now configure and launch the bots from the webinterface. http://0.0.0.0:8087
2021/04/10 15:04:10 11827baa 611e6c66 WARN Could not create Chat-Tabletable Chat already exists
2021/04/10 15:04:10 11827baa 611e6c66 WARN Could not create WhisperReceive-Tabletable WhisperReceive already exists
2021/04/10 15:04:10 11827baa 611e6c66 WARN Could not create Notifications-Tabletable Notifications already exists
2021/04/10 15:04:10 [GENERAL/RADIO ] INFO RadioStation data loaded
2021/04/10 15:04:10 11827baa 611e6c66 INFO Starting instance ts3server://95.138.193.24?port=9987&nickname=KRISZ%20BOT&password=&channel=&channelpassword=
2021/04/10 15:04:11 [GENERAL/RADIO ] INFO Imported radio stations
2021/04/10 15:04:13 11827baa 9291f716 INFO New connection status 1; Error 0
2021/04/10 15:04:13 11827baa 9291f716 INFO New connection status 2; Error 0
2021/04/10 15:04:13 11827baa 9291f716 INFO New connection status 3; Error 0
2021/04/10 15:04:13 11827baa 9291f716 INFO New connection status 4; Error 0
2021/04/10 15:04:13 11827baa 611e6c66 WARN Could not send config: HTTP returned an error: Error; Code: 500; Message: Error
2021/04/10 15:04:14 11827baa 611e6c66 INFO New connection status 1; Error 0
2021/04/10 15:04:14 11827baa 611e6c66 INFO New connection status 2; Error 0
2021/04/10 15:04:14 11827baa 611e6c66 INFO New connection status 3; Error 0
2021/04/10 15:04:14 11827baa 611e6c66 INFO New connection status 4; Error 0
2021/04/10 15:04:23 11827baa INFO JOBS-ADD [admin] https://www.youtube.com/watch?v=XXYlFuWEuKI OK

ERROR: (Photo)
![error](https://user-images.githubusercontent.com/82272112/114270973-df86a280-9a17-11eb-8368-2424cf142970.png)

**Comment by evolutionxbox** [comment] 2021-04-10 14:02
You've dumped a big log, but what is the actual problem?

**Comment by 0KRISZ0** [comment] 2021-04-10 14:15
@evolutionxbox The thing in the picture is the problem

**Comment by irgendwr** [comment] 2021-04-10 21:41
@0KRISZ0 please close this issue.
You are posting output of a software that is not youtube-dl and this is even using an outdated version of youtube-dl.

Either you:
1. Reproduce the issue by **just using youtube-dl** from the command line and open an new issue with **only** the youtube-dl output.
2. or you look in the [forum of the software that you are using](https://forum.sinusbot.com/).

Please don't annoy the youtube-dl maintainers, they are dealing with enough crap already.

While I'm at it: I'm only here because you tagged me by posting this long log with `@irgendwr` in it. Next time, please put it in a code block like this:

    ```
    your log here
    ```

**Closed** 2021-04-11 07:33 UTC
Labels: question
