### ISSUE TITLE
[prosiebensat1] Unable to extract clip id from galileo.tv addresses

### ISSUE THREAD

**Issue by rozhl** [ytdl-org/youtube-dl#28732] opened 2021-04-11 08:17 UTC
However the same video downloads when pointed to https://www.prosieben.de/tv/galileo/videos/... address.

**Comment by TheChatty** [comment] 2021-04-13 21:21
Following output contains example URL which does not work:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.galileo.tv/video/tschernobyl-die-wolke-ueber-deutschland/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-12-15-git-32586a42da-full_build-www.gyan.dev
[debug] Proxy map: {}
[prosiebensat1] tschernobyl-die-wolke-ueber-deutschland/: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\prosiebensat1.py", line 495, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\prosiebensat1.py", line 436, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jensbocklage** [comment] 2021-08-22 16:49
am I missing something in my pull request?

**Comment by dirkf** [comment] 2022-09-01 13:29
Duplicate of #28464.

**Closed by dirkf** 2022-09-01 13:29 UTC
