### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by sawaiborkar** [ytdl-org/youtube-dl#31834] opened 2023-03-14 04:56 UTC
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=t1CvR71yjGk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {'ftp': 'http://172.1.0.15:81', 'https': 'http://172.1.0.15:81', 'http': 'http://172.1.0.15:81'}
[youtube] t1CvR71yjGk: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/youtube-dl/./youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/opt/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Using any YouTube link is throwing up the above error.

**Comment by riprwwa** [comment] 2023-03-14 05:12
Duplicate of this https://github.com/ytdl-org/youtube-dl/issues/31530
Issue quoted above also suggests workarounds/fixes https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

**Comment by rachancheet** [comment] 2023-03-14 06:27
https://github.com/yt-dlp/yt-dlp/issues/6247

**Closed** 2023-03-14 10:13 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-03-14 10:23
>[ ] I'm reporting a broken site support issue

No, you are, even though you shouldn't have been.

>[x] I've searched the bugtracker for similar bug reports including closed ones

Learn how by reading #30839 (**again**?).

>[x] I've read bugs section in FAQ

Also apply this.
