### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by kkbits** [ytdl-org/youtube-dl#30372] opened 2021-12-15 13:01 UTC
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Uz3TV5PpAss']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.19
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Uz3TV5PpAss: Downloading webpage
[youtube] {18} signature length 106, html5 player 204bfffb
[youtube] Uz3TV5PpAss: Downloading player https://www.youtube.com/s/player/204bfffb/player_ias.vflset/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1127, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1202, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1127, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1202, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1127, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1202, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1910, in _real_extract
    signature = self._decrypt_signature(
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1127, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 1202, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/home/kkbits/.local/lib/python3.8/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by KSE-MD** [comment] 2021-12-15 13:05
I also just had this same issue today.
Affects any video direct or via a playlist.

**Comment by dirkf** [comment] 2021-12-15 13:10
Duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), with fix.

Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, kindly close this issue

@brad-tech-dev, @UnixCro, @AdityaKhedkar-2003, @seahorse41, this applies to you too.

**Comment by kkbits** [comment] 2021-12-15 13:20
@dirkf 
Im very sorry, and please do not be mad at me, but generaly im absolutely short on time.
I thought I'm doing a favor to the project, to post the error message with --verbose how it is desired by the command itself.
if it is not an advantage that I post the issue in that way, the next time I can refrain from doing it.

**Comment by dirkf** [comment] 2021-12-15 13:29
It can be helpful to post a log in the existing issue if it's significantly different from the one posted there, but you have to find that issue; the template asks you to try that before opening a new one.

The project set up the issue templates to help you report your problem so that it can easily be resolved, and that's why it's unfortunate if people ignore them. Do continue to report issues if you find them and they are not already reported.

**Comment by UnixCro** [comment] 2021-12-15 13:37
@dirkf Bro how can it actually be that this error appeared overnight.  Why does youtube-dl not work exactly.  I haven't changed anything and I need it for my work

**Comment by dirkf** [comment] 2021-12-15 14:32
Blame Youtube. You can read about it in issue #30363 and its links.

**Closed** 2021-12-16 18:42 UTC
