### ISSUE TITLE
Downloading the audio with the language tag

### ISSUE THREAD

**Issue by astrid79** [ytdl-org/youtube-dl#26816] opened 2020-10-06 05:47 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I do not know if it is possible to download it with the language tag selected from the list, I decided to ask here because I cannot handle this.

here I want to download the audio file with the language tag (like `[de]`) instead of the format code.
```
format code  extension  resolution note
1            m4a        audio only [en] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
3            m4a        audio only [fr] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
2            m4a        audio only [de] DASH audio  128k , m4a_dash container, mp4a.40.2 (44100Hz)
4            mp4        512x288    DASH video  763k , mp4_dash container, avc1.4d4015, video only
5            mp4        768x432    DASH video 1863k , mp4_dash container, avc1.4d401e, video only
6            mp4        1280x720   DASH video 3312k , mp4_dash container, avc1.4d401f, video only
7            mp4        1280x720   DASH video 4277k , mp4_dash container, avc1.64001f, video only
8            mp4        1920x1080  DASH video 5756k , mp4_dash container, avc1.640028, video only (best)
```

**Comment by Fetchinator7** [comment] 2020-10-11 02:01
Will you please post the link to the video? (I've never seen that on a video before.)

**Comment by astrid79** [comment] 2020-10-12 13:57
> Will you please post the link to the video? (I've never seen that on a video before.)

I prepared the above output as an example.

You can check the "Angel One" video on this page as an example demo.
https://shaka-player-demo.appspot.com/demo
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by pukkandan** [comment] 2020-10-17 10:28
The language information is stored with the key "language". So I expected `-f bestaudio[language=en]` to work, but sadly it doesn't . The issue is that the fields available for filtering [is hard-coded in](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1049). You can use your own version with `language` added in as a field as a workaround. Or, you can try writing a bash script to get the format id from the `-F`. I doubt there is any other way.

**Comment by pukkandan** [comment] 2020-10-17 11:06
I have created a pull request that solves this issue. 

In case the pull request doesn't get merged, you can check out [my fork](https://github.com/pukkandan/youtube-dl#changes).

PS: @dstftw, please don't delete the reference to my fork. I am only providing the link because the feature has not been implemented (and honestly is unlikely to ever be implemented) in the this repo despite the pull request. It is not like I am profiting off of it. If you are removing the references, please at least give me a reason why.

**Comment by dstftw** [comment] 2020-10-17 11:09
Promoting any 3rd party forks/app is consedered spam.

**Comment by pukkandan** [comment] 2020-10-17 11:13
@dstftw I'm only trying to help. But your repo, your rules. I will make sure not to do this again.

**Comment by astrid79** [comment] 2020-10-17 15:21
> The language information is stored with the key "language". So I expected `-f bestaudio[language=en]` to work, but sadly it doesn't . The issue is that the fields available for filtering [is hard-coded in](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1049). You can use your own version with `language` added as filterable field. Or, you can try writing a bash script to get the format id from the `-F`. I doubt there is any other way.

@pukkandan Thank you for your interest, yes I've tried this `-f bestaudio[language=en]` before, but it did not work.  I can actually parse it with python and write my own custom code, but it would be more useful to have this feature on youtube-dl
@dstftw It would be great if you could do some update for that.

**Closed** 2020-10-17 16:03 UTC
Labels: question

**Comment by pukkandan** [comment] 2020-10-18 16:33
@astrid79 Yes, it would be enough to add language to the regex to solve this specific issue. However, my method (relaxing the regex to accept any field) has the advantage that the user can filter by any key that the extractor makes available.

**Comment by astrid79** [comment] 2020-10-18 20:37
> @astrid79 Yes, it would be enough to add language to the regex to solve this specific issue. However, my method (relaxing the regex to accept any field) has the advantage that the user can filter by any key that the extractor makes available - `filesize`, or `format_note` for example.

Thank you for your explanatory answers, I'm grateful.
