### ISSUE TITLE
Issue downloading more than 100 tracks of a private playlist (YT Music)

### ISSUE THREAD

**Issue by Fusseldieb** [ytdl-org/youtube-dl#29656] opened 2021-07-26 15:29 UTC
Hi,
as the title implies I'm trying to download my "VIdeos that I liked" playlist off of YouTube to play it in my car.

I used the command

`youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 https://music.youtube.com/playlist?list=LM --cookies /home/fusseldieb/Downloads/youtube.com_cookies.txt`

and that worked perfectly, however it said that it would download 100 videos.

After finishing 100, I thought I'd specify another 100, with

`youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 https://music.youtube.com/playlist?list=LM --cookies /home/fusseldieb/Downloads/youtube.com_cookies.txt --playlist-start 101 --playlist-end 200`

However, it resulted in:

```
[youtube:tab] LM: Downloading webpage
[download] Downloading playlist: Songs, die ich mag
[youtube:tab] Downloading page 1
[youtube:tab] playlist Songs, die ich mag: Downloading 0 videos
[download] Finished downloading playlist: Songs, die ich mag
```

Trying to get the rason why it wasn't working, I specified the parameter "--write-pages"

Which gave me the following in the output file:

```
"alerts": [
    {
      "alertRenderer": {
        "type": "ERROR",
        "text": {
          "runs": [
            {
              "text": "Diese Playlist ist privat."
            }
          ]
        }
      }
```
Translating to "This playlist is private".

I don't know what it might be...

**Comment by przemub** [comment] 2021-07-26 19:14
I have the exact same issue but about my liked videos in "normal" YouTube.

**Comment by pukkandan** [comment] 2021-07-27 10:27
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/28362, https://github.com/ytdl-org/youtube-dl/issues/28788

**Closed** 2023-11-01 15:17 UTC
Labels: duplicate
