### ISSUE TITLE
URL format recently changed on https://www.ceskatelevize.cz

### ISSUE THREAD

**Issue by zprecek** [ytdl-org/youtube-dl#31223] opened 2022-09-04 08:25 UTC
URL format on www.ceskatelevize.cz changed recently from something like `'http://www.ceskatelevize.cz/ivysilani/ivysilani/10441294653-hyde-park-civilizace/214411058091220'`
to:
`https://www.ceskatelevize.cz/porady/16086-bila-pani/29238360926/`.
As a result, the extractor is failing constantly:
```
$ youtube-dl -t --verbose https://www.ceskatelevize.cz/porady/16086-bila-pani/29238360926/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-t', '--verbose', 'https://www.ceskatelevize.cz/porady/16086-bila-pani/29238360926/']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.15.0-46-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[CeskaTelevizePorady] 29238360926: Downloading webpage
ERROR: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ceskatelevize.py", line 282, in _real_extract
    data_url = update_url_query(unescapeHTML(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment] 2022-09-04 11:10
Not that recently, though. Duplicate of #30406.

Please test PR #30713 if you can.

**Comment by dirkf** [comment] 2022-09-21 12:27
Discussion can continue under PR #30713.

**Closed by dirkf** 2022-09-21 12:27 UTC
Labels: broken-IE, duplicate
