### ISSUE TITLE
Udemy - HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Zeddex** [ytdl-org/youtube-dl#29924] opened 2021-09-08 11:01 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS D:\temp\udemy\youtube-dl> ./youtube-dl.exe --cookies udemy.com_cookies.txt --verbose -o '~/udemy-blockchain/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/course/blockchain-developer
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'udemy.com_cookies.txt', '--verbose', '-o', '~/udemy-blockchain/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/course/blockchain-developer']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
[udemy:course] 1172526: Downloading course curriculum
[download] Downloading playlist: 1172526
[udemy:course] playlist 1172526: Collected 121 video ids (downloading 121 of them)
[download] Downloading video 1 of 121
[udemy] 6846516: Downloading webpage
[udemy] 6846516: Downloading lecture JSON
[udemy] 6846516: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2021-10-05 13:23
Duplicate of #29705.

**Closed** 2022-04-27 11:39 UTC
Labels: duplicate
