### ISSUE TITLE
Unable load video from VIMEO 

### ISSUE THREAD

**Issue by SergSZ** [ytdl-org/youtube-dl#31323] opened 2022-11-01 17:46 UTC
## Checklist

- [X ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://player.vimeo.com/video/759434328?h=f8fd4ac538', '--referer', 'https://thewallstreet.pro', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.1 (CPython) - Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg N-102754-g604924a069, ffprobe N-102754-g604924a069
[debug] Proxy map: {}
[vimeo] 759434328: Downloading webpage
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 651, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

May be Vimeo changes player script on JS and JSON-tracklist.

**Comment by dirkf** [comment] 2022-11-01 19:28
> [ ] I've searched the bugtracker for similar bug reports including closed ones

Why not?

Closing as incomplete duplicate of issue (fixed in git master).

**Closed by dirkf** 2022-11-01 19:28 UTC

**Comment by taai** [comment] 2022-11-05 11:41
> > [ ] I've searched the bugtracker for similar bug reports including closed ones
> 
> Why not?
> 
> Closing as incomplete duplicate of issue (fixed in git master).

@dirkf And when can we expect a release with these fixes? Latest release came out in Dec 16, 2021. Probably, people are just testing the latest version and reporting about the issues… 🤷

**Comment by 89z** [comment] 2022-11-05 12:21
> when can we expect a release with these fixes?

https://github.com/ytdl-org/youtube-dl/issues/30773#issuecomment-1283080921
