### ISSUE TITLE
Is the project up?

### ISSUE THREAD

**Issue by shrihanDev** [ytdl-org/youtube-dl#30317] opened 2021-12-04 06:40 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is the project up? The latest commit was made on Jul 1.

**Comment by nicolaasjan** [comment] 2021-12-04 11:08
It seems dead at the moment...

Search the bug tracker and you'll find some threads:
https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+is%3Aopen+dead

Common recommendation:
The [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork.

**Comment by 89z** [comment] 2021-12-04 14:00
I have an alternate package here:

https://github.com/89z/mech

**Comment by Ashish0804** [comment] 2021-12-04 15:21
Yeah it's still up on github if that's what u meant.
It did go down like 2-3 years ago bcoz of DMCA but it came back soon after that.

**Comment by nicolaasjan** [comment] 2021-12-04 18:00
> Yeah it's still up on github if that's what u meant. It did go down like 2-3 years ago bcoz of DMCA but it came back soon after that.

It's indeed 'up' here on GitHub, but the quality of the issue tracker is rapidly deteriorating due to the absence of any moderation...
A few examples:
https://github.com/ytdl-org/youtube-dl/issues/30311
https://github.com/ytdl-org/youtube-dl/issues/30281
https://github.com/ytdl-org/youtube-dl/issues/30264

**Comment by dirkf** [comment] 2021-12-07 10:53
Duplicate of #29965.

**Comment by fstirlitz** [comment] 2021-12-08 11:20
@nicolaasjan It’s not even the worst of it: #29809

**Comment by nicolaasjan** [comment] 2021-12-08 18:04
> @nicolaasjan It’s not even the worst of it: #29809

That's indeed really bad...

**Comment by dirkf** [comment] 2021-12-08 18:26
But almost worth it for @RonRicoSuave's solution, which I guess no-one tagged with a laugh just in case the OP took it seriously ... "guerilla moderation"

**Closed** 2021-12-11 12:18 UTC
Labels: question

**Comment by shrihanDev** [comment] 2021-12-18 07:35
Whoa guys there's a new release!!!

**Comment by nicolaasjan** [comment] 2021-12-18 08:42
> Whoa guys there's a new release!!!

Unfortunately very little has changed.
See also [this Reddit thread](https://old.reddit.com/r/youtubedl/comments/rhxybz/new_release_youtubedl_20211217/).

For example the [throttling issue](https://github.com/ytdl-org/youtube-dl/issues/29326) with YouTube is not fixed.
