### ISSUE TITLE
Add more streaming sites request (if possible)

### ISSUE THREAD

**Issue by gamefreak862** [ytdl-org/youtube-dl#29992] opened 2021-09-19 14:55 UTC
Would it be possible to add All4 and Britbox to youtube-dl?

**Comment by dirkf** [comment] 2021-09-19 22:51
These sites encrypt their media in a way that yt-dl doesn't understand ([Adobe PrimeTime](https://www.csimagazine.com/csi/Channel4-migrates-to-HTML5-with-Adobe-Primetime.php), WideVine, respectively).

For Britbox, duplicate of #19010

**Comment by codehound-00** [comment] 2021-09-19 22:51
It would if this project hadn't been abandoned without comment

**Closed** 2022-01-29 16:33 UTC
Labels: DRM, duplicate
