### ISSUE TITLE
Youtube-dl not working since Monterey update

### ISSUE THREAD

**Issue by Cerveus** [ytdl-org/youtube-dl#31257] opened 2022-09-25 17:54 UTC
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -x --audio-format mp3 'https://www.youtube.com/watch?v=IPb60Xi8TG0&t=1162s'
[youtube] IPb60Xi8TG0: Downloading webpage
WARNING: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
[youtube] IPb60Xi8TG0: Downloading API JSON
ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```

## Description

The issue appeared when updating to Monterey. I've tried with various videos on youtube, tried upgrading, reinstalling youtube-dl and issue persists.

**Comment by dirkf** [comment] 2022-09-25 19:17
> [ ] I've searched the bugtracker for similar issues including closed ones

The point of the template checklist is that you **read** each item in the list and **carry out the check**. Duplicate of #31189 (thx @89z): please carry on the discussion there, where the OP hasn't yet revealed whether the problem was resolved.

**Closed by dirkf** 2022-09-25 19:17 UTC

**Comment by 89z** [comment] 2022-09-25 19:54
https://github.com/ytdl-org/youtube-dl/issues/31258
