### ISSUE TITLE
Use HTTP3/QUIC for youtube downloads

### ISSUE THREAD

**Issue by stefan-walluhn** [ytdl-org/youtube-dl#30132] opened 2021-10-19 20:27 UTC
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It seems that youtube is rate limiting classical HTTP1.1 downloads since some days. I tried to use current versions of youtube-dl on different locations and datacenters in germany and france and was not able to get higher bandwidths than 60KiB/s. I  tried different external downloader (`--external-downloader`), like cUrl, ffmpeg and wget. I can reproduce the behavior with various third party apps, that also rely on classical HTTP1.1, like Kodi Mediacenter.

On the other hand I can utilize my full bandwidth if I use firefox or chromium. A short analysis with Wireshark shows, that modern browsers, that make use of HTTP3/QUIC protocol, are not affected by poor bandwidth.

Can we have HTTP3/QUIC support for youtube-dl?

**Comment by kikuyan** [comment] 2021-10-20 00:31
Probably not. youtube-dl needs to support python 2.6 or higher, and the use of external libraries is very limited.

**Comment by dirkf** [comment] 2021-10-20 10:56
* Strictly the question about HTTP3/QUIC support is not one that has been posted many times, or even at all.
* As @kikuyan says, Python2 compatibility means that some Python3 stack would have to be (probably) re-licensed and back-ported, or written from scratch (both high on the not-going-to-happen list, I would say).
* The constraints might be less onerous for yt-dlp but that doesn't answer OP's question.
* By mentioning `--external-downloader` OP has identified an answer (`--external-downloader curl --external-downloader-args '--http3'`) but an experimental build of _curl_ will be needed that supports actually using, rather than just asking for, HTTP3.

**Comment by gaming-hacker** [comment] 2021-10-21 20:01
Most recent curl versions already support --http3.  The command would be 'curl --http3 http://youtube.com/blah.blah.blah
My version
```
curl 7.78.0 (x86_64-apple-darwin17.7.0) libcurl/7.78.0 OpenSSL/3.0.0 zlib/1.2.11 zstd/1.5.0 libidn2/2.3.1 libpsl/0.21.1 (+libidn2/2.3.2)
Release-Date: 2021-07-21
```
```
     --http0.9       Allow HTTP 0.9 responses
 -0, --http1.0       Use HTTP 1.0
     --http1.1       Use HTTP 1.1
     --http2         Use HTTP 2
     --http2-prior-knowledge  Use HTTP 2 without HTTP/1.1 Upgrade
     --http3         Use HTTP v3
     --ignore-content-length  Ign
```

**Comment by coletdjnz** [comment] 2021-10-30 00:21
Interesting find. Can confirm that using QUIC/HTTP3 bypasses the need to decrypt the n-param. But it's not really feasible for youtube-dl to implement. Especially when there are better/easier solutions to this particular problem.

```
$ youtube-dl q-_7y0WUnW4 --external-downloader "/tmp/curl" --external-downloader-args "--http3"
[youtube] q-_7y0WUnW4: Downloading webpage
[download] Destination: I Rented A Helicopter To Settle A Physics Debate-q-_7y0WUnW4.f313.webm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 1018M    1 18.9M    0     0  4799k      0  0:03:37  0:00:04  0:03:33 4798k^C
ERROR: Interrupted by user
$ youtube-dl q-_7y0WUnW4 --external-downloader "/tmp/curl" --external-downloader-args "--http1.1"
[youtube] q-_7y0WUnW4: Downloading webpage
[download] Destination: I Rented A Helicopter To Settle A Physics Debate-q-_7y0WUnW4.f313.webm
** Resuming transfer from byte position 20717568
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  999M    0  144k    0     0  54942      0  5:17:47  0:00:02  5:17:45 54938^C
ERROR: Interrupted by user
```

But maybe useful to someone needing a temporary workaround and cannot use yt-dlp for whatever reason.

**Comment by zulc22** [comment] 2021-11-08 02:48
I also could not get any speeds over 60kbps in America.

**Comment by dirkf** [comment] 2023-01-29 13:28
For slow YT download, duplicate of #29326.

**Closed by dirkf** 2023-01-29 13:28 UTC
Labels: request
