### ISSUE TITLE
Youtube-dl has suddenly stopped working

### ISSUE THREAD

**Issue by Tardkiller** [ytdl-org/youtube-dl#31634] opened 2023-02-20 21:59 UTC
This is my output:

```
A:\Portable Apps\Youtube-dl>youtube-dl -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-quality 0 --audio-format mp3 https://www.youtube.com/watch?v=C0DPdy98e4c
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestaudio/best', '-ciw', '-o', '%(title)s.%(ext)s', '-v', '--extract-audio', '--audio-quality', '0', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=C0DPdy98e4c']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-12-19-git-48d5aecfc4-full_build-www.gyan.dev, ffprobe 2022-12-19-git-48d5aecfc4-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] C0DPdy98e4c: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


A:\Portable Apps\Youtube-dl>youtube-dl -U
ERROR: can't find the current version. Please try again later.

```
Anyone know what's wrong?

**Comment by cheems277** [comment] 2023-02-20 22:22
I have exactly the same problem

**Comment by GabrielNX** [comment] 2023-02-20 22:34
I have same problem

**Comment by Vangelis66** [comment] 2023-02-20 22:49
Let me repeat what I wrote in another duplicate of this: 

@Tardkiller 

You haven't followed the **recommended procedure** on submitting a new issue, now a **PINNED issue** in the main repo:

![NI](https://user-images.githubusercontent.com/9669492/220207414-6870b63d-e78a-4873-ade4-d55442c69aa9.png)

i.e. #30839 ...

Had you done that, you'd have discovered ca. **100 duplicate issues** with the **same error message**, plus links to the originating issue (now a **[megathread](https://github.com/ytdl-org/youtube-dl/issues/31530)**), with content and info on how to hopefully remedy your predicament... 

To ALL the rest: The same applies to you 😞 ...

**Comment by Tardkiller** [comment] 2023-02-20 23:00
> Let me repeat what I wrote in another **duplicate** of this:
> 
> @Tardkiller :
> 
> You haven't followed the **recommended procedure** on submitting a new issue, now a **PINNED issue** in the main repo:
> 
> ![NI](https://user-images.githubusercontent.com/9669492/220207414-6870b63d-e78a-4873-ade4-d55442c69aa9.png)
> 
> i.e. #30839 ...
> 
> Had you done that, you'd have discovered ca. **100 duplicate issues** with the **same error message**, plus links to the originating issue (now a **[megathread](https://github.com/ytdl-org/youtube-dl/issues/31530)**), with content and info on how to hopefully remedy your predicament...
> 
> To ALL the rest: The same applies to you 😞 ...

Recommended procedure?

I literally did what the program told me: 

`ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug`

**Comment by Vangelis66** [comment] 2023-02-20 23:06
... And when you did as the app requested, i.e. load 

https://yt-dl.org/bug

that brought you to 

https://github.com/ytdl-org/youtube-dl/issues

did it not? The PINNED ISSUE is hard to miss if' you're about to file a "new" issue...

**Comment by Vangelis66** [comment] 2023-02-20 23:14
> I literally did what the program told me:
> 
> ERROR: (...); please report this issue on https://yt-dl.org/bug

@dirkf : Kindly consider my suggestion [here](https://github.com/ytdl-org/youtube-dl/issues/31543#issuecomment-1435406212), at least for future mega-breakages; it's too late for this one, sadly...

**Comment by Tardkiller** [comment] 2023-02-20 23:24
> ... And when you did as the app requested, i.e. load
> 
> https://yt-dl.org/bug
> 
> that brought you to
> 
> https://github.com/ytdl-org/youtube-dl/issues
> 
> did it not? The PINNED ISSUE is hard to miss if' you're about to file a "new" issue...

I didn't see it or look for it. This forum is already hard enough to navigate as it as. 

But hey; if you don't want this issue reported simply remove the thread and remove the suggestion from the software.

**Closed** 2023-02-20 23:35 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-02-20 23:49
Of course I can manually clear up people's mess, but https://github.com/ytdl-org/youtube-dl/issues/31613#issuecomment-1437509345.

In my display, as in the picture above, the pinned issue is much larger than the 'New Issue' button. Did you come to the page in some way that caused the pinned issue not to be shown?

Or would having it directly above the button have made it more obvious? There can be three pinned issues so two dummy issues with title `Look! ------->` could be added at the left and centre.

**Comment by Tardkiller** [comment] 2023-02-21 00:30
I think the problem is mainly that people search the forum for recent threads that have titles that are clear descriptions of their own problem. I didn't notice any because when you close them they disappear. I am not invested enough in or knowledgeable enough about youtube-dl to get from a glance that the "[YouTube] Unable to extract uploader id" is that thread. Because that title doesn't really tell me much. Additionally this forum does not provide timestamps from the last post, just the day of the thread started, so it tells my 4 days ago someone had an issue with a description that I have no clue about. 

I understand now that this is a big issue that just popped up in the past couple of days. You might want to make a forum sticky that says something like "We are aware that the software is currently not working", not some generic "READ THIS BEFORE OPENING A NEW ISSUE!".

/2 cents.
