### ISSUE TITLE
[FranceTV] YouTube-dl

### ISSUE THREAD

**Issue by Hardelot** [ytdl-org/youtube-dl#30008] opened 2021-09-23 13:26 UTC
<![deviennenicolas@DESKTOP-TEVNB6U VideoDownloader]$ youtube-dl https://www.france.tv/films/2804043-l-aine-des-ferchaux.html
[FranceTVSite] 2804043-l-aine-des-ferchaux: Downloading webpage
[FranceTV] 46f058b9-ff7c-4dec-a618-4960720beb83: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.--

######################################################################
  WARNING!
  IGNORING THE FOLLOWING TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
######################################################################

-->

## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by Hardelot** [comment] 2021-09-23 13:27
[deviennenicolas@DESKTOP-TEVNB6U VideoDownloader]$ youtube-dl https://www.france.tv/films/2804043-l-aine-des-ferchaux.html
[FranceTVSite] 2804043-l-aine-des-ferchaux: Downloading webpage
[FranceTV] 46f058b9-ff7c-4dec-a618-4960720beb83: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2021-09-23 14:41
Although you didn't **follow the template** I guess this is a duplicate of #29956.

**Comment by Hardelot** [comment] 2021-09-24 12:45
En Français STP ?

**Comment by Hardelot** [comment] 2021-10-01 06:44
Je souhaite téélcharger :+1: 

* https://www.france.tv/france-2/the-victim/1079175-the-victim.html
* https://www.france.tv/france-2/the-victim/1079173-the-victim.html

Peux-tu m'expliquer davantage STP ?

**Comment by dirkf** [comment] 2021-10-01 09:56
The france.tv site has been changed and the extractor has had to be rewritten. Until a project admin approves the new extractor yt-dl can't handle france.tv. Read more at #29956.

Le site france.tv a été modifié, de sorte que le «extractor» (c'est le logiciel qui traduit du site à yt-dl) a dû être écrit à nouveau. Jusqu'à ce que l'un des adminstrateurs du projêt approuve le module modifié, le téléchargement du site ne fonctionnera pas. Tu peux en savoir plus à #29956.

**Comment by Hardelot** [comment] 2021-10-01 17:04
OK et de ce fait je ne pourrai pas avoir les épisodes 3 et 4 de The Victim...

**Comment by dirkf** [comment] 2021-10-01 20:31
Yes, but see the thread again (a) for another tool that might help (b) for a patch that you might be able to apply to your Unix-like yt-dl installation. You need to find a file whose path ends in `youtube_dl/extractor/francetv.py` and replace it by the one in the patch. Maybe raise an issue with the packaged that installed yt-dl if you didn't install it yourself.

Oui, mais voir à nouveau #29956 (a) pour des autres outils qui pourrait t'aider (b) pour un patch que tu pourrais appliquer à votre installation yt-dl de type UNIX. Tu dois trouver un fichier dont le nom se termine dans `youtube_dl/extractor/francetv.py` et remplacer-le par celui dans le patch, ou soumettre un problème avec le produit logiciel qui a installé yt-dl si tu ne l'as pas installé toi-même.

**Comment by Hardelot** [comment] 2021-10-02 03:53
Pourrais-tu me mettre ici la ligne ou les lignes de commande pour LINUX FEDORA ?

**Comment by Hardelot** [comment] 2021-10-02 09:11
[deviennenicolas@fedora Sasion 1]$ youtube-dl -F https://www.france.tv/france-2/the-victim/1079175-the-victim.html --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.france.tv/france-2/the-victim/1079175-the-victim.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.19-200.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading signed dash manifest URL
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading MPD manifest
WARNING: [FranceTV] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 237, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 197, in _extract_video
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2021-10-02 14:25
OK, there's the relevant file right here:
Voilà que le fichier d'interêt est ceci:

> [deviennenicolas@fedora Sasion 1]$ youtube-dl -F https://www.france.tv/france-2/the-victim/1079175-the-victim.html --verbose 
...
File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 237, in _real_extract
return self._extract_video(video_id, catalog)
...

So you have to download the file `francetv.py.txt` [here](https://github.com/ytdl-org/youtube-dl/issues/29956#issuecomment-919048554); then install and compile it ([you'll need to provide your password](https://fedoramagazine.org/howto-use-sudo/))
Donc il faut télécharger le fichier `francetv.py.txt` [d'ici](https://github.com/ytdl-org/youtube-dl/issues/29956#issuecomment-919048554); puis installer ce fichier et le compiler ([fournissant ton mot de passe](https://fedoramagazine.org/howto-use-sudo/)):
```
cd «répertoire où se trouve le fichier francetv.py.txt»
sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak
sudo cp francetv.py.txt /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
sudo youtube-dl --version
```
If that doesn't work, you can undo the change:
Si ça ne réussira pas, tu peux l'inverser:
```
sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.pyc
sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
sudo youtube-dl --version
```

**Comment by Hardelot** [comment] 2021-10-02 17:41
Désolé de revenir vers toi, mais je n'ai pas ces 3 fichiers : francetv.pyc, francetv.py.bak et francetv.py.txt

**Comment by dirkf** [comment] 2021-10-02 18:25
Please read again. `francetv.pyc` may not exist if you haven't run or installed yt-dl as an administrator. `francetv.py.bak` is created by the line `sudo mv ...`. And as I wrote:
 
STP lire les instructions à nouveau. Il n'importe rien si le fichier francetv.pyc n'existe pas; c'est creé par Python quand on lance yt-dl comme administrateur. Le fichier `francetv.py.bak` sera creé par la ligne `sudo mv ...`. Et comme j'ai écrit: 

> So you have to download the file `francetv.py.txt` [here](https://github.com/ytdl-org/youtube-dl/issues/29956#issuecomment-919048554); then install and compile it ([you'll need to provide your password](https://fedoramagazine.org/howto-use-sudo/))
> Donc il faut télécharger le fichier `francetv.py.txt` [d'ici](https://github.com/ytdl-org/youtube-dl/issues/29956#issuecomment-919048554); puis installer ce fichier et le compiler ([fournissant ton mot de passe](https://fedoramagazine.org/howto-use-sudo/)):

Then the `cd ...` line has to change the working directory so as to find the file `francetv.py.txt` after downloading it.

Puis la ligne `cd «...` doit changer le répertoire actuel pour trouver le fichier `francetv.py.txt` après le télécharger.

**Comment by Hardelot** [comment] 2021-10-03 06:08
[deviennenicolas@fedora ~]$ cd Téléchargements 
[deviennenicolas@fedora Téléchargements]$ sudo su
[sudo] Mot de passe de deviennenicolas : 
[root@fedora Téléchargements]# sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak
[root@fedora Téléchargements]# sudo cp francetv.py.txt /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
[root@fedora Téléchargements]# sudo youtube-dl --version
2021.06.06
[root@fedora Téléchargements]# sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
[root@fedora Téléchargements]# sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.pyc
rm: impossible de supprimer '/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.pyc': Aucun fichier ou dossier de ce type
[root@fedora Téléchargements]# sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py
[root@fedora Téléchargements]# sudo youtube-dl --version
2021.06.06
[root@fedora Téléchargements]# youtube-dl -F https://www.france.tv/france-2/the-victim/1079175-the-victim.html --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.france.tv/france-2/the-victim/1079175-the-victim.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

[root@fedora Téléchargements]# youtube-dl https://www.france.tv/france-2/the-victim/1079175-the-victim.html
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[root@fedora Téléchargements]# exit
exit
[deviennenicolas@fedora Téléchargements]$ youtube-dl -F https://www.france.tv/france-2/the-victim/1079175-the-victim.html --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.france.tv/france-2/the-victim/1079175-the-victim.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading signed dash manifest URL
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading MPD manifest
WARNING: [FranceTV] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 237, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py", line 197, in _extract_video
    self._sort_formats(formats)
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[deviennenicolas@fedora Téléchargements]$ youtube-dl https://www.france.tv/france-2/the-victim/1079175-the-victim.html
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading signed dash manifest URL
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading MPD manifest
WARNING: [FranceTV] Unknown MIME type application/mp4 in DASH manifest
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2021-10-04 02:44
>[deviennenicolas@fedora ~]$ cd Téléchargements [deviennenicolas@fedora Téléchargements]
$ sudo su [sudo] Mot de passe de deviennenicolas : [root@fedora Téléchargements]
\# sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak [root@fedora Téléchargements]
\# sudo cp francetv.py.txt /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py [root@fedora Téléchargements]
\# sudo youtube-dl --version 2021.06.06 [root@fedora Téléchargements]

So far it's all correct. This is where you should have run your yt-dl command:

Jusqu'ici c'est tout correcte. Maintenant tu dois lancer la commande yt-dl:

```
youtube-dl https://www.france.tv/france-2/the-victim/1079175-the-victim.html
```

...

The rest of the commands just reverse the previous commands. These commands were for use if you wanted to restore the original configuration.

Dans le reste tu n'as rien fait sauf inverser les commandes précédentes. Ces commandes pourraient être utilisées si tu voudrais restaurer la configuration originale.

>\# sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py [root@fedora Téléchargements]
\# sudo rm /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.pyc rm: impossible de supprimer '/usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.pyc': Aucun fichier ou dossier de ce type [root@fedora Téléchargements]
\# sudo mv /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py.bak /usr/lib/python3.9/site-packages/youtube_dl/extractor/francetv.py [root@fedora Téléchargements]
\# sudo youtube-dl --version 2021.06.06 [root@fedora Téléchargements]

**Comment by Hardelot** [comment] 2021-10-04 04:50
Je suis sur FEDORA 35 Bêta depuis hier soir :+1: 

[deviennenicolas@localhost-live ~]$ sudo su
[sudo] Mot de passe de deviennenicolas : 
[root@localhost-live deviennenicolas]# sudo rm /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py
[root@localhost-live deviennenicolas]#  sudo rm /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.pyc
rm: impossible de supprimer '/usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.pyc': Aucun fichier ou dossier de ce type
[root@localhost-live deviennenicolas]# sudo mv /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py.bak /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py
mv: impossible d'évaluer '/usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py.bak': Aucun fichier ou dossier de ce type
[root@localhost-live deviennenicolas]# cd Téléchargements
[root@localhost-live Téléchargements]# sudo mv /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py.bak
mv: impossible d'évaluer '/usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py': Aucun fichier ou dossier de ce type
[root@localhost-live Téléchargements]# sudo cp francetv.py.txt /usr/lib/python3.10/site-packages/youtube_dl/extractor/francetv.py
[root@localhost-live Téléchargements]# sudo youtube-dl --version 2021.06.06
2021.06.06
[root@localhost-live Téléchargements]# youtube-dl https://www.france.tv/france-2/the-victim/1079175-the-victim.html
[FranceTVSite] 1079175-the-victim: Downloading webpage
[FranceTV] f67068fb-3fef-45fc-8a18-8924f72e80a9: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[root@localhost-live Téléchargements]# exit
exit
[deviennenicolas@localhost-live ~]$ cd Téléchargements
[deviennenicolas@localhost-live Téléchargements]$ cd VideoDownloader
[deviennenicolas@localhost-live VideoDownloader]$ youtube-dl https://www.france.tv/france-3/hauts-de-france/19-20-nord-pas-de-calais/2803583-emission-du-dimanche-3-octobre-2021.html
[FranceTVSite] 2803583-emission-du-dimanche-3-octobre-2021: Downloading webpage
[FranceTV] 5c6808b2-c344-433d-9d2d-b290918abe94: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Closed** 2022-05-09 14:38 UTC
Labels: duplicate
