### ISSUE TITLE
Dailymotion broken

### ISSUE THREAD

**Issue by christopherosko** [ytdl-org/youtube-dl#23256] opened 2019-11-28 17:15 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/video/x7ohvao', u'-F']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg git-2014-12-04-43f56cd-static
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
```

## Description

Since the last update I get a python error with dailymotion fetcher.

**Comment by christopherosko** [comment] 2019-11-29 09:22
Hi @remitamine ,
From which issue is this the duplicate ? I can't find it. Thanks

**Comment by remitamine** [comment] 2019-11-29 14:39
Duplicate of #20673, it's the same problem.

**Comment by dstftw** [comment] 2019-11-29 16:20
It's more about severity than duplication - previously working extractor is now completely broken under python 2.

**Comment by remitamine** [comment] 2019-11-29 17:04
#20673 closed as the problem no longer applies to twitter extractor, however, the problem still affects all extractors calling `_get_cookies` method.

**Comment by afsharsafavi** [comment] 2019-12-02 23:51
Hello
The problem didn't solve.

`../youtube-dl https://www.dailymotion.com/video/x6d0e8l -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.dailymotion.com/video/x6d0e8l', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.5 (CPython) - Linux-3
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.2.1, ffprobe 4.2.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "./youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib64/python2.7/Cookie.py", line 579, in __init__
    if input: self.load(input)
  File "/usr/lib64/python2.7/Cookie.py", line 635, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'`

**Closed** 2020-05-04 23:02 UTC
