### ISSUE TITLE
[Youtube] Cannot download videos using channel search result page

### ISSUE THREAD

**Issue by jblaufuss** [ytdl-org/youtube-dl#29355] opened 2021-06-22 04:49 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --version
2021.06.06
$ youtube-dl -v https://www.youtube.com/c/PBSNewsHour/search?query=Australia
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/c/PBSNewsHour/search?query=Australia']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.7.9 (CPython) - FreeBSD-11.4-RELEASE-p3-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:tab] PBSNewsHour: Downloading webpage
ERROR: Unable to find selected tab; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2827, in _real_extract
    return self._extract_from_tabs(item_id, webpage, data, tabs)
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2752, in _extract_from_tabs
    selected_tab = self._extract_selected_tab(tabs)
  File "/local/file/path/youtube-dl-venv/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2708, in _extract_selected_tab
    raise ExtractorError('Unable to find selected tab')
youtube_dl.utils.ExtractorError: Unable to find selected tab; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$
```

## Description

I am attempting to archive the a topical slice of a very large youtube channel by using a the URL of a channel-specific keyword search.  It doesn't work, and the log messages ask for a bug to be reported.  I can use the channel URL to download the whole channel, so it seems logical that I should be able to download from the channel search results.

**Comment by LemurPwned** [comment] 2021-06-22 08:21
I have a similar issue, not for a channel but for a search query e.g. `https://www.youtube.com/results?search_query=ducks&sp=EgIoAQ%253D%253D`.

I tried using `ytsearchcc:"ducks"` but it throws `Unable to download webpage: <urlopen error unknown url type: ytsearchcc>`. 
What would be a correct way to construct a query search with filters in `youtube-dl`?

**Comment by pukkandan** [comment] 2021-06-22 10:44
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/29071

---

> What would be a correct way to construct a query search with filters in youtube-dl? 

Not possible since the devs search URLs have not been fixed yet (https://github.com/ytdl-org/youtube-dl/pull/27749)

**Comment by dirkf** [comment] 2022-05-20 10:01
PR #30570.

**Closed by dirkf** 2022-05-20 10:01 UTC
Labels: duplicate
