### ISSUE TITLE
request for iq.com

### ISSUE THREAD

**Issue by Kuju29** [ytdl-org/youtube-dl#30500] opened 2022-01-12 03:25 UTC
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.iq.com/play/attack-on-titan-final-season-episode-1-23e9oqaqyd4?lang=en_us
- Playlist: https://www.iq.com/album/attack-on-titan-final-season-2020-26rwd8fpbix?lang=en_us

## Description

free

**Comment by 89z** [comment] 2022-01-12 03:30
Region restricted:

> This video is not available in your region.

**Comment by kikuyan** [comment] 2022-01-12 03:35
Duplicate of #26822, though bit dated.

**Closed** 2022-01-12 03:38 UTC
Labels: site-support-request

**Comment by 89z** [comment] 2022-01-12 03:43
I dont think #26822 is helpful, as its locked (likely permanently)

**Comment by Kuju29** [comment] 2022-01-12 03:52
> Region restricted:
> 
> > This video is not available in your region.

Are there any download instructions in this file?
https://cache-video.iq.com/dash?tvid=3988067783036100&bid=200&ds=1&vid=abe2c4788688b54418ebe6a4119bf1a5&src=01010031010014000000&vt=0&rs=1&uid=0&ori=pcw&ps=0&k_uid=5e60111908014e5be290f2934905a2ce&pt=0&d=0&s=&lid=&slid=3&cf=&ct=&authKey=d394329f700286fc67e5da98cc1f1433&k_tag=1&ost=0&ppt=0&dfp=a15c6fa285df8352f6ad814c6463acc0b2c1999755b678c5d151a01d840653d180&prio=%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D&k_err_retries=0&up=&su=2&applang=en_us&sver=2&X-USER-MODE=th&qd_v=2&tm=1641959048540&qdy=a&qds=0&k_ft1=141287244169348&k_ft4=34359746564&k_ft5=1&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a15c6fa285df8352f6ad814c6463acc0b2c1999755b678c5d151a01d840653d180%22%7D&ut=0&vf=307b54446e783275e0ef4d2ce7c1be6a

**Comment by kikuyan** [comment] 2022-01-12 04:49
Take a look at yt-dlp. There's also a support request.
Or ask [VideoHelp Forum](https://forum.videohelp.com/forums/48-Video-Streaming-Downloading) if you need quick help.

**Comment by Kuju29** [comment] 2022-01-12 04:51
> 

Thanks! 💯  👍

**Comment by dirkf** [comment] 2022-01-12 14:45
It looks like a subclass of `IqiyiIE` should be able to get `tvid` and `vid` from the `__NEXT_DATA__` JSON so:
```
        video_id, tvid = (str_or_none(next_data['props']['initialState']['play']['curVideoInfo'][x]) for x in ('vid', 'tvId'))
```
But I get error `A00110` which is not diagnosed by the Iqiyi extractor, and doesn't appear to be geo-blocking. Perhaps login details would improve things.

**Comment by Kuju29** [comment] 2022-01-12 15:23
> It looks like a subclass of `IqiyiIE` should be able to get `tvid` and `vid` from the `__NEXT_DATA__` JSON so:
> 
> ```
>         video_id, tvid = (str_or_none(next_data['props']['initialState']['play']['curVideoInfo'][x]) for x in ('vid', 'tvId'))
> ```
> 
> But I get error `A00110` which is not diagnosed by the Iqiyi extractor, and doesn't appear to be geo-blocking (A00111). Perhaps login details would improve things.

I tested with member. still have the same problem. This is the HAR file if you need more information. https://mega.nz/file/kclwnQJQ#qwJV1BSF0rwP7sYXX_LarTuTluTrplF-VO2sXinDgPo

**Comment by dirkf** [comment] 2022-01-12 21:09
Also, it seems that any valid Iqiyi test videos redirect to iq.com, so maybe there's  a new implementation of the media obfuscation process in iq.com, even if the parameters seem to be the same.

A00110 was also encountered in #10088.
