### ISSUE TITLE
yotube dl error Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by GuPa97** [ytdl-org/youtube-dl#30376] opened 2021-12-15 15:19 UTC
## Checklist

- [ ] I'm reporting a new site support request
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

**Comment by nagualcode** [comment] 2021-12-15 15:38
same here

**Comment by Richard-Wai** [comment] 2021-12-15 15:38
I confirm this as well.

**Comment by Yash114Bansal** [comment] 2021-12-15 16:57
Replace `youtube_dl/extractor/youtube.py` this file with
[youtube.py.zip](https://github.com/ytdl-org/youtube-dl/files/7721294/youtube.py.zip)
 First Extract it

**Comment by 89z** [comment] 2021-12-15 17:07
@Yash114Bansal please stop.

**Comment by szekster** [comment] 2021-12-15 18:37
will someone be building a new youtube-dl with the patch?

**Comment by Lukieer** [comment] 2021-12-15 19:55
> will someone be building a new youtube-dl with the patch?

https://github.com/Lukieer/youtube-dl

fixed

**Comment by audyviii** [comment] 2021-12-16 01:04
I am still having this issue on Windows 11.

**Comment by dirkf** [comment] 2021-12-16 03:49
Although you didn't post the required error log, this is plainly a duplicate of [#30363](https://github.com/ytdl-org/youtube-dl/issues/30363#issuecomment-994731986), where a fix was provided.

Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have led you to review the existing issue and not create a new one. As it is, @GuPa97, kindly close this issue.

**Closed** 2022-01-29 17:23 UTC
Labels: site-support-request, duplicate
