### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by Andrey-kosenko** [ytdl-org/youtube-dl#31679] opened 2023-02-24 14:53 UTC
```
[debug] Encodings: locale cp1251, fs utf-8, out UTF-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg n5.1.2-9-g807afa59cc-20221219, ffprobe n5.1.2-9-g807afa59cc-20221219
[debug] Proxy map: {}
[youtube] iPwE3CUgyl8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\Новая папка (3)\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Новая папка (3)\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Новая папка (3)\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "D:\Новая папка (3)\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "D:\Новая папка (3)\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

An error occurred: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mlazzarotto** [comment] 2023-02-24 15:54
This is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/31530

**Closed** 2023-02-24 17:14 UTC
Labels: duplicate, incomplete

**Comment by dirkf** [comment] 2023-02-24 17:15
Also: #30839.
