### ISSUE TITLE
Download of MPEG Dash streams (Zattoo) fails

### ISSUE THREAD

**Issue by cwuensch** [ytdl-org/youtube-dl#31915] opened 2023-03-22 22:11 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser [from my network, not publicly]
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Christian Wünsch\Downloads>youtube-dl --verbose https://1und1-XXXXX-2-dash-live.zahs.tv/HD_ard/m.mpd?z32=MF2...CENSORED...Y6TA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://1und1-XXXXX-2-dash-live.zahs.tv/HD_ard/m.mpd?z32=MF2...CENSORED...Y6TA']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] m: Requesting header
WARNING: Falling back on generic information extractor.
[generic] m: Downloading webpage
[generic] m: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2499, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am trying to download a live stream, which is provided in multipart MPEG Dash Format (DRM-free).
The stream is available via my network provider, so it will be not available from the global internet. From my PC, it is playable via dash.js player from the web.
But youtube-dl cannot read the mpd and download the stream.
(mpd manifest will be attached)

[m.mpd.txt](https://github.com/ytdl-org/youtube-dl/files/11045091/m.mpd.txt)

**Comment by dirkf** [comment] 2023-03-22 23:21
In principle, though I'm not an expert, the manifest looks fine. But:
* not even yt-dl git master knows hows to detect a generic DASH/mpd manifest (unlike HLS, eg)
* even if it did, the function that parses such manifests rejects [those with `type="dynamic"`](https://github.com/Dash-Industry-Forum/dash.js/issues/53).

So you may need to try a different tool for now. yt-dlp seems to be able to handle your stream using `--force-generic` with the link above.
Is it possible

**Comment by Vangelis66** [comment] 2023-03-23 01:45
... Probably a duplicate of original #10787, all the way back from 2016 (!) ...
More recent duplicates include #28032 and #21302...

Grab yourself a fairly recent `FFmpeg` build and try again 😉 ; do note you'd have to pass special `-map` options to it, because the last time I checked `FFmpeg` with **dynamic MPD**s, it couldn't properly parse and auto-select **bestvideo**+**bestaudio** formats amongst the ones present inside the MPD... See some of my comments in the linked duplicates... 

Alternatively, if your setup can take it, search for the `streamlink` python application...

**Closed** 2023-07-31 18:22 UTC
Labels: mpd
