### ISSUE TITLE
Mixcloud failing for below mentioned artist while working for many others tested

### ISSUE THREAD

**Issue by miroslav82** [ytdl-org/youtube-dl#32757] opened 2024-03-29 20:15 UTC
## Checklist

- [ x] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
C:\soft>youtube-dl.exe https://www.mixcloud.com/adambeyer/dcr708-drumcode-radio-live-adam-beyer-live-mix-from-ants-at-zamna-tulum/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mixcloud.com/adambeyer/dcr708-drumcode-radio-live-adam-beyer-live-mix-from-ants-at-zamna-tulum/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.03.24 [71211e7db] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-7-6.1.7601-SP1 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] adambeyer_dcr708-drumcode-radio-live-adam-beyer-live-mix-from-ants-at-zamna-tulum: Downloading JSON metadata
ERROR: adambeyer_dcr708-drumcode-radio-live-adam-beyer-live-mix-from-ants-at-zamna-tulum: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 951, in _parse_json
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\__init__.py", line 318, in loads
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 343, in decode
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 951, in _parse_json
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\__init__.py", line 318, in loads
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 343, in decode
  File "C:\hostedtoolcache\windows\Python\3.4.4\x86\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 863, in wrapper
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 959, in __extract_info
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 571, in extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\mixcloud.py", line 129, in _real_extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\mixcloud.py", line 32, in _call_api
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 944, in _download_json
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 928, in _download_json_handle
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 955, in _parse_json
youtube_dl.utils.ExtractorError: adambeyer_dcr708-drumcode-radio-live-adam-beyer-live-mix-from-ants-at-zamna-tulum: Failed to parse JSON  (caused by ValueError(
'Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
 -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am getting error with Adam Beyer on MixCloud, with any track I try playing. Please find verbose output attached, I am using latest version and tested with nightly release also to verify issue exists.

**Comment by dirkf** [comment] 2024-03-30 00:34
There is a new API host, and it seems that some new (?) tracks are only available through the new host.

PR #32557 should fix this and will be merged soon.

**Comment by djkraven** [comment] 2024-06-03 00:12
I am encountering the same issue using the link below. I also tried the MixCloud link of the original post for Adam Beyer with the same results. Looking at the PR it appears a resolution was determined but not merged yet. Is that correct?   

youtube-dl https://www.mixcloud.com/marrone/ftb-mixtape-guilty-may-2024/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mixcloud.com/marrone/ftb-mixtape-guilty-may-2024/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2024.05.31 [21924742f] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.9.3-060903-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] marrone_ftb-mixtape-guilty-may-2024: Downloading JSON metadata
ERROR: marrone_ftb-mixtape-guilty-may-2024: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 951, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 951, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 863, in wrapper
    return func(self, *args, **kwargs)
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/YoutubeDL.py", line 959, in __extract_info
    ie_result = ie.extract(url)
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/mixcloud.py", line 86, in _real_extract
    cloudcast = self._call_api('cloudcast', '''audioLength
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/mixcloud.py", line 26, in _call_api
    return self._download_json(
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 940, in _download_json
    res = self._download_json_handle(
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 926, in _download_json_handle
    return self._parse_json(
  File "/home/djk/youtube-dl/./youtube-dl/youtube_dl/extractor/common.py", line 955, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: marrone_ftb-mixtape-guilty-may-2024: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by dirkf** [comment] 2024-06-03 09:15
Apparently "soon" was wrong. You could adapt the instructions [here](https://github.com/ytdl-org/youtube-dl/issues/32798#issuecomment-2144013281), changing the PR number to match, and report whether your issue is fixed at #32557.

**Comment by djkraven** [comment] 2024-06-03 12:03
I did the following pull but the version is old. The results are the same. Is the path for the PR pull correct or did I miss something?

curl -L -o ytdl_pr_32802.zip "https://github.com/ytdl-org/youtube-dl/archive/pull/32557/head.zip"

./youtube-dl https://www.mixcloud.com/marrone/ftb-mixtape-guilty-may-2024/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mixcloud.com/marrone/ftb-mixtape-guilty-may-2024/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.12 (CPython) - Linux-6.9.3-060903-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] marrone_ftb-mixtape-guilty-may-2024: Downloading JSON metadata
ERROR: marrone_ftb-mixtape-guilty-may-2024: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/mixcloud.py", line 86, in _real_extract
    cloudcast = self._call_api('cloudcast', '''audioLength
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/mixcloud.py", line 26, in _call_api
    return self._download_json(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 895, in _download_json
    res = self._download_json_handle(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    return self._parse_json(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 910, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: marrone_ftb-mixtape-guilty-may-2024: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2024-06-03 19:47
You have actually to run the PR code as described in the linked instructions. Plainly this is the installed yt-dl:
>`File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 906, in _parse_json
return json.loads(json_string)`

**Comment by djkraven** [comment] 2024-06-10 22:38
The PR is working for Mixcloud. I tested again using new VM Linux Mint that youtube-dl was not on. The version still reports back with an old date of 2021.12.17. Both of the Mixcloud shows retrieved successfully. 

Thank you and look forward to it be merged.

curl -L -o ytdl_pr_32557.zip "https://github.com/ytdl-org/youtube-dl/archive/pull/32557/head.zip"
 unzip ytdl_pr_32557.zip
Archive:  ytdl_pr_32557.zip
ec46d543b4304f17a5169cd92338bbd32af10c71
   creating: youtube-dl-pull-32557-head/
...
 unzip ytdl_pr_32557.zip
Archive:  ytdl_pr_32557.zip
ec46d543b4304f17a5169cd92338bbd32af10c71
   creating: youtube-dl-pull-32557-head/

 python3 -m youtube_dl --version
2021.12.17

python3 -m youtube_dl https://www.mixcloud.com/marrone/ftb-mixtape-guilty-may-2024/ --verbose

**Closed** 2024-06-11 11:38 UTC
Labels: broken-IE
