### ISSUE TITLE
youtube-dl is very slow

### ISSUE THREAD

**Issue by MesterPerfect** [ytdl-org/youtube-dl#30239] opened 2021-11-14 17:17 UTC
hi
I have a server running ubuntu 2020
And I installed youtube-dl to use it to download some playlists from YouTube
But the program is very slow
Even though I using the latest version
I have removed and reinstalled the program and tried many things but to no avail

**Comment by MesterPerfect** [comment] 2021-11-14 17:18
https://i.imgur.com/9b2RkbH.jpg

**Comment by dirkf** [comment] 2021-11-14 18:33
As you would have found by **[simply following the Broken Site Support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template**, this is a duplicate of #29326 (and about 15 other recent issues), where (read to the end) solutions are provided.

**Closed** 2022-01-31 00:31 UTC
Labels: duplicate
