### ISSUE TITLE
Xvideos. Unable to download - error 404

### ISSUE THREAD

**Issue by koopa990** [ytdl-org/youtube-dl#31318] opened 2022-10-29 14:25 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.xvideos.com/video55996109/runsammya_furry_antro_bunny_porno_with_sound_?pl=64479171&plname=furry', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2022-10-10-git-f3b5277057-full_build-www.gyan.dev, ffprobe 2022-10-10-git-f3b5277057-full_build-www.gyan.dev
[debug] Proxy map: {}
[XVideos] 55996109: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

## Description

WRITE DESCRIPTION HERE
A video on the adult website, Xvideos, failed to fetch the video link. There are other times it may spew out error

**Comment by dirkf** [comment] 2022-10-29 15:55
Duplicate of #30271, fixed in git master. See also #30707.

**Closed by dirkf** 2022-10-29 15:55 UTC

**Comment by koopa990** [comment] 2022-10-29 15:57
> Duplicate of #30271, fixed in git master. See also #30707.

I got it under control. Thanks
