### ISSUE TITLE
Downloading a YouTube video by cutting out sponsors

### ISSUE THREAD

**Issue by shivasagarrao** [ytdl-org/youtube-dl#27210] opened 2020-11-26 15:45 UTC
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.11.26**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Add an option to download a YouTube video by cutting out sponsered segments which are available in the [SponsorBlock API](https://github.com/ajayyy/SponsorBlock).
[SponSkrub](https://github.com/faissaloo/SponSkrub/) is an implementation of this feature but it only works for individual videos, not playlists.

**Comment by dstftw** [comment] 2020-11-26 16:05
Duplicate of #26084.

**Closed by dstftw** 2020-11-26 16:05 UTC
