### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);

### ISSUE THREAD

**Issue by Akshaykumarcp** [ytdl-org/youtube-dl#30946] opened 2022-05-14 18:05 UTC
## Verbose log

command: youtube-dl -u MAILID -p PASSWORD https://company_name.udemy.com/statistics-for-data-science-and-business-analysis/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://company_name.udemy.com/statistics-for-data-science-and-business-analysis/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.7.11 (CPython) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "d:\anaconda\envs\ml\lib\site-packages\youtube_dl\extractor\common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "d:\anaconda\envs\ml\lib\site-packages\youtube_dl\YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "d:\anaconda\envs\ml\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\anaconda\envs\ml\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\anaconda\envs\ml\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\anaconda\envs\ml\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\anaconda\envs\ml\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

## Description

I'm trying to download courses from udemy business account. I'm getting above error. 

Does any one know about it and help me!!

**Comment by dirkf** [comment] 2022-05-14 19:01
[Duplicate of #29410](https://github.com/ytdl-org/youtube-dl/issues/29410#issuecomment-1110882032).

**Closed by dirkf** 2022-05-14 19:01 UTC
