### ISSUE TITLE
3SAT: Failed to parse JSON Expecting ',' delimiter

### ISSUE THREAD

**Issue by Chris56** [ytdl-org/youtube-dl#26711] opened 2020-09-26 06:11 UTC
URL: https://www.3sat.de/film/fernsehfilm/meine-schwester-102.html, but the problem is identical with other videos on
https://www.3sat.de/film/fernsehfilm/

Viewing in Browser works, manual downloading after finding master.m3u works.
youtube-dl fails with:
WARNING: [generic] meine-schwester-102: Failed to parse JSON Expecting ',' delimiter: line 23 column 26 (char 576)
ERROR: Unsupported URL: https://www.3sat.de/film/fernsehfilm/meine-schwester-102.html

Used (current) version is 2020.09.20

Verbose log:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.3sat.de/film/fernsehfilm/meine-schwester-102.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.18rc1 (CPython) - Linux-5.4.0-47-generic-x86_64-with-LinuxMint-20-ulyana
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] meine-schwester-102: Requesting header
WARNING: Falling back on generic information extractor.
[generic] meine-schwester-102: Downloading webpage
[generic] meine-schwester-102: Extracting information
WARNING: [generic] meine-schwester-102: Failed to parse JSON Expecting ',' delimiter: line 23 column 26 (char 576)
ERROR: Unsupported URL: https://www.3sat.de/film/fernsehfilm/meine-schwester-102.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 133, column 944
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.3sat.de/film/fernsehfilm/meine-schwester-102.html

**Comment by FichteFoll** [comment] 2021-01-02 13:18
Duplicate of #21185.

**Closed** 2021-03-01 23:04 UTC
