### ISSUE TITLE
nzonscreen content

### ISSUE THREAD

**Issue by petaflot** [ytdl-org/youtube-dl#29712] opened 2021-08-01 18:28 UTC
- [X ] I'm reporting a new site support request
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that none of provided URLs violate any copyrights
- [ X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.nzonscreen.com/title/the-last-man-of-mahana-2017

## Description

for humanity's sake. we need to live.

**Comment by Richienb** [comment] 2021-11-10 08:10
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/29385

**Closed** 2022-01-29 16:10 UTC
Labels: site-support-request, duplicate
