### ISSUE TITLE
TikTok cannot get URL / download a video

### ISSUE THREAD

**Issue by P0SlX** [ytdl-org/youtube-dl#30432] opened 2021-12-26 22:34 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://www.tiktok.com/@leanemarts/video/7043504461670632709 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@leanemarts/video/7043504461670632709', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-1038-oracle-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7043504461670632709: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tiktok.py", line 110, in _real_extract
    page_props = self._parse_json(self._search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

TikTok probably changed something because the regex can't find what it searches for.

**Comment by 89z** [comment] 2021-12-26 23:34
I have an alternative tool that works:

~~~
PS C:\> tiktok 7043504461670632709
GET https://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7043504461670632709
GET https://v16m-default.akamaized.net/33ea87e9f1028feedeb55e274f99bb81/61c9501f/video/tos/useast2a/tos-useast2a-pve-0068/05ca056ae3af4b54becf7fdca79a9bd9/?a=0&br=3552&bt=1776&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=6&er=&ft=~pxS9z4Hh~06B8exqp6HJPD1&l=2021122623330501019105207723B0DCB7&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=Mzw4cGk6ZnFyOTMzNzczM0ApNTczZGU6ZmVpN2c1ZWg2OGdoZC5wcjRvb3NgLS1kMTZzczVfMTA1XjJiXzFgMDJjMDE6Yw%3D%3D&vl=&vr=
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment] 2021-12-26 23:41
Probable duplicate of #30251, where a fix is proposed.

**Closed** 2021-12-27 00:50 UTC
