### ISSUE TITLE
Does not download some videos

### ISSUE THREAD

**Issue by MaximFedarau** [ytdl-org/youtube-dl#30373] opened 2021-12-15 13:25 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=Aepu8msxZ28']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.9 (CPython) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
```

## Description

I post this issue on 12.15.2021, but the 2 days before everything looks good. YouTube-dl can download some videos perfect, but other  videos it can't and it says, that this url is unsupported, but 2 days ago it perfectly downloads this video from this url.

**Comment by hilbix** [comment] 2021-12-15 15:26
Probably duplicate of #30363, please see there.

**Comment by dirkf** [comment] 2021-12-16 03:46
Also, **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** which would have instructed you to provide a verbose log showing **the actual failure**.

Unless your problem is a new one for which you can post the log, @MaximFedarau, kindly close the issue.

**Closed** 2022-01-29 17:20 UTC
Labels: duplicate
