### ISSUE TITLE
YouTube throttling download through yt-dl

### ISSUE THREAD

**Issue by pococito** [ytdl-org/youtube-dl#30075] opened 2021-10-08 17:53 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Videos on YouTube play normally through a browser, but YouTube seems to be discovering yt-dl and throttling download speed to several KB/s instead of MB/s, like it used to work a few days ago. I get the same consistent throttling since a few days. Does anyone else experience this?

**Comment by 89z** [comment] 2021-10-09 01:32
I have an alternate tool here that works:

https://github.com/89z/mech

**Comment by pococito** [comment] 2021-10-09 14:59
@fastily - thanks, dlp works well

**Comment by speaknowpotato** [comment] 2021-10-12 16:45
thanks @fastily , yt-dlp work!

**Comment by NipLars** [comment] 2021-10-13 07:58
Sorry, I just filed a new report on this, did not read properly and associate this thread with my issue.
Is it just youtube-dl or general download limitation now?

Thinking if identified by Google, that Http User-Agent can be changed or let us assign the text for it ourselves so not trackable by Google?
Many browser has this kind of plugin to alter user agent and works very well to fix that a site does not work so well.

**Comment by triplesixman** [comment] 2021-10-13 16:09
> If it's fixed on yt-dlp would anyone give details on what causes the stream to be throttled technically on YouTube side ?

Hi, the problem is detailed here as well as its solution: https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-894619419

Now someone needs to work on this fix and apply it to youtube-dl. But I guess it won't be done before several months, or even next year (considering the workload and the inactivity of the current owner of youtube-dl).

**Comment by 3unjee** [comment] 2021-10-13 19:34
I believe yt-dlp is solving throttling through the Android API at the moment. Am I right ?

**Comment by chris-short** [comment] 2021-11-03 11:26
youtube-dl is definitely being throttled somehow.

**Comment by dirkf** [comment] 2022-01-31 00:38
Closed in af9e72507.

**Closed by dirkf** 2022-01-31 00:38 UTC
Labels: duplicate

**Comment by melMass** [comment] 2022-05-02 13:12
I had no idea youtube-dl was behind, yt-dlp indeed solves the throttling issue.
Thanks
