### ISSUE TITLE
"[debug]" line goes in stdout.

### ISSUE THREAD

**Issue by casinero** [ytdl-org/youtube-dl#14579] opened 2017-10-24 23:22 UTC
When I do
`youtube-dl.exe --no-playlist -v -J -i  ANY_YOUTUBE_VIDEO_URL 1>ytdl.stdout.log 2>ytdl.stderr.log`
Following lines are in ytdl.stderr.log:

    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--no-playlist', '-v', '-J', '-i', 'https://www.youtube.com/watch?v=Ocsl3bVsJZ8']
    [debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
    [debug] youtube-dl version 2017.10.20
    [debug] Python version 3.4.4 - Windows-10-10.0.15063
    [debug] exe versions: ffmpeg N-70348-g9564375, ffprobe N-70348-g9564375
    [debug] Proxy map: {}

And ytdl.stdout.log:

    [debug] Default format spec: bestvideo+bestaudio/best
    {"playlist": null, "view_count": 788201, "thumbnail": ......}

Shouldn't the `[debug] Default format spec: bestvideo+bestaudio/best` line be output through stderr, consistent with other [debug] lines?

I'm asking this because this behaviour change makes it difficult to capture JSON output in a wrapper program.

**Comment by yan12125** [comment] 2017-10-25 03:42
This should go away with #10894 implemented.

**Comment by robbiemorrison** [comment] 2019-01-07 14:46
This bug is still present I believe .. over one year on.

I am running the latest Ubuntu version. Ubuntu will not let me upgrade using `-U`.

The following youtube-dl output is **interspersed** with indented output from my bash script:

```
      name call : youtube-dl --verbose --no-overwrites --prefer-free-formats --get-filename --output "2018-thun-vid.%(ext)s" https://www.youtube.com/watch?v=EAmmUIEsN9A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-overwrites', '--prefer-free-formats', '--get-filename', '--output', '2018-thun-vid.%(ext)s', 'https://www.youtube.com/watch?v=EAmmUIEsN9A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.7 (CPython) - Linux-4.18.0-13-generic-x86_64-with-Ubuntu-18.10-cosmic
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
    exit status : 0
    output name : [debug] Default format spec: bestvideo+bestaudio/best
2018-thun-vid.webm
    information : script ends
```
The offending line that prints to stdout not stderr is:
```
[debug] Default format spec: bestvideo+bestaudio/best
```
This faulty output includes a trailing newline.

thanks to the developers and with best wishes, Robbie

**Comment by d-g** [comment] 2019-07-06 23:01
Dear maintainers and @yan12125 specifically,

may I ask, why this is marked as a feature request?

For anyone barely familiar with CLI, it’s obvious, that debug output has nothing to do with stdout, so observed behaviour is highly unexpected.

And this unexpected behaviour indeed harms usability: as `--verbose` option in config cannot be reversed on command line: `--no-verbose` does not exists and `--quiet` is simply ignored (which is possibly a bug by itself, but nevertheless), it became impossible to sketch a program that invokes youtube-dl(1) and respects user configuration — we can only ignore it completely.

**Comment by mvolfik** [comment] 2020-11-28 17:57
Just came across this. This is even worse as `-J` already includes quiet. This is also uncomfortable for the reason that I can't use `| json_pp` (pretty print json), as it breaks on the [debug] line. The functions `to_stdout`, `_write_string` and others should be reviewed and their usage unified (and probably better documented)

**Closed** 2020-11-28 21:04 UTC
Labels: bug
