### ISSUE TITLE
using mkvtoolnix/mkvmerge utility for metadata, adding thumbnail support subs and and other information embedding in mkv 

### ISSUE THREAD

**Issue by LovelyBloom** [ytdl-org/youtube-dl#31471] opened 2023-01-15 01:25 UTC
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
here's the thing ffmpeg is very slow with mkv but with MKVToolNIX or mkvmerge it is fast they already have cli and documents for integration. we can add video thumbnail support for mkv files and add the option of making them do the metadata and sub merging since ffmpeg is very slow on this front. all the user has to do is download the dependency and choco already has mkvtoolnix
what do you think?

**Comment by dirkf** [comment] 2023-01-15 12:15
If you wish, make a wrapper for your preferred tool(s) that accepts _ffmpeg_ command line syntax and invokes the tool(s).

https://video.stackexchange.com/a/35957 describes how a thumbnail can be embedded in MKV using _ffmpeg_, but I don't think we do that. Open a new issue if that's your problem.

Regarding speed, duplicate of #31470.

**Comment by LovelyBloom** [comment] 2023-01-16 23:23
well you need to be a youtube-dl args expert to be able to pull this off
can you at least show me an example?

**Comment by dirkf** [comment] 2023-01-17 17:32
Just call your script "ffmpeg" and tell yt-dl where to find it using `--ffmpeg-location ...`. You'll need a script called "ffprobe" too. Details will vary according to the script shell involved.

However I would suggest that you follow up the request in #31470 for a verbose log of the "slow" behaviour first. 

> ...  I don't think we do that. ...

No, and yt-dlp does do so.

**Comment by dirkf** [comment] 2023-01-28 16:30
MKV embedding continued in #31454.

**Closed by dirkf** 2023-01-28 16:30 UTC
Labels: request

**Comment by pukkandan** [comment] 2023-01-28 17:57
Related https://github.com/yt-dlp/yt-dlp/issues/126, https://github.com/yt-dlp/yt-dlp/issues/1879

**Comment by dirkf** [comment] 2023-01-28 19:13
Is there some way that the multiple _ffmpeg_ operations can be encoded as a filter graph and passed to a single _ffmpeg_ invocation?

Related: yt-dlp/yt-dlp#126
