### ISSUE TITLE
Unsupported URL: https://www.servustv.com/.....

### ISSUE THREAD

**Issue by ankopein** [ytdl-org/youtube-dl#30245] opened 2021-11-16 20:36 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.06.06**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
user@laptop:~/Videos$ ./youtube-dl -vF 'https://www.servustv.com/unterhaltung/v/aa-1vhrpc4rw2112/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.servustv.com/unterhaltung/v/aa-1vhrpc4rw2112/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-90-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] aa-1vhrpc4rw2112: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1vhrpc4rw2112: Downloading webpage
[generic] aa-1vhrpc4rw2112: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-1vhrpc4rw2112/
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2503, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2571, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2560, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3520, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-1vhrpc4rw2112/
```

## Description

Servus.com should be working. I even found it in the output of `youtube-dl --list-extractors `. So it must be broken. I tried also multiple different URLs, but none was working.

**Comment by kikuyan** [comment] 2021-11-17 00:37
Duplicate of #29485, #29554.
There's a PR #29556. However, development has been stopped for months, so it will not be merged soon, unfortunately.

**Closed** 2021-11-17 09:11 UTC
