### ISSUE TITLE
unable to extract uploader id

### ISSUE THREAD

**Issue by Rahul5252** [ytdl-org/youtube-dl#32068] opened 2023-04-20 11:49 UTC
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by glxblt14** [comment] 2023-04-20 13:26
Me too !

**Comment by mildred** [comment] 2023-04-20 15:15
Probably duplicate of #31530 and yt-dlp seems to have the issue fixed.

**Closed** 2023-04-20 16:46 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-04-20 17:02
>Probably duplicate of #31530 and yt-dlp seems to have the issue fixed.

Why only "Probably"? Also, the problem and its status are clearly and accurately in the issue.

OP et al., follow #30839 **as requested** to avoid unnecessary duplicate issues and find your solution more quickly.
