### ISSUE TITLE
banned.video

### ISSUE THREAD

**Issue by HalvorRaknes** [ytdl-org/youtube-dl#26852] opened 2020-10-09 23:17 UTC
`$ youtube-dl -f best -i --verbose https://banned.video/watch?id=5f7bab002a73f00ed2755e89 https://banned.video/watch?id=5f7f89b091d9ae103cc8405b
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'-i', u'--verbose', u'https://banned.video/watch?id=5f7bab002a73f00ed2755e89', u'https://banned.video/watch?id=5f7f89b091d9ae103cc8405b']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 2.7.17 (CPython) - Linux-5.4.0-48-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[generic] watch?id=5f7bab002a73f00ed2755e89: Requesting header
WARNING: Could not send HEAD request to https://banned.video/watch?id=5f7bab002a73f00ed2755e89: HTTP Error 403: Forbidden
[generic] watch?id=5f7bab002a73f00ed2755e89: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

[generic] watch?id=5f7f89b091d9ae103cc8405b: Requesting header
WARNING: Could not send HEAD request to https://banned.video/watch?id=5f7f89b091d9ae103cc8405b: HTTP Error 403: Forbidden
[generic] watch?id=5f7f89b091d9ae103cc8405b: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by dirkf** [comment] 2020-10-13 10:16
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/26805

**Closed** 2020-10-13 20:03 UTC
