### ISSUE TITLE
age-gated info webpage; ERROR: sign in to confirm your age/HTTP Error 410: Gone

### ISSUE THREAD

**Issue by lex-yey** [ytdl-org/youtube-dl#30953] opened 2022-05-17 02:59 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v -f mp3 "https://youtube.com/playlist?list=PLiYpKid9mmJiHdJrocAKxrmWlBBHuGNE6"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'mp3', 'https://youtube.com/playlist?list=PLiYpKid9mmJiHdJrocAKxrmWlBBHuGNE6']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] PLiYpKid9mmJiHdJrocAKxrmWlBBHuGNE6: Downloading webpage
[download] Downloading playlist: my vocaloid playlist but make it on spotify
[youtube:tab] playlist my vocaloid playlist but make it on spotify: Downloading 46 videos
[download] Downloading video 1 of 46
[youtube] hc0ZDaAZQT0: Downloading webpage
[youtube] hc0ZDaAZQT0: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1731, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
```

## Description

hi!!! so im trying to download around ~250 songs (5 playlists with around 50 songs each) onto an mp3 player, except i only have youtube/spotify playlist links!! ive been working on this for hours going through different sites and applications, transferring playlists from site to site, downloading a trojan (not intentionally </3), etc etc.

so i find this! and i have high hopes. it loads my first playlist name and everything :< and then,,,, it says i need to sign in and confirm my age to access/download the first song in the playlist, which halts the entire download. its a pretty dark song and its age restricted on youtube and i do not know how to get past that with this application. the playlist link works fine in a browser n stuff.

i genuinely do not know what to do at this point, im not Great at intricate techy stuff, and ive looked around but i havent found an issue similar to this/how to solve it. im not sure if this is the right category for this report but im doing my best :( idk how to do cookie bypassing n stuff and im sorry if this is a repeat question, i need the answer explained and laid out very simply and like all together with the commands i need to use.

tbh if anyone has any suggestions on how to do this at all with any free app im so desperate, i just want my music while im swimming </3 honestly at this point it wouldve been faster to manually download everything one by one but i just. i cannot do that to myself. its been like 3 hours with no progress im so tired.

if theres a plugin i can use or a command i overlooked, please please let me know. thank you so much!! <3333

**Comment by dirkf** [comment] 2022-05-17 10:49
For the moment, try using cookies from a logged-in browser session with `--cookies ...`, as explained in the [manual](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl).

Otherwise, duplicate of [#29578](https://github.com/ytdl-org/youtube-dl/issues/30019#issuecomment-1101357292).

**Comment by dirkf** [comment] 2022-06-01 12:22
@lex-yey ?

**Closed** 2022-06-06 17:08 UTC
Labels: clarification-needed, duplicate
