### ISSUE TITLE
Vimeo bug on pure digit urls

### ISSUE THREAD

**Issue by gzz2000** [ytdl-org/youtube-dl#31494] opened 2023-01-25 11:05 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
% youtube-dl -c -i https://vimeo.com/791078894/4616111735 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-c', '-i', 'https://vimeo.com/791078894/4616111735', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 344d32bf7
[debug] Python version 3.10.9 (CPython) - macOS-11.2.3-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[vimeo] 4616111735: Downloading webpage
[vimeo] 4616111735: Downloading JSON metadata
[vimeo] 4616111735: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)


```

## Description

Hello.
I am downloading a bunch of video links from Vimeo.
Most of them work well, except this single one:

https://vimeo.com/791078894/4616111735

By inspecting the format of this url, it seems that the last part (4616111735) by chance is consisted of full digits, without any English letters a-z. The log starts with `Downloading webpage`, instead of `Downloading JSON metadata`.

**Comment by dirkf** [comment] 2023-01-25 13:55
> I've searched the bugtracker for similar issues including closed ones

Nonetheless, duplicate of #29690, fixed in git master.

**Closed by dirkf** 2023-01-25 13:55 UTC

**Comment by gzz2000** [comment] 2023-01-25 13:58
> > I've searched the bugtracker for similar issues including closed ones
> 
> Nonetheless, duplicate of #29690, fixed in git master.

Oh I'm sorry... Thanks for pointing me to that.
