### ISSUE TITLE
Unable to download TikTok videos

### ISSUE THREAD

**Issue by Xihuny** [ytdl-org/youtube-dl#20981] opened 2019-05-07 05:27 UTC
## Verbose log
```
F:\>dl --verbose http://vm.tiktok.com/dAdauQ/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://vm.tiktok.com/dAdauQ/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.04.30
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] dAdauQ: Requesting header
[redirect] Following redirect to https://www.tiktok.com/share/video/6687504561420111110?u_code=d0lgi93ekk94id&preview_pb=0&language=en&utm_source=more&utm_campaign=client_share&utm_medium=android&share_app_name=musically&iid=6687483465229190918&timestamp=1557076959&user_id=6573177672237875206
[TikTok] 6687504561420111110: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\tiktok.py", line 101, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpfeq7l785\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description
This is the log I get when I try to download TikTok videos using share url.

**Comment by ealgase** [comment] 2019-05-07 05:44
Duplicate of #20809

**Closed** 2019-05-07 09:08 UTC
