### ISSUE TITLE
Index Error: list index out of range

### ISSUE THREAD

**Issue by mfarrokhidg** [ytdl-org/youtube-dl#31065] opened 2022-07-01 14:34 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/6025032/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[NhkVod] 6025-032: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2069, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\nhk.py", line 130, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\nhk.py", line 32, in _extract_episode_info
IndexError: list index out of range

## Description

WRITE DESCRIPTION HERE
I have been able to download videos from ''https://www3.nhk.or.jp/nhkworld/en/ondemand/video' but recently it gives 'IndexError: list index out of range' error. Some videos can still be downloaded but others cannot like the followings:

https://www3.nhk.or.jp/nhkworld/en/ondemand/video/6025032/
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2032267/
https://www3.nhk.or.jp/nhkworld/en/ondemand/video/6025031/

**Comment by dirkf** [comment] 2022-07-01 15:17
> I've searched the bugtracker for similar issues including closed ones

Really?

Duplicate of #31028, fixed in git master.

**Closed** 2022-07-16 18:34 UTC
Labels: duplicate
