### ISSUE TITLE
Download from Joyn not Working

### ISSUE THREAD

**Issue by chris83ms** [ytdl-org/youtube-dl#30185] opened 2021-11-01 23:19 UTC
When trying to Download https://edge.vod-prd.s.joyn.de/v0/CiQyY2IzYTM0NC0xMjUzLTQwODgtYjEzMS1hZWNkYTM4YmI5N2E.Cg1hX3BmcTZ2Ympmcjd0EAEYwAQiJDY2NGRjYjY3LWYwMmItNDgyYS1iMWNiLTVhZDA1YWY0YTljMA.pT0y4N97zxrFFttBfoE9E5XE8PwVlurTtZtf-iPVxjY/a_pfq6vbjfr7t/.ism/.m3u8\?filter\=CiQ5MjZiOWIzNC0yNjc1LTQyZWUtYjJlYy1lYTVkMTY2MGMzOTU.Cg1hX3BmcTZ2Ympmcjd0ElcodHlwZT09InZpZGVvIiYmTWF4SGVpZ2h0PD01NzYpfHwodHlwZT09ImF1ZGlvIiYmRm91ckNDPT0iQUFDTCImJnN5c3RlbUxhbmd1YWdlPT0iZGV1Iik.YsxPCw5Hj1IAsxlMSTDv6K6N3l2_ffSIM595WWq2v64

I'll get the message "No video formats found; please report this issue on https://yt-dl.org/bug".

I'm using the latest version of YouTube-dl

**Comment by kikuyan** [comment] 2021-11-02 00:09
DRM protected. youtube-dl doesn't support.
There's a line in the m3u8:
> #EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://6368632f49263790335c554546a6380b",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

**Comment by antifarben** [comment] 2021-12-22 19:06
duplicate of #21441

**Comment by 89z** [comment] 2022-04-23 21:47
Issue should be closed, URL is dead

**Closed** 2023-07-17 02:30 UTC
Labels: duplicate
