### ISSUE TITLE
Error with Facebook video

### ISSUE THREAD

**Issue by rodolfo-medina** [ytdl-org/youtube-dl#31870] opened 2023-03-17 21:46 UTC
I get the following error when trying to download a video from Facebook:

 ERROR: Cannot parse data

The command `youtube-dl -U' gets the following:

 youtube-dl is up-to-date (2021.12.17)

Here's the whole output with the '--verbose' option:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/[...]']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - Linux-6.0.0-5-amd64-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2-1, ffprobe N-98534-g5eb4405fc5, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1254018565441603: Downloading webpage
[facebook] 1254018565441603: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 680, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 594, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks.

**Comment by dirkf** [comment] 2023-03-17 22:51
Follow #30839, please.

This issue is a duplicate of #30872. There is a new FB extractor in PR #30700. If you can, you might try that and report there. Otherwise, the testing for the PR will take account of this report.

**Closed** 2023-03-17 22:51 UTC
Labels: duplicate
