### ISSUE TITLE
Can't download from 10play.com.au

### ISSUE THREAD

**Issue by git-fr** [ytdl-org/youtube-dl#29638] opened 2021-07-24 16:43 UTC
```
 youtube-dl  --geo-bypass --geo-bypass-country au https://10play.com.au/the-bureau-of-magical-things/episodes/season-2/episode-10/tpv210722hbwdx --verbose
 [debug] System config: []
 [debug] User config: []
 [debug] Custom config: []
 [debug] Command-line args: ['--geo-bypass', '--geo-bypass-country', 'au', 'https://10play.com.au/the-bureau-of-magical-things/episodes/season-2/episode-10/tpv210722hbwdx', '--verbose']
 [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
 [debug] youtube-dl version 2021.06.06
 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
 [debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
 [debug] Proxy map: {}
 [debug] Using fake IP 1.139.254.100 (AU) as X-Forwarded-For.
 [TenPlay] tpv210722hbwdx: Downloading JSON metadata
 [TenPlay] 9000000000027800: Downloading webpage
 ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
 File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
 File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
 File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
 File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
 File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

**Comment by section83** [comment] 2021-07-26 01:42
It's a DRM issue.  You need to provide credentials – but, YTDL also needs to be updated to take credentials for 10Play. You could try this fork which works for me (on macOS 10.15.7): https://github.com/yt-dlp/yt-dlp.

**Comment by 89z** [comment] 2022-04-23 20:27
geo blocked:

> 10play is available for Australian residents only

**Comment by dirkf** [comment] 2022-09-16 14:53
Duplicate of #28641.

**Closed by dirkf** 2022-09-16 14:53 UTC
Labels: geo-restricted
