### ISSUE TITLE
youtube description is not working properly

### ISSUE THREAD

**Issue by donek161066** [ytdl-org/youtube-dl#23341] opened 2019-12-07 13:01 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]', '--add-metadata', '-v', 'https://www.youtube.com/watch?v=DPC9erC5WqU']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg git-2019-12-03-12bbfc4
[debug] Proxy map: {}
[youtube] DPC9erC5WqU: Downloading webpage
[youtube] DPC9erC5WqU: Downloading video info webpage
[youtube] {18} signature length 103, html5 player vflYr569U
[youtube] {137} signature length 103, html5 player vflYr569U
[youtube] {248} signature length 103, html5 player vflYr569U
[youtube] {136} signature length 107, html5 player vflYr569U
[youtube] {247} signature length 107, html5 player vflYr569U
[youtube] {135} signature length 103, html5 player vflYr569U
[youtube] {244} signature length 107, html5 player vflYr569U
[youtube] {397} signature length 107, html5 player vflYr569U
[youtube] {134} signature length 103, html5 player vflYr569U
[youtube] {243} signature length 107, html5 player vflYr569U
[youtube] {396} signature length 107, html5 player vflYr569U
[youtube] {133} signature length 107, html5 player vflYr569U
[youtube] {242} signature length 103, html5 player vflYr569U
[youtube] {395} signature length 107, html5 player vflYr569U
[youtube] {160} signature length 107, html5 player vflYr569U
[youtube] {278} signature length 107, html5 player vflYr569U
[youtube] {394} signature length 103, html5 player vflYr569U
[youtube] {140} signature length 107, html5 player vflYr569U
[youtube] {249} signature length 107, html5 player vflYr569U
[youtube] {250} signature length 103, html5 player vflYr569U
[youtube] {251} signature length 107, html5 player vflYr569U
[debug] Invoking downloader on 'https://r6---sn-u2oxu-n11e.googlevideo.com/videoplayback?expire=1575744123&ei=G57rXanhIIyzgAeynq-4CA&ip=79.186.49.182&id=o-AJFWdBnIn40oQFsZEDsAIJdTs_QhVlRg1YWreQtTSQ-e&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-u2oxu-n11e%2Csn-u2oxu-f5fr&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=928750&mime=video%2Fmp4&gir=yes&clen=41256015&dur=344.916&lmt=1574751281873654&mt=1575722439&fvip=8&keepalive=yes&fexp=23842630&beids=9466587&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhALReBMqskSuPPZ6tKbCSSNWzKJi-hyzKkF7Qa9gQnhiPAiA773ETySvgtG64HwEK34rGuv2ynoIvYBVpJOyWRyporQ%3D%3D&sig=ALgxI2wwRgIhAMTI6ir24RJUGHoLFhkn5Tm7B0cOjKb2HpMggnbhj4-4AiEA466IvV9e6qh3_O3s-ULPPJrjCfcgjyOySJciC4K7NhU=&ratebypass=yes'
[download] Destination: Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f136.mp4
[download] 100% of 39.34MiB in 00:51
[debug] Invoking downloader on 'https://r6---sn-u2oxu-n11e.googlevideo.com/videoplayback?expire=1575744123&ei=G57rXanhIIyzgAeynq-4CA&ip=79.186.49.182&id=o-AJFWdBnIn40oQFsZEDsAIJdTs_QhVlRg1YWreQtTSQ-e&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-u2oxu-n11e%2Csn-u2oxu-f5fr&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=928750&mime=audio%2Fmp4&gir=yes&clen=5583813&dur=344.978&lmt=1574748235785267&mt=1575722439&fvip=8&keepalive=yes&fexp=23842630&beids=9466587&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhALReBMqskSuPPZ6tKbCSSNWzKJi-hyzKkF7Qa9gQnhiPAiA773ETySvgtG64HwEK34rGuv2ynoIvYBVpJOyWRyporQ%3D%3D&sig=ALgxI2wwRQIhAJC_tUln8meFaycrprVLNthNi1pCA_he8ViFf7r-ZR7tAiB1Ium6dE3D8yhjiL6ojDxD9WRVAnUoAHPRJvaUxKtSxA==&ratebypass=yes'
[download] Destination: Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f140.m4a
[download] 100% of 5.33MiB in 00:07
[ffmpeg] Merging formats into "Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f136.mp4" -i "file:Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.temp.mp4"
Deleting original file Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f136.mp4 (pass -k to keep)
Deleting original file Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.f140.m4a (pass -k to keep)
[ffmpeg] Adding metadata to 'Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.mp4" -c copy -metadata "description=Translation (Korean & Japanese to English):

Don't Forget (Whoo!)
Underwater squad
I still got camo on my body
Orca ninjas go Rambo

[Verse 1]
Don't forget! Don't forget! That we are the best
Yeah it shines yeah it shines yes we are the ones that shine
Mind your own business you are you I am me
We the killer whales, spread our wings and swim on money
C-O-H-O-R-T, we the Cohort, pay these boys
Motherfucker fucker, mouthing empty words (fuck 'em)
You are you, I am me, get that in your head
While you bitch about others I go and make money

[Verse 2]
Watering brain cell is a daily routine, kiss to a blunt
I tie my hair then go on to a battlefield
Open the map of the world, them ninjas on the mission
Slash them obstacles with no hesitation
No doubt about it when it’s a life and death situation
Just like kill bill all humans are lonely at the end
You best leave as much as you can
Mothafucka, y'all can't feel my pain
No excuses are prepared
Ain't no tinkerbell following those empty eyes
Lotta chicks around here" -metadata "purl=https://www.youtube.com/watch?v=DPC9erC5WqU" -metadata "date=20150101" -metadata "artist=Hi-Lite Records" -metadata "comment=Translation (Korean & Japanese to English):

Don't Forget (Whoo!)
Underwater squad
I still got camo on my body
Orca ninjas go Rambo

[Verse 1]
Don't forget! Don't forget! That we are the best
Yeah it shines yeah it shines yes we are the ones that shine
Mind your own business you are you I am me
We the killer whales, spread our wings and swim on money
C-O-H-O-R-T, we the Cohort, pay these boys
Motherfucker fucker, mouthing empty words (fuck 'em)
You are you, I am me, get that in your head
While you bitch about others I go and make money

[Verse 2]
Watering brain cell is a daily routine, kiss to a blunt
I tie my hair then go on to a battlefield
Open the map of the world, them ninjas on the mission
Slash them obstacles with no hesitation
No doubt about it when it’s a life and death situation
Just like kill bill all humans are lonely at the end
You best leave as much as you can
Mothafucka, y'all can't feel my pain
No excuses are prepared
Ain't no tinkerbell following those empty eyes
Lotta chicks around here" -metadata "title=Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]" "file:Keith Ape - 잊지마 (It G Ma) (feat. JayAllDay, Loota, Okasian & Kohh) [Official Video]-DPC9erC5WqU.temp.mp4"
```

## Description

descriptions arent the same
![Screenshot_11](https://user-images.githubusercontent.com/42392691/70374987-529a7900-18f9-11ea-9a6e-4bf4c145b80b.png)

**Comment by remitamine** [comment] 2019-12-07 13:29
Duplicate of #10758.

**Closed by remitamine** 2019-12-07 13:29 UTC

**Comment by donek161066** [comment] 2019-12-07 14:45
its not duplicate. its problem with wrong interpretation description by youtubue-dl
