### ISSUE TITLE
tweet includes a video accompanied with picture(s)

### ISSUE THREAD

**Issue by TwitterToTelegram** [ytdl-org/youtube-dl#31993] opened 2023-04-04 10:06 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[twitter] 1643027903897010178: Downloading guest token
[twitter] 1643027903897010178: Downloading JSON metadata
[twitter] 1643027903897010178: Downloading JSON metadata
[twitter] 1643027903897010178: Downloading JSON metadata
[twitter] 1643027903897010178: Downloading JSON metadata
.
.
.
[twitter] 1643027903897010178: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests
```

## Description

On Twitter, if a tweet includes two videos or includes a video that is accompanied by pictures, it constantly says "Downloading JSON metadata" on Python 3.9.9 executed using VS Code.  And at the end, the video is not downloaded. 

Example tweet's URL given to youtb-dl:
> https://twitter.com/Aiydin4KSTUV/status/1643027903897010178

The tweet includes a short url as "https://t.co/06IqPawxe8" that if expanded becomes "https://twitter.com/Aiydin4KSTUV/status/1643027903897010178/video/1". Giving the expanded url did not work either.

The Python code is:

import youtube_dl
wlink=r"https://twitter.com/Aiydin4KSTUV/status/1643027903897010178"
ydl_opts = {'outtmpl': filename
            ,'forceduration':True
            ,'quiet': False}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([wlink])

**Comment by dirkf** [comment] 2023-04-04 16:10
I think this is #31281, which will be fixed once someone gets around to back-porting the yt-dlp extractor and assuming that Twitter is still operating and still offering the APIs used by the extractor.

**Comment by october262** [comment] 2023-04-05 10:35
if you just want the video, click on where it says share - click copy link to tweet
and do youtube-dl -o '%(title).20s' "https://twitter.com/Aiydin4KSTUV/status/1643026535790551040?s=20"
to download the video. you may have to add .mp4 to the end of the file name once it is downloaded.

**Comment by dirkf** [comment] 2023-04-07 22:50
Closing as duplicate of #31281.

**Closed by dirkf** 2023-04-07 22:50 UTC
