### ISSUE TITLE
403 when downloading youtube video clips

### ISSUE THREAD

**Issue by LikeMeThis** [ytdl-org/youtube-dl#32791] opened 2024-05-20 03:47 UTC
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 4 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 5 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 6 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 7 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 8 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 9 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 1 (attempt 10 of 10)...
send: b'GET /videoplayback?expire=1716198159&ei=r8ZKZrPPFYmvsfIP09OL2AI&ip=47.254.75.46&id=o-AD9_TwcqDJ6M7m7f_2oTZfsbvIe7ELzMgyIJr9g4lsYC&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=_F&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znse&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2002500&bui=AWRWj2RTHJ1G2wbwRJ73ZdDuov-77N3CxQgdi6_hFSIMtyIe03Qhdr_WOl-tR8GCQp8SjchVodT7QXa7&spc=UWF9f9_urI-KKoOKRvOchfNelF_Ugpr52ZAWCl1JiWObwVN1fuICVqY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=irdZt-IzKdQYT0TK7s0E6EwQ&rqh=1&gir=yes&clen=52897647&dur=204.400&lmt=1687510432366125&mt=1716176223&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=6319224&n=A-wXITQwGhKkIg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXCISmAHbPgWpBTZkOQl3UEQZtrH79GwX6kx7tMXR-9ECIAr4z71rergKrlwZdZG9ZSw5hqEhH4TZsu8vvppsYyAt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhALi5BXdUIY22g99pKAQGCMyiTOONNQ5docVecM7lHsUHAiBb4Vbk3n647r-VEVtRA-3OyD25pER8Mv4Vgo1AmFGrFA%3D%3D&range=0-10485759 HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: rr5---sn-n4v7sns7.googlevideo.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3631.1 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Last-Modified: Wed, 02 May 2007 10:26:10 GMT
header: Content-Type: text/plain
header: Content-Length: 0
header: Connection: close
header: Vary: Origin
header: Cross-Origin-Resource-Policy: cross-origin
header: X-Restrict-Formats-Hint: None
header: X-Content-Type-Options: nosniff
header: Date: Mon, 20 May 2024 03:42:41 GMT
header: Server: gvs 1.0
ERROR: giving up after 10 fragment retries
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 473, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 463, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2222, in download
    res = self.extract_info(
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 856, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 970, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1004, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1839, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2121, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2066, in dl
    return fd.download(name, new_info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 380, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/dash.py", line 78, in real_download
    self.report_error('giving up after %s fragment retries' % count)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 175, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in report_error
    self.trouble(*args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 618, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

This problem occurs when downloading youtube video, would like to ask what is the cause, the tool has been updated to the latest, may be an IP problem?

**Comment by tingkelvin** [comment] 2024-06-23 13:28
I am having the same issue.
Seems like YouTube has blocked it.

**Comment by dirkf** [comment] 2024-06-23 19:03
Given no further evidence from reporters, duplicate of #32815, fixed in master and nightly.

**Closed by dirkf** 2024-06-23 19:03 UTC
Labels: question
