### ISSUE TITLE
[XVideos] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>)

### ISSUE THREAD

**Issue by mirghany** [ytdl-org/youtube-dl#30434] opened 2021-12-27 11:52 UTC
youtube-dl --verbose https://www.xvideos.com/video62548949/amalia_eager_i_invite_my_secretary_to_the_bar_and_we_end_the_party_by_fucking_in_the_bathroom.
[debug] System config: ['--no-mtime', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', '~/Downloads/private/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.xvideos.com/video62548949/amalia_eager_i_invite_my_secretary_to_the_bar_and_we_end_the_party_by_fucking_in_the_bathroom.']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.9 (CPython) - Linux-5.15.6-100.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Proxy map: {}
[XVideos] 62548949: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by kikuyan** [comment] 2021-12-28 00:27
Please search before post. Duplicate of #30276.
There's a PR #30278.

**Comment by Rocksteady18** [comment] 2021-12-28 15:32
Oy, coomers...

**Comment by 89z** [comment] 2021-12-28 15:56
@Rocksteady18 fuck off, freakazoid.

**Closed** 2022-02-05 02:24 UTC
Labels: duplicate
