### ISSUE TITLE
[Pluralsight] Failed to parse JSON

### ISSUE THREAD

**Issue by vsattry** [ytdl-org/youtube-dl#30829] opened 2022-04-07 17:11 UTC
```ShellSession
PS C:\Users\Administrator\Downloads> .\youtube-dl.exe -v
[debug] System config: []
[debug] User config: ['--abort-on-error', '--no-warnings', '--console-title', '--batch-file=batch-file.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36', '--cookies', 'cookies.txt', '--socket-timeout', '10', '--retries', '10', '--continue', '--fragment-retries', '10', '--min-sleep-interval', '60', '--max-sleep-interval', '80', '-f', 'best[height<=720]/worst[height>720]', '-o', '%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)d-%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Batch file urls: ['https://app.pluralsight.com/library/courses/msft-365-identity-services-designing-implementing-services/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] msft-365-identity-services-designing-implementing-services: Downloading JSON metadata
[pluralsight:course] msft-365-identity-services-designing-implementing-services: Downloading JSON metadata
ERROR: msft-365-identity-services-designing-implementing-services: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 906, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pluralsight.py", line 467, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\pluralsight.py", line 93, in _download_course
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 899, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 883, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 910, in _parse_json
youtube_dl.utils.ExtractorError: msft-365-identity-services-designing-implementing-services: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment] 2022-04-08 02:50
Like #30818, duplicate of #30765, except Py3 instead of Py2.

If you had reported this using the [Broken site support template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md), you would have been prompted to check existing issues.

**Comment by Anaristos** [comment] 2022-11-29 21:18
So instead of fixing the video you slap the complainant on the wrist and send him on his way without giving a clue as to how to resolve this problem. Great technique. Protocol over results, that will save the world,l I am sure.

**Comment by dirkf** [comment] 2022-11-30 00:07
So tell us how to fix the problem ... in #30765.

The protocol exists to help everyone: maintainers are saved from wrist-slapping while users are directed to the issue where their problem is being discussed. Directing someone to the relevant issue is not "sending ... on his way". No-one is being paid to do this.

A highly popular downstream fork takes a more draconian view:

>DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
>
>    I understand that I will be blocked if I remove or skip any mandatory* field

**Closed** 2022-11-30 00:07 UTC
Labels: broken-IE, duplicate

**Comment by Anaristos** [comment] 2022-11-30 00:24
That is well and good but you missed the point which is that I didn't get
an answer to my question, instead I had to read about someone being
disciplined. Hardly what I expected when I clicked on the link. I realize
you are not being paid and I do appreciate your time. However there is no
point in volunteering if you are going to resent having to do what you
volunteered to do.

**Comment by dirkf** [comment] 2022-11-30 01:25
If there is an answer it will be found in the original issue #30765. OTOH someone who can't be bothered to click a link deserves more than a wrist-slapping: a spleen-punching, say, or a groin-kicking. As these features have not yet been implemented by GitHub, such a person could arrange to receive the appropriate penalty, perhaps with the help of a nearby enemy, the police (especially in China), or whoever.
