### ISSUE TITLE
filemoon.sx No video formats found'

### ISSUE THREAD

**Issue by piotr47234** [ytdl-org/youtube-dl#32967] opened 2024-11-06 17:45 UTC
python3 ./youtube_dl/__main__.py https://filemoon.sx/e/93rmnwtezs2x --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://filemoon.sx/e/93rmnwtezs2x', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: c5098961b
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.15.131-2-pve-x86_64-with-glibc2.31 - OpenSSL 1.1.1w  11 Sep 2023 - glibc 2.31
[debug] exe versions: ffmpeg 4.3.7-0, ffprobe 4.3.7-0
[debug] Proxy map: {}
[XFileShare] 93rmnwtezs2x: Downloading webpage
ERROR: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/opt/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/ytdl-org/youtube-dl/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/ytdl-org/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/opt/ytdl-org/youtube-dl/youtube_dl/extractor/xfileshare.py", line 278, in _real_extract
    self._sort_formats(result['formats'])
  File "/opt/ytdl-org/youtube-dl/youtube_dl/extractor/common.py", line 1558, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by dirkf** [comment] 2024-11-07 10:57
Duplicate of #32946.

**Closed by dirkf** 2024-11-07 10:57 UTC

**Comment by biemster** [comment] 2025-01-15 12:26
I'm currently getting this error even with #32944 included:
```bash
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://filemoon.sx/e/nvqxe2lfwwvj', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: f7dc45d3a
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-33-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[XFileShare] nvqxe2lfwwvj: Downloading webpage
[XFileShare] nvqxe2lfwwvj: Downloading player page
WARNING: Unable to download webpage: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/lars/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lars/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lars/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/lars/Downloads/youtube-dl/youtube_dl/extractor/xfileshare.py", line 316, in _real_extract
    self._sort_formats(result['formats'])
  File "/home/lars/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 1558, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
```
although it does include a `403: Forbidden` now.
