### ISSUE TITLE
Request login to VK but really it no needs to download video

### ISSUE THREAD

**Issue by walkman99** [ytdl-org/youtube-dl#31055] opened 2022-06-26 20:06 UTC
## Checklist

[x] I'm reporting a broken site support issue
[x] I've verified that I'm running youtube-dl version **2021.12.17**
[x] I've checked that all provided URLs are alive and playable in a browser
[x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
[x] I've searched the bugtracker for similar bug reports including closed ones
[x] I've read bugs section in FAQ

## Verbose log
```
youtube-dl -v https://vk.com/video36655777_456239421

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vk.com/video36655777_456239421']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev, ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Proxy map: {}
[vk] 36655777_456239421: Downloading JSON metadata
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\vk.py", line 325, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\vk.py", line 72, in _download_payload
    self.raise_login_required()
  File "c:\program files\python38\lib\site-packages\youtube_dl\extractor\common.py", line 941, in raise_login_required
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
```
## Description

Some weeks ago it works. Youtube-dl request username and password for this URL, but really no need any login to view this video. And if run with "-u user -p pass" to login, it also not worked. 
Probably VK change something and procedure in youtube_dl\extractor\vk.py", line 72 has incorrect return code.

**Comment by dirkf** [comment] 2022-06-26 22:54
> [x] I've searched the bugtracker for similar bug reports including closed ones

Apparently not. Duplicate of [#31035](https://github.com/ytdl-org/youtube-dl/issues/31035#issuecomment-1161719063), but see also https://github.com/ytdl-org/youtube-dl/issues/31053#issuecomment-1166338490.

.

**Closed** 2022-08-21 09:16 UTC
Labels: duplicate
