### ISSUE TITLE
Twitch: login failure due to missing twitchguard code

### ISSUE THREAD

**Issue by david-wm-sanders** [ytdl-org/youtube-dl#23337] opened 2019-12-06 18:05 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.twitch.tv/videos/<redacted>', '-u', 'PRIVATE', '-v']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92498-g77bf85515e, ffprobe N-92498-g77bf85515e
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in
ERROR: Unable to login. Twitch said: missing twitchguard code
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\twitch.py", line 64, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\twitch.py", line 119, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\twitch.py", line 96, in login_step
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\twitch.py", line 73, in fail
youtube_dl.utils.ExtractorError: Unable to login. Twitch said: missing twitchguard code
```

## Description

On trying to download a video from Twitch, I received the error as shown above. The video is open to subscribers only at the moment, hence the need to provide a username (with -u) and provide the account password at the prompt. On providing the password, login fails with a "missing twitchguard code" error message.

I ran youtube-dl again with --dump-pages and it shows:

```
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Dumping request to https://www.twitch.tv/login
<large base64 encoded dump>
[twitch:vod] Logging in
[twitch:vod] Dumping request to https://passport.twitch.tv/login
<smaller base64 encoded dump>
ERROR: Unable to login. Twitch said: missing twitchguard code
```

The smaller base64 encoded dump, decoded with base64.b64decode(dump), shows:

```
b'{"captcha_proof":"<redacted>","error":"Please enter a Login Verification Code.","error_code":3022,"error_description":"missing twitchguard code"}'
```

It seems like Twitch have introduced a form of login verification - I received an email from Twitch with the subject "Your Twitch Login Verification Code" shortly after running youtube-dl, however there is no prompt by youtube-dl to provide this code in order to continue logging in.

As a note, if I enter an invalid password for the account, I still get `youtube_dl.utils.ExtractorError: Unable to login. Twitch said: invalid password` so I am sure that the above error occurs after the password has been validated as correct by Twitch.

**Comment by colakong** [comment] 2019-12-16 21:39
[This patch](https://gitlab.com/snippets/1923017) worked for me. I didn't see a generic way of passing cli params into InfoExtractor objects on/after creation, so I updated `YoutubeDL.extract_info` method to check for the new `--twitch-guard-code` cli param, and set it in the info extractor object if found. The twitch info extractors then include it during auth if it's set.

When logging in interactively, the browser also includes a `"captcha":{"proof":"_stuff here_"}` key & object in the auth payload. Thankfully it seems to work with just the `twitchguard_code` key & value.

I applied the patch to [a fork of youtube-dl](https://github.com/colakong/youtube-dl), but I'm not going to PR it because there should be a more generic way of applying cli params to arbitrary IE's.

With the patch, the workflow is:
1. Issue the `youtube-dl` command
2. Login fails, you get an email with twitch guard code
3. Issue same `youtube-dl` command, this time with `--twitch-guard-code` specified for the code in your email

**Comment by PolygraphMusic** [comment] 2019-12-18 22:24
@colakong i have the same issue with twitch. 
"ERROR: Unable to login. Twitch said: captcha incorrect" 
Don't know what to do with this at the moment. 
Hope it will be solved.

**Comment by david-wm-sanders** [comment] 2019-12-20 03:05
@PolygraphMusic

The only workaround at the moment seems to be to use the `--cookies` option for youtube-dl as detailed [here](https://github.com/david-wm-sanders/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).

In short:
1. Extract the cookies for domain `.twitch.tv` from your browser (see the link above for extensions that do this extraction for you) to `cookies.txt`
2. Run  `youtube-dl.exe --cookies=cookies.txt https://www.twitch.tv/videos/<numeric_id>` (do not use the youtube-dl `--username` or `--password` options in this case)

**Comment by colakong** [comment] 2019-12-20 05:58
@david-wm-sanders <https://github.com/david-wm-sanders>

That works for me, thanks for the tip :)

**Comment by luduslake** [comment] 2019-12-20 18:53
@david-wm-sanders

Now I get this:
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by HTTPError())

**Comment by david-wm-sanders** [comment] 2019-12-20 19:34
@CLUexe

Could you provide the full output with youtube-dl's `--verbose` option?

At a guess though, I'd say either your cookies (in the cookies file) are expired or, perhaps more likely, youtube-dl can't find the cookies file.

For example, I got a HTTP 403 Forbidden error when I didn't pass the path to the cookies file correctly. I think it showed up as HTTP 403 but when I ran with `--verbose` I could see that other errors, like the invalid argument below, had been suppressed:

`OSError: [Errno 22] Invalid argument: "C:\\Users\\david\\projects\\twitchget\\cookies.txt"`

**Comment by CLUexe** [comment] 2019-12-21 06:57
@david-wm-sanders 

You were spot on, it had something to do with the cookies. The cookies from my Chrome browser gave me the errors but I tried using fresh cookies from Firefox and it worked. Honestly this stuff makes no sense to me if chrome can use the older cookies but youtube-dl can't. Anyway, thanks for your help!

**Comment by reallyuniquename** [comment] 2020-07-14 15:46
If you don't want to bother with `cookies.txt` file you can just dump complete `Cookie` header from network tab of your favorite browser and supply it to yt-dl:
`youtube-dl --add-header "Cookie: unique_id=123; server_session=abcdef" https://www.twitch.tv/videos/12345678`

**Comment by WhiteAls** [comment] 2021-01-12 16:40
still doesnt work for me, even with fresh exported cookies. i tried to export it from the opera and firefox - no luck
```
PS C:\Users\Als\Downloads\chats> ls *.txt


    Каталог: C:\Users\Als\Downloads\chats


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12.01.2021     19:11           2015 1.txt
-a----        12.01.2021     19:32           2072 20200827211039_DECODE_INFO.txt
-a----        12.01.2021     19:15           4705 cookies (4).txt
-a----        12.01.2021     19:00           3202 cookies.txt
-a----        12.01.2021     19:19           1822 twitch.tv_cookies.txt


PS C:\Users\Als\Downloads\chats> youtube-dl --cookies=20200827211039_DECODE_INFO.txt --verbose https://www.twitch.tv/videos/000000000
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies=20200827211039_DECODE_INFO.txt', '--verbose', 'https://www.twitch.tv/videos/000000000']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.01.08
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.21286-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] 000000000: Downloading stream metadata GraphQL
[twitch:vod] 000000000: Downloading video access token GraphQL
[twitch:vod] 000000000: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\users\als\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\als\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\als\appdata\local\programs\python\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\als\appdata\local\programs\python\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\als\appdata\local\programs\python\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\als\appdata\local\programs\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\als\appdata\local\programs\python\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

PS C:\Users\Als\Downloads\chats>

```

**Comment by racingmars** [comment] 2021-01-15 23:00
> still doesnt work for me, even with fresh exported cookies.

Me neither. The cookie method worked for me a week or two ago, so I'm guessing something has recently changed on the Twitch side which is causing the 403 error even with proper cookies now.

**Comment by WhiteAls** [comment] 2021-01-17 15:35
fixed in https://github.com/ytdl-org/youtube-dl/pull/27790

**Closed** 2024-05-25 11:22 UTC
