### ISSUE TITLE
Site Broken (False GeoRestricted Error)

### ISSUE THREAD

**Issue by stefanodvx** [ytdl-org/youtube-dl#29998] opened 2021-09-20 18:36 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.mediasetplay.mediaset.it/video/fireforce/ep-6-i-fiori-di-fuoco-della-promessa_F311040901000601', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-101309-g10341743d2, ffprobe N-101309-g10341743d2
[debug] Proxy map: {}
[Mediaset] F311040901000601: Downloading JSON metadata
[Mediaset] F311040901000601: Downloading MPEG4 SD SMIL data
[Mediaset] F311040901000601: Downloading MPEG4 HD SMIL data
ERROR: This content is not available in your location.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\mediaset.py", line 157, in _real_extract
    raise first_e
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\mediaset.py", line 142, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\theplatform.py", line 47, in _extract_theplatform_smil
    self.raise_geo_restricted(error_element.attrib['abstract'])
  File "c:\users\stefano\appdata\local\programs\python\python39\lib\site-packages\youtube_dl\extractor\common.py", line 947, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
youtube_dl.utils.GeoRestrictedError: This content is not available in your location.
```

## Description

Verbose says its a GeoRestrict error, but thats not true, as Im running the command on my PC where I can watch episodes with no problem as im Italian.

**Comment by kikuyan** [comment] 2021-09-20 22:44
Duplicate of #29218.

**Comment by dirkf** [comment] 2022-01-01 23:27
Show no longer available.

**Closed** 2022-01-29 16:35 UTC
Labels: duplicate
