### ISSUE TITLE
This is time for a release!!!!

### ISSUE THREAD

**Issue by patmconlon** [ytdl-org/youtube-dl#32268] opened 2023-06-04 00:51 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Time for a release and get off your shoulders. Don't want to be rude but it is 2023 and not even close to 2021. Release the updates!

**Comment by dirkf** [comment] 2023-06-04 02:37
Duplicate of #31585

**Closed by dirkf** 2023-06-04 02:37 UTC
