### ISSUE TITLE
[YOUTUBE] ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name... 

### ISSUE THREAD

**Issue by GregoriusT** [ytdl-org/youtube-dl#32986] opened 2024-12-06 13:53 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
==========================
TESTING NORMAL YOUTUBE-DL:
==========================


[debug] System config: []
[debug] User config: ['--no-mtime', '--match-filter', '!is_live', '--retries', 'infinite', '--fragment-retries', '3', '--skip-unavailable-fragments', '--restrict-filenames', '-i', '-o', '/home/gregorius/home/pending/videos/%(title)s___%(id)s.webm', '-f', '(bestvideo[height<=360]+worstaudio/best[height<=360])[protocol!=http_dash_segments][container!^=dash]', '--console-title', '--hls-prefer-native', '--no-cache-dir', '--cookies', '/home/gregorius/home/scripts/video/youtube-dl-cookies']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=eMNXpZZBWFE', '-vf', '(242+249/242+250/242+171/242+251)/(243+249/243+250/243+171/243+251)/18', '--no-playlist', '-o', '/home/gregorius/home/scripts/video/TEST_NORMAL_%(title)s___%(id)s.webm']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Single file build
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-124-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] eMNXpZZBWFE: Downloading webpage
[youtube] Downloading just video eMNXpZZBWFE because of --no-playlist
[youtube] eMNXpZZBWFE: Downloading player 3bb1f723
WARNING: [youtube] Falling back to generic n function search
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1719, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1696, in _extract_n_function_name
    return self._search_regex(
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1719, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1696, in _extract_n_function_name
    return self._search_regex(
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/YoutubeDL.py", line 875, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/YoutubeDL.py", line 971, in __extract_info
    ie_result = ie.extract(url)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 2137, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1754, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
  File "/home/gregorius/home/scripts/video/youtube-dl-normal/youtube-dl/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig function code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.


===========================
TESTING NIGHTLY YOUTUBE-DL:
===========================


[debug] System config: []
[debug] User config: ['--no-mtime', '--match-filter', '!is_live', '--retries', 'infinite', '--fragment-retries', '3', '--skip-unavailable-fragments', '--restrict-filenames', '-i', '-o', '/home/gregorius/home/pending/videos/%(title)s___%(id)s.webm', '-f', '(bestvideo[height<=360]+worstaudio/best[height<=360])[protocol!=http_dash_segments][container!^=dash]', '--console-title', '--hls-prefer-native', '--no-cache-dir', '--cookies', '/home/gregorius/home/scripts/video/youtube-dl-cookies']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=eMNXpZZBWFE', '-vf', '(242+249/242+250/242+171/242+251)/(243+249/243+250/243+171/243+251)/18', '--no-playlist', '-o', '/home/gregorius/home/scripts/video/TEST_NIGHTLY_%(title)s___%(id)s.webm']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2024.08.07 [c5098961b] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-124-generic-x86_64-with-glibc2.35 - OpenSSL 3.0.2 15 Mar 2022 - glibc 2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] eMNXpZZBWFE: Downloading webpage
[youtube] Downloading just video eMNXpZZBWFE because of --no-playlist
[youtube] eMNXpZZBWFE: Downloading player 3bb1f723
WARNING: [youtube] Falling back to generic n function search
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1719, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1696, in _extract_n_function_name
    return self._search_regex(
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1637, in _decrypt_nsig
    jsi, player_id, func_code = self._extract_n_function_code(video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1719, in _extract_n_function_code
    func_name = self._extract_n_function_name(jscode)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1696, in _extract_n_function_name
    return self._search_regex(
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/YoutubeDL.py", line 879, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/YoutubeDL.py", line 975, in __extract_info
    ie_result = ie.extract(url)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 2137, in _real_extract
    self._unthrottle_format_urls(video_id, player_url, dct)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1754, in _unthrottle_format_urls
    n_response = decrypt_nsig(n_param)(n_param, video_id, player_url)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1614, in inner
    raise ret
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1606, in inner
    self._player_cache[cache_id] = func(*args, **kwargs)
  File "/home/gregorius/home/scripts/video/youtube-dl-nightly/youtube-dl/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
    raise ExtractorError('Unable to extract nsig function code', cause=e)
youtube_dl.utils.ExtractorError: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose option and include the complete output.



```

## Description

Well, youtube-dl stopped working entirely now.

I updated both regular and nightly to what the GitHub Repos have, which was basically no update at all since months, despite other unrelated Youtube issues not being fixed yet (like inability to bulk download shorts because it cant parse a channels shorts page, or inability to download anything but simple formats like format 18 unless you run a workaround, or inability to specify maximum video length to be downloaded).

Anyways, looks like Youtube changed their webpage layout again since it's the regex that fails, meaning you cannot download ANYTHING now!

**Comment by dirkf** [comment] 2024-12-06 20:31
This is the same issue as yt-dlp/yt-dlp#11744. I have a fix similar to the PR applied in _yt-dlp_ that will be pushed as soon as QA.

**Comment by GregoriusT** [comment] 2024-12-09 06:58
I should mention again that youtube-dl no longer works at all whatsoever for me, this is not just something i can workaround anymore, because it cant even parse the page of a direct video link.

This Issue has forced me to look into why youtube-dlp was not a drop-in replacement for youtube-dl on my setup, and I eventually found out that the Config File was ignored and that was the Issue I had, meaning I have switched to youtube-dlp and rewritten my Scripts now, and can no longer report Issues here in the future.

**Comment by dirkf** [comment] 2024-12-09 23:06
Please raise the config issue separately since an incompatibility such as you mention is not meant to exist as far as I know.

**Comment by jeffherdzina** [comment] 2024-12-10 03:57
This is the error im getting on a AlmaLinux server...Maybe this will help.

[youtube] SvVS1_hWiZk: Downloading webpage
[youtube] SvVS1_hWiZk: Downloading player 3bb1f723
WARNING: [youtube] Falling back to generic n function search
ERROR: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player n function name\x1b[0m; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Downloads from Python_videos.txt completed.
Downloading videos from /home/jeff/Desktop/Youtube//Computers/Docker/Docker_videos.txt...
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by TheRealMamuth** [comment] 2024-12-10 07:01
Hi same problem but in my case on download meta data form youtube. 

example in jenkins file download wideo and audio works.

![Screenshot at Dec 10 07-58-46](https://github.com/user-attachments/assets/4ac2d54d-1c4b-4f9f-b074-2055380988f2)



```bash
stage('Download Video') {
            steps {
                timestamps {
                    ansiColor('xterm') {
                        sh'''
                            #!/bin/bash
                            set -e

                            # Sprawdzenie obecności youtube-dl
                            if ! command -v youtube-dl >/dev/null 2>&1; 
                            then
                                echo "youtube-dl nie jest zainstalowane. Zainstaluj za pomocą: sudo apt install yt-dlp (lub odpowiednio skonfiguruj alias)"
                                exit 1
                            fi

                            # Sprawdzenie obecności ffmpeg w dowolnej lokalizacji
                            if ! command -v ffmpeg >/dev/null 2>&1; then
                                echo "ffmpeg nie jest zainstalowany. Zainstaluj za pomocą: sudo apt install ffmpeg"
                                exit 1
                            fi

                            echo "GET ALL youtube-dl format video"
                            echo " "
                            youtube-dl -F "${YOUTUBE_VIDEO_URL}"
                            echo " "

                            echo "Start download best video: 4K, HD, SD"
                            video_url="${YOUTUBE_VIDEO_URL}"

                            # Lista preferowanych formatów (priorytet: 337, 315, 335, 299, 298)
                            preferred_formats="337+140/315+140/335+140/299+140/298+140"

                            # Pobierz wideo w najlepszym dostępnym formacie
                            echo "Downloading best available format..."
                            youtube-dl -f "$preferred_formats" -o "%(title)s.%(ext)s" "$video_url"

                            # Konwersja plików MKV na MP4, jeśli są dostępne
                            for i in *.mkv; do
                                if [ -f "$i" ]; then
                                    echo "Converting $i to MP4..."
                                    ffmpeg -i "$i" -c copy "${i%.*}.mp4"
                                    rm "$i"
                                fi
                            done

                            echo "Download and conversion completed."
                        '''
                    }
                }
            }
        }
        stage('Download audio') {
            steps {
                timestamps {
                    ansiColor('xterm') {
                        sh'''
                            set -e
                            youtube-dl -f m4a -o "%(title)s.%(ext)s" ${YOUTUBE_VIDEO_URL}
                        '''
                    }
                }
            }
        }
```

when i try download meta data from youtube this error show:

```bash
stage('Download video descryption and metadata') {
            steps {
                timestamps {
                    ansiColor('xterm') {
                        sh'''
                            set -e
                            youtube-dl --write-description --skip-download -o "%(title)s.%(ext)s" ${YOUTUBE_VIDEO_URL}
                            title=$(youtube-dl --get-title --skip-download -o "%(title)s.%(ext)s" ${YOUTUBE_VIDEO_URL})
                            echo "${title}" > ${title}.title
                            youtube-dl --write-info-json --skip-download -o "%(title)s.%(ext)s" ${YOUTUBE_VIDEO_URL}
                            python3 get_tags.py "${YOUTUBE_VIDEO_URL}"
                        '''
                    }  
                }
            }
        }
```
![Screenshot at Dec 10 07-57-29](https://github.com/user-attachments/assets/a0017981-727c-402d-b0c5-ce6266f33403)

Error info:

```bash
19:34:18    File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1606, in inner
19:34:18      self._player_cache[cache_id] = func(*args, **kwargs)
19:34:18    File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1639, in _decrypt_nsig
19:34:18      raise ExtractorError('Unable to extract nsig function code', cause=e)
19:34:18  youtube_dl.utils.ExtractorError: Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.')); please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
```

**Comment by tansy** [comment] 2024-12-10 08:08
If yt-dlp [fixed](https://github.com/yt-dlp/yt-dlp/issues/11744#issuecomment-2521680838) this in `_extract_n_function_name()`, and ytdl has function with basically the same name and same function/purpose, then is it possible to adapt it to 'our' case?

**Comment by TheRealMamuth** [comment] 2024-12-10 10:03
> To jest ten sam problem, co w przypadku [yt-dlp/yt-dlp#11744](https://github.com/yt-dlp/yt-dlp/issues/11744) . Mam poprawioną wersję do PR _,_ która zostanie opublikowana po kontroli jakości.

This erroe still is in version https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.06

I used this version, I only changed the name to match my jenkins pipeline (executable file)

https://github.com/ytdl-org/youtube-dl/issues/32986#issuecomment-2530602819

**Comment by seproDev** [comment] 2024-12-10 10:24
@TheRealMamuth If you have an issue with yt-dlp, please [open an issue there](https://github.com/yt-dlp/yt-dlp/issues/new/choose). youtube-dl and yt-dlp are different projects. You are the first person that reported the fix in yt-dlp 2024.12.06 not working.

**Comment by TheRealMamuth** [comment] 2024-12-10 10:42
> @TheRealMamuth If you have an issue with yt-dlp, please [open an issue there](https://github.com/yt-dlp/yt-dlp/issues/new/choose). youtube-dl and yt-dlp are different projects. You are the first person that reported the fix in yt-dlp 2024.12.06 not working.

thx - open issue yt-dlp https://github.com/yt-dlp/yt-dlp/issues/11781

**Comment by tansy** [comment] 2024-12-10 15:42
It seems to be fixed in #32987. Tried that and it worked. One can test it [here](https://ufile.io/w28bg4to) (md5: e2e8b4a7cb7a40221b3b72003a43e5df), before it is released.

**Comment by dirkf** [comment] 2024-12-11 01:02
As [@seproDev kindly and accurately commented](https://github.com/yt-dlp/yt-dlp/issues/11744#issuecomment-2525082461), PR #32987 is somewhat misguided. Some fool maintainer relied on the implementation of JS string comparisons that some fool maintainer may have introduced in passing without matching tests, leading to a solution that apparently solved the issue but should not have. However, it is not unrecoverable.

Obviously anyone who wants to use the current PR code may do so but it could fail at any time; also, it will probably be force-pushed out by a better working solution.

In this new player, the challenge JS is testing the type of a variable that is set in a declaration outside the challenge JS, but that is still in scope. The (intended, I guess) effect is that the challenge JS returns the original nsig value if it doesn't know about the variable binding, and so 403 (nowadays) on download.

The _yt-dlp_ solution was to hard-code (a pattern matching) the guilty test and remove it from any challenge JS. This is effective and could be generalised to some extent, but seems unsatisfactory.

As we aren't going to be processing the whole player JS, some better hack is needed. Maybe there could be some way in which `typeof varName` in the challenge JS could search for `var varName = ...` in the whole player JS, but again there are endlessly many other ways in which the binding could have been created.

A direct and also effective tactic can be to hook the evaluation of `return returnValue;` such that if `returnValue` is the original nsig value the statement behaves like `void returnValue;` instead, and the challenge keeps on running. Our interpreter doesn't know anything about nsig values, but the YT extractor can bind a magically named variable when calling the challenge code; then the interpreter can secretly look at that variable and not `return returnValue;` when `returnValue` matches the value of the magic variable. This is fine until the challenge starts raising an Exception (same technique can be applied) or mixing the value of the alien variable into the challenge calculation.

**Comment by nobody93** [comment] 2024-12-14 06:08
when are you going to release a new version with the fix?

Thank you very much

**Comment by TheRealMamuth** [comment] 2024-12-14 07:49
> when are you going to release a new version with the fix?
> 
> 
> 
> Thank you very much
> 
> 

yt-dlp works fine. If in your code you use youtube-dl just download binary of yt-dlp and change name to youtube-dl. It my case works fine

**Comment by Untitled-code** [comment] 2024-12-15 11:15
> when are you going to release a new version with the fix?
> 
> Thank you very much

Looking forward to it too

**Comment by nobody93** [comment] 2024-12-15 20:21
> yt-dlp works fine. If in your code you use youtube-dl just download binary of yt-dlp and change name to youtube-dl. It my case works fine

Indeed works well. Great and thank you very much

**Closed** 2024-12-16 12:38 UTC
