### ISSUE TITLE
SPOTIFY NOT SOPPRTED 

### ISSUE THREAD

**Issue by mansoor-cod** [ytdl-org/youtube-dl#30180] opened 2021-10-31 11:57 UTC
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

anar@linux:~$ youtube-dl open.spotify.com/track/5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e
WARNING: The url doesn't specify the protocol, trying with http
[generic] 5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e: Requesting header
[redirect] Following redirect to https://open.spotify.com/track/5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e
[generic] 5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e: Downloading webpage
[generic] 5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e: Extracting information
ERROR: Unsupported URL: https://open.spotify.com/track/5SrzS4Tuj8M01cale2gnoE?si=501165e0f950499e
anar@linux:~$

**Comment by dirkf** [comment] 2021-10-31 12:54
Spotify is supported. The extractor knows about `/episode/` and `/show/` URLs.

Otherwise, duplicate of #29722, qv.

**Closed** 2022-01-29 16:44 UTC
Labels: site-support-request, duplicate

**Comment by 89z** [comment] 2022-06-18 23:15
https://github.com/ytdl-org/youtube-dl/issues/31037
