### ISSUE TITLE
[Udemy] No video formats found

### ISSUE THREAD

**Issue by RevilionDev** [ytdl-org/youtube-dl#30382] opened 2021-12-16 01:52 UTC
My Errors Output:

youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Any Idea to fix this?

**Comment by dirkf** [comment] 2021-12-16 03:55
Feel free to **follow the instructions for posting a [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=)** including a verbose log as requested there.

**Comment by zdegeorge** [comment] 2021-12-23 22:12
```

[udemy] Provided parameters: graphql-with-react-course 

Project selected: graphql-with-react-course
Cookie path: cookies.txt

Starting download...

[debug] System config: []
[debug] User config: ['--restrict-filenames', '--continue', '--verbose', '--console-title']
[debug] Custom config: []
[debug] Command-line args: ['--cookie', 'cookies.txt', '-o', '~/Movies/Udemy/graphql-with-react-course/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://www.udemy.com/graphql-with-react-course/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] graphql-with-react-course: Downloading webpage
[udemy:course] 1109926: Downloading course curriculum
[download] Downloading playlist: 1109926
[udemy:course] playlist 1109926: Collected 112 video ids (downloading 112 of them)
[download] Downloading video 1 of 112
[udemy] 6515072: Downloading webpage
[udemy] 6515072: Downloading lecture JSON
[udemy] 7779476: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/7779476/files/1109926/7779476/2017-02-13_17-03-16-f96acc65f13ee13b2e55997ca8c92446/1/hls/AVC_1920x1080_800k_AAC-HE_64k/aa00b8c7f68a3b2c1c7d5f11c203b9a3fa32.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMTEwOTkyNi83Nzc5NDc2LzIwMTctMDItMTNfMTctMDMtMTYtZjk2YWNjNjVmMTNlZTEzYjJlNTU5OTdjYThjOTI0NDYvMS8iLCJleHAiOjE2NDAzMTI4ODl9.VmZBJTH6WYD1rebNMBJVsUm599OalZbzbCewGHRuuoI&v=1'
[download] /Users/zachdegeorge/Movies/Udemy/graphql-with-react-course/1 - Why_GraphQL/001-Introduction.mp4 has already been downloaded
[download] 100% of 9.73MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/graphql-with-react-course/1 - Why_GraphQL/001-Introduction.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/graphql-with-react-course/1 - Why_GraphQL/001-Introduction.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/graphql-with-react-course/1 - Why_GraphQL/001-Introduction.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/graphql-with-react-course/1 - Why_GraphQL/001-Introduction.temp.mp4'
[download] Downloading video 2 of 112
[udemy] 6523004: Downloading webpage
[udemy] 6523004: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/udemy.py", line 408, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Finished.
```

Hopefully this will help.

**Comment by zdegeorge** [comment] 2021-12-23 22:24
```
[udemy] Provided parameters: understanding-typescript 

Project selected: understanding-typescript
Cookie path: cookies.txt

Starting download...

[debug] System config: []
[debug] User config: ['--restrict-filenames', '--continue', '--verbose', '--console-title', '--external-downloader', 'wget', '--no-continue']
[debug] Custom config: []
[debug] Command-line args: ['--cookie', 'cookies.txt', '-o', '~/Movies/Udemy/understanding-typescript/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://www.udemy.com/understanding-typescript/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.1 (CPython) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] understanding-typescript: Downloading webpage
[udemy:course] 947098: Downloading course curriculum
[download] Downloading playlist: 947098
[udemy:course] playlist 947098: Collected 176 video ids (downloading 176 of them)
[download] Downloading video 1 of 176
[udemy] 17751414: Downloading webpage
[udemy] 17751414: Downloading lecture JSON
[udemy] 21959808: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/21959808/files/2020-01-21_12-18-08-765610275d3576302058bec98921e0e9/2/hls/AVC_1920x1080_3200k_AAC-HE_64k/aa00b863ae931c81d0d301113557f966c70f.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAyMC0wMS0yMV8xMi0xOC0wOC03NjU2MTAyNzVkMzU3NjMwMjA1OGJlYzk4OTIxZTBlOS8yLyIsImV4cCI6MTY0MDMxNDI0OX0.HH70No5th4r3ZgTZm-gDsz4Wm85PB61v3zJwqyo3B48&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 20
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/001-Welcome_to_the_Course.mp4
[download] 100% of 48.61MiB in 00:08
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/001-Welcome_to_the_Course.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/001-Welcome_to_the_Course.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/001-Welcome_to_the_Course.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/001-Welcome_to_the_Course.temp.mp4'
[download] Downloading video 2 of 176
[udemy] 16949812: Downloading webpage
[udemy] 16949812: Downloading lecture JSON
[udemy] 20907054: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907054/files/2019-11-15_16-16-12-36004b517421ac63aabeb7625303ac69/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa00578fa41796761d7595682882c7da6c2b.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi0zNjAwNGI1MTc0MjFhYzYzYWFiZWI3NjI1MzAzYWM2OS8yLyIsImV4cCI6MTY0MDMxNDI2MH0.-CmyYPP0H7iuZt3dEEI4cQPig0M7eeOqevSc4RzXZYE&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 46
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/002-What_Is_TypeScript_Why_Should_You_Use_It.mp4
[download] 100% of 10.41MiB in 00:12
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/002-What_Is_TypeScript_Why_Should_You_Use_It.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/002-What_Is_TypeScript_Why_Should_You_Use_It.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/002-What_Is_TypeScript_Why_Should_You_Use_It.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/002-What_Is_TypeScript_Why_Should_You_Use_It.temp.mp4'
[download] Downloading video 3 of 176
[udemy] 16949814: Downloading webpage
[udemy] 16949814: Downloading lecture JSON
[udemy] 20907052: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907052/files/2019-11-15_16-16-12-6cdd2e51e9511242b393231d0162398c/2/hls/AVC_1920x1080_1200k_AAC-HE_64k/aa0049a8fe64a3e9b6e053f07c65fc6aa7d5.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi02Y2RkMmU1MWU5NTExMjQyYjM5MzIzMWQwMTYyMzk4Yy8yLyIsImV4cCI6MTY0MDMxNDI3NH0.W-CCtc2CbRyCun68qwU9uiQ6ENhW0phLtrB9MCBElQ8&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 134
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/003-Installing_Using_TypeScript.mp4
[download] 100% of 58.23MiB in 00:42
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/003-Installing_Using_TypeScript.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/003-Installing_Using_TypeScript.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/003-Installing_Using_TypeScript.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/003-Installing_Using_TypeScript.temp.mp4'
[download] Downloading video 4 of 176
[udemy] 16949816: Downloading webpage
[udemy] 16949816: Downloading lecture JSON
[udemy] 20907046: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907046/files/2019-11-15_16-16-12-a5841b8e4d317e61618b309b74fb5c16/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa00ff58302649a31db7bb0801ee395fb2b6.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi1hNTg0MWI4ZTRkMzE3ZTYxNjE4YjMwOWI3NGZiNWMxNi8yLyIsImV4cCI6MTY0MDMxNDMxOX0.dEVv4EJhG7JcEE-HUkUslvmrS0d4ncl1sk-tvUa7DuQ&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 31
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/004-TypeScript_Advantages_-_Overview.mp4
[download] 100% of 7.13MiB in 00:08
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/004-TypeScript_Advantages_-_Overview.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/004-TypeScript_Advantages_-_Overview.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/004-TypeScript_Advantages_-_Overview.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/004-TypeScript_Advantages_-_Overview.temp.mp4'
[download] Downloading video 5 of 176
[udemy] 16949818: Downloading webpage
[udemy] 16949818: Downloading lecture JSON
[udemy] 20907058: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907058/files/2019-11-15_16-16-12-d0adafe9b35a3581666915465dbf1e45/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa00291632af50ecf11d3631afdf0e4bb9fc.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi1kMGFkYWZlOWIzNWEzNTgxNjY2OTE1NDY1ZGJmMWU0NS8yLyIsImV4cCI6MTY0MDMxNDMyOX0.U0bGUSVZQp_UGRyDQpG5CROiWzaQgLMoQ863qXgfpI4&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 43
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/005-Course_Outline.mp4
[download] 100% of 11.49MiB in 00:11
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/005-Course_Outline.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/005-Course_Outline.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/005-Course_Outline.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/005-Course_Outline.temp.mp4'
[download] Downloading video 6 of 176
[udemy] 16949820: Downloading webpage
[udemy] 16949820: Downloading lecture JSON
[udemy] 20907050: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907050/files/2019-11-15_16-16-12-cb80aadd2246ec9fe0044a139c401bae/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa001b84f5802ba252cc7687a6c02d28a40e.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi1jYjgwYWFkZDIyNDZlYzlmZTAwNDRhMTM5YzQwMWJhZS8yLyIsImV4cCI6MTY0MDMxNDM0M30.fIFIku3lxKXcYFs_rtvqs-aAKmat7LWR2OqvelXJuHg&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 33
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/006-How_To_Get_The_Most_Out_Of_The_Course.mp4
[download] 100% of 7.23MiB in 00:08
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/006-How_To_Get_The_Most_Out_Of_The_Course.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/006-How_To_Get_The_Most_Out_Of_The_Course.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/006-How_To_Get_The_Most_Out_Of_The_Course.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/006-How_To_Get_The_Most_Out_Of_The_Course.temp.mp4'
[download] Downloading video 7 of 176
[udemy] 16949822: Downloading webpage
[udemy] 16949822: Downloading lecture JSON
[udemy] 20907048: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20907048/files/2019-11-15_16-16-12-fc708d0571d96c5348e37a78747ff053/2/hls/AVC_1920x1080_1600k_AAC-HE_64k/aa00655a449cfd95f8c9bd3dbf2c91bf66f9.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xNV8xNi0xNi0xMi1mYzcwOGQwNTcxZDk2YzUzNDhlMzdhNzg3NDdmZjA1My8yLyIsImV4cCI6MTY0MDMxNDM1N30.CpbtbefK6E0MdfeiHv0fOvh--qOgP9OS1EA3bhaWKNU&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/007-Setting_Up_A_Code_Editor_IDE.mp4
[download] 100% of 20.89MiB in 00:10
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/007-Setting_Up_A_Code_Editor_IDE.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/007-Setting_Up_A_Code_Editor_IDE.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/007-Setting_Up_A_Code_Editor_IDE.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/007-Setting_Up_A_Code_Editor_IDE.temp.mp4'
[download] Downloading video 8 of 176
[udemy] 16949340: Downloading webpage
[udemy] 16949340: Downloading lecture JSON
[udemy] 20971170: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/20971170/files/2019-11-19_13-28-14-82e5582a08915e9d75860dcff4753aa5/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa0085feb382c3b08199eab8f27c13d06c01.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0xMS0xOV8xMy0yOC0xNC04MmU1NTgyYTA4OTE1ZTlkNzU4NjBkY2ZmNDc1M2FhNS8yLyIsImV4cCI6MTY0MDMxNDM2OX0.M_qdsMQBEuWdPHf0XleCCACIhOUBiHg2tvRoJLXdXeQ&v=1'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 74
[download] Destination: /Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/008-The_Course_Project_Setup.mp4
[download] 100% of 23.90MiB in 00:21
[debug] ffmpeg command line: ffprobe -show_streams 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/008-The_Course_Project_Setup.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/008-The_Course_Project_Setup.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/008-The_Course_Project_Setup.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:/Users/zachdegeorge/Movies/Udemy/understanding-typescript/1 - Getting_Started/008-The_Course_Project_Setup.temp.mp4'
[download] Downloading video 9 of 176
[udemy] 16888052: Downloading webpage
[udemy] 16888052: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/udemy.py", line 408, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Finished.
```

**Comment by kikuyan** [comment] 2021-12-24 00:48
Udemy's "No video formats found" is duplicate of #29925.
Maybe only you can do now is to ignore errors with `-i`.

**Comment by zdegeorge** [comment] 2021-12-27 19:23
I think this issue is caused by the fact that Udemy does not provide links for all the videos on of the project on the landing page of the project, only the first few. I was doing some research and I was able to get the it to work for the first few files that have links on the project page, but as soon as those links disappear youtube-dl stops working. Sounds like it may be out of youtube-dl's hands on this one, which is a bummer.

**Comment by dirkf** [comment] 2021-12-28 21:53
The course items aren't extracted from the page, but using the `https://www.udemy.com/api-2.0/courses/%(course_id)s/cached-subscriber-curriculum-items` API endpoint. Perhaps this returns different result sets depending on the login used, etc.

See also the response to your https://github.com/ytdl-org/youtube-dl/issues/29915#issuecomment-1000356882.

**Closed** 2022-04-27 11:58 UTC
Labels: duplicate
