### ISSUE TITLE
cda.pl

### ISSUE THREAD

**Issue by cypeks** [ytdl-org/youtube-dl#26226] opened 2020-08-03 10:00 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1582, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1396, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 1408, in _calc_cookies
    pr = sanitized_Request(info_dict['url'])
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/utils.py", line 2157, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'GH2Hbdc%5Db452%5DA%3D%5EB9hJ%25rGwta%60%7C%23%3D_%7EvxH%3DD%22%5E%60dhech%60eag%5E%3DB5__e4hf6e576h%60ae%605cf7333agc4ghd43b2e7fe46c4beae336663f6f%60%60h3ge6c_Q5'

```

## Description

WRITE DESCRIPTION HERE

**Comment by selfisekai** [comment] 2020-08-04 08:25
duplicate of #24458 #25477

**Comment by selfisekai** [comment] 2020-11-17 12:46
Fixed in [haruhi-dl](https://haruhi.download), a libre fork of youtube-dl.

**Closed** 2020-11-23 17:52 UTC
