### ISSUE TITLE
> > @snoopyraw Thanks!

### ISSUE THREAD

**Issue by Krishakpuji** [ytdl-org/youtube-dl#29882] opened 2021-08-28 16:46 UTC
> > @snoopyraw Thanks!
> > Doing some early research, there are two types of URLs:
> > ```
> > * Stream URLs: `https://www.tango.me/stream/gw6zDcZxmSRafDdoKvpQtQ`
> > 
> > * Moment URLs: `https://www.tango.me/moments/cxQ3MCH_tIbMcXEi7rG_PA`
> > ```
> 
> Also using Firefox inspector and looking the network stream live.m3u8 has a url like this:
> 
> https://cinema-us-east.tango.me/v1/01b486e328946566b9df310ed148060f/live.m3u8?accountId=ACCOUNTID&expire_at=1624505904&token=TOKEN&tech=lhls
> 
> I don't know if that's useful and maybe the url change based in the location of my IP but I really want to download some music producer stream
> 
> Regards

for private streams the m3u8 link is encrypted. we cannot find the link in the inspect. please tell if you can decrypt and get link for private stream

_Originally posted by @White-Range in https://github.com/ytdl-org/youtube-dl/issues/29244#issuecomment-881891337_

**Comment by apratsunrthd** [comment] 2021-10-02 17:55
@Krishakpuji I'm not understanding what the issue is here. Can you please close this and open your issue using the correct checklist?

**Closed** 2022-04-18 13:27 UTC
Labels: incomplete
