### ISSUE TITLE
Can't recognize youtube short url

### ISSUE THREAD

**Issue by StefSate** [ytdl-org/youtube-dl#30525] opened 2022-01-16 07:05 UTC
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://youtube.com/shorts/o9I6hYxwmzM?feature=share

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2022-01-16 12:44
Duplicate of #30269, where a trivial fix is provided.

**Comment by 89z** [comment] 2022-01-24 00:40
https://github.com/ytdl-org/youtube-dl/issues/30550

**Closed** 2022-02-01 14:40 UTC
Labels: site-support-request, duplicate
