### ISSUE TITLE
Atresplayer - ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError());

### ISSUE THREAD

**Issue by Krosgore** [ytdl-org/youtube-dl#24927] opened 2020-04-21 21:21 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2020.03.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
C:\Users\Krosgore\Desktop\atresplayer>youtube-dl.exe https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/el-resurgir-de-puente-viejo/21-04-20-capitulo-2308_5e83779b7ed1a8d648016a92/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/el-resurgir-de-puente-viejo/21-04-20-capitulo-2308_5e83779b7ed1a8d648016a92/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-17-889ad93, ffprobe git-2020-04-17-889ad93
[debug] Proxy map: {}
[AtresPlayer] 5e83779b7ed1a8d648016a92: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

WRITE DESCRIPTION HERE

**Comment by toni-fiz** [comment] 2020-04-29 14:32
This looks like a duplicate of #24026

**Closed** 2021-05-07 11:12 UTC
