### ISSUE TITLE
Channel 5/My5 Unsupported?

### ISSUE THREAD

**Issue by MysticMerlin** [ytdl-org/youtube-dl#12524] opened 2017-03-22 05:42 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.03.22
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I'm trying to download my first programme from Channel 5 or more precisely My5 & I'm getting the following error & I was led to believe that Channel 5 was supported. I've only been using youtube-dl for several weeks now & I've downloaded from the BBC site & the ITV. I have to say that the ITV downloads do not complete on their own as when I get the error message, rtmpdump exited with error code 1, I then have to re-submit the programme URL for it to continue until it finishes downloading. But it does work eventually & I will have to submit on here what is happening there to see how to overcome it. But in the meantime I want to know how tp download from the Channel 5/My5 site please.
And one other thing. Does youtube-dl work on the Channel 4 site?

C:\Users\Purple PC\youtube-dl>youtube-dl -v https://www.my5.tv/the-gadget-show/s
eason-19/episode-5
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.my5.tv/the-gadget-show/season-19/
episode-5']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.22
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-83585-ga5c1c7a, ffprobe N-83585-ga5c1c7a, rtmpdum
p 2.4
[debug] Proxy map: {}
[generic] episode-5: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-5: Downloading webpage
[generic] episode-5: Extracting information
ERROR: Unsupported URL: https://www.my5.tv/the-gadget-show/season-19/episode-5
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo5tkbgew\bu
ild\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo5tkbgew\bu
ild\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo5tkbgew\bu
ild\youtube_dl\extractor\generic.py", line 2653, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.my5.tv/the-gadge
t-show/season-19/episode-5

C:\Users\Purple PC\youtube-dl>

**Comment by Have-a-Laugh** [comment] 2018-12-03 20:04
@dstftw as this is still open from last year, is it possible it could be visited please, if you need any testing done please let me know, thank you.

`linux@Linux-Laptop:~/Desktop$ youtube-dl -v  https://www.my5.tv/12-gifts-of-christmas
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.my5.tv/12-gifts-of-christmas']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[generic] 12-gifts-of-christmas: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 12-gifts-of-christmas: Downloading webpage
[generic] 12-gifts-of-christmas: Extracting information
ERROR: Unsupported URL: https://www.my5.tv/12-gifts-of-christmas
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2339, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 70, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3318, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.my5.tv/12-gifts-of-christmas

linux@Linux-Laptop:~/Desktop$ `

**Comment by dirkf** [comment] 2021-11-16 01:57
Duplicate of #11407.

**Closed** 2022-01-30 12:36 UTC
Labels: geo-restricted, DRM
