### ISSUE TITLE
Youtube Decode n-parameter failed

### ISSUE THREAD

**Issue by abin2017** [ytdl-org/youtube-dl#30856] opened 2022-04-15 08:21 UTC
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones
- [ ] my code's changeset is 
```
Author: dirkf <fieldhouse@gmx.net>  2022-04-10 12:49:09
Committer: GitHub <noreply@github.com>  2022-04-10 12:49:09
Parent: 871645a4a4a0e12ec8f7bf78a3ad7bf75838ee5c ([RAI] Fix extraction of http formats)
Child:  0000000000000000000000000000000000000000 (Local uncommitted changes, not checked in to index)
Branches: master, remotes/origin/master
Follows: 2021.12.17
Precedes: 

    Disable blank issues
```
## Verbose log

```
[youtube] f3vYFg1tM-0: Downloading webpage
[youtube] f3vYFg1tM-0: Downloading player fae06c11
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "E:\work\01_youtubedl\rep\youtube-dl\youtube_dl\extractor\youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "E:\work\01_youtubedl\rep\youtube-dl\youtube_dl\extractor\youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "E:\work\01_youtubedl\rep\youtube-dl\youtube_dl\extractor\youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "E:\work\01_youtubedl\rep\youtube-dl\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
```

## Description

1. test video link is https://www.youtube.com/watch?v=f3vYFg1tM-0
2. following is '_n_descramble' function's parameters
```
n_param:'9nHkIgOzxZyYvA0FueY'
player_url:'https://www.youtube.com/s/player/fae06c11/player_ias.vflset/en_US/base.js'
video_id:'f3vYFg1tM-0'
```

**Comment by draekko** [comment] 2022-04-15 11:29
Getting something similar

```
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/opt/Apps/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/opt/Apps/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/opt/Apps/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1468, in _extract_n_function_name
    nfunc_and_idx = self._search_regex(
  File "/opt/Apps/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)

```

**Comment by abin2017** [comment] 2022-04-15 12:41
it should be the same issue

**Comment by dirkf** [comment] 2022-04-15 13:04
Yes, new player fae06c11 has appeared.

**Comment by 89z** [comment] 2022-04-15 13:36
@dirkf did you see my comment on the old PR about another approach?

**Comment by abin2017** [comment] 2022-04-15 13:45
@dirkf on my side, today so many youtube video now take new player 'fae06c11'

**Comment by dirkf** [comment] 2022-04-15 14:08
> did you see my comment on the old PR about another approach?

An approach using multiple simultaneous downloads would need a multithreaded downloader. An external downloader (eg, _aria2c_) might already implement that. It's non-trivial in the context of yt-dl itself.

**Comment by 89z** [comment] 2022-04-15 14:26
> An approach using multiple simultaneous downloads would need a multithreaded downloader. An external downloader (eg, _aria2c_) might already implement that.

Aria2 can only do max 16 connections. You need something on the order of 64 or more to make this feasible.

> It's non-trivial in the context of yt-dl itself.

I wont say trivial, but this is definitely doable. Easy mode would be just storing the chunks in memory until all are done downloading. Harder would be truncating a file based on the `contentLength`, then saving the chunks in the right spot as they come in.

> ISTR this was discussed in the original issue about throttling.

Yes, I read this [1]:

> This means even `--http-chunk-size 1M` wont help and neither will aria2c, because server heavily throttles any request to same URL after initial 2-4MB regardless of retries.

but I didn't find that to be the case, at least not anymore. I was able to download at least 50 MB [2] with no reduction in speed. I am willing to test larger videos, but I don't have other test cases at this time. It would need to be a `TVHTML5_SIMPLY_EMBEDDED_PLAYER` video that responds with `url`. I only have one example of that at this time:

~~~
Tq92D6wQ1mg
~~~

and its only a two minute video.

1. https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-938337251
2. https://github.com/zerodytrash/YouTube-Internal-Clients/issues/2#issuecomment-1094416450

**Comment by arrowgent** [comment] 2022-04-15 14:48
given the same report v2021-12-17
**player fae06c11**

```
[youtube] CTPFOpIj0YM: Downloading webpage
[youtube] CTPFOpIj0YM: Downloading MPD manifest
[youtube] CTPFOpIj0YM: Downloading player fae06c11
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/home/catbox/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/catbox/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/catbox/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/home/catbox/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
```

**Comment by 89z** [comment] 2022-04-15 14:54
@arrowgent we are well aware of the issue.

**Comment by dirkf** [comment] 2022-04-15 15:04
Required patch that will be committed shortly:
```py
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -1464,15 +1464,15 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
     # 2. https://code.videolan.org/videolan/vlc/-/blob/4fb284e5af69aa9ac2100ccbdd3b88debec9987f/share/lua/playlist/youtube.lua#L116
     # 3. https://github.com/ytdl-org/youtube-dl/issues/30097#issuecomment-950157377
     def _extract_n_function_name(self, jscode):
-        target = r'(?P<nfunc>[a-zA-Z0-9$]{3})(?:\[(?P<idx>\d+)\])?'
+        target = r'(?P<nfunc>[a-zA-Z_$][\w$]*)(?:\[(?P<idx>\d+)\])?'
         nfunc_and_idx = self._search_regex(
-            r'\.get\("n"\)\)&&\(b=(%s)\([a-zA-Z0-9]\)' % (target, ),
+            r'\.get\("n"\)\)&&\(b=(%s)\([\w$]+\)' % (target, ),
             jscode, 'Initial JS player n function name')
         nfunc, idx = re.match(target, nfunc_and_idx).group('nfunc', 'idx')
         if not idx:
             return nfunc
         return self._parse_json(self._search_regex(
-            r'var %s\s*=\s*(\[.+?\]);' % (nfunc, ), jscode,
+            r'var %s\s*=\s*(\[.+?\]);' % (re.escape(nfunc), ), jscode,
             'Initial JS player n function list ({nfunc}[{idx}])'.format(**locals())), nfunc, transform_source=js_to_json)[int(idx)]
 
     def _extract_n_function(self, video_id, player_url):
```
There were two issues:
* new player fae06c11 used a 2-character function name where previously it was always 3;
* new player's function name included `$` which needed to be escaped when used in a regex.

In fixing these I've made the patterns match any valid LS identifier so as to avoid future surprises.

**Comment by NanaMizukiAnother7** [comment] 2022-04-15 15:13
I can't reproduce here on YT-DLP (using its git master):

```
[youtube] kz451XFgAi0: Downloading webpage
[youtube] kz451XFgAi0: Downloading android player API JSON
[youtube] kz451XFgAi0: Downloading player fae06c11
[info] kz451XFgAi0: Downloading 1 format(s): 22
[download] Destination: [REDACTED]
[download] 100% of 34.31MiB in 00:15
```

**Closed** 2022-04-15 15:12 UTC

**Comment by dirkf** [comment] 2022-04-15 15:19
The (potential) issues were fixed in c571b3a6ab981d7287c2d3575b50b8f63dd830d8 and a7d4acc018378b30188685776e954168e041fa4f respectively.

**Comment by dirkf** [comment] 2022-04-15 15:23
```ShellSession
$ python -m youtube_dl -v -F 'f3vYFg1tM-0'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'f3vYFg1tM-0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: a0068bd6b
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] f3vYFg1tM-0: Downloading webpage
[debug] [youtube] Decrypted nsig orApSevMV853kIssLsu => 5GZaNVi0bl0s1w
[debug] [youtube] Decrypted nsig XmzDiqBGL0Egq5q8pIQ => JMUrpQ9VoFloOA
[info] Available formats for f3vYFg1tM-0:
format code  extension  resolution note
249          webm       audio only tiny   53k , webm_dash container, opus @ 53k (48000Hz), 24.67MiB
250          webm       audio only tiny   68k , webm_dash container, opus @ 68k (48000Hz), 31.60MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 60.01MiB
251          webm       audio only tiny  140k , webm_dash container, opus @140k (48000Hz), 65.27MiB
160          mp4        256x144    144p   52k , mp4_dash container, avc1.4d400c@  52k, 25fps, video only, 24.12MiB
278          webm       256x144    144p   67k , webm_dash container, vp9@  67k, 25fps, video only, 31.27MiB
242          webm       426x240    240p   72k , webm_dash container, vp9@  72k, 25fps, video only, 33.59MiB
133          mp4        426x240    240p  119k , mp4_dash container, avc1.4d4015@ 119k, 25fps, video only, 55.22MiB
243          webm       640x360    360p  114k , webm_dash container, vp9@ 114k, 25fps, video only, 53.17MiB
134          mp4        640x360    360p  226k , mp4_dash container, avc1.4d401e@ 226k, 25fps, video only, 104.75MiB
244          webm       854x480    480p  173k , webm_dash container, vp9@ 173k, 25fps, video only, 80.52MiB
135          mp4        854x480    480p  401k , mp4_dash container, avc1.4d401e@ 401k, 25fps, video only, 186.12MiB
247          webm       1280x720   720p  339k , webm_dash container, vp9@ 339k, 25fps, video only, 157.33MiB
136          mp4        1280x720   720p  826k , mp4_dash container, avc1.64001f@ 826k, 25fps, video only, 383.11MiB
18           mp4        640x360    360p  372k , avc1.42001E, 25fps, mp4a.40.2 (44100Hz), 172.76MiB
22           mp4        1280x720   720p  955k , avc1.64001F, 25fps, mp4a.40.2 (44100Hz) (best)
$
```

**Comment by abin2017** [comment] 2022-04-15 15:55
@dirkf thanks, it works well on this changeset

> The (potential) issues were fixed in [yt-dlp/yt-dlp@c571b3a](https://github.com/yt-dlp/yt-dlp/commit/c571b3a6ab981d7287c2d3575b50b8f63dd830d8) and [yt-dlp/yt-dlp@a7d4acc](https://github.com/yt-dlp/yt-dlp/commit/a7d4acc018378b30188685776e954168e041fa4f) respectively.

**Comment by dirkf** [comment] 2022-04-15 16:12
Those are the yt-dlp commits. For yt-dl, use the updated git master https://github.com/ytdl-org/youtube-dl/commit/a0068bd6bec16008bda7a39caecccbf84881c603.

**Comment by csimpi** [comment] 2022-04-15 20:30
@dirkf  How can I update it to this fixed version `a0068bd`?

**Comment by dirkf** [comment] 2022-04-16 03:19
Presumably, repeat whatever you did for the previous fixed version.

**Comment by csimpi** [comment] 2022-04-16 03:27
Sorry, first I misunderstood and thought I need to checkout another branch, I just had to pull the master, everything works as expected. Thank you. I reallly appreciate the lots of work you guys put in
