### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by music13245678** [ytdl-org/youtube-dl#31562] opened 2023-02-17 23:22 UTC
youtube-dl --dump-json https://youtube.com/watch?v=BaW_jenozKc

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by DanielHeath** [comment] 2023-02-17 23:26
Also seeing this (on the latest release)

```
  $ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

```

**Comment by ProvisionlabTeam** [comment] 2023-02-17 23:31
I think new python release needed)

**Comment by heiloemuc** [comment] 2023-02-17 23:34
youtube-dl --verbose https://youtu.be/nDXbVMQVifE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtu.be/nDXbVMQVifE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.1.12-1-default-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] nDXbVMQVifE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2023-02-17 23:41
Use the issue template (start from #30839 if you like), search for the problem, see that it has been fixed and how to patch it.

Duplicate of #31530.

**Closed by dirkf** 2023-02-17 23:41 UTC
