### ISSUE TITLE
cda downloading not working

### ISSUE THREAD

**Issue by tzji7** [ytdl-org/youtube-dl#25477] opened 2020-05-31 20:48 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.05.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cda.pl/video/1506887ce/vfilm']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.29
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-101-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[CDA] 1506887ce: Downloading webpage
WARNING: unable to extract rating; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[CDA] 1506887ce: Downloading 360p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 360p version information
[CDA] 1506887ce: Downloading 720p version information
WARNING: Unable to download webpage: HTTP Error 404: 
WARNING: [CDA] Unable to download 720p version information
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1589, in process_video_result
IndexError: list index out of range

```

## Description

cda downloading not working

**Comment by kompowiec** [comment] 2020-06-17 18:30
i have 2020.6.16.1 version and i confirm:

```
ytdl --verbose https://www.cda.pl/video/4267274ad
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.cda.pl/video/4267274ad']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.7.7 (CPython) - Linux-5.6.16-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[CDA] 4267274ad: Downloading webpage
WARNING: unable to extract rating; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[CDA] 4267274ad: Downloading 360p version information
[CDA] 4267274ad: Downloading 720p version information
[CDA] 4267274ad: Downloading 1080p version information
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 10, in <module>
    sys.exit(main())
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1582, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1396, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1408, in _calc_cookies
    pr = sanitized_Request(info_dict['url'])
  File "/home/kompowiec2/.local/lib/python3.7/site-packages/youtube_dl/utils.py", line 2157, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib64/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib64/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'G86C_ce%5Db452%5DA%3D%5E2FK%3A65%21%7BHh%3B2%60%24d%7Er%26b3rH%5E%60dhace%60ebc%5EG%3D443b76fhea%60hac4526c%60aac6_25_6hhgac35%60_6_ebhdc7a74b2%60b_5h542ad55%60_Q5'
```

**Comment by Rudloff** [comment] 2020-08-17 14:09
Duplicate of #25477

**Comment by selfisekai** [comment] 2020-11-17 12:46
Fixed in [haruhi-dl](https://haruhi.download), a libre fork of youtube-dl.

**Closed** 2020-11-23 17:52 UTC
