### ISSUE TITLE
Impossible to download videos on RTBF.BE/Auvio

### ISSUE THREAD

**Issue by PDupont815** [ytdl-org/youtube-dl#31178] opened 2022-08-17 12:26 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
D:\youtube\Test>youtube-dl --verbose --no-check-certificate https://www.rtbf.be/auvio/detail_sting-l-electron-libre?id=2929134
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-check-certificate', 'https://www.rtbf.be/auvio/detail_sting-l-electron-libre?id=2929134']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-02-20-56df829, ffprobe git-2020-02-20-56df829
[debug] Proxy map: {}
[RTBF] 2929134: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\rtbf.py", line 139, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I used to download video from rtbf.be web site with youtube-dl. When I failed, usually I downloaded a new version, which solved the issue. Here it appears that I already have the latest.
I you require credential to connect, don't hesitate to mail me. (I'm not sur if it's required).
thank for you help.

Pierre

**Comment by dirkf** [comment] 2022-08-17 13:29
Duplicate of #31114: please follow that issue.

**Closed by dirkf** 2022-08-17 13:29 UTC
