### ISSUE TITLE
Why not update the version number?

### ISSUE THREAD

**Issue by thiliapr** [ytdl-org/youtube-dl#32772] opened 2024-04-26 13:40 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I think the version number is out of date (the version number was `2021.12.17`, but it is now 2024.4.21), but no one updated it. I think outdated version numbers confuse people and make it impossible to tell the difference between old and new versions.
Files with outdated version numbers include:
```
youtube_dl/version.py
youtube_dl/cache.py
ChangeLog
.github/ISSUE_TEMPLATE/4_bug_report.md
.github/ISSUE_TEMPLATE/1_broken_site.md
.github/ISSUE_TEMPLATE/5_feature_request.md
.github/ISSUE_TEMPLATE/2_site_support_request.md
.github/ISSUE_TEMPLATE/3_site_feature_request.md
```
It is also worth mentioning that Release has not been updated since 2021.12.17.

**Comment by nicolaasjan** [comment] 2024-04-26 15:14
See issue #31585

> A new release is overdue but depends on solving certain cross-platform issues in the CI build process. Meanwhile for the main platforms, see #31530 for update hints.

**Comment by dirkf** [comment] 2024-04-27 00:27
If you are using the nightly release, as recommended, you get a sensible version number.

If you're running a git checkout, you get the HEAD.

Duplicate of #32039.

**Closed by dirkf** 2024-04-27 00:27 UTC
Labels: question
