### ISSUE TITLE
Vid unavailable, can download using youtube download sites just fine though?

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [ytdl-org/youtube-dl#22370] opened 2019-09-11 14:59 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.09.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v  https://www.youtube.com/watch?v=cRA8M7dPKbE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=cRA8M7dPKbE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.01
[debug] Python version 2.7.14 (CPython) - Linux
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2
[debug] Proxy map: {}
[youtube] cRA8M7dPKbE: Downloading webpage
[youtube] cRA8M7dPKbE: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/youtube-dl/youtube_dl/extractor/youtube.py", line 2115, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.


```

## Description

Getting unavailable error for this specific video, can load in browser, tried many different ways cant get formats or any streams constantly blanket unavailable.

Was able to download it using sites that download youtube videos. odd, never encountered this before using youtube-dl (Which is what i thought most downloader sites were embedding these days)

**Comment by yan12125** [comment] 2019-09-11 17:22
Most likely duplicate of #22367.

**Closed by yan12125** 2019-09-11 17:22 UTC
