### ISSUE TITLE
Limited 60 Kb/s Download Speed For Videos  

### ISSUE THREAD

**Issue by Aliyansayz** [ytdl-org/youtube-dl#30552] opened 2022-01-24 15:16 UTC
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Destination: G:\video\GTA V - 'Prologue' on RTX™ Gameplay - [4k] Maximum Settings - Ray Tracing Graphics MOD.f299.mp4
[download]  13.8% of 294.11MiB at 51.92KiB/s ETA 01:23:19

As you can see above download speed is very low.

**Comment by FT129** [comment] 2022-01-24 15:26
use yt-dlp https://github.com/yt-dlp/yt-dlp

**Comment by 89z** [comment] 2022-01-24 15:39
I have an alternate tool that works:

~~~
PS C:\> youtube oReoOI7GSVk
POST https://www.youtube.com/youtubei/v1/player
GET https://rr2---sn-q4flrnez.googlevideo.com/videoplayback?expire=1643060033&ei=4cbuYaSAI7ya2_gP5Le9sA4&ip=72.181.23.38&id=o-AKyCrUI9Yho-vzPe7DL5AioqZUOGjXpb3CKdNS-CCGPI&itag=302&source=youtube&requiressl=yes&mh=4f&mm=31%2C26&mn=sn-q4flrnez%2Csn-vgqsknse&ms=au%2Conr&mv=m&mvi=2&pl=19&initcwndbps=1573750&vprv=1&mime=video%2Fwebm&gir=yes&clen=126759250&dur=486.382&lmt=1627736981943371&mt=1643038138&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5316224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgP1N03rchbZ54AWPGvnS-8sDjCLKvJO4YVRABihJuh4YCIQDoyZB40SLCe_nNwUqj2Z0cU1A7CIsu9J58GOR79Ba39g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTInPHty9SeNZsQHCba3xAbD-Yt7PVNOWFmU6Xvt-4wICICy5StLA1raBQlJHZKTBGckNv-EJRCKZ4E2V_nmg1Jkk
7.9%    10.000 MB       8.110 MB/s
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment] 2022-01-24 15:47
Let's assume OP's problem is a YT URL based on the `f299` format id.

Then, in addition to the above responses, as OP would have found by **[simply following the Broken Site Support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template**, this is a duplicate of #29326 (and about 15 other recent issues), where (read to the end) solutions are provided.

**Closed** 2022-01-31 00:31 UTC
Labels: duplicate, question
