### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by Chitranjan6G** [ytdl-org/youtube-dl#30128] opened 2021-10-19 00:36 UTC
There is taking minimum 40-120 minutes in One video downloading.

So improve this issue

**Comment by 89z** [comment] 2021-10-19 01:01
This issue has been posted many times. Please do not post duplicate issues.

**Comment by dirkf** [comment] 2021-10-19 05:58
Duplicate of #29326
See also https://github.com/ytdl-org/youtube-dl/issues/30097#issuecomment-946231355

**Comment by Akczht** [comment] 2021-10-19 13:45
Guys! I'm facing the same issues can something be done about this

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 02:06
> @Akczht I think you need to come to the realization that no one here owes you anything. If you dont like the current state of this program, use something else, or fix it yourself. This is open source, need I remind you that you havent paid anything for this product. Good day.

The question of if something can be done is not a question of entitlement, it's a question for help. I wonder how you helped.

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 02:21
> > The question of if something can be done is not a question of entitlement, it's a question for help.
> 
> The person didnt ask "what can I do to help", the person asked, "can something be done about this", with the assumption being, "when is someone (not me) going to fix this". Its a common response you see in open source threads, of people who get upset when their favorite free tool isnt working exactly the way they want it to.
> 
> > I wonder how you helped.
> 
> I gave a couple of helpful suggestions. Perhaps while writing your clever comment, you didnt bother to fully read mine. Here it is again:
> 
> > If you dont like the current state of this program, use something else, or fix it yourself.

I don't know think you can draw that assumption, but I think it's clearly a request for help. It's unclear why your comment was deleted so now there's no way for anyone to know if you helped. Good news though: you can still help them by commenting!

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 02:22
> > The question of if something can be done is not a question of entitlement, it's a question for help.
> 
> The person didnt ask "what can I do to help", the person asked, "can something be done about this", with the assumption being, "when is someone (not me) going to fix this". Its a common response you see in open source threads, of people who get upset when their favorite free tool isnt working exactly the way they want it to.
> 
> > I wonder how you helped.
> 
> I gave a couple of helpful suggestions. Perhaps while writing your clever comment, you didnt bother to fully read mine. Here it is again:
> 
> > If you dont like the current state of this program, use something else, or fix it yourself.

I don't think you can draw that assumption, but I think it's clearly a request for help. It's unclear why your comment was deleted so now there's no way for anyone to know if you helped. Good news though: you can still help them by commenting!

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 02:37
I ask your indulgence for just a moment, please trust me. Is it so hard to believe that someone asking "can something be done about this" isn't asking for a community know solution.

**Comment by 89z** [comment] 2021-10-20 02:41
Here is the same issue five times:

- https://github.com/ytdl-org/youtube-dl/issues/30097
- https://github.com/ytdl-org/youtube-dl/issues/30102
- https://github.com/ytdl-org/youtube-dl/issues/30109
- https://github.com/ytdl-org/youtube-dl/issues/30119
- https://github.com/ytdl-org/youtube-dl/issues/30128

These are just from the current first page. What should I assume about someone who didnt bother to even read the first page of issues?

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 02:52
I take your point, but perhaps you should assume they need help. Is it really so painful to point people in the right direction instead of criticizing them. Perhaps we need stewards like me to do this.

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 03:10
Yes, thank you for recognizing that I might have been well read on the issue. I would comment that this issue is important because it makes the program ununseable. But as I've commented elsewhere the real problem is that we have a fix, but there's bad management. I don't think we need to attack people that might actually be looking for help, but my conversation with you has been deeply adversarial, despite my efforts. So this is conversation is over and you can criticize to your hearts content, but it's really over.

**Comment by 89z** [comment] 2021-10-20 03:26
Oh no :(

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 03:29
I'll let the conversation speak for itself.

**Comment by Ashwynn-Thorne** [comment] 2021-10-20 03:29
> This guy is sad. The answer is in his face. He literally quoted the answer. And he still doesnt see it. Oh well, some people are beyond help I guess.

I'll let the conversation speak for itself.

**Comment by 89z** [comment] 2021-10-20 03:31
Yeah, keep quoting me, that will deter me. The first three times I handled, but four quotes is too much! I must back down now :(

**Comment by 89z** [comment] 2021-10-20 03:37
Nope sorry, I am restarting the conversation:

![(JPEG Image, 259 × 194 pixels)](https://user-images.githubusercontent.com/73562167/138024257-6d9947ae-0d90-4b51-b8c8-5cbcc241e83d.jpg)

**Closed** 2022-01-31 00:31 UTC
Labels: duplicate
