### ISSUE TITLE
Pluralsight -HTTP Error 403

### ISSUE THREAD

**Issue by msabeq** [ytdl-org/youtube-dl#29980] opened 2021-09-17 12:07 UTC
"C:/Users/msabeq/Videos/Pluralsight/%(playlist)s/%(chapter_number)02d - %(chapter)s/%(playlist_index)02d - %(title)s.%(ext)s"  --sleep-interval 35 --max-sleep-interval 120 --sub-lang en --sub-format srt --write-sub )
[pluralsight:course] microsoft-azure-cloud-concepts: Downloading JSON metadata
[download] Downloading playlist: Microsoft Azure Cloud Concepts
[pluralsight:course] playlist Microsoft Azure Cloud Concepts: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PLZ help me with is error

**Comment by dirkf** [comment] 2021-09-17 22:14
PLZ follow the template.

**Comment by mainul004** [comment] 2021-09-30 07:38
@msabeq I was in the same boat. I used --cookies option instead of --username and --password successfully. Used "Get cookies.txt" extension to get the cookies to a text file. Ref: https://github.com/ytdl-org/youtube-dl/issues/28762

**Comment by dirkf** [comment] 2022-01-18 23:43
Duplicate of #29776.

**Closed** 2022-02-07 12:55 UTC
Labels: duplicate
