### ISSUE TITLE
Incomplete Download of Media Items in Mixed Media Tweets

### ISSUE THREAD

**Issue by Matin-B** [ytdl-org/youtube-dl#32212] opened 2023-05-19 10:57 UTC
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running youtube-dl version **2021.12.17** (yt-dlp --version: **2023.03.04**)
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

On October 5, 2022, Twitter made an exciting announcement regarding the introduction of mixed media tweets, enabling users to share videos, images, and GIFs together within a single tweet. You can find the official announcement on the Twitter Blog through the following link: [Twitter Blog Announcement](https://blog.twitter.com/en_us/topics/product/2022/introducing-mixed-media-videos-images-gifs-together-one-tweet)

However, upon using yt-dlp, I have noticed that it fails to download all media items within mixed media tweets effectively. Specifically, it only retrieves the first item of media, disregarding the additional videos, images, and GIFs present in the tweet.

To better illustrate the issue, I would like to provide you with an example tweet that contains mixed media content:
https://twitter.com/aespa_official/status/1577282815250427907

**Comment by dirkf** [comment] 2023-05-19 12:23
>I've verified that I'm running youtube-dl version 2021.12.17 (yt-dlp --version: 2023.03.04)

So you haven't, then?

yt-dlp: #30839, but this was fixed in https://github.com/yt-dlp/yt-dlp/pull/5183

For yt-dl: duplicate of #31281.

**Closed by dirkf** 2023-05-19 12:23 UTC

**Comment by Matin-B** [comment] 2023-05-19 13:57
> > I've verified that I'm running youtube-dl version 2021.12.17 (yt-dlp --version: 2023.03.04)
> 
> So you haven't, then?
> 
> yt-dlp: #30839, but this was fixed in [yt-dlp/yt-dlp#5183](https://github.com/yt-dlp/yt-dlp/pull/5183)
> 
> For yt-dl: duplicate of #31281.

oh, I sincerely apologize. I had not found this issue.
