### ISSUE TITLE
hotstar not unable to dowload video

### ISSUE THREAD

**Issue by sant527** [ytdl-org/youtube-dl#17957] opened 2018-10-24 12:38 UTC
```
$ youtube-dl --verbose https://www.hotstar.com/sports/cricket/india-vs-windies-2018/188618/match-clips/rayudu-takes-charge-with-73/2001620101
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.hotstar.com/sports/cricket/india-vs-windies-2018/188618/match-clips/rayudu-takes-charge-with-73/2001620101']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.6.4 (CPython) - Linux-4.15.14-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, phantomjs 18, rtmpdump 2.4
[debug] Proxy map: {}
[hotstar] 2001620101: Downloading webpage
[hotstar] 2001620101: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

**Comment by remitamine** [comment] 2018-10-24 14:08
```
youtube-dl --proxy localhost:8080 https://www.hotstar.com/sports/cricket/india-vs-windies-2018/188618/match-clips/rayudu-takes-charge-with-73/2001620101
[hotstar] 2001620101: Downloading webpage
[hotstar] 2001620101: Downloading JSON metadata
[hotstar] 2001620101: Downloading m3u8 information
[download] Destination: Rayudu Takes Charge with 73-2001620101.mp4
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[tcp @ 0x557bc27e1480] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x557bc27dc580] Opening 'https://hssportsprepack.akamaized.net/videos/cricket/indvswi2018/24_10_2018/2001620102/master_Layer7_00001.ts' for reading
[tcp @ 0x557bc2df6b80] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x557bc27dc580] Opening 'https://hssportsprepack.akamaized.net/videos/cricket/indvswi2018/24_10_2018/2001620102/master_Layer7_00002.ts' for reading
[tcp @ 0x557bc2882d80] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
Input #0, hls,applehttp, from 'https://hssportsprepack.akamaized.net/videos/cricket/indvswi2018/24_10_2018/2001620102/master_Layer7.m3u8':
  Duration: 00:02:57.60, start: 2.160222, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Rayudu Takes Charge with 73-2001620101.mp4.part':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   35 fps=0.0 q=-1.0 size=       0kB time=00:00:01.39 bitrate=   0.3kbits/frame=   54 fps= 27 q=-1.0 size=     256kB time=00:00:02.15 bitrate= 974.1kbits/frame=   73 fps= 23 q=-1.0 size=     512kB time=00:00:02.91 bitrate=1439.8kbits/frame=   84 fps= 20 q=-1.0 size=     512kB time=00:00:03.35 bitrate=1250.9kbits/frame=   91 fps= 17 q=-1.0 size=     512kB time=00:00:03.63 bitrate=1154.5kbits/frame=   96 fps= 16 q=-1.0 size=     512kB time=00:00:03.83 bitrate=1094.3kbits/frame=   98 fps= 14 q=-1.0 size=     512kB time=00:00:03.91 bitrate=1071.9kbits
```

**Comment by sant527** [comment] 2018-10-25 05:33
did you check the video. can you use --verbose option also. because the video says download some app

**Comment by remitamine** [comment] 2018-10-25 07:36
> did you check the video.

I did, it's the same video played in the browser.

**Comment by darkmorpher** [comment] 2019-05-14 02:30
Duplicate of #15465

**Comment by remitamine** [comment] 2019-05-14 11:14
> So why proxy works, but not VPN.
most likely Hotstar banned some of Psiphon IPs.

**Closed by remitamine** 2019-05-14 11:14 UTC
Labels: cant-reproduce, geo-restricted
