### ISSUE TITLE
cannot download - ERROR : unable to extract uploader id

### ISSUE THREAD

**Issue by moora** [ytdl-org/youtube-dl#32051] opened 2023-04-17 07:56 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\ruzickova\youtube download> C:\Users\ruzickova\youtube download\pravy_klik_upravit_youtube_download.ps1
.\youtube-dl.exe : [debug] System config: []
At C:\Users\ruzickova\youtube download\pravy_klik_upravit_youtube_download.ps1:2 char:1
+ .\youtube-dl.exe -x -f bestaudio --verbose --audio-quality 0 --audio- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([debug] System config: []:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-x', '-f', 'bestaudio', '--verbose', '--audio-quality', '0', '--audio-format', 'mp3', 'https://www.youtube.com/watch?v=rzrpy9qSSSE&list=
RDEMTQJShkjyApi2KbUtDexMUw&start_radio=1&rv=BPuIe0GyfLQ']
[debug] Encodings: locale cp1250, fs mbcs, out cp1250, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-02-07-git-a52b9464e4-full_build-www.gyan.dev, ffprobe 2021-02-07-git-a52b9464e4-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] Downloading playlist RDEMTQJShkjyApi2KbUtDexMUw - add --no-playlist to just download video rzrpy9qSSSE
[youtube:tab] RDEMTQJShkjyApi2KbUtDexMUw: Downloading webpage
[download] Downloading playlist: Mix - H-Blockx
[youtube:tab] playlist Mix - H-Blockx: Downloading 25 videos
[download] Downloading video 1 of 25
[youtube] rzrpy9qSSSE: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update.
 Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE

**Comment by najk** [comment] 2023-04-17 08:16
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by dirkf** [comment] 2023-04-17 10:19
Indeed, duplicate of #31530.

Using #30839 and the checklist properly would have shown this.

**Closed by dirkf** 2023-04-17 10:19 UTC
