### ISSUE TITLE
[Teachable] Can't download videos. I downloaded same videos yesterday

### ISSUE THREAD

**Issue by saadshabbir735** [ytdl-org/youtube-dl#30962] opened 2022-05-19 22:33 UTC
```
I:\>youtube-dl -v --cookies cookies.txt https://courses.automationplay.com/courses/1391108/lectures/31998698
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://courses.automationplay.com/courses/1391108/lectures/31998698']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 31998698: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 31998698: Downloading webpage
[generic] 31998698: Extracting information
[Teachable] 31998698: Downloading webpage
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\teachable.py", line 176, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by saadshabbir735** [comment] 2022-05-19 22:35
Please help ASAP

**Comment by dirkf** [comment] 2022-05-19 23:04
Duplicate of #30929.

**Closed** 2022-05-21 15:10 UTC
Labels: duplicate
