### ISSUE TITLE
Paramount plus movies 

### ISSUE THREAD

**Issue by Nottoknow2** [ytdl-org/youtube-dl#29038] opened 2021-05-14 02:43 UTC
for examples this wont download https://www.paramountplus.com/movies/spongebob-movie-sponge-on-the-run/tQk_Qooh5wUlxQqzj_4LiBO2m4iMrcPD/

**Comment by Nottoknow2** [comment] 2021-05-14 02:44
[yt.txt](https://github.com/ytdl-org/youtube-dl/files/6476184/yt.txt)

**Comment by harieamjari** [comment] 2021-05-15 12:01
Likely a violation of DMCA

**Comment by Nottoknow2** [comment] 2021-05-15 16:01
> Likely a violation of DMCA and so youtube-dl will not support it.

Paramount shows work like spongebob

**Comment by ryandesign** [comment] 2021-05-17 05:36
Duplicate of #17870.

**Comment by 89z** [comment] 2022-01-22 04:13
https://github.com/ytdl-org/youtube-dl/issues/30491

**Comment by 89z** [comment] 2022-03-06 01:06
https://github.com/ytdl-org/youtube-dl/pull/30085

**Comment by 89z** [comment] 2022-03-10 04:32
this one is DRM

**Closed** 2022-04-12 15:32 UTC
Labels: DRM, duplicate
