### ISSUE TITLE
pornhub: can't download private favorites

### ISSUE THREAD

**Issue by ioistired** [ytdl-org/youtube-dl#17219] opened 2018-08-12 03:41 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
└> youtube-dl -vu youtube-dl-test -p 'K<HC7bbU`cjzGE^;k~x(1aDaq~6[>%vl' https://www.pornhub.com/users/youtube-dl-test/videos/favorites
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vu', 'youtube-dl-test', '-p', 'PRIVATE', 'https://www.pornhub.com/users/youtube-dl-test/videos/favorites']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-30-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHubUserVideos] youtube-dl-test: Downloading page 1
[download] Downloading playlist: youtube-dl-test
[PornHubUserVideos] playlist youtube-dl-test: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: youtube-dl-test
```

### Description of your *issue*, suggested solution and other information

No videos were downloaded. Try making the favorites videos public in https://www.pornhub.com/user/prefs and try again, and it works.
Workaround: make the favorites videos public, start downloading the videos, and once it starts downloading the first one, make them private again.

**Comment by indywatch** [comment] 2018-08-24 20:10
Duplicate of #17196?

**Comment by dirkf** [comment] 2024-10-01 21:19
This should work with the new PH login system and extractor code to handle it. Please open a new issue if not.

**Closed by dirkf** 2024-10-01 21:19 UTC
