### ISSUE TITLE
Downloading from slideslive.com is broken

### ISSUE THREAD

**Issue by CodeGenerator** [ytdl-org/youtube-dl#30881] opened 2022-04-21 17:55 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://slideslive.com/38930945', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.3 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[SlidesLive] 38930945: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/opt/anaconda3/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/opt/anaconda3/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/anaconda3/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/anaconda3/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/anaconda3/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Nothing can be downloaded from slideslive.com.
It seems slideslive.com changed authorization scheme. And extractor should download intermediate token beforehand.

**Comment by dirkf** [comment] 2022-04-28 10:59
You are actually trying to download from slideslive.com. Is that correct? If so, please update the issue title. Otherwise, close the issue?

**Comment by CodeGenerator** [comment] 2022-04-28 14:17
Yeah, thanks for your correction. Fixed.

**Comment by HireTheHero** [comment] 2022-06-18 16:28
Met the same issue. Any updates?

**Comment by HireTheHero** [comment] 2022-09-08 13:57
A workaround is, referring to #29958 , check the video hosted on another service. 
For youtube video see [this](https://github.com/HireTheHero/Machine_Notebooks/blob/main/Slideslive.ipynb). Not sure about other services though (I've seen one example hosted in service called "yoda", which I haven't even heard the name).

**Comment by HireTheHero** [comment] 2022-09-10 06:23
#29958 refers to it. Will investigate further
```
When video service is yoda you can use one of the servers from #EXT-SL-VOD-VIDEO-SERVERS (preferably always the first one) to download that particular video using following URL https://$VIDEO_SERVER/$VIDEO_ID/master.m3u8 which is Apple HLS playlist.
```

**Comment by dirkf** [comment] 2022-09-10 11:40
Anyhow, this is a duplicate of #29954 which PR #29958 was meant to fix. Please test the PR and report issues there.

**Closed by dirkf** 2022-09-10 11:40 UTC

**Comment by CodeGenerator** [comment] 2022-09-24 17:51
> A workaround is, referring to #29958 , check the video hosted on another service. For youtube video see [this](https://github.com/HireTheHero/Machine_Notebooks/blob/main/Slideslive.ipynb). Not sure about other services though (I've seen one example hosted in service called "yoda", which I haven't even heard the name).

Thanks. The workaround works well.
