### ISSUE TITLE
Unable to download from Nicovideo (NicoNico)

### ISSUE THREAD

**Issue by shinoas** [ytdl-org/youtube-dl#29974] opened 2021-09-16 04:09 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nicovideo.jp/watch/sm38036476', '-u,', '--username', 'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg git-2020-06-23-ce297b4, ffprobe git-2020-06-23-ce297b4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm38036476: Downloading webpage
[niconico] sm38036476: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Unable to download even with -u command
Type account password and press [Return]:
[niconico] Logging in
[niconico] sm38036476: Downloading webpage
[niconico] sm38036476: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

WRITE DESCRIPTION HERE

**Comment by kikuyan** [comment] 2021-09-19 01:20
Duplicate of #29225.
The extractor has been broken since site change on mid March.
Other error cases in #28484 and #28990.

**Closed** 2022-02-05 02:47 UTC
Labels: duplicate
