### ISSUE TITLE
"Unable to extract uploader id" error when extracting 

### ISSUE THREAD

**Issue by LenzGr** [ytdl-org/youtube-dl#31577] opened 2023-02-18 14:51 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
% ./youtube-dl --version
2021.12.17
% ./youtube-dl --verbose --audio-format mp3 --skip-download 'https://www.youtube.com/watch?v=etAIpkdhU9Q'
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--audio-format', 'mp3', '--skip-download', 'https://www.youtube.com/watch?v=etAIpkdhU9Q']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.1.10-100.fc36.x86_64-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0.2, ffprobe 5.0.2
[debug] Proxy map: {}
[youtube] etAIpkdhU9Q: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/lenz/Downloads/./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lenz/Downloads/./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lenz/Downloads/./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/lenz/Downloads/./youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/lenz/Downloads/./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Extracing the audio from [this YouTube video](https://www.youtube.com/watch?v=etAIpkdhU9Q) fails with an error message: `Unable to extract uploader id`

**Comment by elgonzo** [comment] 2023-02-18 14:54
> [x] I've searched the bugtracker for similar bug reports including closed ones

Yeah, heard that somewhere already... :-(

**Comment by i-am-dan** [comment] 2023-02-18 15:03
@LenzGr Checkout - https://github.com/ytdl-org/youtube-dl/commit/2dd6c6edd8e0fc5e45865b8e6d865e35147de772

Looks like the fix has been placed. 

I've mentioned this in the commit but - Are you familiar with cloning the repo? If you can't wait for the release you can clone the source code and call 'python __main__.py [URL] ..etc' to download the video and it's been working great. Though, some argument combination does still give this error.

**Comment by dirkf** [comment] 2023-02-18 15:15
> some argument combination does still give this error.

@i-am-dan, please open a new issue, with full details as requested in the issue template, if you can reproduce the error. The current fix shows a `Warning` because the expected field could not be extracted, but does not crash (except under the test harness that enforces "warnings as errors" when the test-case doesn't list the warning text as expected).

Otherwise, duplicate of #31530, so no:
> [x] I've searched the bugtracker for similar bug reports including closed ones

**Closed by dirkf** 2023-02-18 15:15 UTC
