### ISSUE TITLE
NhkVod should allow for letters in the video id

### ISSUE THREAD

**Issue by ke352802081770314** [ytdl-org/youtube-dl#31022] opened 2022-06-12 07:10 UTC
## Checklist

- [yes ] I'm reporting a broken site support
- [yes ] I've verified that I'm running youtube-dl version **2021.12.17**
- [yes ] I've checked that all provided URLs are alive and playable in a browser
- [yes ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [yes ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

verbosity not needed
youtube-dl https://www3.nhk.or.jp/nhkworld/en/ondemand/video/9999e75/
[generic] 9999e75: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9999e75: Downloading webpage
[generic] 9999e75: Extracting information
ERROR: Unsupported URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/9999e75/

## Description

I assume the pattern matching for NhkVod only allows for seven digit video ids, but it seems that in some cases (the first four digits give the "series", apparently 9999 is a catch-all for miscellaneous stuff, and the following three digits the episode, when they need beyond episode 999, the scheme breaks) the 5th character can also be a lowercase letter.
Expected:
the first line of output should start with [NhkVod] not with [generic]
I expect everything will work if the right extractor is used.

**Comment by dirkf** [comment] 2022-06-12 12:11
Fixed in git master by merge of #29682.

Duplicate of #29670.

Still affects 2021.12.17 and yt-dlp master.

**Comment by ke352802081770314** [comment] 2022-06-12 12:15
many thanks for the quick response. apologies for missing the existing bug.

**Closed** 2022-06-12 13:26 UTC
Labels: broken-IE, duplicate, fixed
