### ISSUE TITLE
[BUG] - "Unable to extract uploader id". All videos fail to download.

### ISSUE THREAD

**Issue by couldbejake** [ytdl-org/youtube-dl#32571] opened 2023-09-26 23:54 UTC
## Checklist

Complete

- [V] I'm reporting a broken site support issue
- [V ] I've verified that I'm running youtube-dl version **2021.12.17**
- [V] I've checked that all provided URLs are alive and playable in a browser
- [V] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [V] I've searched the bugtracker for similar bug reports including closed ones
- [V] I've read bugs section in FAQ

## Verbose log

```
PS -> youtube-dl -v https://www.youtube.com/watch?v=nSj1htnz4vE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=nSj1htnz4vE']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.9 (CPython) - Windows-10-10.0.22621-SP0
[debug] exe versions: ffmpeg N-111391-gf6dc85ae16-20230710, ffprobe N-111391-gf6dc85ae16-20230710
[debug] Proxy map: {}
[youtube] nSj1htnz4vE: Downloading webpage
[youtube] nSj1htnz4vE: Downloading API JSON
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\jakenelson\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jakenelson\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\jakenelson\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\jakenelson\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "C:\Users\jakenelson\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

All videos seem to fail to download, I believe this is an update by YouTube. It could be that I'm IP banned, but I have verified this on external servers.

**Comment by aroon** [comment] 2023-09-27 01:06
Seeing the same issue and verified I can reproduce with a a video I was able to download a few months ago.

youtube-dl --verbose "https://www.youtube.com/watch?v=l0Jm-99lhlg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=l0Jm-99lhlg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Darwin-23.1.0-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] l0Jm-99lhlg: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by aroon** [comment] 2023-09-27 01:09
Looks like this might have been addressed in this commit?

https://github.com/ytdl-org/youtube-dl/commit/f7ce98a21e15cb094c772e9082796d009c61578b

**Comment by andrew-werdna** [comment] 2023-09-27 02:14
I'm having the _exact_ same error as OP

**Comment by Pedroooo-byte** [comment] 2023-09-27 02:30
I haven't been able to download anything for a while. I recall the website getting taken down by a court ruling in Germany, but not the actual utility. Could this potentially be a next step in the lawsuit?

**Comment by andrew-werdna** [comment] 2023-09-27 02:39
Here's what I did that got things working for me:
```zsh
cd ~
# clone this repo
git clone git@github.com:ytdl-org/youtube-dl.git
# I created the directory I wanted to download videos to
mkdir -p ~/path/to/my/destination/
cd ~/path/to/my/destination/
# I use ZSH as my shell so I noticed the `youtube-dl/youtube-dl.plugin.zsh` file and I modified it for my uses and ran this straight from my shell
alias youtube-dl="PYTHONPATH=$(realpath ../relative/path/to/repo/youtube-dl) $(realpath ../relative/path/to/repo/youtube-dl)/bin/youtube-dl"
youtube-dl "https://youtube.com/playlist?list=........."
```
It appears to have downloaded all of the videos in the playlist!

**Comment by couldbejake** [comment] 2023-09-27 02:40
That's not q great solution, I'm needing to build this into [spotify2mp3](github.com/couldbejake/spotify2mp3), and want to minimise installation steps.

**Comment by hoochoovu** [comment] 2023-09-27 06:23
Ok. I've solved the problem. This is my first ever contribution to anything on github so spare me. lol

The version everyone is running and unable to update because the -U function doesn't work. To solve this, we'll manually download the ytdl .deb file from Sept. 24 from one of the mirror sites. (Note not all mirrors are working) https://packages.debian.org/sid/all/yt-dlp/download

After downloading the .deb file, open up terminal and install it like you normally would .deb type:

Example for me was: sudo apt install /FILELOCATIONHERE/yt-dlp_2023.09.24-1_all.deb

That's it you're done.

My previous version was 22.04.08 and the correct version now states 23.09.24. I've fully downloaded a video just a few seconds ago.

DOWNLOAD AWAY FOLKS!!!!!

**Comment by couldbejake** [comment] 2023-09-27 09:37
> That's not a great solution, I'm needing to build this into [spotify2mp3](https://github.com/couldbejake/spotify2mp3), and want to minimise installation steps.

Does anyone have a pip solution regarding youtubedl and an update?

**Comment by couldbejake** [comment] 2023-09-27 09:42
> Here's what I did that got things working for me:
> 
> ```shell
> cd ~
> # clone this repo
> git clone git@github.com:ytdl-org/youtube-dl.git
> # I created the directory I wanted to download videos to
> mkdir -p ~/path/to/my/destination/
> cd ~/path/to/my/destination/
> # I use ZSH as my shell so I noticed the `youtube-dl/youtube-dl.plugin.zsh` file and I modified it for my uses and ran this straight from my shell
> alias youtube-dl="PYTHONPATH=$(realpath ../relative/path/to/repo/youtube-dl) $(realpath ../relative/path/to/repo/youtube-dl)/bin/youtube-dl"
> youtube-dl "https://youtube.com/playlist?list=........."
> ```
> 
> It appears to have downloaded all of the videos in the playlist!
> 
> **EDIT 1:** This is the first time I have ever used this tool. For me personally, since I rarely use it, this was an acceptable workaround for the moment. I only wanted to download 1, 4-video playlist because it helped me learn something on a deeper level and I _really_ wanted to make sure I could download this 1 thing. This is obviously not a good long-term way to use this. Now that I have actually used this tool, I _really_ like it and _really_ want to continue using it. We need a better, more solid fix. I'm kinda sad I haven't used python at all in about 7 years.
> 
> **EDIT 2:** I'm not very familiar with this project, why hasn't there been a release in over 21 months? It seems fairly active and popular.

I don't understand why all work on YouTube downloaders are seizing.

**Comment by dirkf** [comment] 2023-09-27 10:38
>[V] I've searched the bugtracker for similar bug reports including closed ones

Really? Review #30839 (**you did read it first?**) for guidance on searching **and for the actual link to the master issue**.

**Closed by dirkf** 2023-09-27 10:38 UTC
