### ISSUE TITLE
Download bilbili videos in 1080p resolution?

### ISSUE THREAD

**Issue by archz2** [ytdl-org/youtube-dl#31382] opened 2022-11-27 11:37 UTC
## Checklist

- [x] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

How can I download bilbili videos in 1080p resolution? By default the videos get downloaded either in 720p or 480p resolution. I suppose that's because to access full HD resolution viewing, Bilibili requires login. What's the workaround?

I also tried using the cookies method by logging into bilbili and exporting my cookies.txt file. Then I used this command. But still the resolution of video was low. 

youtube-dl https://www.bilibili.com/video/BV1W8411b7K5/?=8&share_source=copy_web&vd_source=14d801274def2dd112297a8c82660e8c res:1080--cookies cookies.txt

I get the message '[BiliBili] Format(s) 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them'

**Comment by dirkf** [comment] 2022-11-27 13:34
1. What yt-dl option is `res:1080`?
2. Where are the quotes around the URL?
3. Otherwise, duplicate of #31345.

**Closed by dirkf** 2022-11-27 13:34 UTC
Labels: question

**Comment by archz2** [comment] 2022-11-27 16:27
1. The option is to download in 1080 format. 
2. I've never used quotes around the URL before but I was downloading Youtube and vimeo videos for many years. 

I now used quotes and removed the res:1080 line. Video got downloaded in 480p resolution. 

![image](https://user-images.githubusercontent.com/66735186/204146474-098e4bbd-fdb5-4e57-8689-460d2b17ca15.png)

**Comment by dirkf** [comment] 2022-11-27 19:38
Exactly. The issue of which this is a duplicate is about getting more formats. After the code changes to do that have been mad, the expectation is that 1080p will be available (when the page supports it) when you pass cookies from a logged-in browser session.

yt-dl options are all introduced by `-` or `--` so an intended option `res:1080` will actually be treated as an (unresolvable) URL. Actually, as there's no following space in your original command, both `res:1080--cookies` and `cookies.txt` will be treated as URLs.

The reason for quoting ("Windows", 'POSIX') URLs is that otherwise a special character in the URL confuse the command shell.

Considering your original command
```
youtube-dl https://www.bilibili.com/video/BV1W8411b7K5/?=8&share_source=copy_web&vd_source=14d801274def2dd112297a8c82660e8c res:1080--cookies cookies.txt
```
Windows _cmd_ will see the `&`s and `=`s in the URL as separating a sequence of three commands:
```
youtube-dl https://www.bilibili.com/video/BV1W8411b7K5/?=8
share_source copy_web
vd_source 14d801274def2dd112297a8c82660e8c res:1080--cookies cookies.txt
```
while a POSIX shell will see the `&`s as job separators,
```
youtube-dl https://www.bilibili.com/video/BV1W8411b7K5/?=8
share_source=copy_web
vd_source=14d801274def2dd112297a8c82660e8c res:1080--cookies cookies.txt
```
asking to run the first two commands as background jobs (the second just setting and discarding the shell variable `share_source`), and in the foreground to run the `res:1080--cookies` command with environment variable `vd_source` set to `14d801274def2dd112297a8c82660e8c` and argument `cookies.txt`.

**Comment by dirkf** [comment] 2022-11-27 20:26
From the evidence you provided in https://github.com/yt-dlp/yt-dlp/issues/5655, the "expectation" isn't met. I'll add a note in the original issue.

**Comment by archz2** [comment] 2022-11-28 10:07
What exactly is the command that I must type to download 1080p resolution video?

**Comment by dirkf** [comment] 2022-11-28 14:34
There is no such command now.

Use `-F`/`--list-formats` to show the available formats and `-f ...`/`--format ...` to specify one of the listed formats to download. When we've worked out how 1080p formats can be extracted (if they can), a yt-dl installation with the resulting future Bilibili extractor module will list 1080p formats if the page supports them; probably you'll need to provide cookies from a logged-in browser session as the current error message suggests.

What currently happens is that the extractor gets a data block (JSON) that contains a list of the known qualities (formats) and a separate list of the media links for various qualities. The error message reports all the known qualities that have no associated media links.

Meanwhile, just stand far enough away from the screen that you can't tell the difference between 480p and 1080p.

**Comment by archz2** [comment] 2022-11-28 15:04
> There is no such command now.
> 
> Use `-F`/`--list-formats` to show the available formats and `-f ...`/`--format ...` to specify one of the listed formats to download. When we've worked out how 1080p formats can be extracted (if they can), a yt-dl installation with the resulting future Bilibili extractor module will list 1080p formats if the page supports them; probably you'll need to provide cookies from a logged-in browser session as the current error message suggests.
> 
> What currently happens is that the extractor gets a data block (JSON) that contains a list of the known qualities (formats) and a separate list of the media links for various qualities. The error message reports all the known qualities that have no associated media links.
> 
> Meanwhile, just stand far enough away from the screen that you can't tell the difference between 480p and 1080p.

I'm downloading software tutorials and the UI in those videos can't be seen when one stands far enough away. Had they been other kind of videos like short film, etc. , then it would have been okay.

**Comment by dirkf** [comment] 2022-11-29 12:21
Current final answer, pending back-port: https://github.com/ytdl-org/youtube-dl/issues/31345#issuecomment-1330543131
