### ISSUE TITLE
[Youtube] Reproducible IncompleteRead error

### ISSUE THREAD

**Issue by lake-effect** [ytdl-org/youtube-dl#30651] opened 2022-02-20 00:47 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--add-metadata', 'https://www.youtube.com/watch?v=9yVxzkR1GjI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-167-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.8, avprobe 3.4.8, ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9yVxzkR1GjI: Downloading webpage
[youtube] 9yVxzkR1GjI: Downloading player c3125ad0
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1361, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1272, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 806, in _download_webpage
    raise e
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 801, in _download_webpage
    expected_status=expected_status)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 671, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 721, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "/usr/lib/python3.6/http/client.py", line 480, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 632, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(527156 bytes read, 1424033 more expected)
 (caused by IncompleteRead(527156 bytes read, 1424033 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1361, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1272, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 806, in _download_webpage
    raise e
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 801, in _download_webpage
    expected_status=expected_status)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 671, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 721, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "/usr/lib/python3.6/http/client.py", line 480, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 632, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(527156 bytes read, 1424033 more expected)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1361, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1272, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 806, in _download_webpage
    raise e
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 801, in _download_webpage
    expected_status=expected_status)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 671, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 721, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "/usr/lib/python3.6/http/client.py", line 480, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 632, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(527156 bytes read, 1424033 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1641, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1371, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1361, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1272, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 806, in _download_webpage
    raise e
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 801, in _download_webpage
    expected_status=expected_status)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 671, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 721, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "/usr/lib/python3.6/http/client.py", line 480, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.6/http/client.py", line 632, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(527156 bytes read, 1424033 more expected)
 (caused by IncompleteRead(527156 bytes read, 1424033 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Lately I've run into seemingly arbitrary youtube download cutoffs. This time the sudden incomplete read is bad enough to make resuming not worth it, as the error recurs every time. I know the video exists and can be played directly from the browser. I would expect it to download with no errors as usual under normal conditions.

**Comment by 89z** [comment] 2022-02-20 00:51
> ERROR: Signature extraction failed: Traceback (most recent call last):

I found you can bypass that problem, by just not extracting the signature in the first place. For example, the ANDROID client URLs already include the decrypted signature:

https://github.com/89z/mech/blob/v1.47.7/youtube/youtubei.go#L15-L19

**Comment by pukkandan** [comment] 2022-02-20 11:56
I can't reproduce

```
❯ youtube-dl 9yVxzkR1GjI -v --no-cache
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['9yVxzkR1GjI', '-v', '--no-cache']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg N-105465-gbedb4bac1c-20220206, ffprobe N-105465-gbedb4bac1c-20220206, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] 9yVxzkR1GjI: Downloading webpage
[youtube] 9yVxzkR1GjI: Downloading player c3125ad0
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr3---sn-gwpa-jjwe.googlevideo.com/videoplayback?expire=1645379427&ei=AisSYsTMPJ-fg8UP8cKeiAU&ip=2405%3A201%3Af003%3Ab164%3Aedb4%3A4053%3A157%3Ad58b&id=o-AMUX-I0nSP6pFWlEjLV1WwRJ20WZGg1tjGq0mDIv_rFF&itag=313&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&mh=mc&mm=31%2C29&mn=sn-gwpa-jjwe%2Csn-gwpa-h55r&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=49&gcr=in&initcwndbps=322500&vprv=1&mime=video%2Fwebm&ns=NLHtus6hWSosoXvsIPMQPbkG&gir=yes&clen=275934827&dur=307.080&lmt=1642465861839933&mt=1645357481&fvip=6&keepalive=yes&fexp=24001373%2C24007246&beids=23886206&c=WEB&txp=5532434&n=jeES4hexkWgoIIqC-&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOurynnDHdvbCD-3qHEnoQpsMF1LhAxmB-9uaeDMHXQzAiBUX3In1N4lbutBaFhUxwYpXcf-2PZcnbSPH73ozwmqVA%3D%3D&sig=AOq0QJ8wRQIhALCvY9a4BDS_4sIOOkhhtHbZYopJdCF7JCsbqqd0GqkAAiBgk_NJeyAiHqnYPY-n5qFPQbupeUbEApsoc2fkLYan6w=='
[download] Resuming download at byte 2425413
[download] Destination: Rolo Tomassi - Closer (Official Music Video)-9yVxzkR1GjI.f313.webm
[download]   0.9% of 263.15MiB at 78.16KiB/s ETA 56:56
ERROR: Interrupted by user
```

Can you check if the player URL https://www.youtube.com/s/player/c3125ad0/player_ias.vflset/en_US/base.js opens in an an incognito tab?

**Comment by dirkf** [comment] 2022-02-20 11:57
I can't repeat this either, at least not without trying to download all 2GB of your problem video. There was a signature extraction issue, fixed in the version reported in your log.

You could try it with the latest master version, which you should be able [install locally](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) with `pip3 --user`.

**Closed** 2022-04-18 03:08 UTC
Labels: cant-reproduce
