### ISSUE TITLE
Youtube-dl no longer downloads from xHamster 

### ISSUE THREAD

**Issue by Hermitic** [ytdl-org/youtube-dl#26282] opened 2020-08-08 09:09 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE

C:\Users\S\Downloads\Youtube-dl>youtube-dl -v https://xhamster.com/videos/henry-
and-june-1990-english-xhOK2Wv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://xhamster.com/videos/henry-and-june-19
90-english-xhOK2Wv']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg git-2020-07-29-cbb6ba2, ffprobe git-2020-07-29-cbb6
ba2
[debug] Proxy map: {}
[XHamster] 1990: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\xhamster.py", line 242, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whux
ta\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
```

## Description

WRITE DESCRIPTION HERE

I have used youtube-dl on my Windows 8.1 OS without a problem for several months. Approximately a week or two weeks ago it ceased working with xHamster. It still downloads flawlessly from other sites.

**Comment by nicolaasjan** [comment] 2020-08-09 07:50
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/26157 I think.

I can confirm that [changing one line](https://github.com/ytdl-org/youtube-dl/issues/26157#issuecomment-669103896) in the source code and compile it again fixes it.
Easy on Linux, but I don't know how to do that in Windows.
You will have to ask here or investigate yourself, I'm afraid...
Or wait till a fix in a new version.

**Comment by hitam4450** [comment] 2020-08-12 08:30
Any progress to fix this issue ??

**Comment by Hermitic** [comment] 2020-08-12 09:07
> 
> 
> Any progress to fix this issue ??

There seems to be a solution for the Linux variant of youtube-dl, but this being the Windows variant we may have to wait until programmers release an update.

**Comment by TheRealDude2** [comment] 2020-08-12 09:26
This is true, at least if you want to use the compiled EXE file.

But if you have python installed as a full version, I think it should work just like the Linux version. But I could be wrong on this point.

**Closed** 2020-08-12 14:40 UTC

**Comment by nicolaasjan** [comment] 2020-08-12 15:07
> This is true, at least if you want to use the compiled EXE file.
> 
> But if you have python installed as a full version, I think it should work just like the Linux version. But I could be wrong on this point.
> 
> Update:
> I have just installed Python on a Windows PC. After that you can actually run youtube_dl normally (see DEVELOPER INSTRUCTIONS in documentation), with the adapted changes in the extractors.

Actually building the Windows executable is not very difficult.
Found instructions [here](https://github.com/ytdl-org/youtube-dl/issues/10014#issuecomment-472695214).

1. If you don't already have it, install [Python](https://www.python.org/downloads/release/python-385/).
2. In an elevated command prompt run:
   ` python.exe -m pip install pyinstaller`
3. Download the youtube-dl source code: https://github.com/ytdl-org/youtube-dl/archive/master.zip
4. Extract to the folder `youtube-dl-master`.
5. Change line 132 in youtube-dl-master\youtube_dl\extractor\xhamster.py to:
    `r'window.initials\s*=\s*({.+?})\s*;\s*', webpage, 'initials',`
6. Open a command prompt in the folder `youtube-dl-master` and run:
    `pyinstaller.exe youtube_dl\__main__.py --onefile --name youtube-dl`
7. youtube-dl.exe can then be found in the `dist` subdirectory.

I replaced the official .exe file with the newly built one and downloading from xHamster worked again!
