### ISSUE TITLE
Seems Slow download

### ISSUE THREAD

**Issue by BUR70N** [ytdl-org/youtube-dl#31267] opened 2022-09-30 19:34 UTC
Have review previous comments about slow speeds.

I am on a MacOs with latest updates applied, installed youtube-dl via brew.

Seems very slow on downloading with a 300Mb connections, is there throttling happening or something similar.

Says its going to be over 3hours to download Just under 1Gb

<img width="480" alt="image" src="https://user-images.githubusercontent.com/9333220/193343722-5b5f0a74-a471-41b7-acb2-5becd37ea817.png">

**Comment by dirkf** [comment] 2022-09-30 20:30
Duplicate of #29326 (etc).

You need to install the program from the git master branch, as discussed in the links from the above.

**Closed by dirkf** 2022-09-30 20:30 UTC
Labels: question
