### ISSUE TITLE
XVIDEOS service is not working since yesterday (blocked download) 

### ISSUE THREAD

**Issue by StaryOjciec** [ytdl-org/youtube-dl#30276] opened 2021-11-26 09:34 UTC
- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

I do not know in which section to post the error, please do not close the topic and, if possible, move the query to the appropriate section. Sorry for my english too. 

**Yutube-dl --version = 2021.06.06**
OS = Linux Arch x64 Xfce (Current Release: 2021.11.01 Kernel: 5.14.15)
OS2 = Linux Manjaro x64 Xfce (Current Release: 2021.11.01 Kernel: 5.13.19-2-MANJARO)
OS3 = Linux Mint x64 Xfce (Current Release: 2021.09.16 Kernel: 4.9.1-UBUNTU)
Terminal: XFCE-Terminal 0.8.11 in all cases 

**Problem:**
From yesterday (25/11/2021) https://xvideos.com
stopped working. Youtube-dl does not download any files.
I include an example answer:

> [hp@elitebook ~]$ youtube-dl https://www.xvideos.com/video39701049/sexy_milf_plays_with_her_pumped_pussy
> 
> [XVideos] 39701049: Downloading webpage
> 
> ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>
> [hp@elitebook ~]$ youtube-dl -f hls-1080p https://www.xvideos.com/video39701049/sexy_milf_plays_with_her_pumped_pussy
> 
> [XVideos] 39701049: Downloading 
> 
> ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 >

I am not using a firewall
All ports are open
I have no problems with the internet connection
Youtube-dl works fine on youtube.com 

[hp@elitebook ~]$ youtube-dl --verbose https://www.xvideos.com/video39701049/sexy_milf_plays_with_her_pumped_pussy

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.xvideos.com/video39701049/sexy_milf_plays_with_her_pumped_pussy']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-5.13.19-2-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 39701049: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by Ashish0804** [comment] 2021-11-26 11:53
![image](https://user-images.githubusercontent.com/39122144/143576811-cf92a1e6-09b5-42d0-bc51-f2f0cf60b831.png)
https://nofap.com/
https://www.reddit.com/r/Semenretention/comments/k5fjci/140_days_benefits_of_semen_retention/

Also go outside and touch the green thingy that looks like this (also called `grass` in some parts of the world)
![image](https://user-images.githubusercontent.com/39122144/143576934-cd1de67b-af38-412b-bc7c-6fd2a86c9aa2.png)

**Comment by dirkf** [comment] 2021-11-26 12:08
Also, duplicate of #30271, which was raised and resolved only **yesterday**.

Maybe there's something in that thing about it making you go blind?

**Comment by StaryOjciec** [comment] 2021-11-26 12:29
I am 64 years old and unfortunately I don't know English well and I don't know GitHub, sorry. I cannot find a solution to the problem. I am crippled in a wheelchair, can't see well, can barely read from the big screen at 200dpi. Sorry. I wanted to report a problem because I couldn't find a link.

**Comment by dirkf** [comment] 2021-11-26 13:28
I updated the original issue linked above with patch instructions. Your installation directory is `/usr/lib/python3.9/site-packages/youtube_dl`.

As the maintainers have gone AWOL we can't update the released version itself for the time being.

**Comment by 89z** [comment] 2021-11-26 13:29
@Ashish0804 why dont you go join a church or something, instead of trolling your morality on this issue tracker? I dont care for that site myself, but if people want to download from it, I would say thats a totally acceptable use of this software, especially considering an extractor already exists:

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/xvideos.py

Why dont you go troll the YT-DLP instead, if you want to be a shithead?

**Comment by StaryOjciec** [comment] 2021-11-26 14:04
Where are the revision instructions?


This file 
>/usr/lib/python3.9/site-packages/youtube_dl  
is the same for me as the one in GitHub from the link from this post 
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/xvideos.py

**Comment by dirkf** [comment] 2021-11-26 14:18
See (now that your sight is improving D) the linked post above.

**Comment by AndreVuillemot160** [comment] 2021-11-26 16:59
Truly an amazing discussion.

**Comment by Ashish0804** [comment] 2021-11-26 19:37
@89z I don't have to be a pastor( or whatever church heads are called) to help out a brother.
Links I provided offer genuine help to people and I'm not just trolling.
The porn industry offers it for free so readily bcoz they want you to get hooked on it and eventually pay for more extreme stuff.
There's no shame in being a coomer...there's only shame in deciding to remain a coomer.

The porn industry is also notorious for treating women badly 
https://www.youtube.com/watch?v=DBTb71UzPmY
https://www.youtube.com/watch?v=c_MjD3mvyF8

Also to OP, if you are genuinely 64 and watching/hoarding porn is only thing that satisfies you, then I recommend you go out for walks or stroll on your wheelchair to take fresh air in.

Remember that Zyzz is watching over us all.
![image](https://user-images.githubusercontent.com/39122144/143624143-5df4b057-d129-490a-b019-9d5a4aabf3d5.png)

**Comment by Kano97** [comment] 2021-11-26 23:54
Sorry, I checked the other post with the aforementioned fix. But I'm on Windows using the executable, how may I patch it with this fix? Please and thank you.

**Comment by dirkf** [comment] 2021-11-27 00:22
See https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-972929975
 and/or https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-965425680.

**Comment by nicolaasjan** [comment] 2021-11-27 08:58
> Where are the instructions how to correct it ?
> 
> This file
> 
> > /usr/lib/python3.9/site-packages/youtube_dl
> 
> This file on my computer is the same as the one in GitHub from the link from this post, no differences. Do I need to correct something? https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/xvideos.py

What you could also try is switching to the [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork, in which this very issue has now been fixed in the `master` branch:
https://github.com/yt-dlp/yt-dlp/pull/1799

Not in the release version yet.

**Comment by GreenLunar** [comment] 2021-11-28 08:10
OFFTOPIC

Following @Ashish0804, I think it would be beneficial to output a message for the user to cease or lower consumption of xxx contents. I have xxx contents too, but this whole thing is an ordeal of the ruling class to make us poor, for crying out loud.

@Ashish0804 I suggest this video https://www.youtube.com/watch?v=7XX80DaKIgI by Alex Becker.

P.S. Yesterday I was at the beach a got the phone numbers of two cute ladies + I was 500 meters in the sea and played with fish. IT WAS A FUN DAY!

**Comment by Ashish0804** [comment] 2021-11-28 11:59
"The Porn Industry and its consequences have been a disaster for the human race."

-Barack Obama, 2020

@GreenLunar I'm happy for u to know u hooked up with 2 cuties and enjoyed your day.
Keep enjoying the life King.

At the same time I'm also saddened by the death of that person (no matter how much I hate the industry she worked in).
The fact that she dies poor proves that you are not supporting muh innocent fem-entrepreneur by watching porn, you are simply filling the pockets of the few.

![image](https://user-images.githubusercontent.com/39122144/143766726-78e511b1-1921-4696-979b-8f0970d990ac.png)

**Comment by Bielecki** [comment] 2021-12-04 10:40
@GreenLunar @Ashish0804 yeah, cool. Do you have a solution to issue? If not, stop spamming offtopic, because no one asked you to do so.

**Comment by Ashish0804** [comment] 2021-12-05 09:12
@Bielecki Take your white privilege to somewhere else and stop telling us what we can and cannot do.
No one asked u to police issues on yt-dl either so I humbly ask u to shut the fuck up.
![image](https://user-images.githubusercontent.com/39122144/144740578-dc41f583-40a8-4348-9a30-5009e28a5201.png)

**Comment by Bielecki** [comment] 2021-12-06 10:59
@Ashish0804 take out your racism somewhere else. This is github, not reddit.

**Comment by scramblr** [comment] 2021-12-17 01:37
If you need moderators to help get rid of people on religious crusades in these technical bug fix sections, sign me up. I'd be happy to boot these dumbass fools like @Ashish0804 out.

**Comment by scramblr** [comment] 2021-12-17 01:46
Also, this problem still exists again for xvideos.

**Comment by 89z** [comment] 2021-12-17 01:53
@scramblr I reported him, but they didnt do anything. They didnt even remove the comment. So I dont know if it will help, but if more people report then maybe.

**Comment by scramblr** [comment] 2021-12-17 02:17
I submitted a PR for this issue in the meantime. Hopefully github will take action on the clown.

**Comment by AndreVuillemot160** [comment] 2021-12-17 05:20
Bruh, guys you really hope that the account will be taken down? lol.

**Comment by Menard01** [comment] 2021-12-18 17:02
I am also with this technical problem ... It worked fine before

**Comment by 89z** [comment] 2021-12-28 01:37
https://github.com/ytdl-org/youtube-dl/issues/30434

**Closed** 2022-02-05 02:24 UTC
Labels: duplicate, question
