### ISSUE TITLE
Unable to download youtube-shorts

### ISSUE THREAD

**Issue by Akshayhuddar** [ytdl-org/youtube-dl#30874] opened 2022-04-20 06:38 UTC
Got this error while trying to download youtube shorts, is there any workaround for this.
>youtube-dl https://www.youtube.com/shorts/YrDJUtF54XE
>[youtube:tab] shorts: Downloading webpage
>ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  >https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-04-20 11:06
Duplicate of #30269; fixed in git master.

If you had used one of the relevant issue templates you would have been prompted thus:

>- [ ] I've searched the bugtracker for similar bug reports including closed ones

The search that you would have carried out would have revealed the original issue.

**Closed by dirkf** 2022-04-20 11:06 UTC
Labels: site-support-request, duplicate, fixed
