### ISSUE TITLE
Udemy.com HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>)

### ISSUE THREAD

**Issue by vikiaiteam** [ytdl-org/youtube-dl#22705] opened 2019-10-14 09:18 UTC
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2019.09.28**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
 C:\udemy-downloaded>youtube-dl -v -u xxx@gmail.com -p xxx --cookies C:\udemy-downloaded\udemy-cookies.txt -o "C:\udemy-downloaded\%(
playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s" https://www.udemy.com/course/academic-ielts-writing-task-1 
s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'C:\\udemy-downloaded\\udemy-cookies.txt', '-o', 'C:\\udemy-downloaded\\%(pl
aylist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s.%(title)s.%(ext)s', 'https://www.udemy.com/course/academic-ielts-writing-task-1', '--convert-subs', 'vtt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.7.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93640-ga087764847, ffprobe N-93640-ga087764847
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] course: Downloading webpage
[udemy:course] 2205064: Downloading course curriculum
[download] Downloading playlist: 2205064
[udemy:course] playlist 2205064: Collected 43 video ids (downloading 43 of them)
[download] Downloading video 1 of 43
[udemy] Downloading login popup
[udemy] 13580764: Downloading webpage
[udemy] 13580764: Downloading lecture JSON
[udemy] 13580764: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you ar
e using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python37\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE

**Comment by luizconrado** [comment] 2019-10-16 15:24
I have the exact same problem. Do we have any news about this bug?

**Comment by jeaye** [comment] 2019-10-28 18:19
This has been reported many times, but I haven't yet seen any info on it. I've tried with a cookies.txt file and also with manually specifying `-u` and `-p`. The cookies file gets further, as shown in the logs above, but only as far as seeing all of the videos to download. Once it tries downloading the first video, the 403 shows up again.

**Comment by Shineson1001** [comment] 2019-10-28 20:21
I have the same problem for many days. 
In the Meanwhile i use [udemy-dl](https://github.com/r0oth3x49/udemy-dl) (in a docker container). It works fine.

**Comment by mabdelghaniSP** [comment] 2019-11-03 18:19
I experienced the same issue from Git-bash and from the windows version.
Any help or updates?

**Comment by Darkcast** [comment] 2019-11-06 14:49
> I have the same problem for many days.
> In the Meanwhile i use [udemy-dl](https://github.com/r0oth3x49/udemy-dl) (in a docker container). It works fine.

That tool is also broken it doesnt download the videos either

**Comment by Shineson1001** [comment] 2019-11-06 19:27
> > I have the same problem for many days.
> > In the Meanwhile i use [udemy-dl](https://github.com/r0oth3x49/udemy-dl) (in a docker container). It works fine.
> 
> That tool is also broken it doesnt download the videos either

it works

root@nuc1:/opt/docker-udemydl # cat Dockerfile
FROM python:alpine

RUN apk add --no-cache --update gcc libc-dev libffi-dev openssl-dev git && \
 git clone https://github.com/r0oth3x49/udemy-dl.git && \
 cd udemy-dl && \
 pip install -r requirements.txt && \
 mkdir -p /course

VOLUME ["/course"]

ENTRYPOINT ["python", "/udemy-dl/udemy-dl.py", "-o", "/course"]


docker build -t xxx/your-udemy-dl-image:1.0 . --no-cache
docker run -it --rm -v $(pwd):/course --name tempudemy-dl xxx/your-udemy-dl-image:1.0 -u your-udemy-user -p your-udemy-password https://www.udemy.com/course/xxx

**Comment by davidhenley** [comment] 2019-12-10 22:48
@Darkcast  it works just fine

**Comment by MPW1412** [comment] 2019-12-13 08:31
403 looks like a missmatch in the Metadata. Which data does the udemy-dl script use?

**Comment by pavelloz** [comment] 2020-01-26 16:10
I tried to use gist instructions described here: https://gist.github.com/barbietunnie/8531d9c26cd1c0668e7278c7c4ba5853

But without success.

Heres what i got on current youtube-dl:

```
Downloads|⇒ youtube-dl --cookies cookie.txt https://www.udemy.com/course/hacking-real-websites-legally-2 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'cookie.txt', u'https://www.udemy.com/course/hacking-real-websites-legally-2', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
[udemy:course] 2664834: Downloading course curriculum
[download] Downloading playlist: 2664834
[udemy:course] playlist 2664834: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[udemy] 17022386: Downloading webpage
[udemy] 17022386: Downloading lecture JSON
[udemy] 17022386: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by pavelloz** [comment] 2020-01-26 16:17
@Shineson1001 

For some reason my docker doesnt like the line breaks in this dockerfile:

```
Sending build context to Docker daemon  2.048kB
Error response from daemon: Dockerfile parse error line 4: unknown instruction: GIT
```

Splitting them into multiple RUNs / joining them to one line solved the issue. Thanks for your input.

**Comment by jose1711** [comment] 2020-04-02 17:54
Same here, it dies in exactly same spot everytime I run it:
```
..
[download] Destination: 30318/3.03. Javascript Essentials/14.0303 Boolean Types And Comparison.mp4
[download] 100% of 3.05MiB in 00:00
[download] Downloading video 15 of 92
[udemy] 170627: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by petr-hybler** [comment] 2020-04-03 11:59
Hello guys same here ... any update? It would be helpful to fix it so we can watch those courses offline

OS: linux

`youtube-dl -u #myUsername# -p #MyPassword# https://udemy.com/course/the-ultimate-drawing-course-beginner-to-advanced/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://udemy.com/course/the-ultimate-drawing-course-beginner-to-advanced/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] course: Downloading webpage
[udemy:course] 874012: Enrolling in the course
[udemy:course] 874012: Downloading course curriculum
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by sebastianhritcu** [comment] 2020-04-21 16:38
Hi all,

The download will not work, because the course is not downloadable from the browser. You can check the api calls and search for "download_urls:" and you will see the value is set to null.

The new approach should be to check for the parameter "stream_urls:" and try to download the file.

api call example:
{
"stream_urls":
	{
	"Video":
		[
			{
			"type":"video/mp4",
			"label":"720",
			"file":"https:// bla bla bla"
			}
		]
	}
}

**Comment by darkRaspberry** [comment] 2020-04-24 08:22
I also have this error

**Comment by jadence** [comment] 2020-05-19 16:41
I was having the same 403 error despite purchasing the course. To fix it I did two things:
1) Clear my udemy cookies, log back into udemy.com, and then export a new `cookies.txt`
2) Changed the course URL from `https://www.udemy.com/course/<course_name>/` to `https://www.udemy.com/<course_name>/`

After the above two steps running `youtube-dl --cookies cookies.txt https://www.udemy.com/<course_name>/ --verbose` finally worked!

**Comment by petr-hybler** [comment] 2020-05-20 06:29
sorry ... even that does not work :(

**Comment by Shineson1001** [comment] 2020-05-20 16:53
hi @jadence,
thanks, it works.

**Comment by nbensa** [comment] 2020-05-21 14:17
> 2. Changed the course URL from `https://www.udemy.com/course/<course_name>/` to `https://www.udemy.com/<course_name>/`


This fixed it for me. I downloaded all the videos for the course I bought.

Thanks @jadence

**Comment by Anil86** [comment] 2020-06-11 21:13
@nbensa Can you share your youtube-dl command syntax?

**Comment by nbensa** [comment] 2020-06-11 21:27
@Anil86 
```
youtube-dl https://www.udemy.com/<course-name>/
```

HTH

**Comment by Anil86** [comment] 2020-06-11 21:32
I tried to generate cookie file using *EditThisCookie* chrome extension. But it shows following error:

`'cookies.txt' does not look like a Netscape format cookies file`

**Comment by nbensa** [comment] 2020-06-11 21:51
I used this extension: https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by jadence** [comment] 2020-06-11 22:34
> @jadence , @nbensa Can you share your full youtube-dl's _command syntax_?

@Anil86 - My command I used is `youtube-dl --cookies cookies.txt https://www.udemy.com/<course_name>/ --verbose`
notes:
• The `--verbose` flag almost certainly isn't necessary
• My `cookies.txt` was placed in the same directory I ran the above command in
• My `cookies.txt` file was generated using https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

Good luck!

**Comment by petr-hybler** [comment] 2020-06-13 02:23
guys what os and version of youtube-dl are you running ?? 

**My system**
Ubuntu: 20.04 LTS
Gnome: 3.36.2
youtube-dl: 2020-06-06

and your way simply does not work.. always returns 403 :(

**Comment by petr-hybler** [comment] 2020-06-13 04:27
holly crap it works now .. yes ... I uninstalled and reinstalled python and pip and it works now ...

**Comment by Ar-steve** [comment] 2020-06-14 21:36
> 
> 
> holly crap it works now .. yes ... I uninstalled and reinstalled python and pip and it works now ...

i need help doing what you did. :D i have been trying to download a few vids but i get the error thingy. pleas explain step by step im a noob :(

**Comment by khanu** [comment] 2020-06-24 14:27
Reinstalling python and pip doesn't sound like a viable option for me, gonna try reinstalling youtube-dl via brew to see if it helps

> holly crap it works now .. yes ... I uninstalled and reinstalled python and pip and it works now ...

**Comment by khanu** [comment] 2020-06-24 15:17
> I was having the same 403 error despite purchasing the course. To fix it I did two things:
> 
>     1. Clear my udemy cookies, log back into udemy.com, and then export a new `cookies.txt`
> 
>     2. Changed the course URL from `https://www.udemy.com/course/<course_name>/` to `https://www.udemy.com/<course_name>/`
> 
> 
> After the above two steps running `youtube-dl --cookies cookies.txt https://www.udemy.com/<course_name>/ --verbose` finally worked!

This 🥇

**Comment by Xonshiz** [comment] 2021-05-21 13:36
This seems to be broken now. Have been trying all the mentioned work-arounds, no luck.

**Comment by petr-hybler** [comment] 2021-05-21 13:48
> This seems to be broken now. Have been trying all the mentioned work-arounds, no luck.

arent u experiencing 403 instead? the one with amazon aws s3 storage? they recently migrated a lot of projects to aws and there is no way around atm :(

**Comment by Xonshiz** [comment] 2021-05-21 13:51
Could be that and I've been reading and saw that Udemy has introduced DRM (at least on their new content), so that could also be in the play. Not sure how much this info is on point...

**Comment by petr-hybler** [comment] 2021-05-21 14:03
> Could be that and I've been reading and saw that Udemy has introduced DRM (at least on their new content), so that could also be in the play. Not sure how much this info is on point...

wel check your --verbose output.. if you will see 403 on aws/s3 -> welcome to the club :(

**Comment by Xonshiz** [comment] 2021-05-21 14:19
I don't see any URL in my verbose output... It's failing on downloading login pop up itself...

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-F', '-i', 'https://www.udemy.com/ableton-live-11-course/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.9.5 (CPython) - macOS-11.3.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.5.16/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.5.16/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by petr-hybler** [comment] 2021-05-22 10:17
is your cookie correct? try to delete all cache in your browser.... log in to udemy again, use "export cookies" add on and export the cookie .... and try again with verbose pls

**Comment by Xonshiz** [comment] 2021-05-22 10:38
Did all of that already. That was my first guess... did a clean wipe off cookies on my browser. I've been using another tool "Udeler".. that seems to be downloading at least some courses, but, gets stuck whenever there's an attachment in the course.

**Comment by ThomasChr** [comment] 2021-05-31 05:35
Here is a recent Issue for the AWS Problem: https://github.com/ytdl-org/youtube-dl/issues/28877

**Comment by smaga38** [comment] 2021-07-19 13:31
> У меня была та же ошибка 403, несмотря на покупку курса. Чтобы исправить это, я сделал две вещи:
> 
> 1. Очистите мои файлы cookie udemy, снова войдите на udemy.com, а затем экспортируйте новый `cookies.txt`
> 2. URL курса изменен с `https://www.udemy.com/course/<course_name>/`на`https://www.udemy.com/<course_name>/`
> 
> После двух вышеуказанных шагов запуск, `youtube-dl --cookies cookies.txt https://www.udemy.com/<course_name>/ --verbose`наконец, сработал!

It worked for me too. Even without deleting cookies
Thank you!!

**Comment by 89z** [comment] 2022-04-23 20:25
Issue should be closed, account needed

**Comment by dirkf** [comment] 2022-04-27 12:43
Continued in #22306, closed as solved.

**Closed by dirkf** 2022-04-27 12:43 UTC
Labels: account-needed
