### ISSUE TITLE
yt short , download http link processing

### ISSUE THREAD

**Issue by emelhu** [ytdl-org/youtube-dl#31467] opened 2023-01-14 10:26 UTC
![ytdl-short](https://user-images.githubusercontent.com/7081135/212467427-025e75de-75e5-4555-9006-aed12db5878f.jpg)

## Checklist

- [X] I'm reporting a feature request
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2023-01-14 12:00
> I've searched the bugtracker for similar feature requests including closed ones

Why not?
Duplicate of #30269.

**Closed by dirkf** 2023-01-14 12:00 UTC
Labels: request
