### ISSUE TITLE
Why no now releases ?

### ISSUE THREAD

**Issue by bubul01** [ytdl-org/youtube-dl#31251] opened 2022-09-23 17:22 UTC
Since one year no new release, the autoupdate  feature in youtube dl don't work for me, i use now ytdlp, why annoying user like that ?

I know you'll close this forum because i ask a new relase and you dont want, ho i'm bad i d'ont respect the rule, !!!

Its not a problem i'll be blocked posting, github blocked my account simply saying they dont recognize my computer, but i'have correct password and user login , the next step is to block me because they don't recognize the capcha  or the email i use with the account ! 

## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by 89z** [comment] 2022-09-23 17:28
bad dog.

**Comment by dirkf** [comment] 2022-09-24 23:35
Duplicate of #31067.

**Closed by dirkf** 2022-09-24 23:35 UTC
Labels: duplicate, question

**Comment by 89z** [comment] 2022-09-24 23:41
With all due respect, I think forwarding people to a locked issue is a mistake. You need to give people a platform to discuss. If you don't want to listen to what they say in regards to this specific issue, thats totally fine. Just unsubscribe from the issue.

But to funnel people into a black hole is a shitty thing to do. Please don't misunderstand, I have grown to respect you, but I think this is a bad move.

**Comment by pukkandan** [comment] 2022-10-06 01:45
I recommend pointing users to https://github.com/ytdl-patched/youtube-dl until a new release can be made. Since all similar questions are being pointed to #31067, it would be beneficial to write a comment there and pin that issue
