### ISSUE TITLE
Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by johnlong21** [ytdl-org/youtube-dl#26807] opened 2020-10-04 15:44 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-thumbnail', '-o', '%(title)s-%(uploader)s.%(ext)s', '-x', '-f', 'bestaudio[ext=m4a]/bestaudio[ext=opus]', '--audio-quality', '0', '-v', 'https://www.youtube.com/watch?v=uvsYGauPoiQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-48-lowlatency-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/john/.local/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/john/.local/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2231, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.


```

## Description

as stated above in title, when i try to download a video that has playback on other websites disabled, i can not download the video.

**Comment by pukkandan** [comment] 2020-10-18 18:08
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/26652 and https://github.com/ytdl-org/youtube-dl/issues/26647

**Closed** 2021-01-08 11:24 UTC
