### ISSUE TITLE
"token"  not in video info

### ISSUE THREAD

**Issue by mhordagoda** [ytdl-org/youtube-dl#20764] opened 2019-04-24 00:28 UTC
tried to download https://www.youtube.com/watch?v=Vlbcd_lPNMA

ERROR: Vlbcd_lPNMA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by cinereous** [comment] 2019-04-24 00:31
Dupe of: https://github.com/ytdl-org/youtube-dl/issues/20758
(Temp?) Fix: https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882

**Closed** 2019-04-24 03:00 UTC
