### ISSUE TITLE
KeyError: 'QV'

### ISSUE THREAD

**Issue by chazmabry** [ytdl-org/youtube-dl#32315] opened 2023-06-16 22:06 UTC
## Checklist

- [x ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.2 (CPython) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

## Description

Will not download this link https://www.youtube.com/watch?v=a1NtdZbX9Wg

says this..
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
KeyError: 'QV'

**Comment by bcornec** [comment] 2023-06-17 00:00
I also tried with the master branch of today without more luck, same issue, similar stack trace

**Comment by cg2713** [comment] 2023-06-17 01:05
I have also gotten this error when downloading a ty link

**Comment by lodenrogue** [comment] 2023-06-17 01:45
Same issue happening for me on Mac

**Comment by JCMostwell** [comment] 2023-06-17 04:19
Exactly same here on macOS 13.4

**Comment by arizvisa** [comment] 2023-06-17 04:31
dupe of #32314.

**Comment by dirkf** [comment] 2023-06-17 11:40
>[x] I've searched the bugtracker for similar bug reports including closed ones

Really? Maybe the newest issue before yours?

**Closed by dirkf** 2023-06-17 11:40 UTC
