### ISSUE TITLE
Could a new release be created?

### ISSUE THREAD

**Issue by vsl7** [ytdl-org/youtube-dl#32244] opened 2023-05-28 06:44 UTC
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
The current version of youtube-dl is “unable to extract uploader ID”. If this problem is fixed, could a new release finally be created?

**Comment by dirkf** [comment] 2023-05-28 09:20
Duplicate of #31585.

**Closed by dirkf** 2023-05-28 09:20 UTC
Labels: question
