### ISSUE TITLE
[YouTube] Implement optional YouTube server-imposed throttling bypass

### ISSUE THREAD

**Issue by leveled-up** [ytdl-org/youtube-dl#28859] opened 2021-04-24 18:41 UTC
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.04.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

First of all, thanks for your amazing software 👍🏻 

Recently the following issue is occurring increasingly frequent: In some cases when downloading from YouTube (especially YT Music), the server throttles download speed to 58-60 KiB/s. (My internet connection however is stable and has a constant 4-6 MiB/s bandwith.) This happens in a pattern that I cannot describe more precisely right now. However it seems mostly random but associated to the download url from the extracted info_dict, since `--http-chunk-size` doesn't solve the issue but interrupting the download completely and immediately restarting (video is extracted again) solves the issue most of the time.

If nobody else can come up with another solution, I would recommend implementing a new CLI flag that will cause a check of the download speed against a threshold and will interrupt download and restart the extraction completely if the  download speed falls under the threshold (for some amount of time?).

I would be incredibly grateful for a workaround! :heart: I don't feel comfortable enough in Python to implement one myself and request a push... 😉

**Comment by fosam** [comment] 2021-04-25 14:18
I think i had the speeds go down to 30-40kb/s when i was downloading a playslist (videos) yesterday and the speed never go up again, i just close youtube-dl and run it again and then it continues again with the normal speeds, so this has been my workaround for this too, it seems like we are having the same issue, but i'm not exactly sure though.

**Comment by brentil** [comment] 2021-06-14 14:47
I've been experiencing this issue as well with getting my Watch Later videos using youtube-dl.  I noticed my scripts were taking an entire day to run instead of minutes.  I did a bunch of test runs and found that if I downloaded items rapidly at full speed I would start to get throttled by Youtube.  I tried implementing a variety of settings and finally found that randomizing time between shows and capping the speed kept me from being throttled for the last month.
`--sleep-interval 120 --max-sleep-interval 300 --limit-rate 4M`

Until today...  I stated getting some videos throttled again but at least unlike last time it was a couple of them and not all of them.  I've started expanding my minimum sleep interval to 200 to see if that helps.

**Comment by wajhk** [comment] 2021-06-14 14:50
في اثنين، 14 يونيو، 2021 في 5:48 م، كتب Leith Tussing <
***@***.***>:

**Comment by ewtoombs** [comment] 2021-11-02 06:26
After more experimentation, and some very helpful hints from `mech`, I have been able to reproduce the speeds that `mech` is capable of. I have found that two things are necessary to bypass throttling:

1. Use media links with `c` set to `ANDROID` instead of `WEB` in the query parameters. This would be easy, except for media links are signed, so they can't be edited. The only way I know of to get android media links is the same way mech does it: getting the `streamingData` from `POST /youtubei/v1/player` instead of from `var ytInitialPlayerResponse` in `GET /watch` and setting `clientName` to `ANDROID` (and setting a plausible `clientVersion`).
2. Download the data in chunks of around 10MB or less using a `range=<start>-<end>` query parameter or a `Range:` header. And yes, this is what `mech` does lol.

The user agent is unimportant.

I've written a short python demo of the throttling bypass:

```
#!/usr/bin/env python

from requests import Session
import json

def jprint(j):
    print(json.dumps(j, indent=4))

def api_key(response):
    from bs4 import BeautifulSoup
    import re
    soup = BeautifulSoup(response, 'html.parser')
    key = None
    for script_tag in soup.find_all('script'):
        script = script_tag.string
        if script is not None:
            match = re.search(r'"INNERTUBE_API_KEY":"([^"]+)"', script)
            if match is not None:
                key = match.group(1)
                break
    assert key is not None
    return key


id = 'yiw6_JakZFc'

session = Session()
session.headers = {
    # This is to demonstrate how little the user agent matters, and also for
    # fun.
    'User-Agent': 'Fuck you, Google!',
}

# Hit the /watch endpoint, but we actually only want an API key lol.
response = session.get(
    'https://www.youtube.com/watch',
    params={'v': id},
).content.decode()
key = api_key(response)

# OK, now use the API key to get the actual streaming data.
post_data = {
    'context': {
        'client': {
            'clientName': 'ANDROID',
            'clientVersion': '16.05',
        },
    },
    'videoId': id,
}
data = json.loads(session.post(
    'https://www.youtube.com/youtubei/v1/player',
    params={'key': key},
    data=json.dumps(post_data),
).content)

for f in data['streamingData']['adaptiveFormats']:
    if 'height' in f and f['height'] == 720:
        print(f['url']+'&range=0-10000000')
        break
```

**Comment by ewtoombs** [comment] 2021-11-05 01:08
I implemented the fix in [my youtube client](https://gitlab.freedesktop.org/ewtoombs/footube).

**Comment by porg** [comment] 2022-06-15 21:02
In the past I always got full download speed via youtube-dl.
Today when I used `youtube-dl` again after 1-2 years of not having used it, I was consistently throttling at ca. 50 KB/sec. Also after various stops and resumes. I use youtube-dl 2021.12.17 installed via brew on macOS 11.6.6.

I guess a good method to bypass throttling is to not download anonymously but as a logged in Google/Youtube user.
Hence making the use of cookies as easy and user friendly as possible would very likely help most users to overcome throttling.
`--cookie` is rather for technical users and requires much manual labor and extra software.
`--cookie-from-browser <MyPreferredBrowser>` on the other hand would be very convenient and practically.
Hence pull request https://github.com/ytdl-org/youtube-dl/pull/29201 should may be expedited in order to solve the throttling issue.

**Comment by porg** [comment] 2022-06-15 21:24
I confirm that `yt-dlp` 2022.5.18 in comparison to `youtube-dl` 2021.12.17  successfully bypasses the Youtube throttle!

- I just `cd` ed to another download destination directory, to avoid file overwriting.
- Copied the entire `youtube-dl` command line with all arguments and just exchanged it to `yt-dlp`.
- No cookies argument whatsoever.
- 👍 And bang. No throttle anymore. Full download speed again!

**Comment by ewtoombs** [comment] 2022-06-16 20:50
Looks like this was about to get fixed here: https://github.com/dirkf/youtube-dl/pull/6
Then, nothing happened. Also, looks like this is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/29326 .

**Comment by Elmar1991** [comment] 2022-06-16 22:10
Hello, did you solve the problem? and how did you do that?

**Comment by dirkf** [comment] 2022-06-16 22:21
The following merged PRs fix this issue:
* #30184
* #30366
* #30582
* #30585

To benefit from these you have to install from the git master until the useless sob maintainer makes a new release.

**Comment by gamer191** [comment] 2022-06-17 17:18
> To benefit from these you have to install from the git master until the useless sob maintainer makes a new release

I'm dying🤣

**Comment by gamer191** [comment] 2022-06-17 17:22
> the useless sob maintainer

legend has it he's the worst github maintainer since that Gamer191 guy tried to create a repository that's sole purpose was to host [a useless yt-dlp git diff](https://github.com/yt-dlp/yt-dlp/issues/2039#issuecomment-1067952588)

**Closed** 2022-07-12 21:23 UTC
