### ISSUE TITLE
SLOW SPEED FOR DOWNLOAD ANY VIDEO

### ISSUE THREAD

**Issue by ellipsiis** [ytdl-org/youtube-dl#30186] opened 2021-11-02 03:03 UTC
When I was downloades any video, the download speed is in range 49.05KiB/s and is have 5.75 MByte/s

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by uunnxx** [comment] 2021-11-02 03:54
Please, read other "slow speed issues" before creating an empty duplicate issue.

Check:
#30173 
#30162 
#30125 
#30052 

Or just use another fork, for example [this one.](https://github.com/yt-dlp/yt-dlp)

**Comment by 89z** [comment] 2021-11-02 03:57
I have an alternative tool that is fast:

~~~
PS C:\> youtube -a -1 -v 248 S61ENc51Z1Q
18% bytes=10000000-19999999 10.0 MB/s
37% bytes=20000000-29999999 10.0 MB/s
56% bytes=30000000-39999999 10.0 MB/s
75% bytes=40000000-49999999 10.0 MB/s
93% bytes=50000000-59999999 8.3 MB/s
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment] 2021-11-02 10:36
Specifically, duplicate of #29326, where solutions are provided.

**Comment by BachoSeven** [comment] 2021-11-02 11:17
yea please close this, there are way too many duplicates. Someone with access should pin the mentioned issue.

**Closed** 2021-11-02 16:38 UTC
