### ISSUE TITLE
 Unable to extract uploader id 

### ISSUE THREAD

**Issue by flbfilho** [ytdl-org/youtube-dl#31537] opened 2023-02-17 01:53 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
F:\Downloads>youtube-dl.exe --verbose https://www.youtube.com/watch?v=yk5K5NYwLxM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=yk5K5NYwLxM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube] yk5K5NYwLxM: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE
I don't really know what happened. One day it was working normally, the other doesn't matter what I do, it doesn't work. It is supposed to be a simple issue (update or uploaders id) but I couldn't solve it.

**Comment by Akshat752** [comment] 2023-02-17 03:10
Same issue for me.

**Comment by jrincayc** [comment] 2023-02-17 03:12
See #31538

**Comment by dirkf** [comment] 2023-02-17 11:03
Duplicate of #31530.

**Closed** 2023-02-17 11:03 UTC
Labels: duplicate

**Comment by JohnTRL** [comment] 2023-02-19 10:50
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`
