### ISSUE TITLE
Conversion fails on certain video where videostream has missing frame

### ISSUE THREAD

**Issue by etlam5123** [ytdl-org/youtube-dl#26860] opened 2020-10-10 20:44 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
.\external\youtube-dl.exe -C --cookies cookies.txt --no-mtime -o "downloads\%(upload_date)s [%(uploader)s] %(title)s (%(id)s).%(ext)s" --rm-cache-dir -4 --add-metadata --embed-subs --all-subs -f "(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best" -v --merge-output-format mkv https://www.youtube.com/watch?v=YV_tHOrufkw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-C', '--cookies', 'cookies.txt', '--no-mtime', '-o', 'downloads\\%(upload_date)s [%(uploader)s] %(title)s (%(id)s).%(ext)s', '--rm-cache-dir', '-4', '--add-metadata', '--embed-subs', '--all-subs', '-f', '(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '-v', '--merge-output-format', 'mkv', 'https://www.youtube.com/watch?v=YV_tHOrufkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Public IP address: 95.217.XXX.XXX
Removing cache dir C:\Users\Malte/.cache\youtube-dl ..
[youtube] YV_tHOrufkw: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] YV_tHOrufkw: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602383828/ei/dBuCX6e8I5H_yAWH7rrwBQ/ip/95.217.XXX.XXX/id/615fed1ceaee7e4c/source/youtube/requiressl/yes/playback_host/r6---sn-5goeen7d.googlevideo.com/mh/uo/mm/31%2C26/mn/sn-5goeen7d%2Csn-f5f7lnee/ms/au%2Conr/mv/u/mvi/6/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/mt/1602361563/fvip/6/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgdSXiQBazULin60luzEDqJCnWL530kKzG3kr0e04Oa5oCIQCOnl2DIgJsoXOoTndW-76pMw4Zv8OzENKOIlheh-DaQA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl/lsig/AG3C_xAwRgIhALdst4d3X4A3KaM4QRg7n0B_E2dDOQ0qKYLRyPSeFEziAiEA5WZM0QrIu5XnPArEVvaqjSaIx7q76MeUJjgHbxwlkvU%3D'
[dashsegments] Total fragments: 5
[download] Destination: downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm
[download] 100% of 4.92MiB in 00:01
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602383828/ei/dBuCX6e8I5H_yAWH7rrwBQ/ip/95.217.XXX.XXX/id/615fed1ceaee7e4c/source/youtube/requiressl/yes/playback_host/r6---sn-5goeen7d.googlevideo.com/mh/uo/mm/31%2C26/mn/sn-5goeen7d%2Csn-f5f7lnee/ms/au%2Conr/mv/u/mvi/6/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/vprv/1/mt/1602361563/fvip/6/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgdSXiQBazULin60luzEDqJCnWL530kKzG3kr0e04Oa5oCIQCOnl2DIgJsoXOoTndW-76pMw4Zv8OzENKOIlheh-DaQA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl/lsig/AG3C_xAwRgIhALdst4d3X4A3KaM4QRg7n0B_E2dDOQ0qKYLRyPSeFEziAiEA5WZM0QrIu5XnPArEVvaqjSaIx7q76MeUJjgHbxwlkvU%3D'
[dashsegments] Total fragments: 4
[download] Destination: downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm
[download] 100% of 262.52KiB in 00:00
[ffmpeg] Merging formats into "downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv"
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2065, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\postprocessor\ffmpeg.py", line 523, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

When trying to download the video https://www.youtube.com/watch?v=YV_tHOrufkw as seen in the log above, the conversion fails after the download of the audio and video stream has completed. When running the ffmpeg command manually, the following output is generated:

```
.\external\ffmpeg -y -loglevel "repeat+info" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv" -loglevel verbose
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 4
                    : Segment-Durations-Ms: 5333,5334,5333,4850,
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:00:20.90, start: -0.007000, bitrate: 102 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Output #0, matroska, to 'file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 4
                    : Segment-Durations-Ms: 5333,5334,5333,4850,
                    :
                    :
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame (VP90 / 0x30395056), yuv420p(tv, bt709/unknown/unknown), 1280x720 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, fltp, delay 312 (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'vp9_superframe'; args=''
[matroska @ 000001aba3cf6180] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
No more output streams to write to, finishing.
frame=  323 fps=0.0 q=-1.0 Lsize=    1378kB time=00:00:05.36 bitrate=2105.5kbits/s speed= 536x
video:1336kB audio:67kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Input file #0 (file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm):
  Input stream #0:0 (video): 323 packets read (1368175 bytes);
  Total: 323 packets (1368175 bytes) demuxed
Input file #1 (file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm):
  Input stream #1:0 (audio): 269 packets read (68512 bytes);
  Total: 269 packets (68512 bytes) demuxed
Output file #0 (file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv):
  Output stream #0:0 (video): 323 packets muxed (1368175 bytes);
  Output stream #0:1 (audio): 269 packets muxed (68512 bytes);
  Total: 592 packets (1436687 bytes) muxed
[AVIOContext @ 000001aba434c000] Statistics: 2 seeks, 7 writeouts
[AVIOContext @ 000001aba3ced080] Statistics: 1409024 bytes read, 0 seeks
[AVIOContext @ 000001aba3cec700] Statistics: 98304 bytes read, 0 seeks
Conversion failed!
```

The error hints that something is wrong with the frames of the video stream being processed. And indeed if you play the video stream webm in VLC media player, you can see a lost frame after approximately 320 frames in the statistics tab of the media information window. So it seems that the file fetched by youtube-dl is somehow corrupted.
I can't tell if this is an issue in youtube-dl with the fragments not being fetched correctly and stitched together or if wrong data is sent by the YouTube servers, which is why I'm raising this issue.
Hope my description is clear enough. Thanks.

**Comment by Feathered-Serpent** [comment] 2020-10-10 20:59
I think it must be something with your selected formats. When just doing the exe with the URL without all the options, I get a complete file without errors.

But I also getting streams 298 and 140, not 302 and 251 like yours, thus other codecs.

The file in the end has the following streams:
``
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.2
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 20 s 849 ms
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Title                                    : ISO Media file produced by Google Inc. Created on: 10/08/2020.
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 20 s 944 ms
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Title                                    : ISO Media file produced by Google Inc.
Language                                 : English
Default                                  : Yes
Forced                                   : No
``

**Comment by etlam5123** [comment] 2020-10-10 22:01
True, the default format selection of youtube-dl does not always download the best quality available, so I took that format code which I found on this reddit post: https://www.reddit.com/r/DataHoarder/comments/c6fh4x/after_hoarding_over_50k_youtube_videos_here_is/

What you are getting is 720p H.264 HFR with 128 Kbps AAC audio while my download gets 720p VP9 HFR with VBR ~160 Kbps OPUS audio. Similar codecs with similar or better quality at similar or smaller file sizes.
See this table for the different format codes: https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f

That format selection has worked very reliably so far for me and others, and the different codec should in theory not produce a broken video file.

**Comment by Feathered-Serpent** [comment] 2020-10-10 22:37
Hmm but wouldn't that mean, that ffmpeg has a bug and not the downloader? Because it only downloads the corresponding files.

mkvmerge doesn't have any problems joining the two temp files into a MKV file, which can be played without problems afterwards.

**Comment by etlam5123** [comment] 2020-10-11 00:43
It's not a bug in ffmpeg but normal behavior when it tries to parse a file that is considered corrupt or malformed. It doesn't really help that makemkv seems to work, since youtube-dl uses ffmpeg for that and I'm not aware that makemkv can be used natively instead.
The issue with the conversion is caused by the file in the first place having that one "broken" or "missing" frame as it is also recognized by VLC when playing back the webm file.
Since the frame seems to be at the exact point where the second DASH frame would begin (Segment-Durations-Ms: 5333, [...]), this leads me to believe that this _could be_ an issue with how youtube-dl downloads and saves the frames. But this could also be YouTube delivering the broken file. I'm gonna research and try some things tomorrow, but for now I can't tell.

**Comment by etlam5123** [comment] 2020-10-13 15:10
Without making any changes the download now seems to work fine for this video. Seems to be an issue on YouTube's end, but I wonder if a workaround can be added to youtube-dl for this issue. I'll report back if I find another video with the same issue.

```
.\external\youtube-dl.exe -C --cookies cookies.txt --no-mtime -o "downloads\%(upload_date)s [%(uploader)s] %(title)s (%(id)s).%(ext)s" --rm-cache-dir -4 --add-metadata --embed-subs --all-subs -f "(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best" -v --merge-output-format mkv https://www.youtube.com/watch?v=YV_tHOrufkw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-C', '--cookies', 'cookies.txt', '--no-mtime', '-o', 'downloads\\%(upload_date)s [%(uploader)s] %(title)s (%(id)s).%(ext)s', '--rm-cache-dir', '-4', '--add-metadata', '--embed-subs', '--all-subs', '-f', '(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '-v', '--merge-output-format', 'mkv', 'https://www.youtube.com/watch?v=YV_tHOrufkw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[debug] Public IP address: 95.217.XXX.XXX
Removing cache dir C:\Users\Malte/.cache\youtube-dl ..
[youtube] YV_tHOrufkw: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] YV_tHOrufkw: Downloading MPD manifest
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602622764/ei/zMCFX4OrGYLyyAX0t6SIBg/ip/95.217.XXX.XXX/id/615fed1ceaee7e4c/source/youtube/requiressl/yes/playback_host/r3---sn-4g5e6ns6.googlevideo.com/mh/uo/mm/31%2C29/mn/sn-4g5e6ns6%2Csn-axq7sn7e/ms/au%2Crdu/mv/m/mvi/3/pl/24/nh/%2CIgpwcjAzLmxlZDAzKgkxMjcuMC4wLjE/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1536250/vprv/1/mt/1602601015/fvip/10/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgORxG0cxsJKUEFVOqe185NLvqZ--z5MB6Fs9un9h_j7MCIAF3zGA7rLJe5e2KcfdIufJ5g7T3YH5P3vGPSkEEfs8B/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cnh%2Cinitcwndbps/lsig/AG3C_xAwRgIhAP9WIW00DVW5uUyh8b1ITFCbHgfNp0fNl_KeZGL8rf29AiEAvgSvEMys9awogOsVY4aOwKWB0VJlBx4X07iNvD34JBs%3D'
[dashsegments] Total fragments: 5
[download] Destination: downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm
[download] 100% of 4.94MiB in 00:06
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1602622764/ei/zMCFX4OrGYLyyAX0t6SIBg/ip/95.217.XXX.XXX/id/615fed1ceaee7e4c/source/youtube/requiressl/yes/playback_host/r3---sn-4g5e6ns6.googlevideo.com/mh/uo/mm/31%2C29/mn/sn-4g5e6ns6%2Csn-axq7sn7e/ms/au%2Crdu/mv/m/mvi/3/pl/24/nh/%2CIgpwcjAzLmxlZDAzKgkxMjcuMC4wLjE/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1536250/vprv/1/mt/1602601015/fvip/10/keepalive/yes/fexp/23915654/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgORxG0cxsJKUEFVOqe185NLvqZ--z5MB6Fs9un9h_j7MCIAF3zGA7rLJe5e2KcfdIufJ5g7T3YH5P3vGPSkEEfs8B/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cnh%2Cinitcwndbps/lsig/AG3C_xAwRgIhAP9WIW00DVW5uUyh8b1ITFCbHgfNp0fNl_KeZGL8rf29AiEAvgSvEMys9awogOsVY4aOwKWB0VJlBx4X07iNvD34JBs%3D'
[dashsegments] Total fragments: 4
[download] Destination: downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm
[download] 100% of 262.52KiB in 00:01
[ffmpeg] Merging formats into "downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv"
Deleting original file downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f302.webm (pass -k to keep)
Deleting original file downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).f251.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).mkv'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).mkv" -c copy -metadata "date=20201008" -metadata "description=" -metadata "purl=https://www.youtube.com/watch?v=YV_tHOrufkw" -metadata "comment=" -metadata "title=BUT I DID KIDNAP HIS WIFE" -metadata "artist=Posy" "file:downloads\20201008 [Posy] BUT I DID KIDNAP HIS WIFE (YV_tHOrufkw).temp.mkv"
[ffmpeg] There aren't any subtitles to embed
```

**Comment by tomasz1986** [comment] 2020-12-06 12:59
I have had the same issue very recently with quite a lot of videos. This only happens with VP9 streams. It seems that the files downloaded from YouTube are somewhat corrupted. When played with SMPlayer (mpv), there is no duration displayed, and the videos are unseekable.

Here are two examples from today.

https://youtube.com/watch?v=sH-efMgF2K8
https://youtube.com/watch?v=65w5RdydvJc

This command will lead to `ERROR: Conversion failed!`.

`youtube-dl youtube.com/watch?v=sH-efMgF2K8 --format bestvideo[ext=webm]+bestaudio[ext=webm]`

What is interesting is the fact that I downloaded the same videos a few months ago, and the streams were merged correctly then.

**Closed** 2020-12-06 14:09 UTC

**Comment by tomasz1986** [comment] 2020-12-06 14:24
Are you really unable to reproduce?

```
youtube-dl https://youtube.com/watch?v=sH-efMgF2K8 --format bestvideo[ext=webm]+bestaudio[ext=webm]
[youtube] sH-efMgF2K8: Downloading webpage
[youtube] sH-efMgF2K8: Downloading MPD manifest
[download] [BG2 -EE #4] Baldur's Gate Saga SCS Completionist Playthrough - Freedom Regained... Again-sH-efMgF2K8.f303.webm has already been downloaded
[download] 100% of 271.89MiB
[dashsegments] Total fragments: 219
[download] Destination: [BG2 -EE #4] Baldur's Gate Saga SCS Completionist Playthrough - Freedom Regained... Again-sH-efMgF2K8.f251.webm
[download] 100% of 30.98MiB in 00:22
[ffmpeg] Merging formats into "[BG2 -EE #4] Baldur's Gate Saga SCS Completionist Playthrough - Freedom Regained... Again-sH-efMgF2K8.webm"
ERROR: Conversion failed!
```

Is this working at your end?
