### ISSUE TITLE
Unable to download from nrk.no/nett-tv/bokstav/ (tv.nrk.no's archive)

### ISSUE THREAD

**Issue by MrDemocracy** [ytdl-org/youtube-dl#14105] opened 2017-09-02 20:30 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v http://www.nrk.no/nett-tv/klipp/787748/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.nrk.no/nett-tv/klipp/787748/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.13 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[NRKPlaylist] 787748: Downloading webpage
WARNING: unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: 787748
[NRKPlaylist] playlist 787748: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: 787748
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- **Front page: http://www.nrk.no/nett-tv/bokstav/**
- Single video: http://www.nrk.no/nett-tv/klipp/785988
- Chapter in Single video: http://www.nrk.no/nett-tv/indeks/278046
- Playlist (all episodes): http://www.nrk.no/nett-tv/prosjekt/146

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by josteink** [comment] 2017-09-03 11:24
I can reproduce this issue... Partially. But I'm not sure I would consider it a valid error report.

The URL you are linking to is clearly obsolete, and it even says so on the top. All new online TV from NRK is located at https://tv.nrk.no and this show in particular at this page: https://tv.nrk.no/serie/schrodingers-katt

And on the program-page there, you can see that this episode is not shown to be available.

Since I don't have flash player available... Are you saying the program is actually available via flash video on the old page?

**Comment by MrDemocracy** [comment] 2017-09-03 11:34
Yes, even though it's not available on the new nrk site, it is available in the archive. 
I'm not sure if it uses flash player though. 
The only updated browsers I have found working with the nrk archive site, is Safari with Silverlight or Internet Explorer with either Silverlight or WMP. You can change playback settings by clicking on "Innstillinger", at the top right.

**Comment by josteink** [comment] 2017-09-03 18:33
> Silverlight or WMP

I guess that settles my ability to help out from this Linux laptop :)

**Comment by MrDemocracy** [comment] 2017-09-03 20:06
I just figured out how to download it using VLC and Firefox:

- Open Firefox
- Open developer tools and goto the Network tab
- Select the "Media" filter
- Goto an episode page on the NRK archive and select WMP in settings at the top right on the page
- Download the asf file that appears in the developer tools network tab

<td>

- Open VLC
- Open the Streaming/Exporting Wizard
- "Transcode/Save to file"
- Add the asf file you just downloaded on "Select a stream"
- Enable audio and video
- Click next until you get to "finish"
- Double click the item that was just added to your VLC playlist
- Wait for the playback progress bar to reach the end
- Test the new transcoded file

**Comment by timofonic** [comment] 2017-09-05 05:34
@MrDemocracy So when is that asf file loaded? Is it shown without running Silverlight?

For Linux users: 
* [Pipelight](https://github.com/keithbowes/pipelight) (updated fork): You need to use wine-staging and Firefox with NPAPI support with (ESR?) it. If you don't trust it, run it in a sandboxed/virtualized environment ;)
* [Moonlight](https://github.com/ethus3h/moon-1) ("updated fork, not so sure): It's a reimplementation of Silverlight by the (Trojan Horse) Mono project.

**DISCLAIMER: I never used them**

**Comment by MrDemocracy** [comment] 2017-09-05 08:29
It's loaded when you load the page with WMP selected. It doesn't load if Silverlight is enabled. You can change this by clicking on the "Innstillinger" (settings) link in the top right of the page.

**Comment by barsnick** [comment] 2018-05-23 12:45
While I consider(ed) this request as totally valid, as the "arkiv" (archive) provided content not found on the standard modern day NRK site, all the given URLs are gone as of now, and so is the "arkiv", apparently. I cannot find *any* of its content anymore (apart from what seems to have migrated to the standard site).

**Comment by josteink** [comment] 2018-05-23 12:53
NRK has recently redone their whole web-tv offering "targeting a more modern user-base and use-cases".

This applies to the iOS and Android app, but also the web-frontend. From the bottom of the tv.nrk.no website:

![image](https://user-images.githubusercontent.com/411338/40425562-0680b5b4-5e99-11e8-8bfa-56c2ee8e0633.png)

If they're updating "everything", I find it entirely plausible that they've also removed previously obsolete versions in the process.

**Comment by barsnick** [comment] 2019-01-03 16:24
> While I consider(ed) this request as totally valid, as the "arkiv" (archive) provided content not found on the standard modern day NRK site, all the given URLs are gone as of now, and so is the "arkiv", apparently. I cannot find _any_ of its content anymore (apart from what seems to have migrated to the standard site).

I suggest closing this issue as invalid/outdated, as the given website no longer provides any content.

**Closed** 2020-02-19 23:07 UTC
