### ISSUE TITLE
history-channel relocates content

### ISSUE THREAD

**Issue by kmdawson** [ytdl-org/youtube-dl#23390] opened 2019-12-12 19:42 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--ap-mso', u'Comcast_SSO', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://play.history.com/shows/the-curse-of-oak-island/season-7/episode-6']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.17 (CPython) - Linux-5.3.15-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[generic] episode-6: Requesting header
[0;33mWARNING:[0m Falling back on generic information extractor.
[generic] episode-6: Downloading webpage
[generic] episode-6: Extracting information
[0;31mERROR:[0m Unsupported URL: https://play.history.com/shows/the-curse-of-oak-island/season-7/episode-6
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3347, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://play.history.com/shows/the-curse-of-oak-island/season-7/episode-6

```

## Description

history,com appears to have changed the location of their content from
'https://www.history.com/shows' to 'https://play.history.com/shows'.

The previous URL worked last week (2019-12-04), but does not work this week (2019-12-12). Upon playing in the browser, I discovered that the URL had changed.

**Comment by jlick** [comment] 2019-12-13 09:09
This is probably a duplicate of https://github.com/ytdl-org/youtube-dl/issues/23363 as all of the A&E properties seem to have migrated to a new player this week which breaks the youtube-dl extractor.

**Closed** 2020-12-06 18:50 UTC
