### ISSUE TITLE
I tried different url from Pluralsight and I am always receiving this message error "WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden - ERROR: No video formats found;

### ISSUE THREAD

**Issue by enriqueraso** [ytdl-org/youtube-dl#26210] opened 2020-08-02 06:32 UTC
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2020.07.28**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
C:\Users\enric\Desktop\Pluralsight>youtube-dl.exe https://app.pluralsight.com/library/courses/httpclient-consume-apis-dotnet-core/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://app.pluralsight.com/library/courses/httpclient-consume-apis-dotnet-core/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] httpclient-consume-apis-dotnet-core: Downloading JSON metadata
[download] Downloading playlist: Using HttpClient to Consume APIs in .NET Core
[pluralsight:course] playlist Using HttpClient to Consume APIs in .NET Core: Collected 90 video ids (downloading 90 of them)
[download] Downloading video 1 of 90
[pluralsight] e31c8b89-f660-468e-bbef-c1e98fc0304b-0: Downloading JSON metadata
[pluralsight] e31c8b89-f660-468e-bbef-c1e98fc0304b-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] e31c8b89-f660-468e-bbef-c1e98fc0304b-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] e31c8b89-f660-468e-bbef-c1e98fc0304b-0: Waiting for 4 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://vid.pluralsight.com/clips/resolution/59f3670b-eb10-49af-8f38-80a78b12e4e9/current/mp4/1280x720.mp4?hKRx7u1IjuR-Z5611m6r7ZMnJnwbbi-NbjiyujQQWtb7h56TNcpDhwvSvFr8vyfCJlUBaZ9l2FFXMrlRDV9Fqu9pRGF2Q3VACVYB20A9TGrzrbvt92pqX_32OHUvvBk3dy0Hlj3E7mKDWUEXWXSSihWv8zP4eQdJl_KZ50LueU9ZyoG62sXQEryVs2ai'
[download] Course Overview-59f3670b-eb10-49af-8f38-80a78b12e4e9.mp4 has already been downloaded
[download] 100% of 2.44MiB
[download] Downloading video 2 of 90
[pluralsight] ca1e711f-c46e-4fc6-9ed9-c6db39cd239d-0: Downloading JSON metadata
[pluralsight] ca1e711f-c46e-4fc6-9ed9-c6db39cd239d-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] ca1e711f-c46e-4fc6-9ed9-c6db39cd239d-0: Downloading mp4-high-widescreen viewclip JSON
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] ca1e711f-c46e-4fc6-9ed9-c6db39cd239d-0: Waiting for 5 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\pluralsight.py", line 421, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 1350, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE

I tried different URL from Pluralsight site and I am always receiving this message error "WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden" + "ERROR: No video formats found; "

**Comment by DigitalNotebook** [comment] 2020-11-28 03:55
What's the solution for this error?

**Comment by dirkf** [comment] 2022-02-07 12:32
Duplicate of #27991, now.

See #29234.

**Closed by dirkf** 2022-02-07 12:32 UTC
