### ISSUE TITLE
Is youtube-dl dead?

### ISSUE THREAD

**Issue by emcodem** [ytdl-org/youtube-dl#30267] opened 2021-11-24 21:19 UTC
A user of our forum 

https://ffastrans.com/frm/forum/viewtopic.php?f=6&t=1307

noticed us that there were no more changes in this repository since half a year which indicates that there is something wrong. He also pointed to a heavily maintained alternative: https://github.com/yt-dlp which seems to be a heavily maintained fork.
Is this original youtube-dl repository dead and should we maybe switch to the linked one?

**Comment by 89z** [comment] 2021-11-24 21:35
This issue has been posted many times. Please do not post duplicate issues.

**Comment by dirkf** [comment] 2021-11-24 23:44
Duplicate of (eg) #29965 where the issues are discussed at length (or ad nauseam, if you prefer).

**Comment by artenaki** [comment] 2021-11-25 19:47
Google shut down youtube-dl behind the scenes.

**Comment by 89z** [comment] 2021-11-25 19:49
@artenaki please dont make claims unless you have evidence to support it.

**Comment by Ashish0804** [comment] 2021-11-26 11:54
>Is youtube-dl dead?

No

**Comment by fcore117** [comment] 2021-12-02 14:46
> 

I do not see any fix or commits that backs this claim. From my standpoint yt-dlp is currently that is highly active for now until ytdl returns.

**Comment by dirkf** [comment] 2021-12-02 15:16
Either it's dead, or it might return ...

Probably the best answer in the context is that it's resting after a long squawk.

But this is still a **duplicate of #29965**.

**Comment by dirkf** [comment] 2022-01-29 16:47
Closed by #30568.

**Closed by dirkf** 2022-01-29 16:47 UTC
Labels: duplicate, question
