### ISSUE TITLE
FranceTV slash download impossible (HTTP Error 503)

### ISSUE THREAD

**Issue by greee-fr** [ytdl-org/youtube-dl#31121] opened 2022-07-28 18:08 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
VERBOSE LOG
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.france.tv/slash/drag-race-france/saison-1/3605305-bonjour-bonjour-bonjour.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.15.0-35-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[FranceTVSite] 3605305-bonjour-bonjour-bonjour: Downloading webpage
[FranceTV] 1189e328-8e88-4edd-985c-38bdcbed9074: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

DESCRIPTION 
I live en France (maybe the video is not available from another country ?) and want to download Drag Race France (show issue from Ru Paul Drag Race in USA)
But the download is impossible and ends with errors

**Comment by dirkf** [comment] 2022-07-28 22:21
503 would be fixed by back-porting from yt-dlp (duplicate of #29956), but this requires back-porting some infrastructure code as well.

However in this case yt-dlp finds no formats (from UK), so perhaps the show requires a login or maybe it's just that the manifests (mpd/m3u8) give 403 in the UK, or maybe the show is DRMed.

**Comment by greee-fr** [comment] 2022-07-31 13:13
I have already patch the file francetv.py in /usr/lib/python3/dist-packages/youtube_dl/extractor/ but I got same error
I just tried the fork https://github.com/yt-dlp/yt-dlp and it works with it
This is quite disappointed that youtube-dl don't have frequent update

**Closed** 2023-01-09 02:49 UTC
Labels: duplicate
