### ISSUE TITLE
Error on youtube shorts videos, and solution

### ISSUE THREAD

**Issue by houndmannn** [ytdl-org/youtube-dl#31026] opened 2022-06-13 22:30 UTC
I'm a complete newbie here, so, sorry if I'm repeating or not following the guidelines properly...
On trying to download the new-ish SHORTs category with youtube-dl (latest - 2021.12.17), I get this error "ERROR: Unable to recognize tab page;..." (complete output below).  
BUT a simple change to the URL has fixed the problem for at least 4 SHORTs URLs:
ERROR on https://youtube.com/shorts/KreMNfKqalg?feature=share
  is fixed by changing to 
https://www.youtube.com/watch?v=KreMNfKqalg
i.e.
1) replacing "shorts/" with  "watch?v="  (NO quotes)
2) deleting the ending "?feature=share" (again NO quotes)

BELOW is the complete youtube-dl --verbose output:

20220613-143125:.../XXX> youtube-dl  --verbose "https://youtube.com/shorts/KreMNfKqalg?feature=share"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://youtube.com/shorts/KreMNfKqalg?feature=share']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.5 (CPython) - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-103507-g70f06dd63c-tessus
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-06-13 23:16
Exactly, you discovered the work-around to be used until you install either the git master, or a future release based on it.

Duplicate of #30269.

**Closed by dirkf** 2022-06-13 23:16 UTC

**Comment by houndmannn** [comment] 2022-06-13 23:31
Ah, thanks Dirk!  Sorry to bother you.
Now I have to find the git master, "youtube-dl -U" hasn't worked for a while
