### ISSUE TITLE
Download fails on Viki.com but only one drama.

### ISSUE THREAD

**Issue by Heinzip** [ytdl-org/youtube-dl#28756] opened 2021-04-14 10:47 UTC
Hi,
I've already downloaded several dramas on Viki.com without problems and every time I updated youtube-dl. 
On one drama, youtube-dl throws an Error 400, though the drama can be watched without any restrictions (like Viki-Pass etc.). Other dramas on this website could be downloaded without issues.
Can you solve this problem? Thanks in advance.
Verbose is in txt-file.
[Verbose.txt](https://github.com/ytdl-org/youtube-dl/files/6310197/Verbose.txt)

**Comment by zackmark29** [comment] 2021-04-15 13:56
All Viki content already DRM Protected. 
480p might be available for download

**Comment by Heinzip** [comment] 2021-04-16 08:31
When all Viki content is DRM protected, why can I download many other dramas, but get the error only while downloading this special drama?
If 480p mioght be available, the error won't occur, or am I wrong?

**Comment by Heinzip** [comment] 2021-04-16 08:32
Oops, I clicked the wrong button...

**Comment by namia1** [comment] 2021-04-18 03:17
I can confirm another drama is throwing error 400, other newer things works just fine, hope someone can take a look, thanks.

E:\videodl>youtube-dl.exe https://www.viki.com/videos/1149766v --list-formats --cookies cookie.txt -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.viki.com/videos/1149766v', '--list-formats', '--cookies', 'cookie.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-03-28-git-8b2bde0494-full_build-www.gyan.dev
[debug] Proxy map: {}
[viki] 1149766v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by zackmark29** [comment] 2021-04-18 08:47
> I can confirm another drama is throwing error 400, other newer things works just fine, hope someone can take a look, thanks.
> 
> E:\videodl>youtube-dl.exe https://www.viki.com/videos/1149766v --list-formats --cookies cookie.txt -v
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://www.viki.com/videos/1149766v', '--list-formats', '--cookies', 'cookie.txt', '-v']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2021.04.07
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: ffmpeg 2021-03-28-git-8b2bde0494-full_build-www.gyan.dev
> [debug] Proxy map: {}
> [viki] 1149766v: Downloading video JSON
> ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
> File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5qwpsrl8\build\youtube_dl\YoutubeDL.py", line 2279, in urlopen
> File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
> File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
> File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
> File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
> File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

I told you already it's DRM Protected. They won't fix it

![image](https://user-images.githubusercontent.com/62680932/115139668-c14b2300-a065-11eb-9514-f54f0fd55bef.png)

**Comment by dirkf** [comment] 2022-02-04 15:13
In PR #30596, no login:
* https://www.viki.com/videos/1149766v - DRM

**Closed** 2022-02-04 15:49 UTC
