### ISSUE TITLE
Bandcamp support down

### ISSUE THREAD

**Issue by djvs** [ytdl-org/youtube-dl#26727] opened 2020-09-27 03:47 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl https://vypole.bandcamp.com/album/vy-pole
[Bandcamp:album] vy-pole: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: vy-pole
[Bandcamp:album] playlist vy-pole: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[Bandcamp] leftover: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Every bandcamp album download is broken, tested on multiple artists.  Verified in Firefox inspector there's just a single media stream coming down, looks like parser error

**Comment by JakeIrvine** [comment] 2020-09-27 08:38
I can confirm this is also broken for me, youtube-dl 2020.9.20 on termux android.

**Comment by tadeassoucek** [comment] 2020-09-27 10:43
I can confirm as well, youtube-dl 2020.09.06 on Manjaro Linux.

**Comment by iamleot** [comment] 2020-09-27 11:10
This is probably a duplicate of #26681.

**Comment by JDCourtney1969** [comment] 2020-10-07 19:14
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?  I am guessing it's a result of some changes made by people at Bandcamp....?     Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by tadeassoucek** [comment] 2020-10-08 16:46
@JDCourtney1969 Issues are your way of telling the developers of an application that something is broken, or asking questions.

You just commented on an existing issue. If you want your question answered, I'd recommend opening up a new issue [here](https://github.com/ytdl-org/youtube-dl/issues/new/choose). Select 'Bug Report' and you will be given instructions to follow. Best of luck!

**Comment by all3kcis** [comment] 2020-10-13 21:42
After some tests with https://regex101.com/ it seems ok with following regex
Does anyone can test that ?

https://github.com/ytdl-org/youtube-dl/blob/d65d89183f645a0e95910c3861491a75c26000eb/youtube_dl/extractor/bandcamp.py#L303
Replaced by  `<div[^>]*>(.*?<a[^>]+href="([^"]+?)"[^>]*>.*?)</div>`  


And :
https://github.com/ytdl-org/youtube-dl/blob/d65d89183f645a0e95910c3861491a75c26000eb/youtube_dl/extractor/bandcamp.py#L312
`item":{"name":"([^"]+)*"`
Test and work with :
```
<script type="application/ld json">
        {"datePublished":"15 Oct 2009 00:29:22 GMT","albumRelease":[],"name":"Of Porcelain","byArtist":{"name":"Of Porcelain","@id":"https://ofporcelain.bandcamp.com","@type":"MusicGroup"},"albumProductionType":"https://schema.org/StudioAlbum","genre":"https://bandcamp.com/tag/experimental","keywords":["Experimental","chill","downtempo","ooah","Los Angeles"],"@id":"https://ofporcelain.bandcamp.com/album/a-southern-summers-breeze","numTracks":10,"@type":"MusicAlbum","@context":"https://schema.org","image":"https://f4.bcbits.com/img/a3964058248_2.jpg","track":{"@type":"ItemList","itemListElement":[{"item":{"name":"A Portrait Of You","@id":"https://ofporcelain.bandcamp.com/track/a-portrait-of-you","@type":"MusicRecording","duration":"P00H02M13S"},"position":1,"@type":"ListItem"},{"item":{"name":"Gone Til Morning","@id":"https://ofporcelain.bandcamp.com/track/gone-til-morning","@type":"MusicRecording","duration":"P00H03M31S"},"position":2,"@type":"ListItem"},{"item":{"name":"Bleeding Mirrors Remix","@id":"https://ofporcelain.bandcamp.com/track/bleeding-mirrors-remix","@type":"MusicRecording","duration":"P00H05M32S"},"position":3,"@type":"ListItem"},{"item":{"name":"Carressing The Unknown","@id":"https://ofporcelain.bandcamp.com/track/carressing-the-unknown","@type":"MusicRecording","duration":"P00H06M40S"},"position":4,"@type":"ListItem"},{"item":{"name":"Here For Now","@id":"https://ofporcelain.bandcamp.com/track/here-for-now","@type":"MusicRecording","duration":"P00H05M09S"},"position":5,"@type":"ListItem"},{"item":{"name":"Remembering Self","@id":"https://ofporcelain.bandcamp.com/track/remembering-self","@type":"MusicRecording","duration":"P00H07M44S"},"position":6,"@type":"ListItem"},{"item":{"name":"Signal The Captain","@id":"https://ofporcelain.bandcamp.com/track/signal-the-captain","@type":"MusicRecording","duration":"P00H03M14S"},"position":7,"@type":"ListItem"},{"item":{"name":"The Greatest Distraction","@id":"https://ofporcelain.bandcamp.com/track/the-greatest-distraction","@type":"MusicRecording","duration":"P00H05M05S"},"position":8,"@type":"ListItem"},{"item":{"name":"You Are The Sun","@id":"https://ofporcelain.bandcamp.com/track/you-are-the-sun","@type":"MusicRecording","duration":"P00H05M12S"},"position":9,"@type":"ListItem"},{"item":{"name":"Gone Til Morning feat. Katie Gray","@id":"https://ofporcelain.bandcamp.com/track/gone-til-morning-feat-katie-gray","@type":"MusicRecording","duration":"P00H03M31S"},"position":10,"@type":"ListItem"}],"numberOfItems":10},"albumReleaseType":"https://schema.org/AlbumRelease","dateModified":"15 Oct 2009 04:20:37 GMT"}
    </script>
```

And :
https://github.com/ytdl-org/youtube-dl/blob/d65d89183f645a0e95910c3861491a75c26000eb/youtube_dl/extractor/bandcamp.py#L318
`album_title\s*"?:\s*"((?:\\.|[^"\\])+?)"`  
Test and work witth :
```
<script type="text/javascript" src="https://s4.bcbits.com/bundle/bundle/1/tralbum_head-11e51ed982b734419417bded4efee97f.fr.js" nonce="" data-cart="{"us_state":null,"currency":"USD","country_name":"États-Unis","is_default":false,"payment_type":null,"us_zip":null,"locale":"fr","country":"US","email":null}" data-fan="{"image_id":null,"name":null,"logged_in":false}" data-band="{"facebook_like_enabled":1,"id":556739587,"image_id":13145,"name":"Of Porcelain","has_discounts":false,"fan_email":"ooah@theglitchmob.com","account_id":4038619595}" data-payment="{"paymentType":null,"paymentDownloadPage":null}" data-embed="{"tralbum_param":{"value":2056483154,"name":"album"},"artist":"Of Porcelain","show_campaign":null,"linkback":"https://ofporcelain.bandcamp.com/album/a-southern-summers-breeze","embed_info":{"public_embeddable":"15 Oct 2009 00:29:22 GMT","exclusive_embeddable":null,"item_public":true,"no_track_preorder":false},"art_id":3964058248,"album_title":"A Southern Summer's Breeze","swf_base_url":"https://bandcamp.com"}" data-referrer-token=""nilZ0a2056483154x1602623808"" data-tralbum-collect-info="{"show_wishlist_tooltip":false,"show_collect":true}" data-tralbum="{"featured_track_id":1568283234,"url":"https://ofporcelain.bandcamp.com/album/a-southern-summers-breeze","preorder_count":null,"last_subscription_item":null,"id":2056483154,"playing_from":"album page","package_associated_license_id":null,"artist":"Of Porcelain","freeDownloadPage":"https://bandcamp.com/download?id=2056483154&ts=1602623808.366373752&tsig=628e64b1c7b0c6792f9fe1eb0f0250a2&type=album","defaultPrice":7.0,"is_preorder":false,"album_is_preorder":false,"is_purchased":null,"play_cap_data":null,"is_bonus":null,"has_discounts":false,"FREE":1,"client_id_sig":null,"album_release_date":"13 Oct 2009 00:00:00 GMT","tralbum_subscriber_only":false,"has_video":null,"items_purchased":null,"PAID":2,"hasAudio":true,"for the curious":"https://bandcamp.com/help/audio_basics#steal https://bandcamp.com/terms_of_use","trackinfo":[{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/5caa8485a4169b0de096d96dd654d240/mp3-128/2017404846?p=0&ts=1602710208&t=ec58ea04a8ba1175ab9176982fe4b43395952f00&token=1602710208_5dbf5b379564b02c4004c6ea14bffa14df18e91c"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":1,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"A Portrait Of You","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":2017404846,"video_poster_url":null,"unreleased_track":false,"encodings_id":2866566267,"track_license_id":null,"play_count":null,"is_draft":false,"duration":133.753,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/a-portrait-of-you","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":2017404846,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/950c6d5c432cb9dce740d6e634df9a3d/mp3-128/1907016944?p=0&ts=1602710208&t=c28a0eea186a79f54381db119b77a4407606ffbf&token=1602710208_323b1da6785319f4055beecb8df078054b0f3fc4"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":2,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Gone Til Morning","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":1907016944,"video_poster_url":null,"unreleased_track":false,"encodings_id":4145055478,"track_license_id":null,"play_count":null,"is_draft":false,"duration":211.2,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/gone-til-morning","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":1907016944,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/223f7db3b0bc7204c7d1d9d8627fd510/mp3-128/1970535879?p=0&ts=1602710208&t=0dba8a9723c05277386a6817443fa33094204243&token=1602710208_f1338c24891b0e578b5a3d0be899223bf148fc2f"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":3,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Bleeding Mirrors Remix","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":1970535879,"video_poster_url":null,"unreleased_track":false,"encodings_id":2538319397,"track_license_id":null,"play_count":null,"is_draft":false,"duration":332.055,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/bleeding-mirrors-remix","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":1970535879,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/e2adeeba6670c7fc4b50a0ca1679254d/mp3-128/747565141?p=0&ts=1602710208&t=d0c1eab752acb9dcf23eeccd0d73d3124798f86b&token=1602710208_0ca81f803fca831711521f354402a57c353a1d5a"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":4,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Carressing The Unknown","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":747565141,"video_poster_url":null,"unreleased_track":false,"encodings_id":219405565,"track_license_id":null,"play_count":null,"is_draft":false,"duration":400.0,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/carressing-the-unknown","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":747565141,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/1552908cd95da8b042c374915101a1fa/mp3-128/1274230040?p=0&ts=1602710208&t=889a96455536e7add9912e6aaf51b74afadc3bae&token=1602710208_329684a80a126f29b38e428ddf3514c14490e382"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":5,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Here For Now","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":1274230040,"video_poster_url":null,"unreleased_track":false,"encodings_id":1827666393,"track_license_id":null,"play_count":null,"is_draft":false,"duration":309.041,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/here-for-now","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":1274230040,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/931981bc50745c7019d296f7701efed0/mp3-128/3990815408?p=0&ts=1602710208&t=1408880b5565612726f1c3094211b12a8387ca52&token=1602710208_09c3ba43eefacf840b939bfbf7fe95026dafdfa4"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":6,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Remembering Self","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":3990815408,"video_poster_url":null,"unreleased_track":false,"encodings_id":3287794686,"track_license_id":null,"play_count":null,"is_draft":false,"duration":464.348,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/remembering-self","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":3990815408,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/072513f2e0e8d151cf662639444da80f/mp3-128/1568283234?p=0&ts=1602710208&t=8ef0c8a6366fb97784c83b23c86168d522b4d131&token=1602710208_55d7dc63dedd7f704712fb09eb8db558b599c334"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":7,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Signal The Captain","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":1568283234,"video_poster_url":null,"unreleased_track":false,"encodings_id":1564560356,"track_license_id":null,"play_count":null,"is_draft":false,"duration":194.585,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/signal-the-captain","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":1568283234,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/75540f4707fbbacabdfe1457d7d26299/mp3-128/3648723361?p=0&ts=1602710208&t=a1f362d9f7f519480be5560dd98d438bd82dde72&token=1602710208_49c62b9aa0a3dbde976c44ba8a33b160fd13c939"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":8,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"The Greatest Distraction","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":3648723361,"video_poster_url":null,"unreleased_track":false,"encodings_id":2589233550,"track_license_id":null,"play_count":null,"is_draft":false,"duration":305.116,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/the-greatest-distraction","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":3648723361,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/f3d4352743462770df4e8ca8d41e5b74/mp3-128/3033840971?p=0&ts=1602710208&t=0724afd6f5e450a28532a98ec2aa6adf7541de67&token=1602710208_71c7c6a1b80fb18a8a8471dc832bc789ee9db093"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":9,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"You Are The Sun","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":3033840971,"video_poster_url":null,"unreleased_track":false,"encodings_id":3875502426,"track_license_id":null,"play_count":null,"is_draft":false,"duration":312.805,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/you-are-the-sun","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":3033840971,"video_featured":null,"has_lyrics":false},{"video_source_type":null,"file":{"mp3-128":"https://t4.bcbits.com/stream/c920026b09e149bdf7e54c27017beadc/mp3-128/1323258418?p=0&ts=1602710208&t=7ac884be85602aca583b11f8f3683f5e35886443&token=1602710208_4ca6441ab733554cf57eeb386603412ee9f8348b"},"alt_link":null,"lyrics":null,"has_info":true,"video_source_id":null,"track_num":10,"encoding_error":null,"is_downloadable":true,"license_type":1,"title":"Gone Til Morning feat. Katie Gray","video_mobile_url":null,"album_preorder":false,"encoding_pending":null,"has_free_download":null,"track_id":1323258418,"video_poster_url":null,"unreleased_track":false,"encodings_id":148833875,"track_license_id":null,"play_count":null,"is_draft":false,"duration":211.278,"free_album_download":false,"private":null,"video_caption":null,"video_id":null,"title_link":"/track/gone-til-morning-feat-katie-gray","is_capped":null,"sizeof_lyrics":0,"streaming":1,"id":1323258418,"video_featured":null,"has_lyrics":false}],"packages":null,"art_id":3964058248,"licensed_version_ids":null,"is_private_stream":null,"initial_track_num":null,"use_expando_lyrics":false,"item_type":"album","is_band_member":null,"current":{"type":"album","art_id":3964058248,"require_email_0":null,"new_date":"15 Oct 2009 00:29:22 GMT","band_id":556739587,"audit":0,"upc":null,"selling_band_id":556739587,"title":"A Southern Summer's Breeze","set_price":5.0,"publish_date":"15 Oct 2009 00:29:22 GMT","mod_date":"15 Oct 2009 04:20:37 GMT","download_desc_id":null,"minimum_price_nonzero":null,"download_pref":2,"killed":null,"purchase_url":null,"new_desc_format":1,"about":null,"private":null,"auto_repriced":null,"artist":null,"minimum_price":0.0,"is_set_price":null,"id":2056483154,"featured_track_id":1568283234,"purchase_title":null,"credits":"written & produced by Josh Mayer aka Ooah","require_email":null,"release_date":"13 Oct 2009 00:00:00 GMT"}}" data-site="{"env":"prod","supportEmail":"support@ofporcelain.bandcamp.com","is_custom_domain":null}" data-band-follow-info="{"tralbum_type":"a","tralbum_id":2056483154}"></script>
```

**Closed** 2020-10-17 10:49 UTC

**Comment by 89z** [comment] 2021-12-02 16:01
https://github.com/ytdl-org/youtube-dl/issues/30306
