### ISSUE TITLE
YouTube: youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name (but the video does download)

### ISSUE THREAD

**Issue by Maia-Everett** [ytdl-org/youtube-dl#30883] opened 2022-04-22 07:38 UTC
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl -v "https://www.youtube.com/watch?v=Aw5XqnD6WwQ"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=Aw5XqnD6WwQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-5.13.0-40-generic-x86_64-with-Ubuntu-21.10-impish
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[youtube] Aw5XqnD6WwQ: Downloading webpage
[youtube] Aw5XqnD6WwQ: Downloading MPD manifest
[youtube] Aw5XqnD6WwQ: Downloading player 534c466c
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1514, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1487, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1470, in _extract_n_function_name
    jscode, 'Initial JS player n function name')
  File "/snap/youtube-dl/4630/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://rr1---sn-ov8vuxaxjvh-v8cl.googlevideo.com/videoplayback?expire=1650634353&ei=EVpiYvGiMoWhyAW61LWYDA&ip=5.128.243.91&id=o-ANPP78zOHlZpwbOzDVEOohnqVvBaEa_AsEx00oFNuLTx&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mh=SO&mm=31%2C29&mn=sn-ov8vuxaxjvh-v8cl%2Csn-n8v7znlr&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=19&initcwndbps=1573750&spc=4ocVC8nskdHytRZ-Abo2OQrdvqbQ&vprv=1&mime=video%2Fmp4&ns=UR7MdGlhE0wk_sywZ77hfn4G&gir=yes&clen=32606163&otfp=1&dur=117.366&lmt=1520938931983944&mt=1650612283&fvip=15&keepalive=yes&fexp=24001373%2C24007246&c=WEB&n=5KbcBBNu7gokaDANH&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMNu0GOsnct2DB6lhkT9dvWt74CvGPGWiKG1_jiR3O6YAiEAlVxj9swGnUOyHOCML50h94TecrAdwaNSYA1O-BJquA0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWAlj7E71lXT7K_PUPlWus9IUCjNL0GlOM5Cyzpq0eR8CIBsmOKGb0l5rg32giwuFDqcPjClwsSLF0PRytdr3piiT'
[download] Destination: [FFXIV OST] The Azim Steppe (Day)-Aw5XqnD6WwQ.f136.mp4
[download]   0.2% of 31.10MiB at 64.08KiB/s ETA 08:15
```

## Description

The above warnings are displayed for me when trying to download https://www.youtube.com/watch?v=Aw5XqnD6WwQ.

The video does download, but slowly.

**Comment by dirkf** [comment] 2022-04-22 09:53
There's no n-descrambling in the released 2021.12.17 version.

Your yt-dl must be an older patched version. You need to [update to the latest git master](https://github.com/ytdl-org/youtube-dl/issues/30871#issuecomment-1102666158).

Duplicate of #30856.

**Closed by dirkf** 2022-04-22 09:53 UTC

**Comment by unityconstruct** [comment] 2022-04-23 00:07
Confirming v2021.12.17 fixes the "n function name" issue....

_- still looking for any open tickets for the throttling games on YT ( showed up ~ 7-14d ago )
  - was running a custom build from 2021.06.06 with drop-in patch
  - pulled latest, but throttling still there..._ 


TRACE:
wget https://youtube-dl.org/downloads/latest/youtube-dl
youtube-dl https://www.youtube.com/watch?v=croh7Qo3x9k
[youtube] croh7Qo3x9k: Downloading webpage
[download] Resuming download at byte 3595369
[download] Destination: TWO DEITIES from the BIBLE - can U TELL the DIFFERENCE - podcast 1234-croh7Qo3x9k.f135.mp4
[download]   1.4% of 274.52MiB at 77.74KiB/s ETA 59:26^C
ERROR: Interrupted by user

$ youtube-dl --version
2021.12.17

**Comment by unityconstruct** [comment] 2022-04-23 00:16
nm.. found the thread & pulled master > make = happiness ensued

**Comment by dyura** [comment] 2022-06-22 23:02
I ran into the same problem on Ubuntu 21.10 with youtube_dl  2021.12.17. The problem is with the snap version.  Canonical installs the snap version with apt install. I took this error seriously because my download speed was low and the warning "Unable to decode n-parameter: download likely to be throttled" appeared. As advised in this thread, I downloaded youtube_dl directly from https://youtube-dl.org/downloads/latest/youtube-dl. This error was resolved. However, the download speed did not change. Still pretty low.

**Comment by dirkf** [comment] 2022-06-22 23:10
Youtube-dl doesn't have any explicit library dependencies so there's no reason to install it as a snap. What you thought was advice to install https://youtube-dl.org/downloads/latest/youtube-dl was actually suggesting to [install the program from this GitHub repository](https://github.com/ytdl-org/youtube-dl/issues/31032#issuecomment-1158490846).

**Comment by emacstheviking** [comment] 2023-04-03 07:29
Using a MacMini M1, brokwn for me as of 3rd Apr 2023.
I trued brew upgrade, downloaded directly from https://youtube-dl.org/downloads/latest/youtube-dl and also tried setting up a 3.10 venv and running as a module, all fail with the SAME error message:

```
(env) ➜  Downloads ./youtube-dl --verbose https://www.youtube.com/watch\?v\=EmQcQquj8Hs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=EmQcQquj8Hs']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.10 (CPython) - macOS-13.3-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EmQcQquj8Hs: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/x/Downloads/./youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/x/Downloads/./youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/x/Downloads/./youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/x/Downloads/./youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/Users/x/Downloads/./youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Not sure how to proceed, I'll check out the code I guess, maybe there are issues with a pop installation of that library for an M1 ? Woldn't be the first time I've had problems, pyscopg2 was a pain for a while.

**Comment by emacstheviking** [comment] 2023-04-03 08:19
RESOLVED: FOund the patched version , worked ok.
