### ISSUE TITLE
mixcloud fail

### ISSUE THREAD

**Issue by nhanphm** [ytdl-org/youtube-dl#22912] opened 2019-10-30 14:40 UTC
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2019.10.29**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
C:\Users\nhanp\Desktop\adb>youtube-dl -g https://www.mixcloud.com/thaihoangdj1991/vi%E1%BB%87t-mix-hot-nh%E1%BA%A5t-bxh-2020-anh-h%E1%BB%A9a-kh%C3%B4ng-bao-gi%E1%BB%9D-%C4%91ua-n%E1%BB%AFa-sai-l%E1%BA%A7m-c%E1%BB%A7a-anh-nh%E1%BA%ADt-kyo/
ERROR: Failed to extract matching stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\nhanp\Desktop\adb>youtube-dl -g -f best https://www.mixcloud.com/thaihoangdj1991/vi%E1%BB%87t-mix-hot-nh%E1%BA%A5t-bxh-2020-anh-h%E1%BB%A9a-kh%C3%B4ng-bao-gi%E1%BB%9D-%C4%91ua-n%E1%BB%AFa-sai-l%E1%BA%A7m-c%E1%BB%A7a-anh-nh%E1%BA%ADt-kyo/
ERROR: Failed to extract matching stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
C:\Users\nhanp\Desktop\adb>youtube-dl.exe -g https://www.mixcloud.com/nonstopvn99/nonstop-2018-nh%E1%BA%A1c-phi%C3%AAu-sml-vol1-nonstop-vn/
ERROR: Failed to extract matching stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mxmilkb** [comment] 2019-10-30 17:50
Duplicate of #22821

**Closed** 2019-10-30 18:40 UTC
