### ISSUE TITLE
 ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by LedsHack** [ytdl-org/youtube-dl#31655] opened 2023-02-22 22:16 UTC
- [no] I'm reporting a broken site support issue
- [yes ] I've verified that I'm running youtube-dl version **2021.12.17**
- [yes] I've checked that all provided URLs are alive and playable in a browser
- [yes] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [yes] I've searched the bugtracker for similar bug reports including closed ones
- [yes] I've read bugs section in FAQ

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - Linux-4.4.0-210-generic-x86_64-with-glibc2.23
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17
[debug] Proxy map: {}

![image](https://user-images.githubusercontent.com/41349194/220772125-0589d1c6-f1b0-4cb7-8d74-b1f16c347e6b.png)
link: https://youtu.be/5CRAvfENaic
ERROR: Unable to extract uploader id

**Comment by marcinserwer** [comment] 2023-02-22 22:26
You need to download the latest files then this error will go away. But there is a new bug because soon after playing music, an unknown error pops up and disables music playback

python3 -m pip install --force-reinstall -U https://github.com/ytdl-patched/ytdl-patched/releases/download/2023.02.19.1676776914/ytdl-patched.tar.gz

 python3 -m pip install --force-reinstall -U https://github.com/ytdl-patched/yt-dlp/releases/download/2023.02.22.810/yt-dlp.tar.gz
 
 python3 -m pip install --force-reinstall -U https://github.com/ytdl-patched/youtube-dl/releases/download/2023.02.22.114514/youtube-dl-2023.02.22.114514.tar.gz

**Comment by jbehre1973** [comment] 2023-02-22 23:26
I have the same error on windows 10 (see attached). How to patch youtube-dl here?
![youtube-dl-error-output](https://user-images.githubusercontent.com/114337800/220786355-3527d901-4f09-4a82-9bb9-b0b7f90ec319.png)

**Comment by telecomguyML** [comment] 2023-02-23 00:09
All of the information should be in https://github.com/ytdl-org/youtube-dl/issues/31530.  This issue will be closed when one of the mods come along since this is a duplicate of that issue.

**Comment by dirkf** [comment] 2023-02-23 00:10
> [yes] I've searched the bugtracker for similar bug reports including closed ones

But not well enough? #30839.

**Closed by dirkf** 2023-02-23 00:10 UTC

**Comment by dirkf** [comment] 2023-02-23 00:12
> But there is a new bug because soon after playing music, an unknown error pops up and disables music playback

Follow #30839 and open a new issue for this if appropriate. As yt-dl doesn't do any music playback, you may be seeing a problem with some package that invokes yt-dl.

**Comment by amit11jun** [comment] 2023-02-23 07:43
Previous  week it working fine but now I got **ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**
