### ISSUE TITLE
HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by AliBedaer** [ytdl-org/youtube-dl#24008] opened 2020-02-09 23:08 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.01.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-o', u'%(playlist_title)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', u'--verbose', u'https://app.pluralsight.com/library/courses/aws-developer-getting-started']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-28-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6
[debug] Proxy map: {}
[pluralsight:course] aws-developer-getting-started: Downloading JSON metadata
[download] Downloading playlist: AWS Developer: Getting Started
[pluralsight:course] playlist AWS Developer: Getting Started: Collected 68 video ids (downloading 68 of them)
[download] Downloading video 1 of 68
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

## Description

I'm trying to download a course from Pluralsight but I get this exception every time, username and password are provided

**Comment by Jeroen52** [comment] 2020-02-11 11:51
I'm experiencing the same issue.
A valid username and password is provided with access to the course.
```bash
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'--external-downloader=aria2c']
[debug] Custom config: []
[debug] Command-line args: [u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--sleep-interval', u'35', u'--max-sleep-interval', u'120', u'--sub-lang', u'en', u'--sub-format', u'srt', u'--write-sub', u'--verbose', u'https://app.pluralsight.com/library/courses/data-analysis-shiny-r-playbook/', u'--playlist-start', u'1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.24
[debug] Python version 2.7.16 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-debian-10.3
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1
[debug] Proxy map: {}
[pluralsight:course] data-analysis-shiny-r-playbook: Downloading JSON metadata
[download] Downloading playlist: Data Analysis with Shiny: R Playbook
[pluralsight:course] playlist Data Analysis with Shiny: R Playbook: Collected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by Jeroen52** [comment] 2020-02-11 12:24
One workaround that works is to use a cookies.txt file.
A working command that I use is this.
`youtube-dl --cookies "../cookies.txt" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" --sleep-interval 35 --max-sleep-interval 120 --all-subs --sub-format srt --write-sub --verbose https://app.pluralsight.com/library/courses/data-analysis-shiny-r-playbook`

**Comment by rojter-tech** [comment] 2020-03-04 09:29
> One workaround that works is to use a cookies.txt file.
> A working command that I use is this.
> `youtube-dl --cookies "../cookies.txt" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" --sleep-interval 35 --max-sleep-interval 120 --all-subs --sub-format srt --write-sub --verbose https://app.pluralsight.com/library/courses/data-analysis-shiny-r-playbook`

As soon as the credentials is specifed including the cookiefile has no effect, the error show up immediately after trying to log in. However if I do not specify credentials the first video can be downloaded in some (most) cases. Spended the whole night trying to figure out a proper way to establish client server relation, now it's time to have some rest. :)

**Comment by dRaiNe** [comment] 2020-03-26 09:48
I believe you receive 403 when you are flagged for scraping. If you're flagged, you will receive 403 with some fancy text even in the browser.
Also, if you mix downloading via youtube-dt then break some of their limits and then open browser - there is a window checking for 5 seconds if you're actually a web browser.
Additionally, sometimes if you download a lot via youtube-dl and then open the browser you're not banned yet, but if you click on any video it will be stuck in this 'loading video spinner'.
They employed some checks I guess.

**Comment by geffchang** [comment] 2020-04-05 02:36
> there is a window checking for 5 seconds if you're actually a web browser

Is there a captcha going on?

**Comment by aximili** [comment] 2020-04-07 03:48
> I believe you receive 403 when you are flagged for scraping. If you're flagged, you will receive 403 with some fancy text even in the browser.

That may be true. I was downloading successfully, and suddenly (an hour later) getting 403.
But in browser (incognito) it's all fine.
I logged in as fast as I could (I had auto complete so it was less than 5 seconds), it was successful, I didn't see any error.
Viewing videos are also smooth.

Any work around? :(

**Comment by jeehay** [comment] 2020-04-08 21:58
I'm getting same error, I can login and view the videos without any issue. On some course i am able to download but not all. for example I was download a course then stop and then try to dowload again same course i got 403 error.


[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', '%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', 
'--playlist-start', '1', '--verbose', '--min-sleep-interval', '90', '--max-sleep-interval', '130', 
'https://app.pluralsight.com/library/courses/commvault-virtualization-concepts-configuration/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] commvault-virtualization-concepts-configuration: Downloading JSON metadata
[download] Downloading playlist: Commvault® Virtualization
[pluralsight:course] playlist Commvault® Virtualization: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using 
the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by garchaaman19** [comment] 2020-04-12 12:08
could you help me please, I am getting the same 403 forbidden error. 
I have used this command

`youtube-dl --cookies "../cookies.txt" --username "garchaaman19@gmail.com" --password "aman@123"  --verbose --min-sleep-interval 60 --max-sleep-interval 120  "https://app.pluralsight.com/courses/web-application-penetration-testing-with-burp-suite"
`
And also I have tried another method in batch-file.txt I have mentioned the URL.

**Comment by jeehay** [comment] 2020-04-12 13:09
Please do not put your email and password. 

One thing does work for me on some course is that you login and view few coursing and then try to download it.

**Comment by garchaaman19** [comment] 2020-04-12 13:22
@jeehay Thanks I didnt notice it. Okay I will check if it works. 
I am using ubuntu. Should I try on windows ?

**Comment by jeehay** [comment] 2020-04-12 16:50
I'm on windows. 

Try this. 
View the course in browser, then save the cookies.txt file and also try to break the download into small for example. Put --playlist-start 1 and --playlist-end 10

The above has work for me even for course which didnt download.

**Comment by AbhieSpeaks** [comment] 2020-04-22 18:30
@jeehay Where do you find the cookies.txt file and where do you save it?

**Comment by Hrxn** [comment] 2020-04-22 19:40
@AbhieSpeaks You have to create the cookies.txt file for yourself. You can do that by using one of the browser extensions [1] to export your cookies from signed-in sites from your browser.
And then pass your cookies.txt file to youtube-dl by using the `youtube-dl --cookies "/path/to/your/cookies.txt` commmand-line option.





[1] https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/

**Comment by fullmerjf** [comment] 2020-04-23 22:22
I've tried the cookies and user-agent. It's still unsuccessful. Any other advice?

**Comment by jaimebl** [comment] 2020-04-23 23:23
> I've tried the cookies and user-agent. It's still unsuccessful. Any other advice?

There's just two ways to bypass this error: 
* avoid login by using cookies
* use Python 3.7 or 3.8

**Comment by fullmerjf** [comment] 2020-04-24 15:43
For the benefit of others struggling with this issue: I tried using username and password with youtube-dl and python-3.7.2. I made sure to install the python3 version of youtube-dl (pip3 install -U youtube_dl). This resulted in the same problem (403 on the login page).

I upgraded to python-3.8.2 (and re-ran pip3 install -U youtube_dl, for good measure). This fixed it for me. Now it's working! Thanks!

**Comment by habamax** [comment] 2020-04-24 19:29
@fullmerjf thx!

I had uninstalled scoop youtube-dl, upgraded python to 3.8.2 and `pip3 install -U youtube_dl` and issue has gone.

**Comment by jeehay** [comment] 2020-04-24 21:32
How can i make it work on Windows 10 machine. I cant install python 3.8.2 as its included in my youtube-dl.

**Comment by jeehay** [comment] 2020-04-24 21:49
> @fullmerjf thx!
> 
> I had uninstalled scoop youtube-dl, upgraded python to 3.8.2 and `pip3 install -U youtube_dl` and issue has gone.

This has work for me.


This is what I done on Windows 10
Download "python-3.8.2-amd64.exe" and install
once install open cmd and run "python -m pip install --upgrade pip"
then run "pip3 install -U youtube_dl"

Now i'm able to download the files without any issue.

**Comment by driesvanspauwen** [comment] 2020-04-25 13:30
> @AbhieSpeaks You have to create the cookies.txt file for yourself. You can do that by using one of the browser extensions [1] to export your cookies from signed-in sites from your browser.
> And then pass your cookies.txt file to youtube-dl by using the `youtube-dl --cookies "/path/to/your/cookies.txt"` commmand-line option.
> 
> [1] https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/

If i do that it gives the following error message:
http.cookiejar.LoadError: 'C:\\...\\cookies.txt' does not look like a Netscape format cookies file

What can I do about it?

**Comment by garchaaman19** [comment] 2020-04-25 14:09
@jeehay Thank you this method worked for me, at least for now I am able to download videos.
Thank you.

**Comment by garchaaman19** [comment] 2020-04-25 14:10
> > @fullmerjf thx!
> > I had uninstalled scoop youtube-dl, upgraded python to 3.8.2 and `pip3 install -U youtube_dl` and issue has gone.
> 
> This has work for me.
> 
> This is what I done on Windows 10
> Download "python-3.8.2-amd64.exe" and install
> once install open cmd and run "python -m pip install --upgrade pip"
> then run "pip3 install -U youtube_dl"
> 
> Now i'm able to download the files without any issue.
@jeehay Thank you this method worked for me, at least for now I am able to download videos.
Thank you.

**Comment by josephomorrow** [comment] 2020-04-26 17:41
I use Fedora linux.

I tried a variation of a solution posted in a closed discussion from a few years back:

From ~/ I typed:

rm -fR .cache/youtube-dl

Three downloads that had been "forbidden" for several days all downloaded successfully.

**Comment by brettalton** [comment] 2020-04-28 00:39
So I'm getting the same issue and [I found this old thread](https://github.com/ytdl-org/youtube-dl/issues/6451) that had a (temporary) solution waaay down.

Add this to your command,

```
--no-cache-dir
```

Worked for me with this command,

```
youtube-dl --verbose -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --no-cache-dir "YOUTUBE_LINK_HERE"
```

**Comment by marcelooblan2016** [comment] 2020-04-28 06:08
> bestvideo

thanks for this :)

**Comment by MrAliHD** [comment] 2020-04-28 09:08
> So I'm getting the same issue and [I found this old thread](https://github.com/ytdl-org/youtube-dl/issues/6451) that had a (temporary) solution waaay down.
> 
> Add this to your command,
> 
> ```
> --no-cache-dir
> ```
> 
> Worked for me with this command,
> 
> ```
> youtube-dl --verbose -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --no-cache-dir "YOUTUBE_LINK_HERE"
> ```

Thanks for the help, the (http error 403) did not come up again after using this

youtube-dl -f 299+140 --no-cache-dir https://youtu.be/Ea3Rksl3rOM

**Comment by xq8ed** [comment] 2020-05-01 03:53
> So I'm getting the same issue and [I found this old thread](https://github.com/ytdl-org/youtube-dl/issues/6451) that had a (temporary) solution waaay down.
> 
> Add this to your command,
> 
> ```
> --no-cache-dir
> ```
> 
> Worked for me with this command,
> 
> ```
> youtube-dl --verbose -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --no-cache-dir "YOUTUBE_LINK_HERE"
> ```

I did something similar to this
- First used `youtube-dl --rm-cache-dir`
- Then `youtube-dl -f videocode+audiocode URL`

**Comment by dirkf** [comment] 2022-02-07 12:37
Duplicate of #29776, now.

**Closed by dirkf** 2022-02-07 12:37 UTC
