### ISSUE TITLE
[ADN] Issue downloading premium episodes (with cookies)

### ISSUE THREAD

**Issue by perwwac** [ytdl-org/youtube-dl#17084] opened 2018-07-28 13:35 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
CASE 1 :
E:\Test>youtube-dl.exe -v --cookies E:\Test\cookies.txt  https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'E:\\Test\\cookies.txt', 'https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[ADN] 9148: Downloading webpage
[ADN] 9148: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\adn.py", line 137, in _real_extract
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

CASE 2 : 

E:\Test>youtube-dl.exe -v --cookies E:\Test\cookies.txt  https://animedigitalnetwork.fr/video/initial-d-saison-6-final-stage/8793-episode-1-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'E:\\Test\\cookies.txt', 'https://animedigitalnetwork.fr/video/initial-d-saison-6-final-stage/8793-episode-1-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[ADN] 8793: Downloading webpage
[ADN] 8793: Downloading JSON metadata
[ADN] 8793: Downloading JSON metadata
[ADN] 8793: Downloading m3u8 information
[ADN] 8793: Downloading JSON metadata
[ADN] 8793: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on '**https://free1.animedigitalnetwork.fr/1532809163-0-bc905392c3f411967b7067ea7d8d3c83/video0/playlist.m3u8**'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 164
[download] Destination: Initial D 6th Stage (Final Stage) - Épisode 1-8793.mp4
[download] 100% of 152.38MiB in 00:14

<end of log>


```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- CASE 1 Premium only Video : https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
- CASE 2 Free one : https://animedigitalnetwork.fr/video/initial-d-saison-6-final-stage/8793-episode-1-1

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hello,

First at all, sorry for my english.
I'm subscriber in ADN, and can stream any show in my web browser.
When I want to download a new episode, only available for premium user it fail with the CASE 1 logs.
I have put my cookies in the file "cookies.txt" and it seems to be loaded.

Then I've made another test, with one available for non-suscribed, it download fine, but only in low res (the one available for non subscribed people), it's my CASE 2.
In the debug lines for the case 2, it show that it grab the files on the "free" server.

Is there any special configuration for ADN i'm missing?

Thanks a lot in advance,

Perwac

**Comment by bato3** [comment] 2018-07-29 01:30
@perwwac Fix is pending to merge

**Comment by PierreC93** [comment] 2019-05-07 15:33
i need help to download premium episode ( i got an account ) and can help too

**Comment by JorisGit** [comment] 2019-07-20 11:53
@remitamine I can provide an account if it is necessary I see that there is a label for that.

**Comment by JorisGit** [comment] 2019-07-20 13:12
@remitamine Account sent by email

**Comment by remitamine** [comment] 2019-07-20 13:40
i can't reproduce, using cookies will allow to download premium only content and qualities(720p and 1080p):
without cookies:
```
youtube-dl -F https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
[ADN] 9148: Downloading webpage
[ADN] 9148: Downloading player config JSON metadata
[ADN] 9148: Downloading links JSON metadata
ERROR: ADN said: Vous devez être abonné pour accéder à ce contenu.
```
with cookies:
```
youtube-dl --cookies ~/Downloads/cookies.txt -F https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
[ADN] 9148: Downloading webpage
[ADN] 9148: Downloading player config JSON metadata
[ADN] 9148: Downloading links JSON metadata
[ADN] 9148: Downloading vostf mobile JSON metadata
[ADN] 9148: Downloading m3u8 information
[ADN] 9148: Downloading vostf sd JSON metadata
[ADN] 9148: Downloading m3u8 information
[ADN] 9148: Downloading vostf hd JSON metadata
[ADN] 9148: Downloading m3u8 information
[ADN] 9148: Downloading vostf fhd JSON metadata
[ADN] 9148: Downloading m3u8 information
[ADN] 9148: Downloading vostf auto JSON metadata
[ADN] 9148: Downloading m3u8 information
[info] Available formats for 9148:
format code   extension  resolution note
vostf-416     mp4        640x360     416k , avc1.4d001f, mp4a.40.2
vostf-2527-0  mp4        853x480    2527k , avc1.64001f, mp4a.40.2
vostf-2527-1  mp4        853x480    2527k , avc1.64001f, mp4a.40.2
vostf-6250-0  mp4        1280x720   6250k , avc1.640028, mp4a.40.2
vostf-6250-1  mp4        1280x720   6250k , avc1.640028, mp4a.40.2
vostf-9482-0  mp4        1920x1080  9482k , avc1.640029, mp4a.40.2
vostf-9482-1  mp4        1920x1080  9482k , avc1.640029, mp4a.40.2 (best)
```

**Comment by JorisGit** [comment] 2019-07-20 14:33
> 
> 
> i can't reproduce, using cookies will allow to download premium only content and qualities(720p and 1080p):
> without cookies:
> 
> ```
> youtube-dl -F https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
> [ADN] 9148: Downloading webpage
> [ADN] 9148: Downloading player config JSON metadata
> [ADN] 9148: Downloading links JSON metadata
> ERROR: ADN said: Vous devez être abonné pour accéder à ce contenu.
> ```
> 
> with cookies:
> 
> ```
> youtube-dl --cookies ~/Downloads/cookies.txt -F https://animedigitalnetwork.fr/video/one-piece/9148-episode-846-nami-et-zeus-le-cumulonimbus
> [ADN] 9148: Downloading webpage
> [ADN] 9148: Downloading player config JSON metadata
> [ADN] 9148: Downloading links JSON metadata
> [ADN] 9148: Downloading vostf mobile JSON metadata
> [ADN] 9148: Downloading m3u8 information
> [ADN] 9148: Downloading vostf sd JSON metadata
> [ADN] 9148: Downloading m3u8 information
> [ADN] 9148: Downloading vostf hd JSON metadata
> [ADN] 9148: Downloading m3u8 information
> [ADN] 9148: Downloading vostf fhd JSON metadata
> [ADN] 9148: Downloading m3u8 information
> [ADN] 9148: Downloading vostf auto JSON metadata
> [ADN] 9148: Downloading m3u8 information
> [info] Available formats for 9148:
> format code   extension  resolution note
> vostf-416     mp4        640x360     416k , avc1.4d001f, mp4a.40.2
> vostf-2527-0  mp4        853x480    2527k , avc1.64001f, mp4a.40.2
> vostf-2527-1  mp4        853x480    2527k , avc1.64001f, mp4a.40.2
> vostf-6250-0  mp4        1280x720   6250k , avc1.640028, mp4a.40.2
> vostf-6250-1  mp4        1280x720   6250k , avc1.640028, mp4a.40.2
> vostf-9482-0  mp4        1920x1080  9482k , avc1.640029, mp4a.40.2
> vostf-9482-1  mp4        1920x1080  9482k , avc1.640029, mp4a.40.2 (best)
> ```

Hmm my bad @remitamine , I had to do some manipulation by cloning the repo, change the value int in extractor/adn.py (line 76) and running this command:  ```python3 youtube-dl/youtube_dl/__main__.py --cookies ../cookies.txt --all-subs --skip-download -v https://animedigitalnetwork.fr/video/poco-s-udon-world/7599-episode-12-kake-udon```

But it works very well, thank you very much for the help I think you can close the issue!

**Closed** 2021-01-18 12:17 UTC
Labels: account-needed, cant-reproduce
