### ISSUE TITLE
Tele 5: Unable to extract jwplatform id

### ISSUE THREAD

**Issue by StSch** [ytdl-org/youtube-dl#30557] opened 2022-01-25 15:08 UTC
When I try to download a movie from Tele 5 (e.g. https://tele5.de/mediathek/american-psycho/) I get the following error:

youtube-dl --verbose https://tele5.de/mediathek/american-psycho/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://tele5.de/mediathek/american-psycho/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] Using fake IP 53.189.146.131 (DE) as X-Forwarded-For.
[Tele5] american-psycho: Downloading webpage
ERROR: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tele5.py", line 102, in _real_extract
    jwplatform_id = extract_id(JWPLATFORM_ID_RE, 'jwplatform id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tele5.py", line 91, in extract_id
    return self._html_search_regex(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract jwplatform id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 89z** [comment] 2022-01-25 15:15
Regional lockout:

> Error Code: access.denied.geoblocked

**Comment by StSch** [comment] 2022-01-25 15:19
Where do you see this? Any workaround?

**Comment by dirkf** [comment] 2022-01-25 16:14
Duplicate of #30499, pending PR #30532.

**Comment by spurkopf** [comment] 2022-01-26 10:22
Only for completion:
https://tele5.de/mediathek/american-psycho/
Is not protected with DRM. I could download it with
https://github.com/dirkf/youtube-dl/tree/f-tele5-discofy-Patch
.. but other films are protected with DRM.

**Comment by StSch** [comment] 2022-02-01 18:26
OK, if I got it right there is a patch for this issues on a separate branch. Who decides if it will be merged to master? When does this normally happy? And what do I have to do to test the patch? I have to checkout the branch, build the application and istall it? I am running youtube-dl in Windows' WSL.

**Closed** 2022-02-05 02:08 UTC
Labels: pending-fixes, duplicate

**Comment by StSch** [comment] 2022-02-12 06:57
So the PR has been merged to master. When will there be a new release so 'youtub-dl -U' will update the installation?
