### ISSUE TITLE
francetv. download “www.france.tv” online video temporarily failed.   Unable to download JSON metadata: HTTP Error 404.

### ISSUE THREAD

**Issue by snowmfx** [ytdl-org/youtube-dl#29957] opened 2021-09-13 13:31 UTC
log.
youtube-dl --write-sub --all-subs  --verbose  https://www.francetvinfo.fr/replay-jt/france-2/13-heures/jt-de-13h-du-lundi-13-septembre-2021_4748003.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-sub', '--all-subs', '--verbose', 'https://www.francetvinfo.fr/replay-jt/france-2/13-heures/jt-de-13h-du-lundi-13-septembre-2021_4748003.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffprobe git-2020-04-22-2e38c63
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:8580', 'https': 'https://127.0.0.1:8580', 'http': 'http://127.0.0.1:8580'}
[francetvinfo.fr] jt-de-13h-du-lundi-13-septembre-2021_4748003: Downloading webpage
[FranceTV] e951ac14-3e88-4874-8b3f-aa0355c49641: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); 
please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by lcheylus** [comment] 2021-09-13 14:06
Duplicate of #29956

**Comment by ruleps** [comment] 2021-09-13 14:24
Même problème.

**Closed** 2022-05-09 14:41 UTC
Labels: duplicate
