### ISSUE TITLE
Add support for Mako.co.il

### ISSUE THREAD

**Issue by shlomivman** [ytdl-org/youtube-dl#27523] opened 2020-12-23 22:20 UTC
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2020.12.22**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video stream: https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm

## Description

I want to get the m3u8 link in the following format example:
https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8?hdnea=st%3D1608761736%7Eexp%3D1608762636%7Eacl%3D%2F*%7Ehmac%3D31d3d505cf2096c47c16a11103d21affdce6e1d0445f23a58674fd2ec4aafdef

youtube-dl --verbose --add-metadata --cookies cookies.txt https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--add-metadata', '--cookies', 'cookies.txt', 'https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2020.12.22
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] VOD-6540b8dcb64fd31006: Requesting header
WARNING: Falling back on generic information extractor.
[generic] VOD-6540b8dcb64fd31006: Downloading webpage
[generic] VOD-6540b8dcb64fd31006: Extracting information
ERROR: Unsupported URL: https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\YoutubeDL.py", line 803, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\YoutubeDL.py", line 824, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmprhhzjl7r\build\youtube_dl\extractor\generic.py", line 3446, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm

**Comment by dstftw** [comment] 2020-12-27 14:23
Duplicate of #5734.

**Closed by dstftw** 2020-12-27 14:23 UTC
Labels: site-support-request
