### ISSUE TITLE
DMAX

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#31522] opened 2023-02-09 21:31 UTC
URL was fetched with this tool:
https://github.com/Brawl345/Get-DMAX-Links/blob/master/README.md

```
youtube-dl --verbose 'https://dplaydk.media-edge.prod-vod.h264.io/8cc8f4f2-3623-4b37-aac0-c514c8b3b9d9/hls_fairPlay_ts/edge-cache-token=Expires=1676064352&KeyName=media-edge-key-prod-eu-661a302&Signature=zPVvRnG9zYhp-WzfK2irsPi3kkKMPFVRe9QMCR21jTcvUdjRqiYNSss-3PhuLLcyoD9n2YL4C8act5emU3rgBA/master.m3u8'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://dplaydk.media-edge.prod-vod.h264.io/8cc8f4f2-3623-4b37-aac0-c514c8b3b9d9/hls_fairPlay_ts/edge-cache-token=Expires=1676064352&KeyName=media-edge-key-prod-eu-661a302&Signature=zPVvRnG9zYhp-WzfK2irsPi3kkKMPFVRe9QMCR21jTcvUdjRqiYNSss-3PhuLLcyoD9n2YL4C8act5emU3rgBA/master.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2453, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment] 2023-02-09 23:27
1. This isn't a URL that yt-dl would try to download from an actual DMAX video page, so it's unsurprising that it fails.
2. Because `.../hls_fairPlay_ts/...`.

Your show will not be playable in your browser with DRM disabled.

**Comment by Reiner1210** [comment] 2023-02-09 23:55
@dirkf and - do you want to fix it - in the browser it plays

**Comment by dirkf** [comment] 2023-03-01 23:38
Let us know if it plays in the browser when you disable DRM support (EME). Otherwise duplicate of #31472, whose instructions you didn't follow.

**Closed by dirkf** 2023-03-01 23:38 UTC
Labels: DRM
