### ISSUE TITLE
make one more release

### ISSUE THREAD

**Issue by ahalamgir16** [ytdl-org/youtube-dl#32570] opened 2023-09-26 03:12 UTC
As the last updated release is 2 years old, i think it is the high time to update the release . Please update  it

**Comment by nicolaasjan** [comment] 2023-09-26 04:39
Duplicate of #31585

**Comment by dirkf** [comment] 2023-09-26 09:18
Also, #30839! And https://github.com/ytdl-org/ytdl-nightly/releases.

**Closed by dirkf** 2023-09-26 09:18 UTC
Labels: request
