### ISSUE TITLE
Feature Request: Add ability to exclude youtbe playlists when downloading from whole channel

### ISSUE THREAD

**Issue by altimumdelta** [ytdl-org/youtube-dl#21283] opened 2019-06-02 11:10 UTC
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.05.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

If possible, there could be an ability exclude certain or more playlists when downloading from the whole youtube channel, some channels create smaller videos and don't put them all into a playlist, but they do have a playlist for longer "full-version" videos such as podcasts, and I have to separate the download script so I download the full ones which much lower video quality, no need for video quality if there's 2 heads talking in an office for 3 hours.

**Comment by dstftw** [comment] 2019-06-04 20:55
Duplicate of #8413.

**Closed by dstftw** 2019-06-04 20:55 UTC
Labels: request
