### ISSUE TITLE
getting Unable to extract uploader id, when trying to download a youtube video

### ISSUE THREAD

**Issue by vkscool** [ytdl-org/youtube-dl#31835] opened 2023-03-14 06:28 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

I am using the latest version of youtube-dl, currently it is not able to download any youtube video and failing with below error :- 
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by fwieringen** [comment] 2023-03-14 07:59
Duplicate of this https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by JohanvdS** [comment] 2023-03-14 09:24
same to me the problem

**Closed** 2023-03-14 10:13 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-03-14 10:19
Read #30839.
