### ISSUE TITLE
Https://diode.zone/ download fails

### ISSUE THREAD

**Issue by moeC137** [ytdl-org/youtube-dl#27586] opened 2020-12-30 14:38 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.29**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl -v https://diode.zone/videos/watch/f97feabf-e31f-4907-a580-766ae19b4ad7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://diode.zone/videos/watch/f97feabf-e31f-4907-a580-766ae19b4ad7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.12.29
[debug] Python version 3.8.6 (CPython) - Linux-5.8.18-1-MANJARO-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[PeerTube] f97feabf-e31f-4907-a580-766ae19b4ad7: Downloading video JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/peertube.py", line 549, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 1367, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

I tryed peertube-viewer-rs and every peertube instance works but diode.zone does not.
when trying with peertube-viewer-rs and not the raw youtube-dl i get this error:

[ytdl_hook] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                         
[ytdl_hook] youtube-dl failed: unexpected error occurred                                                                                                    
Failed to recognize file format.      

Possible related issues:
https://gitlab.com/peertube-viewer/peertube-viewer-rs/-/issues/34
https://github.com/ytdl-org/youtube-dl/issues/17368

**Comment by moeC137** [comment] 2020-12-30 17:30
i kinda found a fix:
this is the normal syntax:

youtube-dl -v https://diode.zone/videos/watch/**ee34bde1-e0a3-428d-9939-2d7690845750** 

it dosent work.

here is the syntax that does work:
youtube-dl -v https://diode.zone/static/streaming-playlists/hls/**ee34bde1-e0a3-428d-9939-2d7690845750**/master.m3u8 

for **bold** just swap in the video id you want to download

so i assume the peertube.py extractor here https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/peertube.py needs to implement that syntax.

this would fix diode.zone on all youtube-dl based clients.

**Comment by Sosthene-Guedon** [comment] 2020-12-30 19:11
I think this is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/26002

**Closed** 2021-01-08 20:09 UTC
