### ISSUE TITLE
Downloading extremely slow and unsuccessful

### ISSUE THREAD

**Issue by 3776365hong** [ytdl-org/youtube-dl#30827] opened 2022-04-06 17:27 UTC
Hello, I am attempting downloading several videos using youtube-dl this night but noticed that the downloading speed is extremely slow (around 50-70kib/s). I also searched some images of youtube-dl's CUI when the downloads were normal, and noticed that the warning 'Downloading video info webpage' is missing. I tried several videos and the results are the same.
![Screenshot 2022-04-07 030752](https://user-images.githubusercontent.com/88353199/162032222-2c334e21-8ba9-4d7c-9fdb-c3ae5d416ad8.png)
I then tried to download a relatively short video and wait it to be finished, then I received ERROR message like this:
![Screenshot 2022-04-07 032509](https://user-images.githubusercontent.com/88353199/162032825-d3859406-5e74-4806-b364-109e29eb698c.png)
I searched for hours to find the reason but still cannot figure out what is going on. Is it due to wrong configurations of ffmpeg, or due to some sever problem?

**Comment by 89z** [comment] 2022-04-06 17:29
please dont post duplicate issues

**Comment by dirkf** [comment] 2022-04-06 17:49
Please use the support template. You found a problem, perhaps with the site, or perhaps a more general issue that might be a bug.

Let's try the [Bug report template](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=4_bug_report.md):

---



## Checklist



- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ


## Verbose log



```
PASTE VERBOSE LOG HERE
```


## Description



WRITE DESCRIPTION HERE

----

>- [x] I'm reporting a broken site support issue

Let's say yes for now.

>- [x] I've verified that I'm running youtube-dl version **2021.12.17**

That's probably true because YT made a change that crashed the earlier versions.

>- [x] I've checked that all provided URLs are alive and playable in a browser

Let's say yes. If it wasn't true, you should have checked as asked.

>- [ ] I've checked that all URLs and arguments with special characters are 
properly quoted or escaped

No. Oh look, that explains the error message about `t`. Windows _cmd_ (and POSIX shell) splits commands at `&`. The URL needs to be inside double quotes (single quotes preferred for POSIX).

>- [ ] I've searched the bugtracker for similar bug reports including closed ones

Wow. There are oodles of issues about slow downloads from YouTube, and reading them shows that the issue is fixed in the git master. There is even advice about how to update your Windows yt-dl installation from the GitHub master branch while waiting for the lackadaisical maintainer to get a release out.

>- [ ] I've read bugs section in FAQ

That's now only needed to improve your mind before closing or cancelling the issue.

**Closed by dirkf** 2022-04-06 17:49 UTC

**Comment by mrkapqa** [comment] 2022-04-12 11:29
hello , i am also getting slow downloads around 50kbps, and sometimes it says
`weekly report 04_11_2022.mp4
[download]   1.4% of 17.02MiB at 61.93KiB/s ETA 04:37[download] Got server HTTP error: Downloaded 258723 bytes, expected 17844683 bytes. Retrying (attempt 1 of 10)...
`

**Comment by dirkf** [comment] 2022-04-12 11:35
As above:
>... There are oodles of issues about slow downloads from YouTube, and reading them shows that the issue is fixed in the git master. There is even advice about how to update your Windows yt-dl installation from the GitHub master branch while waiting for the lackadaisical maintainer to get a release out.

`ERROR: Did not get any data blocks` means your network connection is broken in some way.
