### ISSUE TITLE
Unsupported URL (https://motherless.com/D63BB1F)

### ISSUE THREAD

**Issue by tmblrxaos** [ytdl-org/youtube-dl#31128] opened 2022-08-02 11:53 UTC
## Checklist

- [ ] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://motherless.com/D63BB1F

## Description

```
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://motherless.com/D63BB1F'

[Motherless] D63BB1F: Downloading webpage
ERROR: Unable to extract uploader_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://motherless.com/0001DE4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.5 (CPython) - macOS-11.6.8-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1, ffprobe 5.1, rtmpdump 2.4
[debug] Proxy map: {}
[Motherless] 0001DE4: Downloading webpage
ERROR: Unable to extract uploader_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/motherless.py", line 129, in _real_extract
    uploader_id = self._html_search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment] 2022-08-02 13:22
There are two factors to this problem:
1. the site has a new version and the field that was being targeted for `uploader_id` is no longer there;
2. the extraction of `uploader_id` crashes the extractor because of a coding error.

Use `--add-header 'Cookie: _force_desktop_v1=true'` to get the old site until someone updates the extractor.

**Comment by dirkf** [comment] 2022-08-02 13:45
The `uploader_id`  can be found in the new site with the same basic pattern, but changing `thumb-member-username` in the pattern to `(?:thumb-member-username|media-meta-member)`.

Anyone updating the extractor should run the tests to ensure that other metadata is still being correctly extracted.

**Comment by dirkf** [comment] 2022-10-11 21:21
Fixed in https://github.com/ytdl-org/youtube-dl/commit/82e4eca711a128138ed0b84ddb4321e403d56340

**Closed by dirkf** 2022-10-11 21:21 UTC
Labels: broken-IE

**Comment by Vangelis66** [comment] 2022-10-11 21:53
This is, in all probability, a dupe of #29626 (which should also be closed).
