### ISSUE TITLE
"WARNING: Unable to extract video title" and no title filenames.

### ISSUE THREAD

**Issue by antdude** [ytdl-org/youtube-dl#21934] opened 2019-07-29 22:32 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2019.07.27**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$  youtube-dl -v https://www.youtube.com/watch?v=BN6ui0xl15M                                                        
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=BN6ui0xl15M                                                        ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 2.7.15 (CPython) - Linux-4.20.8-200.fc29.x86_64-x86_64-wi                                                        th-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.4, ffprobe 4.0.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BN6ui0xl15M: Downloading webpage
[youtube] BN6ui0xl15M: Downloading video info webpage
WARNING: Unable to extract video title
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r6---sn-n4v7sn7z.googlevideo.com/videop                                                        layback?expire=1564461005&ei=bXM_XZJzuM2P7w-muY7oBg&ip=2001%3A470%3Ac%3Af7a%3A%3                                                        A2&id=o-AM3m3kCj0PcjurxjQkiDmx07qXRtYPD3JXpkzkmRj_Zb&itag=137&aitags=133%2C134%2                                                        C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requir                                                        essl=yes&mm=31%2C26&mn=sn-n4v7sn7z%2Csn-a5msen76&ms=au%2Conr&mv=m&mvi=5&pl=46&in                                                        itcwndbps=441250&mime=video%2Fmp4&gir=yes&clen=31569034&dur=94.999&lmt=156439595                                                        8759136&mt=1564439354&fvip=5&keepalive=yes&c=WEB&txp=2316222&sparams=expire%2Cei                                                        %2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AL                                                        gxI2wwRQIgCmBVmBR32bqzA8UoFlvDy6nCEMY6foBdPcKSJmbj7rMCIQD__0aOZIMucVda_-NAwnyGjM                                                        te-NWl_jgFfALQbMSprw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&l                                                        sig=AHylml4wRQIgBNZAYS3PL-0XF23iwu3FrgJn_byJE-0375Gsml62DLYCIQC1ztiquewWlLFRi3CT                                                        7e1d47VHM16P9g1gAmvOJHxHZw%3D%3D&ratebypass=yes'
[download] Destination: _-BN6ui0xl15M.f137.mp4
[download] 100% of 30.11MiB in 00:04
[debug] Invoking downloader on u'https://r6---sn-n4v7sn7z.googlevideo.com/videop                                                        layback?expire=1564461005&ei=bXM_XZJzuM2P7w-muY7oBg&ip=2001%3A470%3Ac%3Af7a%3A%3                                                        A2&id=o-AM3m3kCj0PcjurxjQkiDmx07qXRtYPD3JXpkzkmRj_Zb&itag=140&source=youtube&req                                                        uiressl=yes&mm=31%2C26&mn=sn-n4v7sn7z%2Csn-a5msen76&ms=au%2Conr&mv=m&mvi=5&pl=46                                                        &initcwndbps=441250&mime=audio%2Fmp4&gir=yes&clen=1539549&dur=95.062&lmt=1564395                                                        949449252&mt=1564439354&fvip=5&keepalive=yes&c=WEB&txp=2311222&sparams=expire%2C                                                        ei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AL                                                        gxI2wwRgIhAJi6aBJE9i3UuI14-yB4c2uTrHxL9ys4lUD-ZdSypWmJAiEApo32Rerwnl8wRytSs1FYSr                                                        zsH-EBLfUDCBv06Jv9sD8%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsi                                                        g=AHylml4wRQIgBNZAYS3PL-0XF23iwu3FrgJn_byJE-0375Gsml62DLYCIQC1ztiquewWlLFRi3CT7e                                                        1d47VHM16P9g1gAmvOJHxHZw%3D%3D&ratebypass=yes'
[download] Destination: _-BN6ui0xl15M.f140.m4a
[download] 100% of 1.47MiB in 00:00
[ffmpeg] Merging formats into "_-BN6ui0xl15M.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:_-BN6ui0                                                        xl15M.f137.mp4' -i 'file:_-BN6ui0xl15M.f140.m4a' -c copy -map '0:v:0' -map '1:a:                                                        0' 'file:_-BN6ui0xl15M.temp.mp4'
Deleting original file _-BN6ui0xl15M.f137.mp4 (pass -k to keep)
Deleting original file _-BN6ui0xl15M.f140.m4a (pass -k to keep)
```

## Description

It looks like Google/YouTube just broke youtube-dl to have no filenames from titles anymore. I see it in two different Linux boxes (my Debian/Jessie v8 and my friend's Fedora).

**Comment by marabu88** [comment] 2019-07-29 22:39
In Windows 10 also...

**Comment by TheERaichu** [comment] 2019-07-29 22:39
I thought it was just me. I updated too but that didn't fix it.

**Comment by richardstevenhack** [comment] 2019-07-29 22:52
I can confirm. I'm running the latest July 27 version. The failure occurred first in Youtube-dl GUI and I reproduced the error from the command line version.

The download occurs, but there is no file name or just an "fxx' type file name and the post-processing (in the GUI) reports either "error" or warning.

I assume Youtube has done something to break the video title reporting.

Example:
` youtube-dl -v https://www.youtube.com/watch?v=OzLAxuD3Vfo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=OzLAxuD3Vfo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.27
[debug] Python version 3.6.5 (CPython) - Linux-4.12.14-lp151.28.10-default-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[youtube] OzLAxuD3Vfo: Downloading webpage
[youtube] OzLAxuD3Vfo: Downloading video info webpage
WARNING: Unable to extract video title
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r2---sn-a5msen76.googlevideo.com/videoplayback?expire=1564462157&ei=7Hc_XfypN8uTkgbnwbTwBA&ip=173.244.36.76&id=o-ANhETEvFQVXb2DnfoRGzcLWgh2Ulh5duSser3CXQ8sqn&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-a5msen76%2Csn-a5meknlz&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1006250&mime=video%2Fmp4&gir=yes&clen=206054729&dur=491.040&lmt=1564317791038347&mt=1564440439&fvip=2&keepalive=yes&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAOe2c6YZWccugRtXrceI4_F3chB48_QIVdUKanpTNowjAiAn4BfuI02baUwD_D6LxNx5uQqPjYFTznS538PbQYsHrw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgRZI0_urwiGJnRr12Ofi08AZL_U2J3AV6cuTM3m_dHxQCIQC4b5KfXp0hXB3jlHiA0vshe999sHWShSKOQ8wry9ME-g%3D%3D&ratebypass=yes'
[download] Resuming download at byte 45483989
[download] Destination: _-OzLAxuD3Vfo.f137.mp4
[download] 100% of 196.51MiB in 01:20
[debug] Invoking downloader on 'https://r2---sn-a5msen76.googlevideo.com/videoplayback?expire=1564462157&ei=7Hc_XfypN8uTkgbnwbTwBA&ip=173.244.36.76&id=o-ANhETEvFQVXb2DnfoRGzcLWgh2Ulh5duSser3CXQ8sqn&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-a5msen76%2Csn-a5meknlz&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=1006250&mime=audio%2Fwebm&gir=yes&clen=6334657&dur=491.061&lmt=1564319332832407&mt=1564440439&fvip=2&keepalive=yes&c=WEB&txp=2301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAMKR3jDtO_h7KmGC3XPeJ9vGbe1EcZJQDAY-UVRDSxJ7AiEA-3EzmQU-gUnYdLniKPE3gs1OZEPfX3HdhOSPhbbS3F4%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgRZI0_urwiGJnRr12Ofi08AZL_U2J3AV6cuTM3m_dHxQCIQC4b5KfXp0hXB3jlHiA0vshe999sHWShSKOQ8wry9ME-g%3D%3D&ratebypass=yes'
[download] Destination: _-OzLAxuD3Vfo.f251.webm
[download] 100% of 6.04MiB in 00:03
[ffmpeg] Merging formats into "_-OzLAxuD3Vfo.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:_-OzLAxuD3Vfo.f137.mp4 -i file:_-OzLAxuD3Vfo.f251.webm -c copy -map 0:v:0 -map 1:a:0 file:_-OzLAxuD3Vfo.temp.mkv
Deleting original file _-OzLAxuD3Vfo.f137.mp4 (pass -k to keep)
Deleting original file _-OzLAxuD3Vfo.f251.webm (pass -k to keep)`

**Comment by AKA-Steve** [comment] 2019-07-29 22:56
Interestingly it seems to only really be the title. Uploader and alt_title give info without issue

**Comment by sebma** [comment] 2019-07-29 23:03
@antdude I think this issue is a major one because the filename needs the video title to be extracted.
Can you please add "on YouTube" in your issue title so that the developers know it impacts all the YouTube down-loaders.

**Comment by thelamer** [comment] 2019-07-29 23:07
Any workarounds to not require this metadata in the CLI variant ?

**Comment by adamwoo2444** [comment] 2019-07-29 23:11
same.

**Closed** 2019-07-29 23:16 UTC
