### ISSUE TITLE
When we have to download player it's not work

### ISSUE THREAD

**Issue by PePinodemrs** [ytdl-org/youtube-dl#30374] opened 2021-12-15 14:08 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by hilbix** [comment] 2021-12-15 15:25
Probably duplicate of #30363, please see there.

We all are waiting for an updated version, as following one stopped working and there is no update available (yet).

    $ ./youtube-dl -U
    youtube-dl is up-to-date (2021.06.06)

**Comment by dirkf** [comment] 2021-12-16 04:03
Also, although you used the [Broken site support issue](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template, you **didn't actually complete it**, rendering the report pointless.

You should complete the information in the issue if it isn't just #30363 again. Otherwise, @PePinodemrs, kindly close this issue.

**Closed** 2021-12-16 13:02 UTC
