### ISSUE TITLE
Incorrect filename from --get-filename option

### ISSUE THREAD

**Issue by kb100** [ytdl-org/youtube-dl#6052] opened 2015-06-22 22:54 UTC
Situation:

```
youtube-dl --get-filename "https://www.youtube.com/watch?v=L0MK7qz13bU"
FROZEN - Let It Go Sing-along _ Official Disney HD-L0MK7qz13bU.webm

youtube-dl "https://www.youtube.com/watch?v=L0MK7qz13bU"
WARNING: Requested formats are incompatible for merge and would be merged into mkv.
ls
FROZEN - Let It Go Sing-along _ Official Disney HD-L0MK7qz13bU.mkv
```

Expected:

```
youtube-dl --get-filename "https://www.youtube.com/watch?v=L0MK7qz13bU"
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
FROZEN - Let It Go Sing-along _ Official Disney HD-L0MK7qz13bU.mkv

youtube-dl "https://www.youtube.com/watch?v=L0MK7qz13bU"
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ls
FROZEN - Let It Go Sing-along _ Official Disney HD-L0MK7qz13bU.mkv
```

**Comment by dstftw** [comment] 2015-06-22 22:56
Duplicate of #5710.

**Closed by dstftw** 2015-06-22 22:56 UTC
Labels: duplicate
