### ISSUE TITLE
Download Support for Joyn.de

### ISSUE THREAD

**Issue by ffw2** [ytdl-org/youtube-dl#31207] opened 2022-08-28 21:05 UTC
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.joyn.de/play/serien/steel-buddies-stahlharte-geschaefte/9-17-der-teppichklopfer
- Single video: https://www.joyn.de/play/serien/hausparty-x-wer-hat-den-besten-vibe/1-1-folge-1

## Description

The provided URL does not require a login, but some other URLs need a login. But that shouldn't matter.

**Comment by dirkf** [comment] 2022-08-29 10:18
Duplicate of #21441.

To progress that issue, someone in the region served by the site would have to demonstrate a video that plays in the browser with any DRM support disabled.

Related: https://github.com/yt-dlp/yt-dlp/issues/3072.

**Closed by dirkf** 2022-08-29 10:18 UTC
Labels: site-support-request
