### ISSUE TITLE
www.arte.tv format change

### ISSUE THREAD

**Issue by faqtos** [ytdl-org/youtube-dl#31510] opened 2023-02-01 19:45 UTC
## Description:
I have downloaded from the site www.arte.tv numerous times in the past, but it seems their format has changed: I get a

> Unable to download JSON metadata: HTTP Error 404: Not Found

(tested with several videos from the site that play well in my browser)

## Verbose log:
```
[debug] System config: ['--prefer-free-formats', '--console-title', '--format=webm/mp4/flv', '--output=%(extractor)s__%(title)s__%(resolution)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.arte.tv/fr/videos/092120-000-A/les-psychedeliques-des-drogues-qui-soignent/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.1.8-arch1-1-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[ArteTV] 092120-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by dirkf** [comment] 2023-02-02 15:33
1. Use the template.
2. Duplicate of #30919 (and #31455) which in turn are new manifestations of #30878.

**Closed by dirkf** 2023-02-02 15:33 UTC
