### ISSUE TITLE
Downloading all videos from a Twitch channel not working

### ISSUE THREAD

**Issue by notcrusage** [ytdl-org/youtube-dl#25553] opened 2020-06-05 19:41 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', '%(upload_date)s_%(id)s %(title)s.%(ext)s', '-f', 'best', '-ci', '--batch-file=links.txt']
[debug] Batch file urls: ['https://www.twitch.tv/baroshnik/videos/all']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:videos:all] baroshnik: Downloading channel info JSON
ERROR: twitch:videos:all returned error: Bad Request - Channel identifier "baroshnik" is in an invalid format
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\twitch.py", line 436, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\twitch.py", line 386, in _extract_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\twitch.py", line 66, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpd0boo4lk\build\youtube_dl\extractor\twitch.py", line 51, in _handle_error
youtube_dl.utils.ExtractorError: twitch:videos:all returned error: Bad Request - Channel identifier "baroshnik" is in an invalid format
```

## Description

WRITE DESCRIPTION HERE
Before today Twitch did not work at all, in the newest update though I am able to install any twitch vod or clip manually. The problem comes when I try to install all twitch videos from a channel
I have tried these links:
https://www.twitch.tv/baroshnik/videos?filter=highlights&sort=time
https://www.twitch.tv/baroshnik/videos?filter=highlights
https://www.twitch.tv/baroshnik/videos?filter=all&sort=time
https://www.twitch.tv/baroshnik/videos?filter=all
^These links simply tell me that "baroshnik" is not live

https://www.twitch.tv/baroshnik/videos/all
^This link is what I used for the verbose above as it is the link people recommend using when download all highlights from a channel. And this one gave a different error.

**Comment by vxbinaca** [comment] 2020-06-06 02:01
Yeah confirming this is a issue it breaks channel extraction.

**Comment by ahmedtds** [comment] 2020-06-06 02:32
duplicate of: https://github.com/ytdl-org/youtube-dl/issues/24263

there's a pull request that fixes it but not being merged for some unknown reason: https://github.com/ytdl-org/youtube-dl/pull/25010

**Comment by dgk6f** [comment] 2020-06-06 07:04
Doesn't #25010 just add support for new URL schemes?
This would therefore not fix the error shown in the log.
That one seems to stem from the display name being used instead of the channel id, even though the latter is required by `/kraken/channels/` [doc](https://dev.twitch.tv/docs/v5/reference/channels#get-channel-by-id).
This behavior can be reproduced by adding `--dump-pages`:
```
[twitch:videos:all] baroshnik: Downloading channel info JSON
[twitch:videos:all] Dumping request to https://api.twitch.tv/kraken/channels/baroshnik
```
```
{"error":"Bad Request","status":400,"message":"Channel identifier \"baroshnik\" is in an invalid format"}
```

The channel id can be obtained via `/kraken/users?login=baroshnik` [ref](https://discuss.dev.twitch.tv/t/get-channel-id-by-user-id-or-display-name-api-v5/12362/2)

**Closed** 2020-09-06 03:46 UTC
