### ISSUE TITLE
Playlist-level matching for --match-filter

### ISSUE THREAD

**Issue by J316** [ytdl-org/youtube-dl#12259] opened 2017-02-25 09:00 UTC
I want to download all the playlists of a channel except "Liked videos" and "Favourites", so I put `--reject-title "Liked videos|Favourites"` in the youtube-dl.conf file, but it keeps downloading them. The program returns `--reject-title: command not found` (I'm using the latest version)

**Comment by yan12125** [comment] 2017-02-25 09:48
Please paste full log of youtube-dl -v "(your video URL)"

**Comment by J316** [comment] 2017-02-25 10:04
`[1] 829
[2] 830
bash: --reject-title: command not found
[2]+  Done                    view=1`
Then it procedes downloading what it should not

**Comment by yan12125** [comment] 2017-02-25 10:08
Please include the command(s) and all outputs. Only the last line does not provide useful information

**Comment by dstftw** [comment] 2017-02-25 11:52
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by J316** [comment] 2017-02-25 12:07
@yan12125 after those lines it goes on and downloads all the videos, there's nothing else to post except the downloading process. The only thing is that those two numbers change everytime I run the command.

@dstftw What is your problem dude? If you don't wanna take care of it then don't, but stop closing issues, this is childish.

**Comment by yan12125** [comment] 2017-02-25 12:13
> the command

That's the most important one. I guess you've used a wrong command. Anyway no one can give a conclusion with so little information. Whether you believe it or not, _all_ lines in your log are important.

**Comment by dstftw** [comment] 2017-02-25 12:26
@J316 childish is ignoring the rules and not providing proper reports. I close and will close all the incomplete reports. If one doesn't even bother to provide necessary info I won't bother trying to help.

**Comment by J316** [comment] 2017-02-25 12:27
`youtube-dl -o "/home/user/youtube-dl/%(uploader)s/%(playlist)s/%(title)s.%(ext)s" https://www.youtube.com/user/MullkyB/playlists --reject-title "Liked videos" -v
[debug] System config: ['-ci', '-o', '/home/user/youtube-dl/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '/home/user/youtube-dl/%(uploader)s/%(playlist)s/%(title)s.%(ext)s', 'https://www.youtube.com/user/MullkyB/playlists', '--reject-title', 'Liked videos', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.22
[debug] Python version 3.6.0 - Linux-4.4.51-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlists] MullkyB: Downloading webpage
[download] Downloading playlist: Brian Mullin
[youtube:playlists] playlist Brian Mullin: Downloading 7 videos
[download] Downloading video 1 of 7
[youtube:playlist] LLArBP0HP6aYpSVQQ4YbuYqQ: Downloading webpage
[download] Downloading playlist: Liked videos
[youtube:playlist] LLArBP0HP6aYpSVQQ4YbuYqQ: Downloading page #1
[youtube:playlist] playlist Liked videos: Downloading 155 videos
[download] Downloading video 1 of 155
[youtube] 017xiEkXpaA: Downloading webpage
[youtube] 017xiEkXpaA: Downloading video info webpage
[youtube] 017xiEkXpaA: Extracting video information
[youtube] 017xiEkXpaA: Downloading MPD manifest
[debug] Invoking downloader on 'https://r9---sn-nx5cvox-hpae7.googlevideo.com/videoplayback?mm=31&mn=sn-nx5cvox-hpae7&keepalive=yes&initcwndbps=942500&upn=zO3xM3p3-ak&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ei=mHexWPTgIM_M1gKRIw&ms=au&itag=302&mt=1488025403&mv=m&gir=yes&signature=6E8C7127EE696C1CB879877AD66EF8922E75447A.09A8EC1561629D1E89ED193475FEDA65B0147C98&ipbits=0&requiressl=yes&id=o-ANObt5RJpXN0Qnosh61FbbAP8-PdgjwDXUpzlEUB2Gh7&gcr=it&nh=EAE&beids=%5B9452307%5D&key=yt6&lmt=1487246219027303&source=youtube&dur=6965.533&ip=87.19.254.216&mime=video%2Fwebm&pl=15&clen=1307868700&expire=1488047096&ratebypass=yes'
[download] Resuming download at byte 261120
[download] Destination: /home/user/youtube-dl/Flat Earth And Other Hot Potatoes/Liked videos/Patricia Steere _ Mark Sargent. 144. The Secret Show. Flat Earth & Other Hot Potatoes.f302.webm
[download]   0.1% of 1.22GiB at 907.66KiB/s ETA 23:26^C`

I run this in another OS, the `command not found` error didn't show up, but the command is still ignored

**Comment by J316** [comment] 2017-02-25 12:29
@dstftw Maybe you did not receive enough love as a kid? Whatever. Keep doing your games

**Comment by yan12125** [comment] 2017-02-25 13:53
```--reject-title``` uses video titles not playlist titles. Use ```--match-filter "playlist_title != 'Liked videos'"``` instead.

**Comment by J316** [comment] 2017-02-25 17:59
@yan12125 It works on skipping this way, thanks. But it skips the videos one by one, and since the "Liked videos" and similar playlists can be huge, is there a way to skip the whole playlist at once? Maybe adding a command like `--reject-playlist`

**Comment by yan12125** [comment] 2017-02-25 18:05
Yes, extending --match-filter to handle playlists is a good idea.

**Comment by J316** [comment] 2017-02-25 18:06
@yan12125 Since it's regex I should be able to put a list like `'Liked videos|Favourites` right? But it doesn't work. Is it the weong syntax?

**Comment by yan12125** [comment] 2017-02-25 18:09
Regular expressions are not supported yet. See also #9092

**Comment by J316** [comment] 2017-02-25 18:12
How can I exclude more than one value?

**Comment by yan12125** [comment] 2017-02-25 18:13
Use ```&```. See https://github.com/rg3/youtube-dl/blob/master/README.md#video-selection

**Comment by dstftw** [comment] 2019-06-04 20:54
Duplicate of #8413.

**Closed by dstftw** 2019-06-04 20:54 UTC
Labels: request
