### ISSUE TITLE
6play (Hungarian edition) download error

### ISSUE THREAD

**Issue by streamnetvps** [ytdl-org/youtube-dl#31496] opened 2023-01-25 23:43 UTC
Using YOUTUBE-DL.EXE v2021.12.17 latest edition and giving the proper URL link for the application the app recognizes the [6play] as a format, downloads the JSON metadata and sends an ERROR: No video formats found. (See picture attached)

Note1: Hungarian IP address should be used to access the data. (and yes, testing has been done in Hungary).
Note2: Video stream includes multiple size formats for different quality playback
Note3: This 6play format playing creates several <500KB size files, aka chunks, which should be merged together to give a complete file for the video.

If you need a VPN connection for testing the above issue please contact me.
Any help would be appreciated. Thank you.
-Robert.

![youtube-dl02](https://user-images.githubusercontent.com/13987294/214717341-367d833a-8d99-4078-8597-78d9cddd904d.JPG)

**Comment by dirkf** [comment] 2023-01-26 00:42
Duplicate of #25111.

**Closed by dirkf** 2023-01-26 00:42 UTC
