### ISSUE TITLE
youtube-dl: uploader_id, not error: invalid rate limit specified 

### ISSUE THREAD

**Issue by webpvl** [ytdl-org/youtube-dl#31539] opened 2023-02-17 04:13 UTC
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -verbose -r 10K   https://www.youtube.com/watch?v=Up6p_dV7eEI    
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-verbose', '-r', '10K', 'https://www.youtube.com/watch?v=Up6p_dV7eEI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

After apt update/upgreade - problem occured then  sudo pip install --upgrade youtube_dl - no change problem remains.
"youtube-dl: error: invalid rate limit specified"  similar to https://github.com/ytdl-org/youtube-dl/issues/31423
"-r 20K" from https://stackoverflow.com/questions/29998711/youtube-dl-rate-limit-download-speed-and-auto-resume-download
was attempted but Error remained.

**Comment by dirkf** [comment] 2023-02-17 11:00
Duplicate of #31530.

**Comment by dirkf** [comment] 2023-02-17 11:03
Did you just file this issue at random? Wrong title, checked (wrongly) items that weren't performed, mentioned completely unrelated issue with diagnostic not in posted log, ...

**Closed by dirkf** 2023-02-17 11:03 UTC

**Comment by webpvl** [comment] 2023-02-18 01:48
(First unreported)  "error: invalid rate limit specified" - my mistake!  I believe the error is not the same as " "Unable to extract uploader id"" 

Sorry I missed the fact that there was two errors reported depending on whether or not i used "-r 10K"
Second error - the error i quoted and did not notice was different than the first error i got without 
using  the option "-r 10K" (bellow)

(First Error)
"[debug] Command-line args: ['-verbose', 'https://www.youtube.com/watch?v=Up6p_dV7eEI']
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: invalid rate limit specified"

Not the same as quoted response of  error #31530

"ERROR: [youtube] 3h5-QPbKoVg: Unable to extract uploader id" from " Youtube : "Unable to extract uploader id" #31530 "
