### ISSUE TITLE
[FranceTV] Unable to download JSON metadata

### ISSUE THREAD

**Issue by Kurt85055** [ytdl-org/youtube-dl#30711] opened 2022-03-04 12:55 UTC
C:\Program Files\ffmpeg\bin>youtube-dl --all-subs --verbose https://www.francetvinfo.fr/replay-magazine/franceinfo/vrai-ou-fake-l-emission/vrai-ou-fake-l-emission-du-samedi-19-fevrier-2022_4972032.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--all-subs', '--verbose', 'https://www.francetvinfo.fr/replay-magazine/franceinfo/vrai-ou-fake-l-emission/vrai-ou-fake-l-emission-du-samedi-19-fevrier-2022_4972032.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22567
[debug] exe versions: ffmpeg 2021-03-09-git-c35e456f54-full_build-www.gyan.dev, ffprobe 2021-03-09-git-c35e456f54-full_build-www.gyan.dev
[debug] Proxy map: {}
[francetvinfo.fr] vrai-ou-fake-l-emission-du-samedi-19-fevrier-2022_4972032: Downloading webpage
[FranceTV] f54540fc-9234-11ec-8799-41749944cef0: Downloading video JSON
**ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found** (caused by HTTPError()); **please report this issue on https://yt-dl.org/bug** . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment] 2022-03-04 14:33
Unless you have applied the relevant patch, duplicate of #29956

**Comment by Kurt85055** [comment] 2022-03-07 12:04
Hello dirkf,

I suppose I can patch the **francetv.py** file with @sarnoud's fix only on Linux; I'm on **Windows** and have only **youtube-dl.exe** in my **C:\ffmpeg\bin** folder which does not require **Python** that is already embedded into the binary. I have unzpped youtube-dl.exe and can see that there is a folder named y**outube_dl** which contains a folder named **extractor** which contains also **francetv.pyo** which is a **compiled** Python file! I can see no way how to patch this compiled file!

Best regards
[Kurt85055](https://github.com/Kurt85055)

**Comment by dirkf** [comment] 2022-03-07 13:48
Apparently it is possible (replace the .pyo file with the new .py file, recompress) but I haven't tried it.

For the moment, it's probably better to try [yt-dlp](https://github.com/yt-dlp/yt-dlp) for this site. It seems to work for your page.

We'll try to update yt-dl's extractor from the yt-dlp one, but the latter assumes some core changes that haven't been pulled back into yt-dl yet.

**Comment by rautamiekka** [comment] 2022-03-07 14:22
> Hello dirkf,
> 
> I suppose I can patch the **francetv.py** file with @sarnoud's fix only on Linux; I'm on **Windows** and have only **youtube-dl.exe** in my **C:\ffmpeg\bin** folder which does not require **Python** that is already embedded into the binary. I have unzpped youtube-dl.exe and can see that there is a folder named y**outube_dl** which contains a folder named **extractor** which contains also **francetv.pyo** which is a **compiled** Python file! I can see no way how to patch this compiled file!
> 
> Best regards [Kurt85055](https://github.com/Kurt85055)

The only way is to install Python and download the source code. Technically you could get the universal binary (which is just a ZIP file) but that's pointless.

**Comment by dirkf** [comment] 2022-03-07 14:35
A successful patch of the Windows self-extracting build **was** previously reported in connection with the YT unthrottling patch. It depended on a specific Windows zip tool.

**Comment by Kurt85055** [comment] 2022-03-07 15:14
I confirm that [yt-dlp](https://github.com/yt-dlp/yt-dlp) has worked perfectly for my FranceTV page!

**Closed** 2022-05-09 14:32 UTC
Labels: duplicate

**Comment by nbanb** [comment] 2023-08-14 16:51
I confirm that today (20230814), I didn't succeed in making work francetv with youtube-dl and described patchs under Debian GNU Linux BUT [yt-dlp](https://github.com/yt-dlp/yt-dlp) had perfectly work for me
