### ISSUE TITLE
[youtube] can't download short videos

### ISSUE THREAD

**Issue by TomDiy001** [ytdl-org/youtube-dl#30910] opened 2022-05-02 03:02 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

[Version]
OS: Linux vultr.guest 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
app: youtube-dl is up-to-date (2021.12.17)

[Expected]
can download the video by URL: https://www.youtube.com/shorts/wxxJlOoPSnw

[Actual]
show errors as below.
`root@vultr:~/video# youtube-dl https://youtube.com/shorts/wxxJlOoPSn
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by dirkf** [comment] 2022-05-02 16:32
Duplicate of #30269; fixed in git master.

If you had actually done this

>- [x] I've searched the bugtracker for similar bug reports including closed ones

(say, **searching** for the word "shorts", rather than just scanning the first page of the issue list), it would have revealed the original issue and its pending resolution.

**Closed by dirkf** 2022-05-02 16:32 UTC
