### ISSUE TITLE
:\Users\oluadepe>youtube-dl.exe https://www.udemy.com/course/introduction-to-cloud-computing-on-amazon-aws-for-beginners/learn/lecture/21307000 [udemy:course] course: Downloading webpage ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by Oluadepe** [ytdl-org/youtube-dl#30281] opened 2021-11-27 15:21 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.06.06**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2021-11-27 18:40
1. Likely a duplicate of #29915.
2. If OP can't manage to complete a [bug report](https://github.com/ytdl-org/youtube-dl/issues/new?template=1_broken_site.md) properly, cloud computing with AWS will be quite challenging, beginners' course or not.

**Closed** 2022-01-29 14:54 UTC
Labels: duplicate
