### ISSUE TITLE
YouTube "shorts" format unsupported

### ISSUE THREAD

**Issue by cjm51213** [ytdl-org/youtube-dl#31377] opened 2022-11-23 16:18 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
# youtube-dl --verbose https://youtube.com/shorts/Dc8aMUtS2YM
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://youtube.com/shorts/Dc8aMUtS2YM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-5.19.15-201.fc36.x86_64-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 835, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

WRITE DESCRIPTION HERE
Pretty simple an self-explanatory: YouTube shorts seems to present an unsupported page format and youtube-dl doesn't seem to be able to work with it.

**Comment by cjm51213** [comment] 2022-11-23 16:19
Help me, "Obi Wan youtube-dl"! You are my only hope ...

**Comment by dirkf** [comment] 2022-11-23 16:53
>  I've searched the bugtracker for similar bug reports including closed ones

Really? Duplicate of #30760.

**Closed by dirkf** 2022-11-23 16:53 UTC

**Comment by cjm51213** [comment] 2022-11-23 17:01
>> I've searched the bugtracker for similar bug reports including closed ones
Really? I never claimed to have done this.

**Comment by cjm51213** [comment] 2022-11-23 17:02
>>> I've searched the bugtracker for similar bug reports including closed ones
> Really? I never claimed to have done this.

Oops ... My mistake. I apparently did claim I did this. Sorry.

**Comment by cjm51213** [comment] 2022-11-23 17:19
Since I will probably not be the last person to "discover" this problem, how hard would it be to simply avoid all the reports? Look for the naive, offending URL and tactically replace it with the compliant one. I don't know if Python supports this, but I suspect that you get the idea: 

> sed
> 's/https:\/\/.*youtube.com/shorts/\(.*\)\?.*/https:/www.youtube.com/watch?v=\1/'

Sorry for my ignorance of this previous discussion, but with a tiny bit of foresight, the whole charade could have been avoided. You know, avoid all the stupid users that think downloading YouTube videos should, you know, download YouTube videos ...

**Comment by dirkf** [comment] 2022-11-23 17:24
The code has been fixed since February. If you don't want to install the development code or one of the nightly builds in forks, just use the bare ID (but you won't get the unthrottled download).

**Comment by cjm51213** [comment] 2022-11-23 17:45
Hi Dirk, 

> The code has been fixed since February. If you don't want to install the
> development code or one of the nightly builds in forks, just use the bare ID
> (but you won't get the unthrottled download).
... by which you mean the current "development version" has been fixed? I think I am running the most current "production" version, and that is what almost everybody will be using, so "the code" is an ambiguous term that would lead people to believe that "what they have" has been fixed since February. I don't know the sophistication level of your user base, but I would call myself average, and I had to ask for advice. How many folks will say, "This damn thing doesn't work. Oh, the hell with it."? 

It is not unreasonable for users to think that the URL as presented in the browser, should also work with youtube-dl. Since "shorts" has recently become far more widely accessible, you might want to "patch" your "current version", meaning your current "production" version, meaning the version most users will have, with just the tactical URL re-write that I described, and avoid the wasted time you will incur instructing users that the failure is the result of their naivety and that "the code" does the right thing, but that they don't have "the code". 

Thanks for the help, 
-- 
Chris. 

V:916.799.9461 
F:916.974.0428 
A: Because we read from top to bottom, left to right.
    Q: > Why should I start my reply below the quoted text?

**Comment by dirkf** [comment] 2022-11-23 18:44
The reason for the checkboxes is to help people solve the problem without creating a new issue. Even a naïve user should find the original issue (actually #30760) either directly or from an earlier duplicate, where the solution and work-arounds are documented. Just use `Dc8aMUtS2YM`. But then you seem to be a top-quoter so I guess it's hopeless ...

**Comment by dirkf** [comment] 2022-11-23 19:33
The message you want would have required someone early in 2021 to predict the advent of a new URL pattern in YouTube. As the pattern will be correctly handled in the next release, there wouldn't be any point in adding a message retrospectively ("The URL format you are downloading used not to be directly supported but is now").

Stack traces are possibly unfriendly but provide incontrovertible evidence as opposed to "help! youtube-dl didn't work". While n**** users sometimes have trouble determining that, eg, a 403 error from site A is almost certainly a different issue from the same error for site B, developer(s) can tell immediately and sometimes go straight to the problem line of code.

We don't show back-traces for predictable extraction errors, say when the site extractor determines that the requested item has expired, or isn't accessible because of the user's location. Whether a predictable error is correctly categorised does depend on the pains taken by the author of the extractor, though.

See how this post appears underneath your last one!

**Comment by cjm51213** [comment] 2022-11-23 19:41
Hi Dirk, 

It's been fun. 
-- 
Chris. 

V:916.799.9461 
F:916.974.0428 
A: Because we read from top to bottom, left to right.
    Q: > Why should I start my reply below the quoted text?
