### ISSUE TITLE
ERROR: Unsupported URL: https://www.cbs.com/shows/video/Q2WEP4xBevidk9SQrsq3W7_j9hCKuBuE/

### ISSUE THREAD

**Issue by gogo9th** [ytdl-org/youtube-dl#31420] opened 2022-12-14 07:22 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

Hi, 

Youtube-DL used to work for this website, but not now  for some reason:

`$ youtube-dl [%url%](https://www.cbs.com/shows/video/Q2WEP4xBevidk9SQrsq3W7_j9hCKuBuE/)`

I wonder if you could check out if it's possible to make this work.. Thanks.

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment] 2022-12-14 16:27
Problem 1 is that the extractor expects another component between `/shows` and `video/`. You can work around that by putting `/v/` there.

But then you get problem 2 (#31361) which is that the site offers no playable formats.

Duplicate of #31361.

**Closed by dirkf** 2022-12-14 16:27 UTC
