### ISSUE TITLE
What if some extractors have their own DEFAULT_OUTTMPL?

### ISSUE THREAD

**Issue by sheerluck** [ytdl-org/youtube-dl#20544] opened 2019-04-03 10:06 UTC
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

In ```YoutubeDL.py``` in ```def prepare_filename(self, info_dict)``` in line 660
```
outtmpl = self.params.get('outtmpl', DEFAULT_OUTTMPL)
```

```outtmpl``` does not depend on value of "extractor" key in ```template_dict```
So ```outtmpl``` is ```'%(title)s-%(id)s.%(ext)s'``` most of the time

**And it's perfectly fine**

But when extractor is "Imgur", well... it would be nice to have ```outtmpl``` equal ```'%(playlist_title)s-%(id)s.%(ext)s'```

Something like this:
```
            def from_extractor(default, info):
                if info["extractor"] == "Imgur":
                    return '%(playlist_title)s-%(id)s.%(ext)s'
                return default
```

If you run ```$ youtube-dl https://imgur.com/gallery/gH2YifC``` you will get
```
[download] Destination: Imgur-PMVKzz1.mp4
```

When I run my patched youtube-dl I get
```
[download] Destination: Message in a bottle-PMVKzz1.mp4
```

Who knows, maybe other extractors have more suitable DEFAULT_OUTTMPL as well, right?

**Comment by sheerluck** [comment] 2019-04-03 12:35
oh and this bug too:
```
$ youtube-dl https://imgur.com/gallery/HvW5QyI
[imgur:gallery] HvW5QyI: Downloading JSON metadata
[download] Downloading playlist: ¯\_(ツ)_/¯
[imgur:gallery] playlist ¯\_(ツ)_/¯: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Imgur] FzIfHVd: Downloading webpage
[download] Destination: ¯_(ツ)_¯-FzIfHVd.mp4
[download] 100% of 880.96KiB in 00:00
[download] Finished downloading playlist: ¯\_(ツ)_/¯
```

Destination should be ```¯\_(ツ)_/¯-FzIfHVd.mp4```  and not ```¯_(ツ)_¯-FzIfHVd.mp4```

**Comment by remitamine** [comment] 2019-04-03 13:03
> oh and this bug too:
Destination should be ¯\_(ツ)_/¯-FzIfHVd.mp4 and not ¯_(ツ)_¯-FzIfHVd.mp4

not a bug, try to create the file manually.

**Comment by sheerluck** [comment] 2019-04-03 13:28
I got ```[download] Destination: ¯⧹_(ツ)_⧸¯-FzIfHVd.mp4``` with this:

![image](https://user-images.githubusercontent.com/5173768/55482561-74868200-562d-11e9-94ae-600657c0d216.png)

**Comment by sheerluck** [comment] 2019-04-03 16:59
works for both Windows and Linux.

**Comment by dstftw** [comment] 2019-04-03 17:13
Duplicate of #3101.

**Closed by dstftw** 2019-04-03 17:13 UTC
