### ISSUE TITLE
Ruutu.fi has issues downloading.

### ISSUE THREAD

**Issue by wikuw** [ytdl-org/youtube-dl#21031] opened 2019-05-09 17:36 UTC
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.04.30**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.ruutu.fi/video/3401964']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.10 (CPython) - Darwin-18.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[Ruutu] 3401964: Downloading XML
[Ruutu] 3401964: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Ruutu] 3401964: Checking https URL
[Ruutu] 3401964: https URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ruutu.py", line 143, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```



Video at given URL works fine on browser.  I have no account at ruutu.fi

**Comment by svalavuo** [comment] 2019-05-10 07:39
Yes. Something is broken/changed.
Tried with ruutu.fi video I have downloaded earlier. Now ruutu.fi tells 403 and after that youtube-dl says that video is DRM protected. Both videos plays nicely with browser.

**Comment by jusrose** [comment] 2019-05-10 19:26
i have it downloaded with pip on linux and it does the same thing. pls show work around and fix

**Comment by svalavuo** [comment] 2019-05-20 11:37
With modifications from juzza1 youtube-dl is working with ruutu.fi again! 👍

**Comment by matti** [comment] 2019-05-29 17:24
confimed, works.

**Comment by kuco28** [comment] 2019-05-31 00:39
I tested it and it no longer works.
Yes, I have the latest version.

**Comment by juzza1** [comment] 2019-05-31 07:51
> 
> 
> I tested it and it no longer works.
> Yes, I have the latest version.

I had no problems downloading a few new releases, are you sure you are using my fork, or have applied the pull request into the version you are using? The patch is not yet merged into the master branch. If you are indeed using the patched version, can you please paste the url(s) which did not work for you here.

**Comment by kuco28** [comment] 2019-05-31 10:49
> The patch is not yet merged into the master branch.

Oh, nevermind then. It was like 2 am when I wrote it and was tired so forgot about that.
I replaced file and it works fine. Sorry for the trouble.

**Comment by juzza1** [comment] 2019-05-31 13:13
> 
> 
> > The patch is not yet merged into the master branch.
> 
> Oh, nevermind then. It was like 2 am when I wrote it and was tired so forgot about that.
> I replaced file and it works fine. Sorry for the trouble.

Glad to hear that. To avoid confusion, could you also update your comment in the pull request?

**Comment by Jiriss** [comment] 2019-06-09 16:54
Unfortunately this problem is still valid in the newest version

[debug] youtube-dl version 2019.06.08
--
[Ruutu] 3381638: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Ruutu] 3381638: Checking https URL
[Ruutu] 3381638: https URL is invalid, skipping

**Comment by matti** [comment] 2019-06-10 17:55
because this hasnt been merged?

**Comment by matti** [comment] 2019-06-10 17:56
this partch works just fine, downloaded bunch of temppraris

**Comment by kuco28** [comment] 2019-06-14 04:33
They changed something.
Few days ago it worked and was able to download each video but now I guess I need a subscription.
`ERROR: Probably a Ruutu+ video, authentication required. Consider sending PR for proper handling of Ruutu+ videos with credentials.`

**Comment by matti** [comment] 2019-08-19 20:40
juzza1's patch still works today.

**Comment by ronilaukkarinen** [comment] 2019-09-04 16:35
@juzza1's patch confirmed working just now. Should be merged.

**Comment by fuloating** [comment] 2019-09-05 20:19
with the patch is it possible to download content that require authentication to ruutu.fi (ruutu+ content)?

**Comment by matti** [comment] 2019-10-10 17:59
I don't have ruutu account, but I did just downloaded some tempparis so this patch still works at least without login.

**Comment by matti** [comment] 2019-10-17 11:02
```
git clone https://github.com/juzza1/youtube-dl.git
cd youtube-dl
git checkout ruutufix
python -m youtube_dl https://www.ruutu.fi/video/2948499
```

**Comment by Jiriss** [comment] 2019-11-08 16:47
When will include the patch to repository under an original project of youtube-dl (https://github.com/ytdl-org/youtube-dl/)?

**Comment by svalavuo** [comment] 2020-01-04 23:10
Something is broken again. :-(

[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.ruutu.fi/video/3523622', u'--netrc', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.12 (CPython) - Linux-4.8.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, rtmpdump 2.4
[debug] Proxy map: {}
[Ruutu] 3523622: Downloading XML
[Ruutu] 3523622: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Ruutu] 3523622: Checking https URL
[Ruutu] 3523622: https URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/ruutu.py", line 143, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by svalavuo** [comment] 2020-01-06 18:43
Sorry, that needed ruutu+ and I don't have that.
Tried another:
youtube-dl https://www.ruutu.fi/video/3530318 --netrc --verbose
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'https://www.ruutu.fi/video/3530318', u'--netrc', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.01.01
[debug] Python version 2.7.12 (CPython) - Linux-4.8.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.1.3-0york1, ffprobe 4.1.3-0york1, rtmpdump 2.4
[debug] Proxy map: {}
[Ruutu] 3530318: Downloading XML
ERROR: This video is DRM protected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/ruutu.py", line 141, in _real_extract
    raise ExtractorError('This video is DRM protected.', expected=True)
ExtractorError: This video is DRM protected.

**Comment by uuksu** [comment] 2020-01-08 18:12
It seems that multiple things have change it Ruutu that causes youtube-dl to break.
New download flow should be something like this to work:
1. Authenticate to Ruutu.fi, get gatling_token from cookie
2. Make call to https://gatling.nelonenmedia.fi/media-xml-cache?id=<id here>&v=3 with video id and get playlist url
3. Make call to https://gatling.nelonenmedia.fi/auth/access/v2?stream=<playlist url here>&timestamp=<timestamp>&gatling_token=<gatling_token here> and get authenticated playlist url (playlist + JWT token in url)
4. Download from playlist

**Comment by matti** [comment] 2020-04-01 16:53
non-ruutu+ things still work

**Comment by joonas-fi** [comment] 2020-05-18 08:54
@matti has the right answer, things still work (I just confirmed by downloading some stuff) in @juzza1's branch, and he even had instructions on how to use the branch: https://github.com/ytdl-org/youtube-dl/issues/21031#issuecomment-543122469 (thanks for being a champ ❤️ )

Here's to hoping the PR gets accepted soon..

**Comment by ExTechOp** [comment] 2020-06-07 19:26
Is there some special reason @juzza1's branch hasn't been merged into the main source in six months, if it works?

**Comment by ExTechOp** [comment] 2020-11-24 15:42
Oh how wonderful, the @juzza1 branch is still under RIAA DMCA takedown, although the main youtube-dl source no longer is.

**Comment by matti** [comment] 2020-11-24 18:23
Is it? I'll push my local copy soon

**Comment by ExTechOp** [comment] 2020-11-25 18:18
If you do, can you please try to get it merged into the normal youtube-dl, instead of being a special branch?

**Closed** 2020-12-11 23:50 UTC
Labels: account-needed, geo-restricted

**Comment by matti** [comment] 2022-01-20 19:02
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/3893/150404841-070b542b-0ad3-4cd9-b705-9e122fb09809.png">

^-- regular ffmpeg works just fine now
