### ISSUE TITLE
[BBC] ERROR: Unable to extract playlist data

### ISSUE THREAD

**Issue by VWPAD** [ytdl-org/youtube-dl#30291] opened 2021-11-30 02:31 UTC
## Checklist

- [ X] I'm reporting a broken site support issue
- [X ] I've verified that I'm running youtube-dl version **2021.06.06**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones (A similar issue was reported by Billybangleballs opened this issue on Jun 15, 2017
- [ X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
`$ youtube-dl --verbose https://www.bbc.com/news/av/world-europe-59468682
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bbc.com/news/av/world-europe-59468682']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-5.11.0-40-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[bbc] world-europe-59468682: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 1255, in _real_extract
    webpage, 'playlist data'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

WRITE DESCRIPTION HERE
Unable to extract playlist from https://www.bbc.com/news/av/world-europe-59468682
Noted in Linked Pull Requests Successfully merging a pull request may close this issue.
remitamine added the geo-restricted label on May 31, 2018

**Comment by 89z** [comment] 2021-11-30 02:36
https://github.com/ytdl-org/youtube-dl/issues/29926

**Comment by dirkf** [comment] 2021-11-30 06:36
Duplicate of #29926.

Fixed in PR #30292.

**Comment by 89z** [comment] 2021-12-04 02:51
I have an alternate tool that works:

~~~
PS C:\> bbc -hf bbc.com/news/av/world-europe-59468682
GET http://walter-producer-cdn.api.bbci.co.uk/content/cps/news/world-europe-59468682
GET http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/p0b779gc
GET http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/77c6b7-p0b779gc/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b.ism/pc_hd_abr_v2_hls_master.m3u8?__gda__=1638607706_7715b8c686408a38b9c198a76f06358d
{ID:0 Resolution:384x216 Bandwidth:400000 Codecs:mp4a.40.5,avc1.42C015 URI:http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/77c6b7-p0b779gc/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b.ism/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b-audio_eng=96000-video=281000.m3u8}
{ID:1 Resolution:512x288 Bandwidth:565000 Codecs:mp4a.40.5,avc1.4D4015 URI:http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/77c6b7-p0b779gc/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b.ism/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b-audio_eng=96000-video=437000.m3u8}
{ID:2 Resolution:704x396 Bandwidth:979000 Codecs:mp4a.40.5,avc1.4D401F URI:http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/77c6b7-p0b779gc/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b.ism/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b-audio_eng=96000-video=827000.m3u8}
{ID:3 Resolution:960x540 Bandwidth:1802000 Codecs:mp4a.40.5,avc1.64001F URI:http://vod-hls-ww-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/77c6b7-p0b779gc/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b.ism/vf_p0b779gc_dcca2be6-4e96-49cf-a657-b913b0dee50b-audio_eng=96000-video=1604000.m3u8}
~~~

https://github.com/89z/mech

**Comment by 89z** [comment] 2022-01-29 01:23
https://github.com/ytdl-org/youtube-dl/issues/30565

**Closed** 2022-02-05 02:51 UTC
Labels: duplicate
