### ISSUE TITLE
Unable to recognize tab page YouTube-dl and can't download videos from YouTube shorts

### ISSUE THREAD

**Issue by maikeru2991** [ytdl-org/youtube-dl#30760] opened 2022-03-21 22:47 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl --verbose 'https://www.youtube.com/shorts/o38ilgL25lc'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/shorts/o38ilgL25lc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: fed93bb93
[debug] Python version 3.9.10 (CPython) - macOS-12.3-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

Unable to recognize tab page YouTube-dl and can't download videos from YouTube shorts

**Comment by 89z** [comment] 2022-03-21 22:52
Just use the ID:

~~~
PS C:\> youtube-dl o38ilgL25lc
[youtube] o38ilgL25lc: Downloading webpage
[youtube] o38ilgL25lc: Downloading player 293baa5d
[download] Destination: When u sit in the emergency exit row 😂-o38ilgL25lc.f398.mp4
[download]   3.4% of 5.95MiB at 80.93KiB/s ETA 01:12
~~~

**Comment by dirkf** [comment] 2022-03-22 13:20
Also, duplicate of #30269; fixed in git master.

**Comment by 89z** [comment] 2022-04-03 16:14
https://github.com/ytdl-org/youtube-dl/issues/30813

**Comment by 89z** [comment] 2022-04-08 12:44
https://github.com/ytdl-org/youtube-dl/issues/30834

**Comment by 89z** [comment] 2022-08-26 03:53
https://github.com/ytdl-org/youtube-dl/issues/31202

**Comment by maikeru2991** [comment] 2022-10-05 08:32
Somebody on here got back to me a while ago and you don’t put the entire URL, just the video ID at the end of the URL, and it works perfect.

Wow while everyone’s here I know this probably goes against forum decorum,but I  have a css landing page template for a website that I gotta get done today and I can’t get the page to format/render correctly… I’m using concrete CMS and of course they’ve taken all of the necessary steps to make it as difficult as possible for customers to get what they want.  I had some code that worked as an override to the CMS but maybe I just put it in the wrong location. Any tips greatly appreciated.



photograph Michael Patmon Marketing Designer M (314) 669-4430 E ***@***.*** My Company Street, City Zip Code, Country www.my-company.com facebook icon twitter icon youtube icon linkedin icon instagram icon pinterest icon Banner

**Comment by Rudxain** [comment] 2022-10-27 03:39
> just the video ID at the end of the URL

As I said at https://github.com/ytdl-org/youtube-dl/pull/30577#issuecomment-1292927326 , I'm still impressed that this is possible in YTDL but not YT itself lol

**Closed** 2022-10-27 09:50 UTC
Labels: site-support-request, duplicate, fixed
