### ISSUE TITLE
Unable to download France 5 documentary

### ISSUE THREAD

**Issue by MouettE-SC** [ytdl-org/youtube-dl#20639] opened 2019-04-11 02:34 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.07*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.france.tv/france-5/enquete-de-sante/944399-alzheimer-comment-lutter-contre-la-maladie.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.5.3 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-debian-9.8
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[FranceTVSite] 944399-alzheimer-comment-lutter-contre-la-maladie: Downloading webpage
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading video JSON
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading geo restriction info
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading signed m3u8-download manifest URL
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading signed hls_v5_os manifest URL
[FranceTV] acccbd7f-488d-4384-a269-63a18776c25c: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/charles/ytb/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/charles/ytb/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/charles/ytb/lib/python3.5/site-packages/youtube_dl/extractor/francetv.py", line 209, in _real_extract
    return self._extract_video(video_id, catalog)
  File "/home/charles/ytb/lib/python3.5/site-packages/youtube_dl/extractor/francetv.py", line 169, in _extract_video
    self._sort_formats(formats)
  File "/home/charles/ytb/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1326, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

**Comment by NiesmialyGosc** [comment] 2019-04-11 11:20
I have, too, encountered an issue when downloading the m3u8 info:

D:\video>youtube-dl --proxy socks4://185.165.64.70:4145 --all-subs --convert-subs srt -o "7741.mp4" --retries 200 https://www.france.tv/france-2/amour-gloire-et-beaute/944315-amour-gloire-et-beaute.html
[FranceTVSite] 944315-amour-gloire-et-beaute: Downloading webpage
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading video JSON
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading geo restriction info
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading signed m3u8-download manifest URL
WARNING: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.>
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading signed m3u8-download manifest URL
WARNING: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.>
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading m3u8 information
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading signed hls_v5_os manifest URL
[FranceTV] 1da49989-c30c-490d-865c-560b3dad8662: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.>
[info] Writing video subtitles to: 7741.fr.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 130
[download] Destination: 7741.mp4
[download]   2.3% of ~141.22MiB at 37.56KiB/s ETA 54:44      ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.>

Please can this be looked into

**Comment by baptx** [comment] 2019-04-21 10:22
@NiesmialyGosc this looks like a duplicate of https://github.com/ytdl-org/youtube-dl/issues/17835, I have shared a workaround there if you are interested.

**Comment by dstftw** [comment] 2019-07-16 16:07
>La vidéo n'est pas disponible

**Closed by dstftw** 2019-07-16 16:07 UTC
