### ISSUE TITLE
Twitter 

### ISSUE THREAD

**Issue by misakikaoru2006** [ytdl-org/youtube-dl#32155] opened 2023-05-06 00:18 UTC
.\youtube-dl.exe https://twitter.com/i/status/1654380407205294080
[twitter] 1654380407205294080: Downloading guest token
[twitter] 1654380407205294080: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2023-05-06 08:43
Duplicate of #32007.

**Closed by dirkf** 2023-05-06 08:43 UTC
