### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by weswitt** [ytdl-org/youtube-dl#20761] opened 2019-04-24 00:15 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

youtube-dl -v --verbose https://www.youtube.com/watch?v=kt1-hLsIjqg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--verbose', 'https://www.youtube.com/watch?v=kt1-hLsIjqg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.6.7 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] kt1-hLsIjqg: Downloading webpage
[youtube] kt1-hLsIjqg: Downloading video info webpage
ERROR: kt1-hLsIjqg: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call you
tube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/wesw/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/wesw/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/home/wesw/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: kt1-hLsIjqg: "token" parameter not in video info for unknown reason; please report this
 issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Cannot download this specific video. I get "token" parameter not in video info for unknown reason

**Comment by cinereous** [comment] 2019-04-24 00:32
Dupe of: https://github.com/ytdl-org/youtube-dl/issues/20758
(Temp?) Fix: https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882

**Comment by MantaRayDeeJay** [comment] 2019-04-24 02:15
Idem under Windows 10 :

youtube-dl.exe 2019.04.17

1) Batch Script Output

[youtube] DMv3lQcSZGM: Downloading webpage
[youtube] DMv3lQcSZGM: Downloading video info webpage
ERROR: DMv3lQcSZGM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-overwrites', '--format', '137+140/136+140/135+140/134+140/best', '--merge-output-format', 'mp4', '--batch-file', '\\\\syno212\\video\\_from Internet\\Clips vidéos\\_Internet Download Sources\\Clips\\Video\\Variété internationale\\2 Unlimited\\Nouveau dossier\\_yt_solo_video.txt', '--verbose']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=DMv3lQcSZGM']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube] DMv3lQcSZGM: Downloading webpage
[youtube] DMv3lQcSZGM: Downloading video info webpage
ERROR: DMv3lQcSZGM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 1693, in _real_extract
youtube_dl.utils.ExtractorError: DMv3lQcSZGM: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

2) Youtube List link ("yt_solo_video.txt")
https://www.youtube.com/watch?v=iPOmFUid3vA&list=OLAK5uy_loCgtMGKQkbLfL2qXvKJHobpRVawNd-FY

**Closed** 2019-04-24 03:00 UTC
