### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Ken-n** [ytdl-org/youtube-dl#31563] opened 2023-02-18 01:22 UTC
## Checklist
- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
Kens-MacBook-Pro:~ ken$ youtube-dl --proxy 127.0.0.1:7890 -F --verbose https://www.youtube.com/watch?v=KyQI6tGHxBU
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'127.0.0.1:7890', u'-F', u'--verbose', u'https://www.youtube.com/watch?v=KyQI6tGHxBU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {u'http': u'127.0.0.1:7890', u'https': u'127.0.0.1:7890'}
[youtube] KyQI6tGHxBU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description
MacOS 10.14.6 just happened that unable to download any YouTube sources.

**Comment by dirkf** [comment] 2023-02-18 02:17
> [x] I've searched the bugtracker for similar bug reports including closed ones

But apparently not. Duplicate of #31530.

**Closed by dirkf** 2023-02-18 02:17 UTC

**Comment by Ken-n** [comment] 2023-02-18 03:27
> #31530

Not for MacOS, Only does Windows have a workaround to fix it.

**Comment by Ken-n** [comment] 2023-02-18 03:28
> > [x] I've searched the bugtracker for similar bug reports including closed ones
> 
> But apparently not. Duplicate of #31530.

Not for MacOS, Only does Windows have a workaround to fix it.
https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435466725

**Comment by JohnTRL** [comment] 2023-02-19 10:50
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`

**Comment by TrHgTung** [comment] 2023-10-31 10:36
> Y'all, go /youtube_dl/extractor/common.py.
> 
> Line 983 change `fatal=True` to `fatal=False`

It works! Thank you so much!

**Comment by dirkf** [comment] 2023-10-31 10:41
No, use the nightly release: #30839, #31530
