### ISSUE TITLE
Downloading from a Youtube URL stopped working

### ISSUE THREAD

**Issue by 4nanook** [ytdl-org/youtube-dl#31676] opened 2023-02-24 09:00 UTC
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -v https://www.youtube.com/watch?v=MWoQW-b6Ph8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=MWoQW-b6Ph8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.7 (CPython) - Linux-6.1.12-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.1, ffprobe 5.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MWoQW-b6Ph8: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

WRITE DESCRIPTION HERE
As of today, I can not download ANY youtube URL, get an error message:
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by rseiffert** [comment] 2023-02-24 09:26
Same here. Stopped working on MacOS Ventura 13.2.1. Installed yt-download via brew

```
❯ youtube-dl -v https://youtu.be/HyHNuVaZJ-k
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/HyHNuVaZJ-k']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ba6d87eed
[debug] Python version 3.11.2 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2
[debug] Proxy map: {}
[youtube] HyHNuVaZJ-k: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by rc24t** [comment] 2023-02-24 10:04
Same on Android 12 with /e/ OS 1.8.1, yt being accessed through Seal interface.

**Comment by MattiSG** [comment] 2023-02-24 10:16
After a first pass of research, this seems to be a duplicate of https://github.com/ytdl-org/youtube-dl/issues/31530, which has a fix in https://github.com/ytdl-org/youtube-dl/pull/31675. The blocking point [seems to be](https://github.com/ytdl-org/youtube-dl/issues/31585) CI pipeline delivery rather than the bugfix itself.

@4nanook could you please confirm and, if that is the case, close this issue?

Other people passing by: please prefer emoji reactions (that don't send notifications) over comments unless you add specific information. Let's all do our part in not drowning open-source maintainers 🙂

**Comment by TheNeoBurn** [comment] 2023-02-24 10:25
Same on Debian. I solved this by replacing the RegEx in `extractor/youtube.py` inline `1794`:

```diff
-            'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
+            'uploader_id': self._search_regex(r'/@([^"/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
```

The background: There seems to be no uploader reference in the page in the format `/channel/uploader_id` or `/user/uploader_id` anymore but the format present is `/@uploader_id`. I don't know how to request the change but posting this here might help?!

**Closed** 2023-02-24 10:49 UTC

**Comment by dirkf** [comment] 2023-02-24 10:53
> [x] I've searched the bugtracker for similar bug reports including closed ones

That was supposed to be

> ... a first pass of research ...

as requested (to put it politely) in #30839.
