### ISSUE TITLE
i don't know what's happen.ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError());

### ISSUE THREAD

**Issue by jeffrey126** [ytdl-org/youtube-dl#26904] opened 2020-10-16 14:15 UTC
E:\DOWNLOAD\youtube-dl>youtube-dl -f 95 -g https://www.youtube.com/watch?v=dWzUzjgTr_Q
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
DEBUG:
E:\DOWNLOAD\youtube-dl>youtube-dl -f 95 -g https://www.youtube.com/watch?v=dWzUzjgTr_Q -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '95', '-g', 'https://www.youtube.com/watch?v=dWzUzjgTr_Q', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 2020-10-14-git-6bdfea8d4b-full_build-www.gyan.dev, ffprobe 2020-10-14-git-6bdfea8d4b-full_build-www.gyan.dev
[debug] Proxy map: {'https': 'https://127.0.0.1:10809', 'http': 'http://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
---------------------
Please help me~

**Comment by Chew** [comment] 2020-10-16 15:14
Duplicate of #23638

**Closed** 2020-10-17 10:21 UTC
Labels: question
