### ISSUE TITLE
How to download from Arte ?

### ISSUE THREAD

**Issue by Phil171** [ytdl-org/youtube-dl#31020] opened 2022-06-11 10:39 UTC
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi gentlemen,
I cannot download movie from Arte, my youtube-dl is up to date and I can view the movie I want to download in the Arte viewer.
I use Xubuntu 20.04 up to date too.

Here is the return from command in Terminal :
`phil@phil-XPS-15-7590:~$ youtube-dl --verbose https://www.arte.tv/fr/videos/098039-000-A/cleves/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.arte.tv/fr/videos/098039-000-A/cleves/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.13.0-48-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[ArteTV] 098039-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

phil@phil-XPS-15-7590:~$ 
`
My english is not very good, so excuse my faults.
Is there some trick to download, I've search in this site with "Arte" word but not found or understood, sorry.
Best regards from France, Philippe

**Comment by dirkf** [comment] 2022-06-11 12:44
Arte changed their interface, and the yt-dl extractor no longer works. There is a PR for the derived yt-dlp project which we'll pull when it's stable. Meanwhile you can try installing and testing the yt-dlp PR (post in that thread).

See #30878 for more details.

**Comment by dirkf** [comment] 2022-11-30 19:45
And duplicate of #30919.

**Closed by dirkf** 2022-11-30 19:45 UTC
Labels: question
