### ISSUE TITLE
[Udemy] ERROR: Unable to download webpage: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by fhcaglayan** [ytdl-org/youtube-dl#29915] opened 2021-09-06 14:00 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```

C:\>youtube-dl.exe -u **** -p **** https://www.udemy.com/course/learn-advanced-java/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/course/learn-advanced-java/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default```
```

## Description

I was trying to download the learn advanced Java course which I have bought from Udemy for offline watching purposes. However, youtube-dl gives me an error when trying to do so.

**Comment by Zeddex** [comment] 2021-09-08 10:46
I have the same error

**Comment by pbpalomino** [comment] 2021-09-08 18:07
Your URL is not right.

try 

`youtube-dl.exe -u **** -p **** https://www.udemy.com/learn-advanced-java/ --verbose`

**Comment by fhcaglayan** [comment] 2021-09-08 18:19
Same problem unfortunately:

C:\>youtube-dl.exe -u **** -p **** https://www.udemy.com/learn-advanced-java/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/learn-advanced-java/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by fhcaglayan** [comment] 2021-09-08 18:20
If you want in private I can share my account details with a temporary password so you can try for yourself as well.

**Comment by pbpalomino** [comment] 2021-09-08 18:56
@fhcaglayan may be an unescaped string from you password

Try using cookies.

this works on my machine

```
youtube-dl ^
--cookies udemy_cookies.txt ^
-o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' ^
'YOURURL' ^
--verbose
```
`^` splits large lines.

**Comment by fhcaglayan** [comment] 2021-09-08 19:26
I have also tried with password temp1234... Might that also be unescaped?

**Comment by Michael-Obele** [comment] 2021-09-23 12:57
Having the same error over here. No solutions yet?

**Comment by dirkf** [comment] 2021-11-17 15:33
See also #29410.

**Comment by brskl88** [comment] 2021-11-28 10:10
Hey everybody.I have almost the same problem.My problem is when i start to download it downloads first video without any problems.It is on my hard disk.But when it starts to download second one it gives the error.I use cookie method and i export the cookie file by "Export Cookies" extension on Firefox.But on my case it gives another error when it tries to download second video.It says 

[udemy] 15779426: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug

So i add my verbose output here.

**Verbose Output**

```
youtube-dl --cookies cookie.txt --verbose https://www.udemy.com/the-advanced-cryptocurrency-trading-course-with-strategies/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookie.txt', '--verbose', 'https://www.udemy.com/the-advanced-cryptocurrency-trading-course-with-strategies/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-27-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] the-advanced-cryptocurrency-trading-course-with-strategies: Downloading webpage
[udemy:course] 2500544: Downloading course curriculum
[download] Downloading playlist: 2500544
[udemy:course] playlist 2500544: Collected 39 video ids (downloading 39 of them)
[download] Downloading video 1 of 39
[udemy] 15929840: Downloading webpage
[udemy] 15929840: Downloading lecture JSON
[udemy] 19874331: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/19874331/files/2019-09-10_20-55-46-ceaae9486ee7f497888103ddf974b304/2/hls/AVC_1920x1080_800k_AAC-HE_64k/aa0025a2af4592ba37f10526c90a4b4ff6c6.m3u8?provider=cdn77&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0wOS0xMF8yMC01NS00Ni1jZWFhZTk0ODZlZTdmNDk3ODg4MTAzZGRmOTc0YjMwNC8yLyIsImV4cCI6MTYzODEwOTM4MH0.7JGx6OM1vh3_hOMK2Pt3W18fYzckuL3FdWkljG4LK7A&v=1'
[download] What You Will Learn in This Course-19874331.mp4 has already been downloaded
[download] 100% of 19.40MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:What You Will Learn in This Course-19874331.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "What You Will Learn in This Course-19874331.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:What You Will Learn in This Course-19874331.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:What You Will Learn in This Course-19874331.temp.mp4'
[download] Downloading video 2 of 39
[udemy] 15779426: Downloading webpage
[udemy] 15779426: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/udemy.py", line 408, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

So is there any solution to fix it?Or do i make any mistakes when writing my command?Thank you.

**Comment by dirkf** [comment] 2021-11-28 11:47
That looks like #25656, not that it helps.

**Comment by brskl88** [comment] 2021-11-28 13:40
> That looks like #25656, not that it helps.

Thank you for the response.I already removed that part of the link as it says to remove "/course/".but it didn't fix the problem.is there another solution to fix this?the interesting thing is everything works for first video and it downloads it.but for second one it gives the error.

**Comment by dirkf** [comment] 2021-11-28 22:39
Try loading the failing video in your browser. That may reveal what the problem is.

**Comment by razafinarivohanania** [comment] 2021-12-03 05:03
I'm facing with the same issue descripted on topic also whatever i use my username/password or using cookies.

**Comment by zdegeorge** [comment] 2021-12-23 14:56
I was having the `403` issue, and then I was having an extract login-form form issue, but I was able to resolve both of them and get youtube-dl working with Udemy. 

First I was able to resolve the 403 by logging into the website in chrome and then downloading the cookie file and including it with the '--cookie /path/to/cookie.txt' option. (See [How do I pass cookies to youtube-dl](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl)). But then I was still getting the error:

```
ERROR: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

It turns out this was caused because in my youtube-dl request I was passing `-u username -p password` options to the request which was causing the login popup preventing the download. 

Also to note, in the URL for a course in Udemy, i.e. `https://www.udemy.com/course/understanding-typescript/`, there is an extra `/course/` that needs to be removed for the request. So the URL should instead look like `https://www.udemy.com/understanding-typescript/`.

Put all this together and a valid request should look like:
```
youtube-dl --cookie /path/to/cookies.txt -o '~/your/path/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/COURSE-NAME/
```
Where you replace the path to the cookie file, the path to the output directory, and the course name in the Udemy URL. 

Hope this helps :)

**Comment by dirkf** [comment] 2021-12-23 15:17
>... in the URL for a course in Udemy, i.e. https://www.udemy.com/course/understanding-typescript/, there is an extra /course/ that needs to be removed for the request ...

This should be handled automatically. Could you post some logs showing behaviour with/without `course/`?

**Comment by dirkf** [comment] 2021-12-29 14:54
On reflection I can't see how stripping `course/` could affect the extraction **unless** through redirection back to the unstripped URL.

There seem to be two major problems here:
* the extractor hasn't been properly updated for more than a year, judging by old failed PRs that appear to target the current site structure;
* yt-dl web requests are being subjected to some sort of protocol violation presumably imposed through Cloudflare, so that any request may randomly be rejected with 403 (this is how redirection might have an effect).

This happens despite trying Python versions from 2.7 to 3.9, removing the `Accept:` header, varying the UA, ...

From the metadata, the site may possibly also be serving videos with DRM.

It has an optional Download button that the Instructor can enable. It may be easier to ask for that.

**Comment by thelonghop** [comment] 2021-12-31 16:03
I'm getting this error as well.  Have tried with -u/-p and with cookies, with and without /courses/

$ youtube-dl --verbose --cookies ./network008 -o '%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s' https://www.udemy.com/comptia-network-n10-008/
[debug] System config: [u'-o', u'/home/user1/Videos/ytdl/%(title)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'./network008', u'-o', u'%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s. %(title)s.%(ext)s', u'https://www.udemy.com/comptia-network-n10-008/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.13.0-22-generic-x86_64-with-LinuxMint-20.2-uma
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] comptia-network-n10-008: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dirkf** [comment] 2021-12-31 16:18
Looks like the same problem. If someone can work out how to fix Cloudflare's protocol violation (2nd bullet [above](https://github.com/ytdl-org/youtube-dl/issues/29915#issuecomment-1002633321)) it could be possible to make further progress.

**Comment by 89z** [comment] 2021-12-31 21:54
I would be wary of any patches like this one: https://github.com/ytdl-org/youtube-dl/issues/29915#issuecomment-1000370573

@dirkf is a known copyright violator https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-958689745

**Comment by dirkf** [comment] 2022-01-01 02:15
Someone hasn't read https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-959870082.

PR #30184 doesn't offer code derived from VLC for merging.

**Comment by 89z** [comment] 2022-01-01 02:28
> PR #30184 doesn't offer code derived from VLC for merging.

Yes it does.

**Comment by dirkf** [comment] 2022-01-01 02:54
Read the PR. The code offered for merge is based on yt-dlp now. And you still haven't read the linked comment.

**Comment by 89z** [comment] 2022-01-01 02:57
> Read the PR. The code offered for merge is based on yt-dlp now. And you still haven't read the linked comment.

Please dont tell me what Ive read and havent read. I read the thread, where you repeatedly tried to claim credit for a derived work in violation of VLC copyright. And if you changed the code away from that, you didnt document it anywhere, as I checked the original comment, and every single commit message.

**Comment by dirkf** [comment] 2022-01-01 03:21
You clearly haven't checked these most recent commits (the last in particular), nor read the updated description in the PR:
>@dirkf Back-port JS interpreter upgrade from yt-dlp PR ytdl-org#1437 d577b92
>@dirkf Handle default in switch better 116500e
>@dirkf Fix splice to handle float e74c63b
>@dirkf Back-port test_youtube_signature.py from yt-dlp and fix JSInterp acco… ff2dcd5
>@dirkf Refactor JSInterpreter._separate c3b0045
>@dirkf Implement n-param descrambling using JSInterp 905d1d2

No-one tried to claim credit for anything, as credit for the procedure in the original work-around was specifically attributed to the youtube.lua author, whose wishes were respected as soon as they were clarified.

**Comment by 89z** [comment] 2022-01-01 03:27
> No-one tried to claim credit for anything, 

@dirkf it hurts me when you continuously try to deceive people:

> I am the original author of this code and I am willing to release it under Unlicense

**Comment by dirkf** [comment] 2022-01-01 03:38
He **still** hasn't read https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-959870082. Also, https://www.goodreads.com/quotes/5765172-sir-i-have-found-you-an-argument-but-i-am.

**Comment by 89z** [comment] 2022-01-01 03:55
@dirkf Instead of linking to your own comment, maybe you can link to where the original author granted you permission to relicense your derived work?

**Comment by dirkf** [comment] 2022-01-01 04:05
No work from VLC is being relicensed, but https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-958689745.

**Comment by 89z** [comment] 2022-01-01 04:19
@dirkf I am confused, as your link says the exact opposite of what youre suggesting. It says that you arent the author, and you arent authorized to publish that code as UniLicense.

**Comment by dirkf** [comment] 2022-01-01 04:44
The original Python code for PR #30184 that became mildly controversial and to which the [LUA author's comment](https://github.com/ytdl-org/youtube-dl/pull/30184#issuecomment-958689745) applies (also note the words "Not sure that ...") was designed and written on the possibly naive assumption that the LUA author had released any copyright attaching to the offered model descrambling code, whether by accepting a fair use exception or by relicensing.

I am, as the PR template, perhaps inadequately, asks, the author of the Python code. The PR as it stands absolutely conforms to the LUA author's wishes according to the linked comment and later clarification. Neither the original Python code for PR #30184 nor any later version adapted against YT changes is offered for merging.

**Comment by 89z** [comment] 2022-01-01 05:04
You seem to be doing a lot of assuming here, with a lack of actual evidence to back up what you're saying. Here you just assumed that you could just take some GPL code, rewrite it in Python, and slap whatever license you want on it:

> was designed and written on the possibly naive assumption that the LUA author had released any copyright attaching to the offered model descrambling code, whether by accepting a fair use exception or by relicensing.

It seems even now you still think that, based on your tone and wording. Newsflash, you cant do that. It would be best if you just closed the PR, or mark it as draft, so that people aren't confused by the license violation currently existing.

> I am, as the PR template, perhaps inadequately, asks, the author of the Python code. The PR as it stands absolutely conforms to the LUA author's wishes according to the linked comment and later clarification. Neither the original Python code for PR #30184 nor any later version adapted against YT changes is offered for merging.

As mentioned above, if you don't plan on merge, PR should be closed or marked as draft. Otherwise you're just perpetuation the idea that its a valid PR, when it seems by your own admission its not. Nothing is to stop you from recommending people use it as a drop it, but just the act of leaving it open proves you haven't accepted the fact that it cant legally be merged, as you've yet to get permission from the author to do that.

**Comment by dirkf** [comment] 2022-01-01 11:53
The author of the LUA code posted a suggestion that the same approach could be used in yt-dl. As it became clear that this was not offered with a copyright release, should one have been required, the code finally offered for merging is **completely different**.

**Comment by agails** [comment] 2022-02-09 13:17
> I was having the `403` issue, and then I was having an extract login-form form issue, but I was able to resolve both of them and get youtube-dl working with Udemy.
> 
> First I was able to resolve the 403 by logging into the website in chrome and then downloading the cookie file and including it with the '--cookie /path/to/cookie.txt' option. (See [How do I pass cookies to youtube-dl](https://github.com/ytdl-org/youtube-dl#user-content-how-do-i-pass-cookies-to-youtube-dl)). But then I was still getting the error:
> 
> ```
> ERROR: Unable to extract login-form form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ```
> 
> It turns out this was caused because in my youtube-dl request I was passing `-u username -p password` options to the request which was causing the login popup preventing the download.
> 
> Also to note, in the URL for a course in Udemy, i.e. `https://www.udemy.com/course/understanding-typescript/`, there is an extra `/course/` that needs to be removed for the request. So the URL should instead look like `https://www.udemy.com/understanding-typescript/`.
> 
> Put all this together and a valid request should look like:
> 
> ```
> youtube-dl --cookie /path/to/cookies.txt -o '~/your/path/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/COURSE-NAME/
> ```
> 
> Where you replace the path to the cookie file, the path to the output directory, and the course name in the Udemy URL.
> 
> Hope this helps :)

Thank you so much, your instructions worked like a charm! This should be highlighted on the main page!

**Comment by nicheath** [comment] 2022-03-05 19:56
youtube-dl 2021.12.17 still has this problem however using --cookies is a workaround.

**Comment by pashakiz** [comment] 2022-03-06 16:34
What's wrong?

```
youtube-dl --cookies c:\udemy_cookies.txt -o 'E:/Udemy/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/typescript-full/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'c:\\udemy_cookies.txt', '-o', 'E:/Udemy/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/typescript-full/', '--verbose']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] typescript-full: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\udemy.py", line 442, in _real_extract
    course_id, title = self._extract_course_info(webpage, course_path)
  File "c:\python39\lib\site-packages\youtube_dl\extractor\udemy.py", line 78, in _extract_course_info
    course_id = course.get('id') or self._search_regex(
  File "c:\python39\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by nicheath** [comment] 2022-03-08 19:33
> What's wrong?
youtube-dl 2021.12.17 still has a problem using -u and -p

note
> however using --cookies is a workaround.

**Comment by dirkf** [comment] 2022-03-08 23:59
> What's wrong?
> 
>```
> ...
> ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ...
>```
See #30719.

**Comment by GwamakaCharles** [comment] 2022-05-16 08:55
### TESTED AND WORKS ON A MAC OS

1. Install youtube-dl through `brew install youtube-dl`. If you used curl, you can remove it through `rm -rf /usr/local/bin/youtube-dl`.
2. If you face symlink permissions ERRORS, run `sudo chown -R $(whoami) $(brew --prefix)/*` then `brew doctor` and fix each error according to the instructions.
3. `brew cleanup`
4. `brew link youtube-dl`
5. `cd .` (navigate to your favorable location that you wish to put your videos folder)
6. Login to udemy and get site cookies text file. I used [Get Cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/).
7. `mkdir MyVideos`. (name it as you wish)
8. `youtube-dl --cookies udemy.com_cookies.txt -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/<course-name>`
9. Done! 🎮

**Comment by niharika1102** [comment] 2023-04-13 08:35
> Same problem unfortunately:
> 
> C:>youtube-dl.exe -u **** -p **** https://www.udemy.com/learn-advanced-java/ --verbose [debug] System config: [] [debug] User config: [] [debug] Custom config: [] [debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/learn-advanced-java/', '--verbose'] [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252 [debug] youtube-dl version 2021.06.06 [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362 [debug] exe versions: none [debug] Proxy map: {} [udemy:course] Downloading login popup ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 634, in _request_webpage File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen File "C:\Python\Python34\lib\urllib\request.py", line 470, in open File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response File "C:\Python\Python34\lib\urllib\request.py", line 508, in error File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

Same issue for me

**Comment by dirkf** [comment] 2023-04-13 17:45
Still duplicate of #29410.

**Closed by dirkf** 2023-04-13 17:45 UTC
Labels: broken-IE, account-needed, duplicate
