### ISSUE TITLE
Playlist Names Issue

### ISSUE THREAD

**Issue by walksonair** [ytdl-org/youtube-dl#27044] opened 2020-11-17 16:17 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2020.11.17**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
user@Comp-Ether YouTube Videos % youtube-dl -o '%(playlist)s/%(playlist_index)s - %(upload_date)s_%(title)s.%(ext)s' --add-metadata --write-auto-sub -v -i 'https://www.youtube.com/c/ShaanGeo/playlists' 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(playlist)s/%(playlist_index)s - %(upload_date)s_%(title)s.%(ext)s', '--add-metadata', '--write-auto-sub', '-v', '-i', 'https://www.youtube.com/c/ShaanGeo/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.17
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] ShaanGeo: Downloading webpage
[download] Downloading playlist: Shaan Geo - Playlists
[youtube:tab] playlist Shaan Geo - Playlists: Downloading 15 videos
[download] Downloading video 1 of 15
[youtube:tab] PLDNT5GdnIF8DtB_OTR8sDdudDyMefQ160: Downloading webpage
[download] Downloading playlist: PLDNT5GdnIF8DtB_OTR8sDdudDyMefQ160
[youtube:tab] playlist PLDNT5GdnIF8DtB_OTR8sDdudDyMefQ160: Downloading 5 videos
[download] Downloading video 1 of 5
[youtube] rIOTFWy-q3c: Downloading webpage
[youtube] rIOTFWy-q3c: Looking for automatic captions
[youtube] rIOTFWy-q3c: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: PLDNT5GdnIF8DtB_OTR8sDdudDyMefQ160/1 - 20200206_പാസ്ത പായസം _ Pasta Payasam _ Macaroni Payasam Malayalam Recipe.en.vtt
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1605650906/ei/evWzX8CqH8XCkgbIh5PIDA/ip/50.34.61.154/id/ac8393156cbeab77/source/youtube/requiressl/yes/playback_host/r1---sn-nx5s7n7z.googlevideo.com/mh/SR/mm/31%2C29/mn/sn-nx5s7n7z%2Csn-nx5e6n76/ms/au%2Crdu/mv/m/mvi/1/pl/16/tx/23951656/txs/23951655%2C23951656%2C23951657%2C23951658%2C23951659%2C23951660%2C23951661/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1132500/vprv/1/mt/1605629198/fvip/1/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgS2Dug_ycqnTnA4-nELXzZXroHoPLCQqCSz8rF2oFQ3cCIQD2yoj6bHh8hFT-NUWr2_pun2uRQpI_Fo6h7BcIE0jPQg%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgHC0zSzPmD3UvDeG2K6vDL6DhIxe8yFACgYZ1Vwm1gYcCIAJDDlGM-RJ3von2HKhAWvqtlHKFJLBGCYPh9Weh0Xqa'
[dashsegments] Total fragments: 46
[download] Destination: PLDNT5GdnIF8DtB_OTR8sDdudDyMefQ160/1 - 20200206_പാസ്ത പായസം _ Pasta Payasam _ Macaroni Payasam Malayalam Recipe.f137.mp4
[download]  32.6% of ~76.29MiB at 67.95MiB/s ETA 00:11^C
ERROR: Interrupted by user

```

## Description

When trying to download an entire playlist, the playlist name doesn't resolve to proper name but rather to a playlist ID which is less useful. This used to work before where I could get a folder of different playlists properly named but now the folder names of playlists are human unidentifiable.

**Comment by dstftw** [comment] 2020-11-17 16:19
Duplicate of #27015.

**Closed by dstftw** 2020-11-17 16:19 UTC
