### ISSUE TITLE
Some specific videos not downloading

### ISSUE THREAD

**Issue by Kochise** [ytdl-org/youtube-dl#30352] opened 2021-12-11 11:19 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.06.06**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

- - - 8< - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-v', '--ignore-errors', '--continue', '--hls-prefer-native', '--no-overwrites', '--no-progress', '--no-mark-watched', '--no-call-home', '--all-subs', '--sub-format', 'srt/best', '--write-description', '--write-thumbnail', '--download-archive', 'youtube-dl_done.txt', '--batch-file', 'youtube-dl_videos.txt']
[debug] Command-line args: ['-f', 'bestvideo[height<=1080][fps<50][ext=mp4]+bestaudio[ext=m4a]/mp4', '--merge-output-format', 'mp4', '--config-location', 'youtube-dl_videos.cnf']
[debug] Batch file urls: ['Molly Rocket (737 videos)', 'https://www.youtube.com/c/MollyRocket/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n4.4.1-20211102, ffprobe n4.4.1-20211102
[debug] Proxy map: {}

[youtube] fDSVYJMXnIQ: Downloading webpage
[youtube] fDSVYJMXnIQ: Downloading player dc05ba20
[info] Writing video description to: Handmade Hero Day 488 - Adding an In-Game Editor-fDSVYJMXnIQ.description
[youtube] fDSVYJMXnIQ: Downloading thumbnail ...
[youtube] fDSVYJMXnIQ: Writing thumbnail to: Handmade Hero Day 488 - Adding an In-Game Editor-fDSVYJMXnIQ.jpg
[debug] Invoking downloader on 'https://rr1---sn-capm-vnae.googlevideo.com/videoplayback?requiressl=yes&dur=8288.896&mt=1639220688&lmt=1543251356823855&id=o-AKlX1JPKwATYAal_sgycgPQ1koWpbplAEbHHiNU8GML1&source=youtube&ratebypass=yes&initcwndbps=1862500&ei=2Ya0YZnkGMv5yQWmn4moBA&txp=5432432&mime=video%2Fmp4&ns=e_2tAP-gfCF0w38iVOevIcUG&fexp=24001373%2C24007246&mh=cQ&lsig=AG3C_xAwRQIgPfUvKI_EkrIMEuvyJXZqkzG-6txWE89uK3gS6tyUL7ICIQCCdc7d6x4NthqEKhl84QvM4sCaSzE5N2Vw3_YcQfuPrA%3D%3D&mm=31%2C29&pl=22&itag=22&mvi=1&vprv=1&mn=sn-capm-vnae%2Csn-5go7yne6&expire=1639242553&n=NdLqls-3fbIHEA&ip=176.125.235.114&ms=au%2Crdu&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&mv=m&fvip=1&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&sig=AOq0QJ8wRAIgJQFmEhZ0UlFAbhfZ_lXEunNqC4qlqts4wMbwrQ1c5RwCIBFUQVJ5O5xv4k23z1-9QgZ0f5Hz63nS7URAUBEirXGx'
[download] Destination: Handmade Hero Day 488 - Adding an In-Game Editor-fDSVYJMXnIQ.mp4
[download] Got server HTTP error: Downloaded 3992940 bytes, expected 304187881 bytes. Retrying (attempt 1 of 10)...

- - - 8< - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[debug] System config: []
[debug] User config: []
[debug] Custom config: ['-v', '--ignore-errors', '--continue', '--hls-prefer-native', '--no-overwrites', '--no-progress', '--no-mark-watched', '--no-call-home', '--all-subs', '--sub-format', 'srt/best', '--write-description', '--write-thumbnail', '--download-archive', 'youtube-dl_done.txt', '--batch-file', 'youtube-dl_videos.txt']
[debug] Command-line args: ['-f', 'bestvideo[height<=1080][fps<50][ext=mp4]+bestaudio[ext=m4a]/mp4', '--merge-output-format', 'mp4', '--config-location', 'youtube-dl_videos.cnf']
[debug] Batch file urls: ['Alex Ridgeway Farrier (65 videos)', 'https://www.youtube.com/c/AlexRidgewayFarrier/videos', 'https://www.youtube.com/watch?v=j4M4QNzyriY']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg n4.4.1-20211102, ffprobe n4.4.1-20211102
[debug] Proxy map: {}

[youtube] j4M4QNzyriY: Downloading webpage
[youtube] j4M4QNzyriY: Downloading MPD manifest
[info] Writing video description to: WHATS INSIDE A HORSE'S HOOF - BASIC HOOF ANATOMY-j4M4QNzyriY.description
[youtube] j4M4QNzyriY: Downloading thumbnail ...
[youtube] j4M4QNzyriY: Writing thumbnail to: WHATS INSIDE A HORSE'S HOOF - BASIC HOOF ANATOMY-j4M4QNzyriY.webp
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1639242908/ei/PIi0YbapNNeCyQWKzI-4Ag/ip/176.125.235.114/id/8f833840dcf2ae26/source/youtube/requiressl/yes/playback_host/r1---sn-capm-vnae.googlevideo.com/mh/G9/mm/31%2C29/mn/sn-capm-vnae%2Csn-5goeen7k/ms/au%2Crdu/mv/m/mvi/1/pl/22/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2808750/vprv/1/mt/1639220927/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAP54KV67LdGKSuGEks3FNpanvFuZdnlKF91Dbha2hj7gAiATzRP8L_V3ot051lnEAGTU1AxyBU7YNlqFXSvJvuSciw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAOtSmWYY5rLoPQkZi4FKkq5o6u5NnknX7XTm91aGJ153AiByk7CjZpZLl4a3P5JOux0jd97RyHwCjaYWvaJ0Ta9KFw%3D%3D'
[dashsegments] Total fragments: 120
[download] Destination: WHATS INSIDE A HORSE'S HOOF - BASIC HOOF ANATOMY-j4M4QNzyriY.f136.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
[debug] Invoking downloader on 'https://r1---sn-capm-vnae.googlevideo.com/videoplayback?lmt=1600694119768799&vprv=1&id=o-AE0riXAICsLnJvYUywWXr4oCPW17DW-fWRbwq7Jr9_Xz&clen=9746456&ms=au%2Crdu&ip=176.125.235.114&mt=1639220927&mh=G9&itag=140&ns=1qces07zQXPPBE-P1XxA0AYG&mime=audio%2Fmp4&mn=sn-capm-vnae%2Csn-5goeen7k&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&pl=22&source=youtube&otfp=1&txp=1211222&mm=31%2C29&fvip=1&gir=yes&dur=602.186&fexp=24001373%2C24007246&requiressl=yes&mv=m&mvi=1&expire=1639242908&keepalive=yes&n=X_A-_I8HFecLpg&ei=PIi0YbapNNeCyQWKzI-4Ag&sig=AOq0QJ8wRAIgRjyZGCo36j7GU5VXr0R2rNa4eASHa0IM6cDR85YaMT8CIELekaUlcpKwTLoliyctLPP6HAULjcfmClv3vQVHZ17i&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&c=WEB&initcwndbps=2808750&lsig=AG3C_xAwRQIhANeGPcJBaeM_RD3KRxVtAfX5zfh9_eOs644Sq9QTjRaFAiAYlePKvmT0_PDC7ujEpGmqXjNo91AVrYREKSpqFGilrA%3D%3D'
[download] Destination: WHATS INSIDE A HORSE'S HOOF - BASIC HOOF ANATOMY-j4M4QNzyriY.f140.m4a
[download] Download completed

- - - 8< - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

## Description

**SOME** specific videos do not get downloaded.

**HOWEVER** they works in the browser or using https://loader.to/en36/1080p-video-downloader.html

Add your own bellow.

**Comment by dirkf** [comment] 2021-12-11 14:07
Not reproducible without the verbose log including the prologue showing the options selected, like this:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '299', '--ignore-config', 'j4M4QNzyriY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] j4M4QNzyriY: Downloading webpage
...
```
Include the actual command line too if it doesn't include private information!

**Comment by 89z** [comment] 2021-12-11 14:07
You should provide the command you used

**Comment by Kochise** [comment] 2021-12-11 17:48
Ok, it was in stderr, not in stdout...

Edited the post above.

**Comment by dirkf** [comment] 2021-12-11 20:33
With your settings yt-dl went for format 136+140:
```
[info] Available formats for j4M4QNzyriY:
format code  extension  resolution note
139          m4a        audio only DASH audio   50k , m4a_dash container, mp4a.40.5 (22050Hz), 3.50MiB
251          webm       audio only tiny   98k , webm_dash container, opus @ 98k (48000Hz), 7.04MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 9.29MiB
278          webm       256x144    DASH video   95k , webm_dash container, vp9, 30fps, video only
160          mp4        256x144    DASH video  108k , mp4_dash container, avc1.4d400b, 30fps, video only
242          webm       426x240    DASH video  220k , webm_dash container, vp9, 30fps, video only
133          mp4        426x240    DASH video  242k , mp4_dash container, avc1.4d400c, 30fps, video only
243          webm       640x360    DASH video  405k , webm_dash container, vp9, 30fps, video only
134          mp4        640x360    360p  425k , mp4_dash container, avc1.4d401e@ 425k, 30fps, video only, 30.51MiB
244          webm       854x480    DASH video  752k , webm_dash container, vp9, 30fps, video only
135          mp4        854x480    DASH video 1155k , mp4_dash container, avc1.4d4014, 30fps, video only
247          webm       1280x720   DASH video 1505k , webm_dash container, vp9, 30fps, video only
136          mp4        1280x720   DASH video 2310k , mp4_dash container, avc1.4d4016, 30fps, video only
302          webm       1280x720   DASH video 2646k , webm_dash container, vp9, 60fps, video only
298          mp4        1280x720   DASH video 3465k , mp4_dash container, avc1.4d400d, 60fps, video only
299          mp4        1920x1080  1080p60 4377k , mp4_dash container, avc1.64002a@4377k, 60fps, video only, 314.20MiB
303          webm       1920x1080  DASH video 4410k , webm_dash container, vp9, 60fps, video only
18           mp4        640x360    360p  554k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 2496k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```
And I got the same result ("HTTP Error 404: Not Found. Retrying fragment 1").

There is some server issue with format 136 in this video at YT. This doesn't exclude the possibility of deliberate misconfiguration in favour of YT web clients, but it would be strange if only this format, and not eg 1080 formats, were targeted, as seems to be the case.

Add `[format_id!=136]` (but you'll get 135 @ 854x480 instead) or just save time by putting `22/` at the beginning of your format option, so you get the pre-merged version if available (and if YT doesn't suddenly change the definition of format 22).

**Comment by Kochise** [comment] 2021-12-12 06:45
1280x720 ? I requested 1920x1080, but I see that it is only available in 60 fps. Strange that they do not offer a lower frame rate.

Anyway, how defining a list of format options, from best to lowest and ytdl trying each until it finds the most suitable one ?

**Comment by dirkf** [comment] 2021-12-12 12:33
That's what the `/`does. So in your example (your command-line format option ends in `/mp4`, which should probably have been `/best[ext=mp4]`):
```
-f 'bestvideo[ext=mp4][height=1080][fps=50]+bestaudio[ext=m4a]/bestvideo[ext=mp4][height=1080][fps=60]+bestaudio[ext=m4a]/bestvideo[ext=mp4][height<=?1080][fps<=?50]+bestaudio[ext=m4a]/best[ext=mp4]'
```
I don't say that this is convenient but generally it's more of a problem for completist mass downloaders, since the defaults, perhaps slightly amended to exclude webm+opus codecs, are normally adequate and can be overridden if necessary by manually specifying a format id (eg 22).

Traditionally the USA likes 60fps since the electricity uses 60Hz.

**Comment by Kochise** [comment] 2021-12-12 13:12
"completist mass downloaders" : I'd prefer "completist mass archivers"

Try downloading mfGPMJ8A0QY or CMGRa4_UjE4 for example...

60Hz or not, 30 fps is more than enough, even films are usually 24 fps.

But the difference between 1080p and 720p is quite noticeable though.

Thank for the hint, I'd like not to be too much dependent on yt's will to keep their code (ie. 22) constant across time.

**Comment by Kochise** [comment] 2021-12-17 13:18
Same for DRE0NlRLZVk and a few other from the same channel, mp4 or webm.

**Comment by dirkf** [comment] 2022-01-29 19:29
> BTW, what the question mark for in format description (ie. [fps<=?50]) ?

It means that if the item (`fps`, here) is missing, the filter passes. Otherwise, a missing value makes the filter fail. So for instance, you can apply a filter for `fps` to video+audio metadata without excluding all the audio items.

**Closed by dirkf** 2022-01-29 19:29 UTC
