### ISSUE TITLE
RedBullTV

### ISSUE THREAD

**Issue by dtykhon** [ytdl-org/youtube-dl#23283] opened 2019-12-01 14:27 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl "https://www.redbull.com/int-en/episodes/the-rocky-mountains-traverse-explorers-documentaries-s03-e05" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.redbull.com/int-en/episodes/the-rocky-mountains-traverse-explorers-documentaries-s03-e05', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[generic] the-rocky-mountains-traverse-explorers-documentaries-s03-e05: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-rocky-mountains-traverse-explorers-documentaries-s03-e05: Downloading webpage
[generic] the-rocky-mountains-traverse-explorers-documentaries-s03-e05: Extracting information
ERROR: Unsupported URL: https://www.redbull.com/int-en/episodes/the-rocky-mountains-traverse-explorers-documentaries-s03-e05
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.redbull.com/int-en/episodes/the-rocky-mountains-traverse-explorers-documentaries-s03-e05
```

## Description

This is FIRST Redbull.com report in 2019

**Comment by sergey-rufanov** [comment] 2019-12-02 03:16
Duplicate of #22037
They changed domain from from redbull.tv to redbull.com, and slightly changed url-s for videos.

**Closed** 2019-12-02 06:51 UTC
