### ISSUE TITLE
This repo is dead! RIP youtube-dl, please use yt-dlp repo

### ISSUE THREAD

**Issue by filixm** [ytdl-org/youtube-dl#30022] opened 2021-09-26 03:53 UTC

**Comment by rautamiekka** [comment] 2021-09-26 04:37
[Not so much dead as inactive through circumstances outta control.](https://github.com/ytdl-org/youtube-dl/issues/29965#issuecomment-922377500)

**Comment by filixm** [comment] 2021-09-26 04:42
No, its dead dead, like as in not living any more, circumstances are completely irrelevant.  Zeds dead baby, zeds dead.

**Comment by MuenchenSued** [comment] 2021-09-26 09:29
yt-dlp contains all of the latest youtube-dl functions:

> Merged with youtube-dl commit/379f52a: (v2021.06.06) You get all the latest features and patches of youtube-dl in addition to all the features of youtube-dlc

**Comment by dirkf** [comment] 2021-09-26 10:48
Duplicate of #29956

**Comment by pukkandan** [comment] 2021-09-26 14:10
Hopefully the project isn't dead and the maintainers will return. We atleast know they are in good health thanks to https://github.com/ytdl-org/youtube-dl/issues/29965#issuecomment-922377500

In either case, please do not open issues like this. There are already multiple issues discussing the same thing https://github.com/ytdl-org/youtube-dl/issues/29965 https://github.com/ytdl-org/youtube-dl/issues/29872 https://github.com/ytdl-org/youtube-dl/issues/29753. Opening more issues for the same serves no purpose other than bloat the issue tracker

**Comment by 89z** [comment] 2021-09-26 14:28
This whole issue is kind of disgusting.

@filixm, at the time of your post, it appears you didnt even know the circumstances for the lack of updates. For all you knew, the maintainer could have been literally dead, and youre on here making "Pulp Fiction" jokes. Shame on you.

@pukkandan you dont have privileges on this repo, so youre not in a position to tell anyone to do anything here. Stop it.

Only person who made a comment of any value was @rautamiekka, thanks for that. Its pretty simple, if you dont like the current state of YouTube-DL, dont use it and/or use something else.

**Comment by pukkandan** [comment] 2021-09-26 14:34
> @pukkandan you dont have privileges on this repo, so youre not in a position to tell anyone to do anything here. Stop it.

It seems @d9z do not understand the meaning of "please". Also ironic how you are asking me to "stop it" :D

**Comment by 89z** [comment] 2021-09-26 14:38
@pukkandan buzz off troll, this isnt YT-DLP repo, I think you got lost.

**Comment by pukkandan** [comment] 2021-09-26 14:41
Comment by @89z 
> @pukkandan buzz off troll, this isnt YT-DLP repo, I think you got lost.

Let's leave it for others to judge who's trolling here. Have a nice day

**Comment by 89z** [comment] 2021-09-26 14:46
@pukkandan oh no, please dont let me be judged by high quality GitHubbers like you!

**Comment by filixm** [comment] 2021-09-26 15:04
I apologize for opening a Pandora's box.  First let me be very clear, no one owns anyone anything, this is an open source, free tool that people should use at their own discretion and risk.  However, there are tons of projects that rely on youtube-dl so its a major dependency for many developers.  I would not have been able to create my project without it, so I actually hold youtube-dl and its developers in high regard.  Having said that, little transparency can go a long way.  I also have a free service that I offer to people and feel strong obligation to make sure it works, if not at least put up a message.  I wasn't making joke about anyone dying, just meant that this repo seemed a bit dead after nearly 4 month of no updates. No hard feelings.

**Comment by pirate486743186** [comment] 2021-09-28 22:19
@dstftw
Announce **SOMETHING** in the main page of the project, Anything.
It's 3 months now since the last commit.

**Comment by triplesixman** [comment] 2021-09-28 23:08
> @dstftw Announce **SOMETHING** in the main page of the project, Anything. It's 3 months now since the last commit.

It is even more anticipated than the return of Jesus. That is to say.

**Comment by fastily** [comment] 2021-09-29 23:41
Folks, it's pretty clear dstftw doesn't have the time/interest to continue maintaining the project at this time.

Instead of repeatedly pinging/emailing him, please use the actively maintained fork, [yt-dlp](https://github.com/yt-dlp/yt-dlp).  It's a drop in replacement for youtube-dl and includes fixes for a large number of recently reported bugs.

**Comment by rautamiekka** [comment] 2021-09-30 09:53
Time, yes, he doesn't have that ATM. Interest, no, that ain't the problem.

> No, its dead dead, like as in not living any more, circumstances are completely irrelevant. Zeds dead baby, zeds dead.

Since when has circumstances not mattered ? They matter the most here, if anything. Not dead, just not the priority.

**Comment by rautamiekka** [comment] 2021-09-30 19:42
When you put it that way, true, I agree.

**Comment by bnw42** [comment] 2021-09-30 23:18
Just scroll back over the earlier versions of this thread. Someone contacted dstftw (currently the sole 'gatekeeper') and he is in the process of moving house as well as being very busy at work. He has no spare time to devote to this project, which in the end is just a hobby (he doesn't get paid after all). Eventually he'll resurface .. until then use a yt-dl fork if your favourite site is now broken. And do keep in mind that open source projects do tend to have a limited lifespan - when the devs retire & no-one steps forward to take over they die, usually after forking.

Remember, dstftw is a volunteer. He is under no obligation to do *anything* with yt-dl. yt-dl is after all free and not a commercial application.

**Comment by triplesixman** [comment] 2021-09-30 23:40
> Just scroll back over the earlier versions of this thread. Someone contacted dstftw (currently the sole 'gatekeeper') and he is in the process of moving house as well as being very busy at work. He has no spare time to devote to this project, which in the end is just a hobby (he doesn't get paid after all). Eventually he'll resurface .. until then use a yt-dl fork if your favourite site is now broken. And do keep in mind that open source projects do tend to have a limited lifespan - when the devs retire & no-one steps forward to take over they die, usually after forking.
> 
> Remember, dstftw is a volunteer. He is under no obligation to do _anything_ with yt-dl. yt-dl is after all free and not a commercial application.

Under the pretext that youtube-dl is free it can be inactive for several months, without news? lol

With the number of users, contributors, it would be normal that other people can update it. 

I find it abnormal that everything depends on only one person. If you think otherwise, good for you, but you are wrong.

**Comment by bnw42** [comment] 2021-09-30 23:45
Just scroll back over the earlier versions of this thread. Someone contacted dstftw (currently the sole 'gatekeeper') and he is in the process of moving house as well as being very busy at work. He has no spare time to devote to this project, which in the end is just a hobby (he doesn't get paid after all). Eventually he'll resurface .. until then use a yt-dl fork if your favourite site is now broken. And do keep in mind that open source projects do tend to have a limited lifespan - when the devs retire & no-one steps forward to take over they die, usually after forking.

Remember, dstftw is a volunteer. He is under no obligation to do *anything* with yt-dl. yt-dl is after all free and not a commercial application.

**Comment by bnw42** [comment] 2021-09-30 23:59
*shrug* you get what you pay for. If you want a product with guaranteed updates, you'll need to pay for it.

What I think about the lack of an update is not the point. The project has one 'gatekeeper' developer and he is currently not available. Yes, that's not an ideal situation, but it's the situation. There were two last year but the other one retired and dstftw evidently never got around to authorising someone else. Anyone who feels strongly enough about it could hunt down his email address, contact him & ask to be given the authority to act as a senior developer.

**Comment by Trit34** [comment] 2021-10-03 11:24
@bnw42 It’s good to have news. While we’re awaiting for him to go back to us, we can still patch the broken extractors individually, so this is not as problematic as it could be (for Linux users, at least: Windows users currently have no possibility to patch their dedicated version and should use yt-dlp for now, and I don’t know about Mac users).

Hopefully it won’t be too long…

**Comment by rautamiekka** [comment] 2021-10-03 16:11
Mac is a NIX using much of the same as Linux, so it's about the same for Linux and Mac. I'm pretty sure there are tools or other methods for something similar to do it on Window$, but I also haven't researched into it.

**Comment by bnw42** [comment] 2021-10-03 22:40
I agree .. some more news would be good. In an earlier version of this thread someone managed to contact dstftw and amongst the issues dstftw was dealing with with was that he was unable to get a reliable home internet connection. I don't know his current situation, but I presume that he has what *he* considers valid reasons for 4 months of silence. Yes, for the rest of us it's frustrating, especially for users & devs of other software that incorporates yt-dl. Sadly it wouldn't be the first open source project that was abandoned by the one key person without a word leaving it dead it the water with all the users having no clue as to the fate. Truecrypt was a classic case.

**Comment by dirkf** [comment] 2022-01-29 16:01
Closed by #30568.

**Closed by dirkf** 2022-01-29 16:01 UTC
Labels: duplicate

**Comment by Behinder** [comment] 2022-03-25 11:21
I think I start looking at the code and documentation as I need youtube-dl for my scripts and try to understand what it is doing under the hood and maybe rewrite it e.g. in Swift

**Comment by pirate486743186** [comment] 2022-03-26 17:56
@Behinder
You may be interested in yt-dlp instead
https://github.com/yt-dlp/yt-dlp

**Comment by pc00per** [comment] 2022-10-02 13:39
It's literally no big deal for a Linux user. All we have to do, is install yt-dlp &
`alias youtube-dl='yt-dlp'`
`ln -s /usr/bin/yt-dlp /usr/local/bin/youtube-dl`
& then keep using youtube-dl
You'd have no issues even if you replace one with another 🤌
