### ISSUE TITLE
pluralsight.com Error 403

### ISSUE THREAD

**Issue by cesardiaz-dev** [ytdl-org/youtube-dl#25032] opened 2020-04-27 14:55 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'ASPNET/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '30', '--max-sleep-interval', '60', '--playlist-start', '16', 'https://app.pluralsight.com/library/courses/dotnet-core-aspnet-core-configuration-options', '--verbose', '--rm-cache-dir']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
Removing cache dir C:\Users\DiazOspina/.cache\youtube-dl ..
[pluralsight:course] dotnet-core-aspnet-core-configuration-options: Downloading JSON metadata
[pluralsight:course] dotnet-core-aspnet-core-configuration-options: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpjwbwqymm\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

## Description

I think this issue is caused by the new CAPTCHA that it has implemented.

**Comment by naruto3650** [comment] 2020-04-27 15:24
I am receiving the same error

**Comment by Marouenbenbelgacem** [comment] 2020-04-27 21:23
try to change --sleep-interval put it 380 or 400

**Comment by hysan** [comment] 2020-04-27 21:31
> try to change --sleep-interval put it 380 or 400

I had mine set higher than that and wasn't able to download a single file.

**Comment by Jennifer1506** [comment] 2020-04-28 13:00
I have the same error too

**Comment by zackmark29** [comment] 2020-04-28 13:43
Let's just wait for the update. they are busy right now for sure for fixing the error on many site

**Comment by Paddywaan** [comment] 2020-04-28 14:01
I also am now experiencing 403.

`youtube-dl https://www.youtube.com/watch?v=X2WH8mHJnhM
[youtube] X2WH8mHJnhM: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden`

**Comment by isaakmwenje** [comment] 2020-04-28 16:07
try this command on your terminal it works...
youtube-dl --rm-cache-dir

**Comment by dirkf** [comment] 2022-02-07 12:35
Duplicate of #27996, now.

**Closed by dirkf** 2022-02-07 12:35 UTC
