### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by Linux2010** [ytdl-org/youtube-dl#31594] opened 2023-02-19 08:10 UTC
```
youtube-dl 'https://www.youtube.com/watch?v=YopE2S3TodY'
[youtube] YopE2S3TodY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Linux2010** [comment] 2023-02-19 08:12
my version:  youtube-dl       2021.12.17

**Comment by Linux2010** [comment] 2023-02-19 08:17
I am concerned that the latest code has solved this problem, can you give a new Tag.
Thanks

**Comment by RackhamLeNoir** [comment] 2023-02-19 08:27
I get the same issue on Mac. The homebrew version seems to be old though…

`youtube-dl --verbose https://www.youtube.com/watch\?v\=9cL7HVU-uU4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=9cL7HVU-uU4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 17c872fb5
[debug] Python version 3.11.2 (CPython) - macOS-13.2.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9cL7HVU-uU4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by nathandegrave** [comment] 2023-02-19 08:31
Suddenly dealng with this as well. It worked all the way up until today.

**Comment by aryanator** [comment] 2023-02-19 08:48
> Suddenly dealng with this as well. It worked all the way up until today.

yes exactly! my project was working till yesterday and today it says this

**Comment by dirkk0** [comment] 2023-02-19 08:53
duplicate of #31530

**Comment by FelixOngati** [comment] 2023-02-19 08:55
Facing the same issue even after upgrading to the latest release.

**Comment by Linux2010** [comment] 2023-02-19 09:02
## My solution：
- Pull the latest code
- cd ~/youtube-dl
- change version.py  like this 
    - __version__ = '2023.02.19.local'
- change cache.py
   - _DEFAULT_VERSION = '2023.02.19.local' 
- python setup.py build
- python setup.py install
- run youtbe-dl

**Comment by RackhamLeNoir** [comment] 2023-02-19 09:03
`sed 's/solution/workaround/g'`

That said, the discussion should continue on https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by paulr909** [comment] 2023-02-19 09:45
@Linux2010 
Great solution, works for me.

**Comment by Linux2010** [comment] 2023-02-19 10:11
I noticed with this upgrade, the speed limit was lifted.
The previous version was only 40kb/s.（2021.12.17 tags）
Is there any risk that google will block my ip and not let me download it ？

```
[DEBUG] 2023-02-19 18:09:44,921 [download]  16.5% of 129.30MiB at  2.68MiB/s ETA 00:40
[DEBUG] 2023-02-19 18:09:45,031 [download]  28.9% of 19.59GiB at  2.62MiB/s ETA 01:30:42
[DEBUG] 2023-02-19 18:09:45,140 [download]  40.0% of 338.87MiB at  1.44MiB/s ETA 02:21
[DEBUG] 2023-02-19 18:09:45,517 [download]  98.7% of 346.94MiB at  1.33MiB/s ETA 00:03
[DEBUG] 2023-02-19 18:09:45,620 [download]  19.2% of 129.30MiB at  2.18MiB/s ETA 00:48
[DEBUG] 2023-02-19 18:09:45,821 [download]   1.0% of 76.04MiB at 290.13KiB/s ETA 04:25
[DEBUG] 2023-02-19 18:09:46,009 [download]  40.3% of 338.87MiB at  1.43MiB/s ETA 02:21
[DEBUG] 2023-02-19 18:09:46,300 [download]   1.6% of 76.04MiB at 293.48KiB/s ETA 04:20
[DEBUG] 2023-02-19 18:09:46,388 [download]  29.0% of 19.59GiB at  2.70MiB/s ETA 01:27
```

**Comment by JohnTRL** [comment] 2023-02-19 10:37
Y'all, go /youtube_dl/extractor/common.py.
Line 983, change: `fatal=True` to `fatal=False`

**Comment by oio0312** [comment] 2023-02-19 12:07
> 

more detall ?  thanks

**Closed** 2023-02-19 12:52 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-02-19 12:59
#30839

**Comment by dirkf** [comment] 2023-02-19 13:01
>Is there any risk that google will block my ip and not let me download it ？

Apparently not yet.
