### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl

### ISSUE THREAD

**Issue by ivanko76** [ytdl-org/youtube-dl#31744] opened 2023-03-02 19:11 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x ] I've checked that all provided URLs are alive and playable in a browser
- [ x  ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.youtube.com/watch?v=L6-66XSSXHw']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] L6-66XSSXHw: Downloading webpage
[youtube] L6-66XSSXHw: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
 include its complete output.```


## Description

<!--
Provide an explanation of your issue in an arbitrary form. Please make sure the description is worded well enough to be understood, see https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient. Provide any additional information, suggested solution and as much context and examples as possible.
If work on your issue requires account credentials please provide them or explain how one can obtain them.
-->

While at trying to see versions of videos with youtube-dl  -F  <URL of YouTube video> , I´m not able to do so. The message I get is:

"   ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl    "

**Comment by johnlinp** [comment] 2023-03-02 20:08
I believe that your report is a duplicate of #31530.

**Comment by dirkf** [comment] 2023-03-02 22:53
And #30839.

**Closed by dirkf** 2023-03-02 22:53 UTC

**Comment by Vangelis66** [comment] 2023-03-03 23:34
> I believe that your report is a duplicate of https://github.com/ytdl-org/youtube-dl/issues/31530.

... Not to mention **the very same OP** had just submitted previous #31743 😠 , which was rightly closed and with directions to follow **already provided**...
