### ISSUE TITLE
About france.tv videos ?

### ISSUE THREAD

**Issue by dufoin** [ytdl-org/youtube-dl#30010] opened 2021-09-23 17:40 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hi,
 I'm working with the updated version (june 2021) but it's now impossible to dowload videos from francetv by example : 
https://www.france.tv/france-2/complement-d-enquete/2738309-penuries-de-medicaments-a-quoi-jouent-les-labos.html
Thank you
Regards
DB

**Comment by kikuyan** [comment] 2021-09-23 20:16
Duplicate of #29956.

**Closed** 2022-05-09 14:36 UTC
Labels: duplicate, question
