### ISSUE TITLE
Cannot download this video from Youtube

### ISSUE THREAD

**Issue by cr7mmsa** [ytdl-org/youtube-dl#26059] opened 2020-07-19 11:10 UTC
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
I cannot download this youtube video from youtube: https://youtu.be/2N3dhl7ZVtw
Verbose:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/2N3dhl7ZVtw']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 2N3dhl7ZVtw: Downloading webpage
[youtube] 2N3dhl7ZVtw: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r6---sn-h0jeen76.googlevideo.com/videoplayback?expire=1595178546&ei=0ikUX_bKF8ap1gLWxqVI&ip=85.204.8.135&id=o-AJTPegs2acqHq3vuiWWr2BYbURxvI-DmsBuI3sZxGKR0&itag=22&source=youtube&requiressl=yes&mh=c1&mm=31%2C29&mn=sn-h0jeen76%2Csn-h0jeln7l&ms=au%2Crdu&mv=m&mvi=6&pl=21&initcwndbps=1743750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=14821.297&lmt=1580305469517601&mt=1595156813&fvip=1&fexp=23883097&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAK9oVzmMIl12tBmhCPT2UsqaBS_SUk8jUkR6O6JTWBX3AiEAx3lEbq7XlncJeOe6s5wqTVzQysYnqFRXmSHR9kpwhR0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALaWmQYPtWS8EoEhZLFSUqX0Ue1jIcKbcEvN5Dp7oLG8AiAF_j6rVRqBTJN9vEu33UHehENAprQUZ1u3k3sw35xpNQ%3D%3D'
[download] Destination: 12th Lecture Kaplan Step 3 CA Surgery Hill August 8, 2014-2N3dhl7ZVtw.mp4
[download]   0.7% of 789.99MiB at 523.05KiB/s ETA 25:36   [download] Got server HTTP error: Downloaded 5575041 bytes, expected 828367257 bytes. Retrying (attempt 1 of 10)...

ERROR: Did not get any data blocks
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 808, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\http.py", line 342, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\http.py", line 312, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\common.py", line 165, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 625, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 587, in trouble

**Comment by Ruffythemonkey** [comment] 2020-07-19 12:11
Hey dear developers, check this out: u5NuRpXqhGQ
YTDl response: YouTube said: Unable to extract video data

**Comment by cr7mmsa** [comment] 2020-07-19 17:52
So what is the problem?

**Comment by bersbersbers** [comment] 2020-07-19 19:45
- @Ruffythemonkey's `u5NuRpXqhGQ` is age-restricted, need to use (e.g.) the cookie method to sign in to download
- @cr7mmsa `2N3dhl7ZVtw` downloads beyond 1.2% for me.

**Comment by cr7mmsa** [comment] 2020-07-19 20:28
@bersbersbers It download few percents then it stops see the verbose

**Comment by bersbersbers** [comment] 2020-07-19 20:32
@cr7mmsa I have seen that. Yours stops at 0.7%, mine continues further. So I don't see the same problem as you do. If yours stops at varying percentages, you should indicate that.

**Comment by cr7mmsa** [comment] 2020-07-19 21:05
@bersbersbers AAA I understand now, so what is the problem you think sir?

**Comment by cr7mmsa** [comment] 2020-07-19 21:06
Majd Ghawi, is ready to play, so i think he is a good player, so I think we can put him at any position we want

**Comment by bersbersbers** [comment] 2020-07-20 06:26
@cr7mmsa your output shows "Default format spec: best/bestvideo+bestaudio", which is unusual - it shows "bestvideo+bestaudio/best" for me. 

I can reproduce your problem with
```youtube-dl -v https://youtu.be/2N3dhl7ZVtw -f best```
 - indeed, it breaks at 0.7%. Seems like a duplicate of https://github.com/ytdl-org/youtube-dl/issues/17148

You might try 
```youtube-dl -v https://youtu.be/2N3dhl7ZVtw -f webm```
or
```youtube-dl -v https://youtu.be/2N3dhl7ZVtw -f bestvideo+bestaudio```
in the meantime. The latter is working for me.

**Comment by cr7mmsa** [comment] 2020-07-20 09:11
@bersbersbers yes it works when i put -f webm, can you explain to me why?

**Comment by cr7mmsa** [comment] 2020-07-20 09:11
@bersbersbers as i know that youtube-dl will choose the best format

**Comment by bersbersbers** [comment] 2020-07-20 09:18
@cr7mmsa in short, the content is missing on YouTube. Read https://github.com/ytdl-org/youtube-dl/issues/17148 and, if interested, on the meaning of `-f` (https://github.com/ytdl-org/youtube-dl#format-selection) and the difference between `bestvideo+bestaudio` and `best` (https://github.com/ytdl-org/youtube-dl/issues/5447). Also note that for some reason, your installation does *not* the default format settings (`bestvideo+bestaudio/best`, but `best/bestvideo+bestaudio`).

**Comment by cr7mmsa** [comment] 2020-07-20 14:31
@bersbersbers thank you sir, just one last question. I used bestvideo+bestaudio/best option, it downloads perfectly but i have one problem, that youtube-dl doesn't use my highest download speed, it's low speed why? and do you know how i can fix that?

**Comment by bersbersbers** [comment] 2020-07-20 14:34
> youtube-dl doesn't use my highest download speed, it's low speed why? and do you know how i can fix that?

Sorry, don't know.

**Closed** 2020-07-22 11:54 UTC
