### ISSUE TITLE
Plurasight HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by panosru** [ytdl-org/youtube-dl#22131] opened 2019-08-17 08:41 UTC
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

I saw many old topics for pluraslight which are closed and none of them provides any solution, as far for open tickets with plural sight I haven't seen any related to my errors.
## Description
Screenshots are self-explanatory:
![screenshot2](https://user-images.githubusercontent.com/400362/63208968-a5022080-c0e3-11e9-9ef0-c8b3347b3153.jpg)
![screenshot1](https://user-images.githubusercontent.com/400362/63208966-9f0c3f80-c0e3-11e9-87c1-b887c0acb5d0.jpg)

My login data is correct, I'm able to watch the courses though my account and Plurasight desktop player,

I'm getting the same result either with
```
//app.pluralsight.com/library/courses/data-transactions-spring
```
or
```
https://app.pluralsight.com/library/courses/data-transactions-spring
```

The url is working fine
![screenshot3](https://user-images.githubusercontent.com/400362/63209035-89e3e080-c0e4-11e9-9705-7ec626409edf.jpg)

**Comment by panosru** [comment] 2019-08-17 08:46
@dstftw at least point me to which is duplicate and where is the solution, don't just mark it like many other closed topics.

**Comment by dstftw** [comment] 2019-08-17 08:58
There is no solution as well as there is no problem. To make problem valid you must provide account credentials.

**Comment by panosru** [comment] 2019-08-17 09:00
I can provide them if you asked for me instead of just mark the topic closed. Let me know where I can send them to you.

**Comment by dstftw** [comment] 2019-08-17 17:56
I don't plan to work on this in near future.

**Comment by panosru** [comment] 2019-08-18 08:49
@dstftw bottom line, do you need an account or not?

**Comment by dstftw** [comment] 2019-08-18 12:09
The bottom line is: work on this will require account credentials. At the same time I won't be able to work on this soon.

**Comment by DcsPeterDickten** [comment] 2019-08-21 09:01
I have the same problem. They have some software right now that detects third-party downloader even if you choose VERY long delays between the video downloads. Therefore they block the account and you get an email like this:

> Pluralsight has detected the use of third-party applications to download courses. This is a violation of our Terms of Use and will result in your account being permanently banned.

**Comment by softteam42** [comment] 2019-08-21 09:05
I have the same problem. They have some software right now that detects third-party downloader even if you choose VERY long delays between the video downloads. Therefore they block the account and you get an email like this:

Pluralsight has detected the use of third-party applications to download courses. This is a violation of our Terms of Use and will result in your account being permanently banned.

**Comment by panosru** [comment] 2019-08-21 09:06
@softteam42 Downie 3 for MacOS works fine. Don't wait any support for youtube-dl, obviously there isn't any intention to support it, just use another software.

Cheers

**Comment by softteam42** [comment] 2019-08-21 09:09
@panosru  Thank you very much! I really loved youtube-dl ... sad :-(

**Comment by panosru** [comment] 2019-08-21 09:13
@softteam42 I'm not a maintainer, I do not speak on behalf of the project. But based on the issues, and the way the maintainer responds to issues, I assume that there is no interest on fixing the issue, at least not for pluralsight, who knows, maybe Pluralsight had the idea to support them financially in exchange to not provide support for pluralsight, I do not not, I do not care any more :)

:)

**Comment by dirkf** [comment] 2022-02-07 12:40
Duplicate of #29776, now.

**Closed by dirkf** 2022-02-07 12:40 UTC
Labels: account-needed
