### ISSUE TITLE
Problem downloading a short

### ISSUE THREAD

**Issue by atkimi** [ytdl-org/youtube-dl#30979] opened 2022-05-26 08:43 UTC
/usr/local/bin/youtube-dl -iv https://www.youtube.com/shorts/Hga0NuSHkPQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-iv', u'https://www.youtube.com/shorts/Hga0NuSHkPQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-110-generic-x86_64-with-LinuxMint-20.3-una
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-05-26 11:01
Duplicate of #30269; fixed in git master, as you would have found by [following the template](https://github.com/ytdl-org/youtube-dl/issues/30839).

**Closed by dirkf** 2022-05-26 11:01 UTC
