### ISSUE TITLE
Crunchyroll fails to download free videos

### ISSUE THREAD

**Issue by ghost** [ytdl-org/youtube-dl#27385] opened 2020-12-12 01:17 UTC
## Checklist

- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2020.12.12**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--cookies', u'crunchyroll.com_cookies.txt', u'--user-agent', u'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36', u'-f', u'best', u'--no-check-certificate', u'--recode-video', u'mp4', u'--all-subs', u'-i', u'-a', u'FILE.txt', u'--verbose']
[debug] Batch file urls: [u'https://www.crunchyroll.com/my-hero-academia/episode-1-izuku-midoriya-origin-730707']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.12.12
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-56-generic-x86_64-with-LinuxMint-20-ulyana
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 730707: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2248, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

## Description

WRITE DESCRIPTION HERE

Okay. when i go to download from crunchyroll.com with the appropriate user agent and cookies.txt file, youtube-dl outputs a http 403 error.

this is the command by the way. not sure where i was supposed to put it:

youtube-dl --cookies crunchyroll.com_cookies.txt --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -f best --no-check-certificate --recode-video mp4 --all-subs -i -a FILE.txt

**Comment by Columbo199X** [comment] 2020-12-20 15:40
Same here
```
F:\youtube-dl>youtube-dl --cookies "cookies.txt" --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0" -v https://www.crunchyroll.com/giant-gorg/episode-5-the-island-of-the-god-726265
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0', '-v', 'https://www.crunchyroll.com/giant-gorg/episode-5-the-island-of-the-god-726265']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[crunchyroll] 726265: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwx5ikkp6\build\youtube_dl\YoutubeDL.py", line 2248, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by selfisekai** [comment] 2021-01-10 10:16
@morgan-rm-rf @Columbo199X both of your URLs are not playable in browser. ytdl is not magic, blame crunchyroll.

check with a working URL like this one (works for me): https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-1-the-end-of-the-beginning-and-the-beginning-of-the-end-783450

**Comment by lejoueur50** [comment] 2021-01-20 14:02
Any news about that ? I have a similar problem : 
```
youtube-dl https://www.crunchyroll.com/fr/rent-a-girlfriend/episode-1-rent-a-girlfriend-796247 --user-agent "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"  --cookies /home/pi/Desktop/cookies.txt -v

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.crunchyroll.com/fr/rent-a-girlfriend/episode-1-rent-a-girlfriend-796247', u'--user-agent', u'Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36', u'--cookies', u'/home/pi/Desktop/cookies.txt', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 2.7.16 (CPython) - Linux-5.4.83-v7l+-armv7l-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 796247: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

**Comment by selfisekai** [comment] 2021-01-20 19:43
Could you please try to download without `--cookies`?

**Comment by lejoueur50** [comment] 2021-01-20 19:57
I've just tried, but the same problem occur
```
youtube-dl https://www.crunchyroll.com/fr/rent-a-girlfriend/episode-1-rent-a-girlfriend-796247 --user-agent "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"  -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.crunchyroll.com/fr/rent-a-girlfriend/episode-1-rent-a-girlfriend-796247', u'--user-agent', u'Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.01.16
[debug] Python version 2.7.16 (CPython) - Linux-5.4.83-v7l+-armv7l-with-debian-10.7
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 5, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll] 796247: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2274, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

```

**Comment by selfisekai** [comment] 2021-01-21 15:38
Could you run it with `--write-pages` and paste the file contents on some pastebin? here's a one if you want: https://bin.ddd.rip/

**Comment by lejoueur50** [comment] 2021-01-21 16:01
I've tried with it, but the result seems to be similar than others tries that were done
Here is the link : https://bin.ddd.rip/ugehulelof

**Comment by selfisekai** [comment] 2021-01-21 16:29
oh, so ytdl doesn't create a webpage dump file when the request fail, noted.

anyway, I just got into the same problem and managed to see the response content: basically, fuck Cloudflare.
```html
<h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
<p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
```

**Comment by Columbo199X** [comment] 2021-02-01 21:22
> 
> 
> @morgan-rm-rf @Columbo199X both of your URLs are not playable in browser. ytdl is not magic, blame crunchyroll.
> 
> check with a working URL like this one (works for me): https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-1-the-end-of-the-beginning-and-the-beginning-of-the-end-783450

The URL is working but it's probably region-blocked in your case.

**Comment by selfisekai** [comment] 2021-02-01 22:23
oh, fuck crunchyroll for showing generic errors on region lock then

**Comment by Columbo199X** [comment] 2021-02-01 22:27
So I've been testing several combinations and none worked. It doesn't matter if the video is available in your region or not.
Using --cookies or --cookies with --user-agent will both result in random 403 errors and sometimes 502 as seen here [#27490](https://github.com/ytdl-org/youtube-dl/issues/27490)
This makes batch downloading episodes a tedious task because you don't know when it will error.

**Comment by Mennaruuk** [comment] 2021-02-02 04:01
Crunchyroll also not working, didn't matter even when I specified user agent 😞

**Comment by ckaotik** [comment] 2021-03-28 19:14
I also had the error, and only got it to work once I disabled the `_login` function. Likely because I have username and password stored in my `.netrc`. It seems Cloudflare is specifically protecting the login page, it sometimes (rarely) works but most of the time I get a 403 error. Maybe we could rely solely on unathorized access or user cookies?

**Comment by selfisekai** [comment] 2021-03-28 20:19
@ckaotik Accounts from `.netrc` are only used when you specify the `--netrc` option. This is about Cloudflare anti-bot protection, which sends some JavaScript shit to be resolved by browser. Possible workarounds, if you need that:
1. open Crunchyroll in your browser, then specify `--cookies` with cookies.txt [extracted](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) [from it](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) - your browser will pass the Cloudflare challenge automatically, and set some cookies that indicate that.
2. use a different IP somehow (proxy, VPN, etc.)

**Closed** 2022-06-12 23:55 UTC
Labels: outdated-version
