### ISSUE TITLE
Unable to download somes videos from youtube

### ISSUE THREAD

**Issue by benjibasson83** [ytdl-org/youtube-dl#31556] opened 2023-02-17 19:56 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
youtube-dl --no-cache-dir --extract-audio --verbose --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=ytywevJ8xOM[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--verbose', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=ytywevJ8xOM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.16 (CPython) - Linux-5.18.8-porteus-x86_64-Intel-R-_Core-TM-_i3_CPU_______M_370__@_2.40GHz-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ytywevJ8xOM: Downloading webpage
[youtube] ytywevJ8xOM: Downloading player 11e3a4ec
[youtube] ytywevJ8xOM: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Hi. I'm Unable to download video from https://www.youtube.com/watch?v=ytywevJ8xOM. it do the error ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2023-02-17 20:25
> [x] I've searched the bugtracker for similar issues including closed ones

[Really?](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+uploader+-label%3Aduplicate) Duplicate of #31530.

**Closed** 2023-02-17 20:25 UTC
Labels: duplicate
