### ISSUE TITLE
yt-dlp versus youtube-dl? (Age-gated content)

### ISSUE THREAD

**Issue by rubyFeedback** [ytdl-org/youtube-dl#29601] opened 2021-07-20 21:21 UTC
Hey guys,

Some time ago I reported that Google is playing hardball and age-gated videos are no longer working
with youtube-dl. There are also a few more sites where youtube-dl, without age-gated content, does
not work, but I assume these can be fixed eventually if someone figures out where to find the video.

Today I used "yt-dlp" though and I could download an age-gated video from youtube. And this is confusing
me. I do not know how yt-dlp does it, but would it not be better for youtube-dl to also add support for
this out of the box? I no longer have an active Google account after google started its mass-sniffing
surveillance project (FLoC); I don't want to give Google any more private information ever again, but
I am still using  some Google services (hard to avoid this monster that it has become). I'd like to keep
on using youtube-dl since it's great, but at the least for age-gated videos I now use yt-dlp. But ideally
it would be great if youtube-dl can work with age-gated content fine. No idea how yt-dlp but perhaps
someone else knows how yt-dlp does it.

**Comment by 89z** [comment] 2021-07-22 02:20
You can get most videos with just the `X-Goog-Api-Key` header (`key` query parameter). However some videos do in fact require logging in, with no workaround [1].

For those videos, the best option I have found so far is using OAuth with an `Authorization` header (`access_token` query parameter) [2].

1. https://www.youtube.com/embed/Cr381pDsSsA
2. https://developers.google.com/identity/protocols/oauth2/web-server

**Comment by fstirlitz** [comment] 2021-07-22 14:45
Why not just switch to yt-dlp wholesale?

This project hasn’t had a commit in three weeks, and a full release in six. Where it might have looked merely moribund before (see #26462), it’s pretty much dead now.

**Comment by 89z** [comment] 2021-08-09 13:39
example video?

**Comment by dirkf** [comment] 2022-04-18 12:14
Duplicate of #29578.

**Closed by dirkf** 2022-04-18 12:14 UTC
Labels: request, duplicate
