### ISSUE TITLE
ERROR: Unable to extract uploader id

### ISSUE THREAD

**Issue by cebaraldi** [ytdl-org/youtube-dl#31534] opened 2023-02-16 21:03 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ youtube-dl https://www.youtube.com/watch?v=qOtgxpDyGPw&list=PLXMQSu-PgWl8qRb_ubTdOmbF4ORDJ36C0&index=1
[1] 15292
[2] 15293
$ [youtube] qOtgxpDyGPw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Currently I am using the actual version of youtube-ld on a updated Ubuntu 22.04. As you will expect the corresponding playlist, too, cannot be downloaded. But please let me first report the error message when downloading a single element of the playlist.

Thanks for your support or suggestions in advance and  kind regards,
Claudio

**Comment by elgonzo** [comment] 2023-02-16 21:08
>  I've searched the bugtracker for similar bug reports including closed ones

Seriously, you didn't do that. Not a bit...

**Comment by Ceirced** [comment] 2023-02-16 21:12
Might have the same issue also on 22.04 an also on 20.04. Since a few hours the uploader id error keeps happening. At the beginning, some videos still worked but now every download seems to fail the same way.

**Comment by cebaraldi** [comment] 2023-02-16 21:25
Seriously, if someone would present an obvious link to the bugtracker, then
I would try to search for the mentioned issue. I have not seen it. Are you
able to help in this case? Then please provide a link to that information.

Thanks,
Claudio

**Comment by mainboarder** [comment] 2023-02-16 21:34
watch the issue id: https://github.com/ytdl-org/youtube-dl/issues/31533

**Comment by cebaraldi** [comment] 2023-02-16 21:36
Thank you so much! I'll have a look.

Bye now,
Claudio

**Comment by elgonzo** [comment] 2023-02-16 21:54
> Seriously, if someone would present an obvious link to the bugtracker, then I would try to search for the mentioned issue.

Ah, you know, why would anyone do that? You have already proven that you don't mind pretending/lying that you already did, so why not keep the pretense up?

**Comment by s5410s** [comment] 2023-02-16 22:50
> watch the issue id: #31533 and open issues https://github.com/ytdl-org/youtube-dl/issues

I make this patch for youtube-dl

--- youtube_dl/extractor/youtube.py     2023-02-17 00:42:29.996275160 +0300
+++ youtube_dl/extractor/youtube.py     2023-02-17 00:59:30.730192638 +0300
@@ -1791,7 +1791,7 @@
                 microformat.get('uploadDate')
                 or search_meta('uploadDate')),
             'uploader': video_details['author'],
-            'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
+            'uploader_id': self._search_regex(r'/(?:channel/|user/|@)([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
             'uploader_url': owner_profile_url,
             'channel_id': channel_id,
             'channel_url': 'https://www.youtube.com/channel/' + channel_id if channel_id else None,
             
[youtube-dl.patch](https://github.com/ytdl-org/youtube-dl/files/10761556/youtube-dl.txt)

**Comment by dirkf** [comment] 2023-02-16 23:24
Duplicate of #31530.

**Closed by dirkf** 2023-02-16 23:24 UTC

**Comment by rafaleo** [comment] 2023-02-17 17:18
yt-dlp corrected this same bug today, but working with pip only, not conda

**Comment by JohnTRL** [comment] 2023-02-19 10:49
Y'all, go /youtube_dl/extractor/common.py.

Line 983 change `fatal=True` to `fatal=False`
