### ISSUE TITLE
Fails to utilize proxy

### ISSUE THREAD

**Issue by Yuoter** [ytdl-org/youtube-dl#32924] opened 2024-09-05 12:44 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Nightly release of youtube-dl-2024.08.07 works locally, but when deployed to cloud it constantly faces IP bans. I tried to use Zyte proxies with youtube-dl, but it seems that it fails to utilize them.
I guess it is problem that it lacks functionality of verification of CA certificates. 

youtube-transcript-api had the similar issue that it failed to utilize Zyte proxies and it was resolved by this fork where verification of CA certificate was added:
https://github.com/jdepoix/youtube-transcript-api/issues/303#issuecomment-2274163459
https://github.com/danielsanmartin/youtube-transcript-api/commit/f6f51d007f14fd588a3c95c4c7abb6d36f536e4a

Could you add option to verify the CA certificates, so that it would be possible to use Zyte proxies for ban handling with the library? I tried a number of ways to use Zyte proxies without verifying zyte-ca.crt, but without the verification of zyte-ca.crt, it does not work and gives an error.

Here is Zyte’s information on their zyte-ca.crt certificate: https://docs.zyte.com/misc/ca.html

**Comment by dirkf** [comment] 2024-09-05 16:54
Pls review #32549 to see if any of that discussion clarifies your problem. If not, we'd need rather more detail to take this further. But maybe yt-dlp/yt-dlp#10930 will solve it at least for _yt-dlp_.

**Comment by Yuoter** [comment] 2024-09-05 19:21
@dirkf thank you! 

"Pls review https://github.com/ytdl-org/youtube-dl/issues/32549 to see if any of that discussion clarifies your problem."
Thank you, I will investigate it, but at first glance there is interesting information, but as far as I understand this thread is about bug in previous versions of urllib that youtube-dl utilizes. They talked about versions of urllib before third one. 

Here [1890#issuecomment-986977600](https://github.com/yt-dlp/yt-dlp/issues/1890#issuecomment-986977600) was said:
"> A descent fix would be to migrate to `urllib3` (https://github.com/urllib3/urllib3) which I confirm can handle secure web proxy."

The thing is that I am using urllib3==2.2.2. So might be the issue that I described is not related to [32549](https://github.com/ytdl-org/youtube-dl/issues/32549)

**Comment by dirkf** [comment] 2024-09-06 08:09
We use urllib2. _yt-dlp_ might use urllib3 or other HTTP networking libraries, depending on settings.

**Comment by Yuoter** [comment] 2024-09-06 10:14
@dirkf Ah, thanks for the clarification, considering this fact the issue with youtube-dl might be related [32549](https://github.com/ytdl-org/youtube-dl/issues/32549)

I am not that familiar with how youtube-dl code works which is why would like to ask you.
How do you think is a big chunk of work to update youtube-dl dependency on urllib2 to urllib3?
And is it possible at all or some functionality may be lost because of such an update of dependency?

**Comment by dirkf** [comment] 2024-09-06 11:15
It's out of scope (unless someone wants to write a urllib2 wrapper for urllib3, which would really defeat the object): use _yt-dlp_ if you need urllib3. I think the way forward for fancy connectivity is local proxying, or adding a feature for external requesters as mentioned in the linked issue

**Comment by Yuoter** [comment] 2024-09-07 20:20
@dirkf Got it, thanks!

**Comment by dirkf** [comment] 2024-09-08 10:58
In that case I'll mark this as a duplicate of #32549.

**Closed by dirkf** 2024-09-08 10:58 UTC
Labels: question
