### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by enclle** [ytdl-org/youtube-dl#31519] opened 2023-02-07 09:30 UTC
Hello,

  youtube-dl keeps showing this message:

  "WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/youtube_dl-2021.12.17-py3.8.egg/youtube_dl/extractor/youtube.py", line 1524, in _n_descramble
    raise ExtractorError('Unhandled exception in decode')
youtube_dl.utils.ExtractorError: Unhandled exception in decode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Output of youtube-dl -U --verbose:

"[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.9 (CPython) - macOS-11.7.2-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)"

Thank you.

**Comment by dirkf** [comment] 2023-02-07 12:02
Duplicate of #31509.

**Closed by dirkf** 2023-02-07 12:02 UTC
