### ISSUE TITLE
How to retain the origilal serial number in a playlist?

### ISSUE THREAD

**Issue by blueray453** [ytdl-org/youtube-dl#20580] opened 2019-04-06 11:34 UTC
I tried` --playlist-items` & `%(playlist_index)s` together. But they are not playing along well.

**Command Tried**
`youtube-dl -o '%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s' <URL of The Playlist> --playlist-items 16,21,37`

**Current Output**

1-Title Of First Video

2-Title Of Second Video

3-Title Of Third Video

**Expected Output**

16-Title Of First Video

21-Title Of Second Video

37-Title Of Third Video

What am I missing?

**Comment by remitamine** [comment] 2019-04-06 11:36
Duplicate of #10591.

**Closed** 2019-04-06 11:36 UTC

**Comment by blueray453** [comment] 2019-04-06 12:03
I think the [original question](https://github.com/ytdl-org/youtube-dl/issues/10591) is locked. It also does not provide any solution. Only asks the question with some suggestions.

Has there been any progress regarding that issue?

**Comment by remitamine** [comment] 2019-04-06 12:18
> I think the [original question](https://github.com/ytdl-org/youtube-dl/issues/10591) is locked. It also does not provide any solution. Only asks the question with some suggestions.
> 
> Has there been any progress regarding that issue?

there is a proposed fix, but it hasn't been reviewed yet.
