### ISSUE TITLE
Unable to download Youtube Videos

### ISSUE THREAD

**Issue by axelfk** [ytdl-org/youtube-dl#31544] opened 2023-02-17 12:01 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
me@kiste:~/bin> youtube-dl -f mp4 -o test.mp4 https://www.youtube.com/watch?v=_GTo4q4EnHE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mp4', '-o', 'test.mp4', 'https://www.youtube.com/watch?v=_GTo4q4EnHE', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.9 (CPython) - Linux-6.1.11-1.g16a4964-default-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 4.4.3, ffprobe 4.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] _GTo4q4EnHE: Downloading webpage
[youtube] _GTo4q4EnHE: Downloading player 11e3a4ec
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
return func(self, *args, **kwargs)
File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
ie_result = ie.extract(url)
File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Hello, 
this morning I´ve tried to download a video from youtube and it fails.
I´ve tried:
https://www.youtube.com/watch?v=HjBo--1n8lI
https://www.youtube.com/watch?v=_GTo4q4EnHE
https://www.youtube.com/watch?v=ucdaEjd1Y4A

I then downloaded another video from Dailymotion, but it works perfectly.

Beste Grüsse
axel

**Comment by GurvanKervern** [comment] 2023-02-17 12:29
Same issue with this playlist https://www.youtube.com/watch?v=3nB1Ntku06w&list=PLH2l6uzC4UEVUmJdTMStYXad_sI73_T0x . Nothing changed youtube-dl -U (already at the latest version, but I did download playlist with that version recently)

**Comment by Yotty0404** [comment] 2023-02-17 12:44
I got the same error too.
I was even able to download a few days ago with the exact same code.

**Comment by steve8x8** [comment] 2023-02-17 13:52
Duplicate of #31530?

**Comment by dirkf** [comment] 2023-02-17 13:54
> [x] I've searched the bugtracker for similar issues including closed ones

[Really?](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+uploader+-label%3Aduplicate) Duplicate of #31530.

**Closed by dirkf** 2023-02-17 13:54 UTC
