### ISSUE TITLE
Unable to recognise tab page

### ISSUE THREAD

**Issue by Blutyek** [ytdl-org/youtube-dl#30550] opened 2022-01-24 00:39 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/shorts/QsqsT3659Ss']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.14 (CPython) - Linux-4.12.14-lp150.12.25-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg N-97612-g2b32068, ffprobe N-97612-g2b32068
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

youtube-dl fails to download a Youtube video that plays fine in Firefox

**Comment by 89z** [comment] 2022-01-24 00:41
Just use the ID:

~~~
PS D:\Desktop> youtube-dl.exe QsqsT3659Ss
[youtube] QsqsT3659Ss: Downloading webpage
[download] Destination: You Gotta Localize the Lesion-QsqsT3659Ss.f398.mp4
[download]   4.3% of 5.34MiB at 58.51KiB/s ETA 01:29
~~~

**Comment by dirkf** [comment] 2022-01-24 02:02
Indeed. Also, duplicate of #30269.

**Closed** 2022-02-01 14:40 UTC
Labels: duplicate
