### ISSUE TITLE
Can't download from criterionchannel.com, unsupported URL

### ISSUE THREAD

**Issue by mheins57** [ytdl-org/youtube-dl#30449] opened 2022-01-01 03:09 UTC
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.criterionchannel.com/high-and-low/videos/high-and-low']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.7 (CPython) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] high-and-low: Requesting header
WARNING: Falling back on generic information extractor.
[generic] high-and-low: Downloading webpage
[generic] high-and-low: Extracting information
ERROR: Unsupported URL: https://www.criterionchannel.com/high-and-low/videos/high-and-low
Traceback (most recent call last):
  File "/Users/mth/opt/anaconda3/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mth/opt/anaconda3/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/mth/opt/anaconda3/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/Users/mth/opt/anaconda3/lib/python3.9/site-packages/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.criterionchannel.com/high-and-low/videos/high-and-low

```

## Description

I'm brand new using youtube-dl, but I think I followed the directions.  Am trying to record a movie from criterionchannel.com but I get the "Unsupported URL" error each time.  I can play the indicated URL ok in my browser (Firefox).  My system is an M1 MacBook Pro running MacOS 12.0.1.  I searched the bug database, and saw a couple of similar bugs which were closed, but nothing recent.

**Comment by 89z** [comment] 2022-01-01 03:16
If you can provide credentials I can try to fix it. Run the following command and reply back with the output:

~~~
echo USER:PASS | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by dirkf** [comment] 2022-01-01 04:07
This (ie the penultimate line) in the page doesn't appear encouraging:
```
window.VHX.video = {
      id: "465719",
      status: "pending",
      isLive: "false",
      scheduled_at: "",
      isDRM: "true",
      isTrailer: "false",
    };
```

**Comment by kikuyan** [comment] 2022-01-01 04:14
Not supported https://github.com/ytdl-org/youtube-dl/search?q=criterionchannel&state=open&type=issues

**Comment by dirkf** [comment] 2022-01-01 04:17
So also, duplicate of #20408.

**Comment by mheins57** [comment] 2022-01-01 09:11
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1ArR2ZDK0pxMHhjUHJN
NTZBVDZ2eWw0OFdMR21JblZiYzB6QmFXTHhzCnBITCtJYmNFVlRRbURFWTFBVTBC
R1lpL29pVWduWFFiVCt4ejUvcmd6L0UKLS0tIFhLcDlpZFdLVkY1RGtqd0ZtYWZK
ZTRTZUU3SExDZlFXMjVOanBSOVlIcDgKeArGd3wY56NUnIG3Z/oJHNedTR39QZWY
e55FBSPuTLC6pFKYXLNItIH39jKaYhmDfsjZqEljvZ7MzTdSwTU=
-----END AGE ENCRYPTED FILE-----

**Comment by mheins57** [comment] 2022-01-01 09:12
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd1ArR2ZDK0pxMHhjUHJN
NTZBVDZ2eWw0OFdMR21JblZiYzB6QmFXTHhzCnBITCtJYmNFVlRRbURFWTFBVTBC
R1lpL29pVWduWFFiVCt4ejUvcmd6L0UKLS0tIFhLcDlpZFdLVkY1RGtqd0ZtYWZK
ZTRTZUU3SExDZlFXMjVOanBSOVlIcDgKeArGd3wY56NUnIG3Z/oJHNedTR39QZWY
e55FBSPuTLC6pFKYXLNItIH39jKaYhmDfsjZqEljvZ7MzTdSwTU=
-----END AGE ENCRYPTED FILE-----

**Comment by mheins57** [comment] 2022-01-01 09:16
P.S. Thanks for taking a look.  Please let me know when you’re done with my account info (so I can change the password).

Michael

**Comment by 89z** [comment] 2022-01-01 16:46
Thanks, I was able to log in. The media links are easily available:

https://drm.vimeocdn.com/1641090211-0xa72ebd75caa973a40bb219b0f03ab854de999dcd/01/432/13/327163529/1281250748,1281250737,1281250749,1281250740/1281250749-4-t1.m4s?assetId=327163529

but as other mentioned, they are protected by Vimeo DRM. So I think I cannot help in this case.

**Comment by sandchar99** [comment] 2022-01-03 23:58
I have tried as well and (although not helpful) believe that VIMEO DRM prevents me from doing the same. I am getting the same "unsupported url" error

**Closed** 2022-01-29 17:30 UTC
Labels: DRM, duplicate

**Comment by 3052** [comment] 2024-05-20 12:46
I have made an implementation if anyone is interested:

~~~
msg=GET URL="https://api.vhx.com/videos/high-and-low?url=high-and-low"
msg=GET URL=https://api.vhx.tv/videos/465719/files
msg=GET URL="https://player.vimeo.com/skyfire/redirect/327163529.mpd?drm=1&expires=1716223514&hevc=0&max_height=1080&pssh=0&sig=266e5a12c1738995dfd7b2c7ad6fe5b2893c9e9e&text_tracks=1"
msg=GET URL="https://drm.vimeocdn.com/1716223514-0x13058bcb0aadd8a68af98b312f764f25f715c446/01/432/13/327163529/1281250749,1281250740,1281250748,1281250737/master.mpd?assetId=327163529&pssh=0"
msg=GET URL="https://drm.vimeocdn.com/1716223514-0x13058bcb0aadd8a68af98b312f764f25f715c446/01/432/13/327163529/1281250749,1281250740,1281250748,1281250737/1281250749-0-t1.m4s?assetId=327163529"
msg=POST URL="https://drm.vhx.com/v2/widevine?token=eyJhbGciOiJIUzI1NiJ9.eyJhc3NldF9pZCI6MzI3MTYzNTI5LCJ2aWRlb19pZCI6NDY1NzE5LCJjbGlwX2lkIjozMjcxNjM1MjksImV4cCI6MTcxNjIyNzExNCwib2ZmbGluZV9saWNlbnNlIjpmYWxzZSwiaGRjcCI6dHJ1ZX0.zdY26ojdbMte1plPiGbni2eSqpumFoI93Sa5Eu-cO1Y"
msg="0.47 %" size="19.87 megabyte" rate="19.87 megabyte/s"
~~~
