### ISSUE TITLE
Pluralsight 403 forbidden

### ISSUE THREAD

**Issue by kkord** [ytdl-org/youtube-dl#30540] opened 2022-01-18 22:26 UTC
receiving a 403 forbidden, youtube-dl updated.

`[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://app.pluralsight.com/library/courses/windows-server-administration-concepts-active-directory/', '-o', 'C:/Users/PRIVATE/Videos/Pluralsight/%(playlist)s/%(chapter_number)02d - %(chapter)s/%(playlist_index)02d - %(title)s.%(ext)s', '--sleep-interval', '35', '--max-sleep-interval', '120', '--sub-lang', 'en', '--sub-format', 'srt', '--write-sub']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] windows-server-administration-concepts-active-directory: Downloading JSON metadata
[download] Downloading playlist: Windows Server Administration Concepts: Active Directory
[pluralsight:course] playlist Windows Server Administration Concepts: Active Directory: Collected 20 video ids (downloading 20 of them)
[download] Downloading video 1 of 20
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default`

**Comment by dirkf** [comment] 2022-01-18 23:42
Duplicate of #29776.

**Closed** 2022-02-07 12:55 UTC
Labels: duplicate
