### ISSUE TITLE
youtube-dl not working

### ISSUE THREAD

**Issue by errod1** [ytdl-org/youtube-dl#31531] opened 2023-02-16 19:30 UTC
ERROR: Unable to extract uploader id;

youtube-dl.exe  https://youtu.be/zhXvyd8VbOM
[youtube] zhXvyd8VbOM: Downloading webpage
[youtube] zhXvyd8VbOM: Downloading m3u8 information
[youtube] zhXvyd8VbOM: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

i have the last version:

>youtube-dl.exe -U
youtube-dl is up-to-date (2021.12.17)

please help!

thanks

**Comment by augustsaintfreytag** [comment] 2023-02-16 19:41
If you can, please change the title to what the actual problem is, not just that it’s “not working” so it can be triaged. If I wanted to report it, I would’ve titled it after the error description, something like `"Unable to extract uploader id" for YouTube videos`.

**Comment by Grub4K** [comment] 2023-02-16 19:43
Duplicate of #31530, which was closed by @dirkf (maybe consider reopen?)

**Comment by HexadimensionalerAlp** [comment] 2023-02-16 19:49
Same problem, stopped working on windows and linux independently on the same time. Worked 1 time out of around 50 tries.
![youtube-dl-error](https://user-images.githubusercontent.com/38053277/219471599-c06cc90f-4a03-4201-a091-d0f766abe885.png)

**Comment by augustsaintfreytag** [comment] 2023-02-16 19:54
Can confirm that this was fixed in commits made today for `yt-dlp` and that the latest version on `master` is working.

I honestly followed a Google search for the error description here and didn’t notice this is the repo for `yt-dl`, not `yt-dlp`, still hope the information is useful to you over here.

**Closed** 2023-02-16 22:45 UTC

**Comment by younikingneerajgupta** [comment] 2023-09-19 09:21
I am also facing this issue kindly help
