### ISSUE TITLE
Can't download from viki

### ISSUE THREAD

**Issue by subaddic** [ytdl-org/youtube-dl#30619] opened 2022-02-08 11:17 UTC
```
Microsoft Windows [Version 10.0.19043.1466]
(c) Microsoft Corporation. All rights reserved.



C:\Users\Ebony\YTDL>C:\Users\Ebony\YTDL\youtube-dl.exe https://www.viki.com/videos/1178890v-u, --username Private-p, --password private
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Ebony\YTDL>C:\Users\Ebony\YTDL\youtube-dl.exe https://www.viki.com/movies/37584c-present-still-perfect-u, --username Private-p, --password Private
[viki:channel] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\Ebony\YTDL>C:\Users\Ebony\YTDL\youtube-dl.exe https://www.viki.com/videos/1191388v-u, username Private-p, password Private
[viki] 1191388v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
these were errors I got while trying to download. Not sure what I'm doing so sorry if I do this wrong. Just hoping for some answers. I don't know what it means to call with the --verbose flag.

**Comment by dirkf** [comment] 2022-02-08 13:04
Duplicate of #30592 (etc), fixed in git master.

>... I don't know what it means to call with the --verbose flag.

You put `--verbose` (or `-v`) as an option string after the yt-dl command, conventionally before the URL. [Separate options with space rather than comma (even if comma may be a valid separator). It's a good idea to put the URL and maybe also your username and password in "double-quotes" in case they contain characters that could be misunderstood by the command-line shell.](https://ss64.com/nt/syntax-esc.html). Eg:
```
C:\Users\Ebony\YTDL>C:\Users\Ebony\YTDL\youtube-dl.exe -v --username "Private" -p "Private" "https://www.viki.com/videos/1191388v-u"
...
```
Also, the [Fine Manual](https://github.com/ytdl-org/youtube-dl#user-content-description).

**Closed** 2022-06-08 02:36 UTC
Labels: duplicate, fixed
