### ISSUE TITLE
Can't download on M6 Replay 

### ISSUE THREAD

**Issue by tigerwolf974** [ytdl-org/youtube-dl#28722] opened 2021-04-10 06:22 UTC
➜  ~ 
**I try to download a video on M6 replay but i get an error.**
Link is : [https://www.6play.fr/objectif-top-chef-p_4454/semaine-1-journee-1-s6-c_12756767](https://www.6play.fr/objectif-top-chef-p_4454/semaine-1-journee-1-s6-c_12756767)
Can i have some help please ?
> ```
> youtube-dl -F https://www.6play.fr/objectif-top-chef-p_4454/semaine-1-journee-1-s6-c_12756767 --verbose 
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'-F', u'https://www.6play.fr/objectif-top-chef-p_4454/semaine-1-journee-1-s6-c_12756767', u'--verbose']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2021.04.07
> [debug] Python version 2.7.16 (CPython) - Darwin-20.2.0-x86_64-i386-64bit
> [debug] exe versions: ffmpeg N-101901-gb593abda6c-tessus
> [debug] Proxy map: {}
> [6play] 12756767: Downloading JSON metadata
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/sixplay.py", line 113, in _real_extract
>     self._sort_formats(formats)
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
>     raise ExtractorError('No video formats found')
> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 
> ```

**Comment by Jaaa01** [comment] 2021-07-15 07:06
Same issue reported here:
https://github.com/ytdl-org/youtube-dl/issues/29549

tigerwolf974 would better say nothing.

**Comment by dirkf** [comment] 2022-10-14 10:41
Duplicate of #24967.

**Closed by dirkf** 2022-10-14 10:41 UTC
