### ISSUE TITLE
[Pluralsight] Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug 

### ISSUE THREAD

**Issue by tretanriyan** [ytdl-org/youtube-dl#30609] opened 2022-02-07 06:42 UTC
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--sleep-interval', '150', '--max-sleep-interval', '200', '--limit-rate', '1M', '-o', '%(playlist_index)s-%(chapter_number)s-%(title)s-%(resolution)s.%(ext)s', '--verbose', 'https://app.pluralsight.com/library/courses/architecting-asp-dot-net-core-applications-best-practices']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] architecting-asp-dot-net-core-applications-best-practices: Downloading JSON metadata
[download] Downloading playlist: Architecting ASP.NET Core Applications: Best Practices
[pluralsight:course] playlist Architecting ASP.NET Core Applications: Best Practices: Collected 71 video ids (downloading 71 of them)
[download] Downloading video 1 of 71
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment] 2022-02-07 11:16
Duplicate of #29776, unfortunately.

**Closed** 2022-02-07 12:55 UTC
Labels: broken-IE, account-needed, duplicate
