### ISSUE TITLE
PluralSight ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); 

### ISSUE THREAD

**Issue by rrskumar4** [ytdl-org/youtube-dl#26331] opened 2020-08-15 01:29 UTC
Hello Team need an assistance in below:

C:\Y>youtube-dl.exe -U
youtube-dl is up-to-date (2020.07.28)

C:\Y>youtube-dl -u ****** -p ****** https://app.pluralsight.com/library/courses/commvault-help-desk-operator/table-of-contents
[pluralsight:course] commvault-help-desk-operator: Downloading JSON metadata
[download] Downloading playlist: Commvault® Help Desk Operator
[pluralsight:course] playlist Commvault® Help Desk Operator: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Y>youtube-dl -u ****** -p ****** https://app.pluralsight.com/library/courses/commvault-help-desk-operator/table-of-contents --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://app.pluralsight.com/library/courses/commvault-help-desk-operator/table-of-contents', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] commvault-help-desk-operator: Downloading JSON metadata
[download] Downloading playlist: Commvault® Help Desk Operator
[pluralsight:course] playlist Commvault® Help Desk Operator: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 627, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

tried adding cookies.txt also no luck

Thanks in advance

**Comment by sagarvd01** [comment] 2020-08-15 05:14
Same here. Getting the following

```
>youtube-dl -U
youtube-dl is up-to-date (2020.07.28)
[pluralsight:course] illustrator-cc-crafting-visual-identity-2441: Downloading JSON metadata
[download] Downloading playlist: Crafting a Visual Identity in Illustrator CC
[pluralsight:course] playlist Crafting a Visual Identity in Illustrator CC: Collected 16 video ids (downloading 16 of them)
[download] Downloading video 1 of 16
[pluralsight] Downloading login page
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by booyaa** [comment] 2020-08-15 11:57
Will try to see if this workaround still works: #24008

**Comment by dirkf** [comment] 2022-02-07 12:22
Duplicate of #29776, now.

**Closed by dirkf** 2022-02-07 12:22 UTC
