### ISSUE TITLE
Youtube-dl does not list all formats available on Youtube during a livestream

### ISSUE THREAD

**Issue by mlindner** [ytdl-org/youtube-dl#29013] opened 2021-05-09 07:37 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2021.04.26**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.youtube.com/watch?v=J71s2KmkSrc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Git HEAD: 227445ece
[debug] Python version 3.9.5 (CPython) - macOS-11.3-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] J71s2KmkSrc: Downloading webpage
[youtube] J71s2KmkSrc: Downloading m3u8 information
[youtube] J71s2KmkSrc: Downloading MPD manifest
[info] Available formats for J71s2KmkSrc:
format code  extension  resolution note
91           mp4        256x144     290k , avc1.42c00b, 15.0fps, mp4a.40.5
92           mp4        426x240     546k , avc1.4d4015, 30.0fps, mp4a.40.5
93           mp4        640x360    1209k , avc1.4d401e, 30.0fps, mp4a.40.2
94           mp4        854x480    1568k , avc1.4d401f, 30.0fps, mp4a.40.2
95           mp4        1280x720   2969k , avc1.4d401f, 30.0fps, mp4a.40.2
96           mp4        1920x1080  5420k , avc1.640028, 30.0fps, mp4a.40.2 (best)
```

## Description

When loading this video https://www.youtube.com/watch?v=J71s2KmkSrc I can see in the browser a 4K option available (format code 313) but youtube-dl does not show that as a valid option.

```
$ youtube-dl -F 'https://www.youtube.com/watch?v=J71s2KmkSrc'
[youtube] J71s2KmkSrc: Downloading webpage
[youtube] J71s2KmkSrc: Downloading m3u8 information
[youtube] J71s2KmkSrc: Downloading MPD manifest
[info] Available formats for J71s2KmkSrc:
format code  extension  resolution note
91           mp4        256x144     290k , avc1.42c00b, 15.0fps, mp4a.40.5
92           mp4        426x240     546k , avc1.4d4015, 30.0fps, mp4a.40.5
93           mp4        640x360    1209k , avc1.4d401e, 30.0fps, mp4a.40.2
94           mp4        854x480    1568k , avc1.4d401f, 30.0fps, mp4a.40.2
95           mp4        1280x720   2969k , avc1.4d401f, 30.0fps, mp4a.40.2
96           mp4        1920x1080  5420k , avc1.640028, 30.0fps, mp4a.40.2 (best)
```

**Comment by dirkf** [comment] 2021-05-09 10:03
```
$ youtube-dl -v -F  --ignore-config 'https://www.youtube.com/watch?v=J71s2KmkSrc'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--ignore-config', 'https://www.youtube.com/watch?v=J71s2KmkSrc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] J71s2KmkSrc: Downloading webpage
[info] Available formats for J71s2KmkSrc:
format code  extension  resolution note
249          webm       audio only tiny   51k , webm_dash container, opus @ 51k (48000Hz), 31.60MiB
250          webm       audio only tiny   66k , webm_dash container, opus @ 66k (48000Hz), 40.76MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 79.26MiB
251          webm       audio only tiny  132k , webm_dash container, opus @132k (48000Hz), 81.12MiB
160          mp4        256x144    144p   34k , mp4_dash container, avc1.4d400c@  34k, 30fps, video only, 20.92MiB
278          webm       256x144    144p   35k , webm_dash container, vp9@  35k, 30fps, video only, 21.60MiB
242          webm       426x240    240p   51k , webm_dash container, vp9@  51k, 30fps, video only, 31.50MiB
133          mp4        426x240    240p   75k , mp4_dash container, avc1.4d4015@  75k, 30fps, video only, 46.42MiB
243          webm       640x360    360p   86k , webm_dash container, vp9@  86k, 30fps, video only, 52.69MiB
134          mp4        640x360    360p  139k , mp4_dash container, avc1.4d401e@ 139k, 30fps, video only, 85.11MiB
244          webm       854x480    480p  133k , webm_dash container, vp9@ 133k, 30fps, video only, 81.64MiB
135          mp4        854x480    480p  239k , mp4_dash container, avc1.4d401f@ 239k, 30fps, video only, 146.56MiB
247          webm       1280x720   720p  268k , webm_dash container, vp9@ 268k, 30fps, video only, 164.14MiB
136          mp4        1280x720   720p  453k , mp4_dash container, avc1.64001f@ 453k, 30fps, video only, 277.50MiB
248          webm       1920x1080  1080p  359k , webm_dash container, vp9@ 359k, 30fps, video only, 220.23MiB
137          mp4        1920x1080  1080p  902k , mp4_dash container, avc1.640028@ 902k, 30fps, video only, 552.71MiB
271          webm       2560x1440  1440p 1698k , webm_dash container, vp9@1698k, 30fps, video only, 1.02GiB
313          webm       3840x2160  2160p 4662k , webm_dash container, vp9@4662k, 30fps, video only, 2.79GiB
18           mp4        640x360    360p  226k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 138.86MiB
22           mp4        1280x720   720p  581k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$ 
```
You may have a configuration option that masks format 313, eg only selecting mp4 format. Format 313 is webm/vp9. 

If you know a format code you can download it with (eg) `-f 313` even if it isn't listed using `-F`.

**Comment by mlindner** [comment] 2021-05-10 02:34
@dirkf The list of formats available has changed since I posted this. I now see what you do, but regardless, at the time i posted (namely while the stream was ongoing) the 4k option was not available.

**Comment by mlindner** [comment] 2021-05-10 02:38
Here is another stream that appears to be continuous showing the lack of 4k option. https://www.youtube.com/watch?v=2CD9aEjFZwU

**Comment by kikuyan** [comment] 2021-05-10 03:06
Found #28117, marked duplicate of #10787.

**Comment by dirkf** [comment] 2021-05-10 08:59
> Also you could have seen in my posted log that I don't have any other configuration options applied.

Good point. 

> Here is another stream that appears to be continuous showing the lack of 4k option. https://www.youtube.com/watch?v=2CD9aEjFZwU

I have a list of formats like the original one you quoted (ie avc1+mp4a in various resolutions). And the web player shows what list of formats?

Anyhow, based on @dstftw's marking of the similar issue #28117 as a duplicate, I assume he understands the underlying problem (if it is one).

**Comment by pukkandan** [comment] 2021-05-13 20:32
youtube-dl doesn't currently support downloading live DASH. Hence why some formats are missing

**Comment by dirkf** [comment] 2021-05-14 03:09
Colour me confused as yt-dl was definitely able to capture the UEFA Champions League final 2019, streamed live with DASH.

When @mlindner listed the formats and didn't get 313 even though it was shown in the browser, was 313 a different format from the one listed in my output?

What would have been the result of running yt-dl with `-f 313` at that point?

**Comment by pukkandan** [comment] 2021-05-14 04:54
> doesn't currently support downloading live DASH

By "live dash", I mean the dash manifest of an ongoing livestream

**Closed** 2021-05-16 12:54 UTC

**Comment by ValZapod** [comment] 2021-05-20 20:20
Wow. Eurovision livestream is in VP9, yet it cannot see it. https://www.youtube.com/watch?v=dVICcSLIHCM
