### ISSUE TITLE
[Broken] TikTokUser/Channel

### ISSUE THREAD

**Issue by fosam** [ytdl-org/youtube-dl#26997] opened 2020-11-16 17:49 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.18**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Windows\System32>youtube-dl https://www.tiktok.com/@alanwalkermusic --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.tiktok.com/@alanwalkermusic', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.11.12
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2020-11-14-git-46e362b765-full_build, ffprobe 2020-11-14-git-46e362b765-full_build
[debug] Proxy map: {}
[generic] @alanwalkermusic: Requesting header
WARNING: Falling back on generic information extractor.
[generic] @alanwalkermusic: Downloading webpage
[generic] @alanwalkermusic: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@alanwalkermusic
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwrmvn5tt\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwrmvn5tt\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwrmvn5tt\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@alanwalkermusic

C:\Windows\System32>
```

## Description

**Unable to download TikTok channel page:**

![99199685-348ff680-27a1-11eb-8e66-6925fbbd85bd](https://user-images.githubusercontent.com/52612348/99285434-c8ac9d00-2837-11eb-96e1-b7b2446b571f.png)

**Comment by Mippy** [comment] 2020-11-16 17:57
See the valid structure for a TikTok user download:

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tiktok.py#L106

**Comment by fosam** [comment] 2020-11-16 19:50
> I am not sure how you can obtain that kind of link.

That is the old url scheme for profile links, now i think it has changed so it won't work anymore. TikTok always changes.

**Comment by llacb47** [comment] 2020-11-16 19:53
Duplicate of https://github.com/ytdl-org/youtube-dl/issues/23264

**Comment by fosam** [comment] 2020-11-18 13:21
That one has been open for so long, let's hope it gets fixed soon

**Comment by TaktakTaktouk** [comment] 2020-11-18 15:04
this happen also with a single video from tiktok

**Comment by Ekolu** [comment] 2020-11-26 10:15
I can also confirm that single tiktok video download does not work and that tiktok channel videos download also does not work. Could you guys please look into it? TikTok is becoming one of the biggest video sharing platform worldwide, it is a pity youtube-dl does not support it.

**Comment by fosam** [comment] 2020-11-26 11:53
Youtube dl supports it, it's just broken

**Closed** 2020-11-29 01:18 UTC
