### ISSUE TITLE
[Ted] Unable to extract info json

### ISSUE THREAD

**Issue by ergeka** [ytdl-org/youtube-dl#31684] opened 2023-02-24 18:44 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl --verbose "https://www.ted.com/talks/clement_freze_penser_le_hasard_rationnellement?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ted.com/talks/clement_freze_penser_le_hasard_rationnellement?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[ted] clement_freze_penser_le_hasard_rationnellement: Downloading webpage
ERROR: Unable to extract info json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/ted.py", line 151, in _real_extract
    return self._talk_info(url, name)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/ted.py", line 182, in _talk_info
    info = self._extract_info(webpage)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/ted.py", line 139, in _extract_info
    info_json = self._search_regex(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract info json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

**Comment by ergeka** [comment] 2023-02-24 18:48
Linux Mint 21.1 cinnamon 5.6.7
Noyau linux 5.15.0-60 generic

**Comment by dirkf** [comment] 2023-02-24 19:30
Duplicate of #30561. Also, #30839.

**Closed by dirkf** 2023-02-24 19:30 UTC

**Comment by ergeka** [comment] 2023-02-25 08:54
Excuse me
Gérard.

**Comment by dirkf** [comment] 2023-02-25 12:20
It was some time ago!

**Comment by erdoukki** [comment] 2023-02-26 15:18
Héllo,

same issue...
Specific issue...

Will report here, and reclose the issue...
Then I will take a look to the referred (already known) issue to look if it could help to report...


The issue on LinuxMINT, 202302 full updated (but upgraded from previous release 2022...)
I get the same problem and fixed with all remove and uninstall from debian/ubuntu package, pip in root env (with sudoà and user env...

Then install again of yt-dlp with pip (user default env only)...

All workd fine with the given url on this specific error !!

**Comment by ergeka** [comment] 2023-02-26 16:33
Hi,
Thanks with that : it's now ok for me ! :-)
Gérard
