### ISSUE TITLE
southpark.cc.com

### ISSUE THREAD

**Issue by dwaderich** [ytdl-org/youtube-dl#23098] opened 2019-11-15 14:48 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dl version **2019.11.05**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'https://southpark.cc.com/full-episodes/s23e07-board-girls', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-94431-g42a2edcc1d, ffprobe N-94431-g42a2edcc1d
[debug] Proxy map: {}
[southpark.cc.com] s23e07-board-girls: Downloading webpage
[southpark.cc.com] ac8deadf-b355-11e9-9fb2-70df2f866ace: Downloading info
[southpark.cc.com] 5e762877-82df-4404-befa-f35edc18eb52: Extracting information
[southpark.cc.com] 5e762877-82df-4404-befa-f35edc18eb52: Downloading video urls
ERROR: southpark.cc.com returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\mtv.py", line 287, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\mtv.py", line 216, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\mtv.py", line 228, in _get_videos_info_from_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\mtv.py", line 156, in _get_video_info
youtube_dl.utils.ExtractorError: southpark.cc.com returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.
```

## Description

unable to process video from southpark.cc.com.

**Comment by Ajithkumarsekar** [comment] 2019-11-15 15:30
Have you checked this website https://southpark.cc.com/full-episodes/s23e07-board-girls. It says the video is not available

**Comment by dwaderich** [comment] 2019-11-15 15:36
yes, that URL works as expected.  it does look like the video is now hosted by hulu though; not sure if thats always been the case

**Comment by remitamine** [comment] 2019-11-15 15:39
Duplicate of #1629.

**Closed by remitamine** 2019-11-15 15:39 UTC
