### ISSUE TITLE
error on arte.tv

### ISSUE THREAD

**Issue by warichnict** [ytdl-org/youtube-dl#31389] opened 2022-11-30 15:22 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
918010$ ~/bin/youtube-dl.exe -v https://www.arte.tv/de/videos/106622-000-A/fuer-eine-frau/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.arte.tv/de/videos/106622-000-A/fuer-eine-frau/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[ArteTV] 106622-000-A: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default


```

## Description

dosnt work n arte movie (which is also not downloadable through the app, some are for 48h or so but this not), it plays in browser but gets 404 in command line

**Comment by dirkf** [comment] 2022-11-30 19:42
Duplicate of #30919, where you can read about the proposed resolution and interim work-arounds, and yet 
> I've searched the bugtracker for similar bug reports including closed ones

**Closed by dirkf** 2022-11-30 19:42 UTC
