### ISSUE TITLE
youtube-dl is broken on youtube

### ISSUE THREAD

**Issue by Sollidottingen** [ytdl-org/youtube-dl#31756] opened 2023-03-04 08:25 UTC
## Checklist

- [x] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by MrRawes** [comment] 2023-03-04 09:59
duplicate of #31755

**Comment by Sollidottingen** [comment] 2023-03-04 10:15
How can i +1 the original error?

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: ***@***.***>
Skickat: den 4 mars 2023 10:59
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [ytdl-org/youtube-dl] youtube-dl is broken on youtube (Issue #31756)


duplicate of #31755<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fytdl-org%2Fyoutube-dl%2Fissues%2F31755&data=05%7C01%7C%7C2498a76ec0ad4eaf41cb08db1c972f2f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638135207874996224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gcr4%2F5FT2xfQvao3Vyf0VhJKZC1Hw2smSDUpHvg%2BjKk%3D&reserved=0>

**Closed** 2023-03-04 11:24 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-03-04 11:39
**Still** #30839.
