### ISSUE TITLE
Pluralsight.com - Unable to log in

### ISSUE THREAD

**Issue by KarlG1965** [ytdl-org/youtube-dl#22425] opened 2019-09-16 09:05 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.09.12.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o%(playlist_index)s - %(title)s.%(ext)s', '-v', '--min-sleep-interval', '40', '--max-sleep-interval', '70', '--limit-rate', '350K', '--playlist-start', '1', 'https://www.pluralsight.com/courses/vue-getting-started']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.12.1
[debug] Python version 3.6.8 (CPython) - Linux-5.2.14-050214-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2, phantomjs 5
[debug] Proxy map: {}
[pluralsight:course] vue-getting-started: Downloading JSON metadata
[download] Downloading playlist: Vue: Getting Started
[pluralsight:course] playlist Vue: Getting Started: Collected 64 video ids (downloading 64 of them)
[download] Downloading video 1 of 64
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    self.initialize()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 433, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pluralsight.py", line 165, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/pluralsight.py", line 215, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Unable to login to Pluralsight with my active account and password. I confirm that I can login and view via a web browser

**Comment by lucasdistasi** [comment] 2019-09-19 01:20
Did you find a solution? It works on Windows but for me never worked on Linux.

**Comment by blakeex** [comment] 2019-10-01 19:03
I got issue when downloading Pluralsight video.

`
C:\Users\AceJoe\Documents\Pluralsight>youtube-dl --username "joehh@gmail.com" --
password "$WqQ4Rntm*QgMCW" --verbose --sleep-interval 120 "https://app.pluralsig
ht.com/library/courses/clean-architecture-patterns-practices-principles/table-of
-contents" --all-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-
-verbose', '--sleep-interval', '120', 'https://app.pluralsight.com/library/cours
es/clean-architecture-patterns-practices-principles/table-of-contents', '--all-s
ubs']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.09.28
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] clean-architecture-patterns-practices-principles: Downloadi
ng JSON metadata
[download] Downloading playlist: Clean Architecture: Patterns, Practices, and Pr
inciples
[pluralsight:course] playlist Clean Architecture: Patterns, Practices, and Princ
iples: Collected 35 video ids (downloading 35 of them)
[download] Downloading video 1 of 35
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to login: Invalid user name or password
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91gr
vc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91gr
vc\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91gr
vc\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91gr
vc\build\youtube_dl\extractor\pluralsight.py", line 165, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpyi91gr
vc\build\youtube_dl\extractor\pluralsight.py", line 198, in _login
youtube_dl.utils.ExtractorError: Unable to login: Invalid user name or password


C:\Users\AceJoe\Documents\Pluralsight>`

**Comment by niks290192** [comment] 2019-11-01 17:01
Issue on Mac 

pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by xandor-dev** [comment] 2020-05-06 18:08
Until recently yt-dl was worked fine but now the same cmd produced an error:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--ignore-errors', '--verbose', '--sleep-interval', '92', '--merge-output-format', 'mp4', '-o', '%(autonumber)s-%(title)s-%(id)s.%(ext)s', 'https://app.pluralsight.com/library/courses/aspdotnet-core-signalr-getting-started/table-of-contents']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.05.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] aspdotnet-core-signalr-getting-started: Downloading JSON metadata
[download] Downloading playlist: Getting Started with ASP.NET Core SignalR
[pluralsight:course] playlist Getting Started with ASP.NET Core SignalR: Collected 35 video ids (downloading 35 of them)
[download] Downloading video 1 of 35
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\common.py", line 433, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\pluralsight.py", line 165, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpybwhja3m\build\youtube_dl\extractor\pluralsight.py", line 215, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment] 2022-02-07 12:39
Duplicate of #29776, now.

**Closed by dirkf** 2022-02-07 12:39 UTC
