### ISSUE TITLE
[ITV] ERROR: Unable to extract params ('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by Qiangong2** [ytdl-org/youtube-dl#32410] opened 2023-07-06 20:45 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
python3 -m youtube_dl --user-agent "Mozilla/5.0" -f mp4/best http://www.itv.com/watch/the-chase/1a7842/1a7842a1903 --hls-prefer-ffmpeg --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--user-agent', 'Mozilla/5.0', '-f', 'mp4/best', 'http://www.itv.com/watch/the-chase/1a7842/1a7842a1903', '--hls-prefer-ffmpeg', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: f24bc9272
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit - OpenSSL 3.1.1 30 May 2023
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0, rtmpdump 2.4
[debug] Proxy map: {}
[ITV] 1a7842a1903: Downloading webpage
ERROR: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/Orca/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 829, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Orca/Downloads/youtube-dl/youtube_dl/YoutubeDL.py", line 850, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/Users/Orca/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 535, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Orca/Downloads/youtube-dl/youtube_dl/extractor/itv.py", line 193, in _real_extract
    params = extract_attributes(self._search_regex(
                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/Orca/Downloads/youtube-dl/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

I'm trying to download videos from ITV, however, each time I try (regardless of the video), I get an "unable to extract params" error. I am using the latest master. I can watch any of the shows through the browser without issue.

Only similar issue I've been able to find is #22638 which does not give a fix

**Comment by xaoscience** [comment] 2023-07-06 21:11
My error ("unable to extract uploader id") may be related and caused by the same RegexNotFoundError('Unable to extract %s' % _name).

`Enter query: Hello
Searching Hello
YQHsXMglC9A
ffplay version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', '-o', '-', 'https://www.youtube.com/watch?v=YQHsXMglC9A']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] YQHsXMglC9A: Downloading webpage    0KB sq=    0B f=0/0   
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by dirkf** [comment] 2023-07-06 22:41
@xaoscience, no: read #30839 as asked.

#22638 hasn't got anything to do with ITV. Unfortunately the ITV(x) page structure has changed. The desired playlist URL can now be found with this:
```diff
--- old/youtube_dl/extractor/itv.py
+++ new/youtube_dl/extractor/itv.py
@@ -189,14 +189,19 @@
 
         webpage = self._download_webpage(url, video_id)
 
-        # now quite different params!
-        params = extract_attributes(self._search_regex(
-            r'''(<[^>]+\b(?:class|data-testid)\s*=\s*("|')genie-container\2[^>]*>)''',
-            webpage, 'params'))
-
-        ios_playlist_url = traverse_obj(
-            params, 'data-video-id', 'data-video-playlist',
-            get_all=False, expected_type=url_or_none)
+        ios_playlist_url = url_or_none(self._search_regex(
+            r'''\bplaylistUrl['"]\s*:\s*(?P<q>"|')(?P<url>https?://magni\.itv\.com/playlist/(?:(?!(?=q)).)+)''',
+            webpage, 'playlist URL', group='url', fatal=False))
+
+        if not ios_playlist_url:
+            # legacy: does it ever happen?
+            params = extract_attributes(self._search_regex(
+                r'''(<[^>]+\b(?:class|data-testid)\s*=\s*("|')genie-container\2[^>]*>)''',
+                webpage, 'params'))
+
+            ios_playlist_url = traverse_obj(
+                params, 'data-video-id', 'data-video-playlist',
+                get_all=False, expected_type=url_or_none)
 
         headers = self.geo_verification_headers()
         headers.update({
```
Again unfortunately, then we get 404 
```console
...
[ITV] 1a7842a1903: Downloading webpage
[ITV] 1a7842a1903: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found ...
```
when fetching the data with the URL.

Perhaps @Vangelis66 can advise on how, or if at all, the POST to the playlist URL can be modified so as to return valid data.

**Comment by ta264** [comment] 2023-07-07 13:03
I ran into this yesterday.  I believe the issue is the variantAvailability parameter.  Currently it is sending:

```
'variantAvailability': {
                    'player': 'hls',
                    'featureset': {
                        'min': ['hls', 'aes', 'outband-webvtt'],
                        'max': ['hls', 'aes', 'outband-webvtt']
                    },
                    'platformTag': 'mobile'
                }
```
This returns 404 and the following message:
```
{
	"Message": "something needed to service this request was missing",
	"TransactionId": "oas-xxx"
}
```

The desktop web client sends:
```
  "variantAvailability": {
    "player": "hls",
    "featureset": {
      "min": [
        "mpeg-dash",
        "widevine",
        "outband-webvtt",
        "hd",
        "single-track"
      ],
      "max": [
        "mpeg-dash",
        "widevine",
        "outband-webvtt",
        "hd",
        "single-track"
      ]
    },
    "platformTag": "dotcom"
  }
```

But the response from this doesn't allow the download to work.

FWIW I think this 404 might only apply to newer shows.  It fails for
https://www.itv.com/watch/tour-de-france/34067/1a7000a0353

But the original POST params work for the built in test case:
https://www.itv.com/watch/vera/1a7314/1a7314a0014

**Comment by iskigow** [comment] 2023-07-07 13:21
Similar on some YouTube URLs, but as a WARNING and it is still possible to download the file.

```bash
❯ youtube-dl --verbose -w -o "Day4.mp4" https://youtu.be/nlGIBcMc-oo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-w', '-o', 'Day4.mp4', 'https://youtu.be/nlGIBcMc-oo']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-46-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] nlGIBcMc-oo: Downloading webpage
[youtube] nlGIBcMc-oo: Downloading player 1dda5629
WARNING: [youtube] Unable to decode n-parameter: download likely to be throttled (Unable to extract Initial JS player n function alias (Wsa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1668, in _n_descramble
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1640, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/youtube.py", line 1623, in _extract_n_function_name
    real_nfunc = self._search_regex(
  File "/usr/local/lib/python3.10/dist-packages/youtube_dl/extractor/common.py", line 1013, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player n function alias (Wsa[0]); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://rr2---sn-oxunxg8pjvn-jbgs.googlevideo.com/videoplayback?expire=1688755497&ei=yQioZMvDDcyM5gTQkY7IBw&ip=179.214.217.22&id=o-AN1CqedAxlpevC41ieTVpR0EAIOiR6_NeT3NEVmUJW8n&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=Nh&mm=31%2C29&mn=sn-oxunxg8pjvn-jbgs%2Csn-bg0eznsk&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1128750&spc=Ul2Sq6rib7rdlS1A10ohPTnKYyfvUXYvx0tyWRZK_w&vprv=1&svpuc=1&mime=video%2Fmp4&ns=pb-C5sBpt8XZ1WsWV8bOb7EO&gir=yes&clen=915079030&dur=6916.966&lmt=1686771608585056&mt=1688733654&fvip=5&keepalive=yes&fexp=24007246%2C24362685%2C51000023&c=WEB&txp=5432434&n=gZvM5UW5G7a5PAEo&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgYj1e5Y1PfcQklLfJj9440Hj_zDGNfbCakywIt72SwmgCIDjZ7YtBvpa2Ud0jPML8koPfGQhw01XebMZ8vev7UyEV&sig=AOq0QJ8wRQIhAIH9K5Qo_MfCVtz9_AH-F2dIdRCvIj9VJDQOZ7au_cVLAiAkDRRnrb2uZbIOQUW6IlzHSVdccfa9DeH9T9tf1CoJ1g=='
[dashsegments] Total fragments: 88
[download] Destination: Day4.f137.mp4
[download]   1.1% of ~880.00MiB at 72.49KiB/s ETA 03:24:58
```

**Comment by dirkf** [comment] 2023-07-07 23:34
@iskigow, unrelated: you need to update from the master code; see #32292 etc.

**Comment by dirkf** [comment] 2023-07-07 23:40
>I ran into this yesterday. I believe the issue is the variantAvailability parameter. ...

The desktop client is tied into the DRM stuff. We pretend to be an old mobile, hence `'platformTag': 'mobile'`. Maybe the 404 response is indicating that now there are no media links matching the `featureset` that we want.

**Comment by iskigow** [comment] 2023-07-08 00:05
> @iskigow, unrelated: you need to update from the master code; see #32292 etc.
> 

I'm using the master code, but I will update, rebuild and test again. Thanks.

**Comment by 3052** [comment] 2024-10-27 15:26
are these methods still valid? from my testing DRM is required now:

~~~
10:25:04 INFO GET URL="https://content-inventory.prd.oasvc.itv.com/discovery?query=%7B+titles%28filter%3A+%7B+legacyId%3A+%221%2F7314%2F0014%22+%7D%29+%7B+...+on+Episode+%7B+seriesNumber+episodeNumber+%7D+...+on+Film+%7B+productionYear+%7D+brand+%7B+title+%7D+latestAvailableVersion+%7B+playlistUrl+%7D+title+%7D+%7D"
10:25:04 INFO POST URL=https://magni.itv.com/playlist/itvonline/ITV/1_7314_0014.003
10:25:05 INFO GET URL="https://itvpnpdotcom.blue.content.itv.com/1-7314-0014-003/34/2/VAR028-HD-s/1-7314-0014-003_34_2_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1730042690~exp%3D1730064290~acl%3D/1-7314-0014-003/%2A~hmac%3D3d7081560064290b3fdb25e37093456d4308ca55f8da76051004fd88747b0555"
10:25:06 INFO GET URL="https://itvpnpdotcom.blue.content.itv.com/1-7314-0014-003/34/2/VAR028-HD-s/1-7314-0014-003_34_2_VAR028-HD-s.ism/dash/1-7314-0014-003_34_2_VAR028-HD-s-video=2000536.dash"
10:25:06 INFO POST URL="https://itvpnp.live.ott.irdeto.com/Widevine/getlicense?AccountId=itvpnp"
10:25:06 INFO CDM PSSH=CAESEIa5o8mmj0Pxh1+Z4TU9NlYiEjEtNzMxNC0wMDE0LTAwM18zNDgB key="LkR2HiMp4wEXKLZuA0sBZw=="
10:25:08 INFO 0.23 % size="2.67 megabyte" rate="2.51 megabyte/s"
~~~

**Comment by dirkf** [comment] 2024-10-27 18:40
As above, there used to be an edge case that would cause non-DRM low-res media to be served but that stopped working. Obvs if anyone who can spend time researching the issue comes up with a new work-around it can be implemented, but I'm not optimistic.

**Comment by 3052** [comment] 2024-10-27 18:49
I would recommend closing issue - I just finished the first public implementation of ITVX and from what I can tell DRM is required

**Comment by 3052** [comment] 2024-10-27 18:51
I would recommend closing issue - I just finished the first public implementation of ITVX and from what I can tell DRM is required

@PacoH

**Comment by Vangelis66** [comment] 2024-10-27 19:02
... For those still wanting some (detailed) answers, a recap: 

Nov 2022 saw `ITV Hub` turn into `itvX`; 

During the `ITV Hub` era, `yt-dl` would pretend to be an **old iPhone** to grab 540p **HLSe** streams (HLSe = AES-128 encrypted HLS, a form of "soft" DRM); desktop clients would get **cenc** (full-blown-DRM) MPEG-DASH streams.

`itvX` will since deliver **Apple FairPlay** (full-blown-DRM) HLS streams to "old iPhones"; together with the overall site changes, `yt-dl` became totally kaput for `itvX` ...

A "hack" was discovered to **forcefully request**/extort the decommissioned (but still extant) HLSe mobile streams for use with `yt-dl`.

The "hack" was authored into Python [code](https://github.com/ytdl-org/youtube-dl/pull/30266) and merged into the `master` branch on Feb 4 2023.

`itvX` gradually re-broke the extractor in the month of **July 2023**, but the "hack" itself was finally defeated on July 26 2023: HLSe streams for programmes could no longer be "extorted" (the necessary infra shut down?), thus putting a **definite end** to the `itvX` `yt-dl` extractor (since `yt-dl` won't ever "touch" full-blown DRM) :cry: ...

References: 
https://github.com/yt-dlp/yt-dlp/issues/5570
https://github.com/yt-dlp/yt-dlp/issues/10937

> but I'm not optimistic

...same here :wink: ...

> I would recommend closing issue

I tend to agree, so as not to harbour false hopes... 
It has been a nice ride for many years...

**Comment by 3052** [comment] 2024-10-27 19:10
note as my code block above shows its still very possible to download from ITVX, just not with YouTube-DL/YT-DLP because of policy reasons

**Comment by dirkf** [comment] 2024-10-27 19:43
Happy to re-open if anyone offers a solution, and meanwhile `STVPlayerIE` still appears to work (UK-only, I expect) for the many ITV shows that are also available on STV. North Britain FTW.

**Closed by dirkf** 2024-10-27 19:43 UTC
Labels: broken-IE
