### ISSUE TITLE
IMDB not downloading trailer 

### ISSUE THREAD

**Issue by michael1t** [ytdl-org/youtube-dl#30846] opened 2022-04-11 23:07 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
 youtube-dl https://www.imdb.com/video/vi1266857241

**Comment by dirkf** [comment] 2022-04-11 23:23
>PASTE VERBOSE LOG HERE

So do it, or, if your report is a duplicate of #30824, post there and close this.

**Comment by michael1t** [comment] 2022-04-13 18:33
Sorry forgot verbose data
C:\>youtube-dl http://www.imdb.com/video/imdb/vi393265945?ref_=cs_ov_vi --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.imdb.com/video/imdb/vi393265945?ref_=cs_
ov_vi', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1
[debug] Proxy map: {}
[imdb] 393265945: Downloading JSON metadata
[imdb] 393265945: Downloading m3u8 information
[imdb] 393265945: Downloading webpage
ERROR: Unable to extract video metadata; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\imdb.py", line 93, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c
6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video metadata; please re
port this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.

**Comment by dirkf** [comment] 2022-04-16 04:37
So, duplicate of #30824.

**Closed by dirkf** 2022-04-16 04:37 UTC
