### ISSUE TITLE
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by tshabarek** [ytdl-org/youtube-dl#31330] opened 2022-11-06 11:47 UTC
I am trying to download from UDEMY using cookies but I am receiving this error:

C:\Users\Administrator>youtube-dl.exe --cookies C:\Users\Administrator\Desktop\5f8b09fc-0b2e-4a62-bd52-ffac804329ed.txt https://www.udemy.com/course/flutter-advanced-course-clean-architecture-with-mvvm --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Users\\Administrator\\Desktop\\5f8b09fc-0b2e-4a62-bd52-ffac804329ed.txt', 'https://www.udemy.com/course/flutter-advanced-course-clean-architecture-with-mvvm', '--verbose']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.20348
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
[udemy:course] 4256518: Downloading course curriculum
[download] Downloading playlist: 4256518
[udemy:course] playlist 4256518: Collected 180 video ids (downloading 180 of them)
[download] Downloading video 1 of 180
[udemy] 28121274: Downloading webpage
[udemy] 28121274: Downloading lecture JSON
[udemy] 28121274: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment] 2022-11-06 15:45
Duplicate of #30802, as you would have found by following the broken site issue template.

**Closed by dirkf** 2022-11-06 15:45 UTC
