### ISSUE TITLE
udemy download not possible

### ISSUE THREAD

**Issue by Reiner1210** [ytdl-org/youtube-dl#32058] opened 2023-04-18 20:24 UTC
youtube-dl https://www.udemy.com/course/ngrx-course/learn/lecture/15943110?start=15#overview --verbose --cookies udemy.txt 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.udemy.com/course/ngrx-course/learn/lecture/15943110?start=15#overview', '--verbose', '--cookies', 'udemy.txt']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-5.19.0-38-generic-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] course: Downloading webpage
[udemy:course] 1673770: Downloading course curriculum
[download] Downloading playlist: 1673770
[udemy:course] playlist 1673770: Collected 48 video ids (downloading 48 of them)
[download] Downloading video 1 of 48
[udemy] 16194654: Downloading webpage
[udemy] 16194654: Downloading lecture JSON
[udemy] 16194654: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by dirkf** [comment] 2023-04-18 21:18
Duplicate of #30802.

In that issue a similar command appeared to work for @skupjoe, but also see https://github.com/ytdl-org/youtube-dl/issues/30802#issuecomment-1110929816.

**Closed by dirkf** 2023-04-18 21:18 UTC

**Comment by Reiner1210** [comment] 2023-04-18 22:53
@dirkf you are a funny - closing issues will not solve problems .... if you do not like leave the project

**Comment by dirkf** [comment] 2023-04-19 10:42
Discuss your problem in the existing issue, where, as I pointed out, it is said to be solved.

**Comment by skupjoe** [comment] 2023-04-20 04:51
@Reiner1210 please ensure that you are using this plugin to get the cookies for your `cookies.txt` and that you are using the `Netscape` format:
https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc
