### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 404

### ISSUE THREAD

**Issue by dbjock** [ytdl-org/youtube-dl#28327] opened 2021-03-03 01:30 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.03.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--playlist-reverse', '--verbose', '--min-sleep-interval', '10', '--max-sleep-interval', '30', '--dateafter', 'now-4weeks', '--download-archive', '/home/UTubeVids/testing/downloaded.txt', '-i', '-f', 'best', '-o', '/home/UTubeVids/testing/%(uploader)s/%(playlist)s/%(playlist)s - %(release_date)s - %(title)s [%(id)s].%(ext)s', '--batch-file=/home/UTubeVids/testing/channel_list.txt']
[debug] Batch file urls: ['https://www.youtube.com/channel/UC0woBco6Dgcxt0h8SwyyOmw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.02
[debug] Python version 3.8.6 (CPython) - Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:tab] UC0woBco6Dgcxt0h8SwyyOmw: Downloading webpage
[download] Downloading playlist: Megaprojects - Home
[youtube:tab] playlist Megaprojects - Home: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube:tab] UC0woBco6Dgcxt0h8SwyyOmw: Downloading webpage
[download] Downloading playlist: Megaprojects - Videos
[youtube:tab] Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/pops/youtube-dl/venv/lib64/python3.8/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/pops/youtube-dl/venv/lib64/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

Error received on first URL in channel list. Other channels successfully downloaded.

**Comment by xijin1337** [comment] 2021-03-03 01:48
same problem here

**Comment by libjared** [comment] 2021-03-03 01:48
I'm also seeing this with no arguments other than a public playlist URL and `--verbose`.

**Comment by afe2c3** [comment] 2021-03-03 01:49
Serverside issue. Dupe of #28289

**Comment by afe2c3** [comment] 2021-03-03 01:49
check existing issues beforehand

**Comment by colethedj** [comment] 2021-03-03 01:51
After some investigating, I might be wrong about it being server side - https://github.com/ytdl-org/youtube-dl/issues/28289#issuecomment-789362801

**Comment by Z4R10N** [comment] 2021-03-03 02:28
Same error here. Version 2021.02.10

No error with version 2020.12.31 - Just limits playlists to 30 [old problem].

**Comment by eldr4** [comment] 2021-03-03 02:58
Same issue here
verbose-
D:\Youtube Vids 2\BG Kumbi> yt -r 8m -ciw https://www.youtube.com/c/BGKumbi/videos --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-r', '8m', '-ciw', 'https://www.youtube.com/c/BGKumbi/videos', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.03.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube:tab] BGKumbi: Downloading webpage
[download] Downloading playlist: BG Kumbi - Videos
[youtube:tab] Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_qzp9er5\build\youtube_dl\extractor\common.py", line 632, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp_qzp9er5\build\youtube_dl\YoutubeDL.py", line 2275, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Closed** 2021-03-03 04:43 UTC
