### ISSUE TITLE
Unable to extract video data on YouTube

### ISSUE THREAD

**Issue by ffteame** [ytdl-org/youtube-dl#26023] opened 2020-07-16 19:24 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
 youtube-dl -v https://www.youtube.com/watch?v=gGctiXX3r9Y
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=gGctiXX3r9Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-962.3.2.lve1.5.31.el7.x86_64-x86_64-with-redhat-7.7-Valery_Bykovsky
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[youtube] gGctiXX3r9Y: Downloading webpage
ERROR: gGctiXX3r9Y: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: gGctiXX3r9Y: YouTube said: Unable to extract video data
```

## Description

Hello. I have been encountering this problem for several days, I get this error on most videos. How can I solve the problem?

**Comment by qazwsxdonjon** [comment] 2020-07-16 19:40
I've been getting the same error message recently when trying to download age-restricted videos. I recreated my cookies file but that didn't help anything.

**Comment by ffteame** [comment] 2020-07-16 20:03
I tried with login, but again I get 404 error. (user age is public)

youtube-dl -v -u "*****" -p "*****" "https://www.youtube.com/watch?v=gGctiXX3r9Y"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.youtube.com/watch?v=gGctiXX3r9Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-962.3.2.lve1.5.31.el7.x86_64-x86_64-with-redhat-7.7-Valery_Bykovsky
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
WARNING: Unable to look up account info: HTTP Error 404: Not Found
[youtube] gGctiXX3r9Y: Downloading webpage
ERROR: gGctiXX3r9Y: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1893, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
ExtractorError: gGctiXX3r9Y: YouTube said: Unable to extract video data

**Comment by slowthgt** [comment] 2020-07-16 22:16
#25954 which is a duplicate of #25945 confirms that anything age-restricted is not accessible, even when providing logged in credentials/cookies

**Comment by altimumdelta** [comment] 2020-07-17 12:01
Yeah, happens to me too with this video: https://www.youtube.com/watch?v=ev26u3pcw6g
It does say `ERROR: ev26u3pcw6g: YouTube said: Unable to extract video data` exactly, checking it on another browser reveals the probable issue, it's age-gated and not working unless logged into youtube.

**Comment by Celsyum** [comment] 2020-07-17 12:03
same with youtube-dl -g https://www.youtube.com/watch?v=KLDIDG1ED3o

**Closed** 2020-07-17 20:12 UTC

**Comment by spiralsam** [comment] 2020-07-28 14:47
just commenting on this: I had a video giving this error, so I happened to try it again with JDownloader, and it downloaded just fine without login/cookies
