### ISSUE TITLE
[Udemy] youtube_dl.utils.ExtractorError: No video formats found

### ISSUE THREAD

**Issue by shubhamagarwal1** [ytdl-org/youtube-dl#30455] opened 2022-01-03 11:25 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

(base) PS C:\Users\shubh\Downloads\youtube-DL> youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: avconv present, avprobe present, ffmpeg 2021-12-30-git-12f21849e5-full_build-www.gyan.dev, ffprobe 2021-12-30-git-12f21849e5-full_build-www.gyan.dev
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

--------------------------------

(base) PS C:\Users\shubh\Downloads\youtube-DL> youtube-dl --cookie C:\Users\shubh\Downloads\udemy.com_cookies.txt -o 'C:/UdemyDownloads/SIE/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/siefinraexam/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookie', 'C:\\Users\\shubh\\Downloads\\udemy.com_cookies.txt', '-o', 'C:/UdemyDownloads/SIE/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/siefinraexam/', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: avconv present, avprobe present, ffmpeg 2021-12-30-git-12f21849e5-full_build-www.gyan.dev, ffprobe 2021-12-30-git-12f21849e5-full_build-www.gyan.dev
[debug] Proxy map: {}
[udemy:course] siefinraexam: Downloading webpage
[udemy:course] 1748644: Downloading course curriculum
[download] Downloading playlist: 1748644
[udemy:course] playlist 1748644: Collected 236 video ids (downloading 236 of them)
[download] Downloading video 1 of 236
[udemy] 14991748: Downloading webpage
[udemy] 14991748: Downloading lecture JSON
[udemy] 18371590: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/18371590/files/2019-06-04_13-55-17-6c78055b578ce785e9f5e5ad5d663433/1/hls/AVC_1920x1080_800k_AAC-HE_64k/aa001da044de0f8b61938037fe1e610e8b88.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0wNi0wNF8xMy01NS0xNy02Yzc4MDU1YjU3OGNlNzg1ZTlmNWU1YWQ1ZDY2MzQzMy8xLyIsImV4cCI6MTY0MTIyNTI1Nn0.gMm_4t-dJtAdlJBkNSkpa3omvsw_PVC6A3GesDs5HwU&v=1'
[download] C:\UdemyDownloads\SIE\1748644\1 - Course Introduction\Course Introduction.mp4 has already been downloaded
[download] 100% of 1.68MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\UdemyDownloads\SIE\1748644\1 - Course Introduction\Course Introduction.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\UdemyDownloads\SIE\1748644\1 - Course Introduction\Course Introduction.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\UdemyDownloads\SIE\1748644\1 - Course Introduction\Course Introduction.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\UdemyDownloads\SIE\1748644\1 - Course Introduction\Course Introduction.temp.mp4"
[download] Downloading video 2 of 236
[udemy] 14632682: Downloading webpage
[udemy] 14632682: Downloading lecture JSON
[udemy] 18629010: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.udemy.com/assets/18629010/files/2019-06-21_19-11-56-8dbb4a06876c703cfd632e057d5f15c5/1/hls/AVC_1920x1080_800k_AAC-HE_64k/aa00caab0a1bc017837c716237b707e2c4e3.m3u8?provider=cloudfront&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiMjAxOS0wNi0yMV8xOS0xMS01Ni04ZGJiNGEwNjg3NmM3MDNjZmQ2MzJlMDU3ZDVmMTVjNS8xLyIsImV4cCI6MTY0MTIyNTI1N30.OEt3m6fmUYnOuwOq3igmShrOyHAB4kn_XPpxT8jGNwU&v=1'
[download] C:\UdemyDownloads\SIE\1748644\2 - Section 1 - Conducting Yourself as a Financial Services Professional\SIE Exam Overview.mp4 has already been downloaded
[download] 100% of 4.06MiB
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\UdemyDownloads\SIE\1748644\2 - Section 1 - Conducting Yourself as a Financial Services Professional\SIE Exam Overview.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "C:\UdemyDownloads\SIE\1748644\2 - Section 1 - Conducting Yourself as a Financial Services Professional\SIE Exam Overview.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\UdemyDownloads\SIE\1748644\2 - Section 1 - Conducting Yourself as a Financial Services Professional\SIE Exam Overview.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:C:\UdemyDownloads\SIE\1748644\2 - Section 1 - Conducting Yourself as a Financial Services Professional\SIE Exam Overview.temp.mp4"
[download] Downloading video 3 of 236
[udemy] 14967712: Downloading webpage
[udemy] 14967712: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\udemy.py", line 408, in _real_extract
    self._sort_formats(formats, field_preference=('height', 'width', 'tbr', 'format_id'))
  File "c:\programdata\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

I see the "No video format found" error when I try to download a course from Udemy.

**Comment by kikuyan** [comment] 2022-01-03 11:45
Tons of duplicates, actually.

**Comment by dirkf** [comment] 2022-01-03 12:09
In particular, duplicate of #29925.

**Comment by 89z** [comment] 2022-01-29 19:11
https://github.com/ytdl-org/youtube-dl/issues/30569

**Closed** 2022-04-27 11:55 UTC
Labels: duplicate
