### ISSUE TITLE
cannot download from youtube using youtube-dl version 2021.12.17

### ISSUE THREAD

**Issue by xyz-cba** [ytdl-org/youtube-dl#31718] opened 2023-02-27 18:50 UTC
$ youtube-dl --verbose "https://www.youtube.com/watch?v=ymSq4wHrqyU"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ymSq4wHrqyU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ymSq4wHrqyU: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/yonatan/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yonatan/.local/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/yonatan/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/yonatan/.local/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/home/yonatan/.local/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tomascarlo** [comment] 2023-02-27 19:32
duplicate of [#31717](https://github.com/ytdl-org/youtube-dl/issues/31718)

**Comment by linux-rox** [comment] 2023-02-27 19:33
This is a known issue: https://github.com/ytdl-org/youtube-dl/issues/31530

See link for workarounds.  What worked for me was pip install --upgrade git+https://github.com/ytdl-org/youtube-dl.git@master.  You may have to install pip and/or git.  You might also have to adjust your $PATH variable, if (as in my case) the upgrade is downloaded to $HOME/.local/bin.  You do that by editing .bashrc or .profile.

**Comment by boberle** [comment] 2023-02-27 19:49
I got the same error. The release dates back to 2021, but Youtube-dl is regularly updated. You seem to be on Linux, so you can clone the repo and get the last version of Youtube-dl (assuming you have `git` and `make` installed):

```
git clone https://github.com/ytdl-org/youtube-dl.git
cd youtube-dl
make youtube-dl
./youtube-dl YOUR_VIDEO_URL
```

This works for me.

**Comment by Barlafuss** [comment] 2023-02-27 21:37
@boberle thanks for the hint, worked here too !

**Comment by Vangelis66** [comment] 2023-02-27 21:58
**OP** had just opened [another duplicate](https://github.com/ytdl-org/youtube-dl/issues/31714) mere hours ago, so I can't, in all honestly, fathom the need for yet another one 😡 ... Directions [already posted](https://github.com/ytdl-org/youtube-dl/issues/31714#issuecomment-1446336730) in that previous one should have been followed - if English poses a challenge to you, use your favourite machine translator...

**Comment by Sprinterfreak** [comment] 2023-02-27 22:19
Same issue here. Installing via pip directly from master https://github.com/ytdl-org/youtube-dl/commit/f7ce98a21e15cb094c772e9082796d009c61578b like @linux-rox suggested unfortunately did not work. I guess make vs. pip should make no difference in this regard?

**Comment by Sprinterfreak** [comment] 2023-02-27 22:27
Update, did work but must be installed fresh. Pip's --upgrade does not work in this case.

```bash
pip uninstall -y youtube-dl
pip install git+https://github.com/ytdl-org/youtube-dl.git@master
```
Success

**Closed** 2023-02-27 23:09 UTC

**Comment by xyz-cba** [comment] 2023-02-28 10:20
Thanks a lot. It works.
