### ISSUE TITLE
youtube-dl failed to extract uploader id

### ISSUE THREAD

**Issue by nibaro-sbT** [ytdl-org/youtube-dl#31622] opened 2023-02-20 07:44 UTC
I did the checklist, and tried it on 2 different computers, seams like youtube got updated, and now the yt-dl is broaken. 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=JRdYSGh-g3s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - Linux-6.0.1-arch2-1-x86_64-with-glibc2.36
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] JRdYSGh-g3s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by nibaro-sbT** [comment] 2023-02-20 07:56
It works tho if I download the code from github and run it with __main__.py maby outdated binary issue?

**Comment by rnhurt** [comment] 2023-02-20 08:58
> It works tho if I download the code from github and run it with **main**.py maby outdated binary issue?

I was also able to clone this repo, run it manually, and download the MP4 file.  However, the ERROR turned into a WARNING, so there is still something wrong somewhere.  🤔

**Comment by mcarthur-cpt** [comment] 2023-02-20 09:44
youtube-dl --verbose -f best https://www.youtube.com/playlist?list=PLVybe8kv4KtahEz0fD68HURDD8NGig34y
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', 'best', 'https://www.youtube.com/playlist?list=PLVybe8kv4KtahEz0fD68HURDD8NGig34y']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg N-109468-gd39b34123d-20221231, ffprobe N-109468-gd39b34123d-20221231
[debug] Proxy map: {}
[youtube:tab] PLVybe8kv4KtahEz0fD68HURDD8NGig34y: Downloading webpage
[download] Downloading playlist: DL
[youtube:tab] playlist DL: Downloading 82 videos
[download] Downloading video 1 of 82
[youtube] QCKUpFMmKJw: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by edwinjue** [comment] 2023-02-20 09:50
hasn't been merged but this PR fixes the issue https://github.com/ytdl-org/youtube-dl/pull/31568#pullrequestreview-1304594825

**Comment by Krisselack** [comment] 2023-02-20 10:06
Thank you, solution worked for me as well. Warning is also there. 
git clone https://github.com/ytdl-org/youtube-dl/
cd youtube-dl 
replace command youtube-dl (in the youtube-dl folder) with: 
python __main__.py --options

**Comment by juanfal** [comment] 2023-02-20 11:24
Same here:

     $ youtube-dl --verbose 'https://www.youtube.com/watch?v=_w1I_2RsH-c'
    [debug] System config: []
    [debug] User config: []
    [debug] Custom config: []
    [debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=_w1I_2RsH-c']
    [debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
    [debug] youtube-dl version 2021.12.17
    [debug] Python version 3.11.2 (CPython) - macOS-13.2.1-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] _w1I_2RsH-c: Downloading webpage
    ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
        return func(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
        ie_result = ie.extract(url)
                    ^^^^^^^^^^^^^^^
      File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
        ie_result = self._real_extract(url)
                    ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
        'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Seifert69** [comment] 2023-02-20 12:09
I'm having the same issue. It's a "private" video (anyone who has the link can view) so I suspect that is the cause of the problem.

**Comment by m0ntana** [comment] 2023-02-20 12:13
i have same issue with music videos i used to listen for a months

```
m0ntana@panamtana:~$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
m0ntana@panamtana:~$ youtube-dl --verbose "https://www.youtube.com/watch?v=flYaIdG4asY"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=flYaIdG4asY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.9.2 (CPython) - Linux-5.10.0-17-amd64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] flYaIdG4asY: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by deuxlames** [comment] 2023-02-20 15:32
Hello, any chance  new binaries are compiled anytime soon ? I tried To clone the repo and run __man__.py but got SSL errors...

**Comment by m0ntana** [comment] 2023-02-20 15:55
> Hello, any chance new binaries are compiled anytime soon ? I tried To clone the repo and run **man**.py but got SSL errors...

clone repo, apply patch from [here](https://github.com/ytdl-org/youtube-dl/pull/31568#pullrequestreview-1304594825) then run
```
sudo pip3 install ./youtube-dl
```
where "youtube-dl" is repo directory

**Closed** 2023-02-20 16:00 UTC
Labels: duplicate

**Comment by dirkf** [comment] 2023-02-20 16:08
It's a warning because the `uploader_id` wasn't extracted.

>I did the checklist, and tried it on 2 different computers, seams like youtube 

And yet you still opened this issue instead of reading the solution linked from the text of the existing issue #31530?
