### ISSUE TITLE
Can't download youtube shorts video

### ISSUE THREAD

**Issue by inmessi** [ytdl-org/youtube-dl#31080] opened 2022-07-10 06:11 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by inmessi** [comment] 2022-07-10 06:16
I tried to download youtube shorts video but it showed:
```
ERROR: Unable to recognize tab page!
```

**Comment by dirkf** [comment] 2022-07-10 14:47
> I've searched the bugtracker for similar bug reports including closed ones

Obvs not.

Duplicate of #30269, fixed in git master by PR #30577.

**Closed** 2022-07-10 14:51 UTC
