### ISSUE TITLE
youtube_dl.utils.ExtractorError: Could not find JS function 'na'

### ISSUE THREAD

**Issue by deatrys** [ytdl-org/youtube-dl#30384] opened 2021-12-16 04:47 UTC
I am running the latest version of "youtube-dl"
A particular video gave me an error.
Just below is the output from trying it with --verbose flag.

```
~/ytdl-verbose.sh https://www.youtube.com/watch?v=dsFpUW48Tnc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', '~/Music/from-youtube/%(title)s.%(ext)s', '-f', 'best', 'https://www.youtube.com/watch?v=dsFpUW48Tnc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] dsFpUW48Tnc: Downloading webpage
[youtube] dsFpUW48Tnc: Downloading player f3c4e04d
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1622, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'na'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Jarib13** [comment] 2021-12-16 05:07
i just got the same error, also using most updated version. I successfully downloaded videos just a few days ago

**Comment by kikuyan** [comment] 2021-12-16 05:07
Duplicates.
Before making a new issue report, take a little look at other recent titles.
Besides 2021.04.26 is not the latest.

**Comment by supersu-man** [comment] 2021-12-16 05:11
Duplicate of #30363, with fix.

**Comment by deatrys** [comment] 2021-12-16 05:12
Ok.  My version of Linux thought it was most updated.  I will look into this right away.

**Comment by deatrys** [comment] 2021-12-16 05:16
> Duplicate of #30363, with fix.

From what I saw there, it looks like the 'fixes' are to not-use youtube-dl,
along with comments of "what is the fix? how do i fix it?"

i'll see if i can find a more-updated version than 2021.04.26 to run.

deatrys

**Comment by deatrys** [comment] 2021-12-16 05:18
Updating with the readme's installation instructions, but error persists.  Instructions followed:
```
To install it right away for all UNIX users (Linux, macOS, etc.), type:

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by deatrys** [comment] 2021-12-16 05:20
Updated with readme's installation instructions, but error persists.

Instructions followed:
```
To install it right away for all UNIX users (Linux, macOS, etc.), type:

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

I then modified my shell-script to run the file of "/usr/local/bin/youtube-dl" which I just placed, and the same error results.

**Comment by kwankunghkg** [comment] 2021-12-16 06:57
just downloaded with wget command and still reporting error.
 --version 2021.06.06  was working 3 days ago,
Now, failed.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1349, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'na'; please report this issue on https://yt-dl.org/bug .

**Comment by mjezewski** [comment] 2021-12-16 07:06
Same issue with the latest version 
youtube-dl is up-to-date (2021.06.06)

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    func = self._extract_signature_function(
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1262, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1331, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'na';

**Comment by s3n0** [comment] 2021-12-16 09:43
The same problem here, but... I am using the exe-file (Windows binary). 

If the fix / patch already exists... could someone please compile `youtube-dl` into a new binary file for Windows (exe-file) ?

Thanks.

**Comment by aliostad** [comment] 2021-12-16 09:46
Same here.

**Comment by s3n0** [comment] 2021-12-16 09:53
> Same here - on Mac and python 3.9. Obviously youtube have changed something again.

OMG, read the discussion. BUG is already solved for Unix/Linux based systems :). Just download / update new one. But... we need also the new exec binary file for Windows system :).

**Comment by deatrys** [comment] 2021-12-16 10:07
> > Same here - on Mac and python 3.9. Obviously youtube have changed something again.
> 
> OMG, read the discussion. BUG is already solved for Unix/Linux based systems :). Just download / update new one. But... we need also the new exec binary file for Windows system :).

if a different branch has it working, i think part of the point of github is being able to merge it into the master so that it can be 'solved' but youtube-dl doesn't work for me for the video i want

**Comment by aliostad** [comment] 2021-12-16 10:49
> > Same here - on Mac and python 3.9. Obviously youtube have changed something again.
> 
> OMG, read the discussion. BUG is already solved for Unix/Linux based systems :). Just download / update new one. But... we need also the new exec binary file for Windows system :).

Dude, not so fast. I am an idiot but not this much. I did update, version is 2021.06.06

**Comment by mjezewski** [comment] 2021-12-16 10:51
This version does not work on Linux - tested today morning. Read the thread
and you will find the note.

**Comment by ProgammerOrProGamer** [comment] 2021-12-16 11:26
Why is Youtube trolling us again? I guess they enjoy it.

**Comment by s3n0** [comment] 2021-12-16 11:28
@mjezewski  @aliostad 

https://github.com/ytdl-org/youtube-dl/issues/30384#issuecomment-995447198

I'm not going to look for more in depth. Find it for yourself. He reiterates that BUG is resolved. Just download the necessary files and fix the source code.

If you're not an idiot like you write @aliostad  (sorry, but you wrote that you're an idiot... I didn't write this and I didn't mean it that way), then it won't be a problem for you at all. Just find it in the next DUPLICATE discussion about this BUG, where exactly is the problem and how this BUG can be solved.

**Comment by deatrys** [comment] 2021-12-16 11:31
hi. i was merely reporting the bug because the program suggested that i could and it seemed like a good idea.  its not very important to me for it to work right now.  just trying to help the devs get it working in general.
deatrys

**Comment by aliostad** [comment] 2021-12-16 11:52
OK, let's close it then @deatrys

**Comment by aliostad** [comment] 2021-12-16 11:56
But I will tell you @s3n0 this:

As someone who has been working on OSS for years whose contributions are used in production by thousands, your attitude is stinking. Have some respect. You could have simply said the problem is fixed and PR raised, waiting for merge and release, instead of trolling.

**Closed** 2021-12-16 11:55 UTC

**Comment by s3n0** [comment] 2021-12-16 12:06
@aliostad 

And where do you make sure I haven't been a developer my whole life (I'm an older person) ? Maybe I'm even older (by age) and I have more experience ! But you can't know that. So I beg you to mention the word "respect" !!!

**I will respond to your exalted speech in the same way, through the exalted speech:**
And what is even more important ? You MUST NEVER write on behalf of other people! Everyone has their own and specific opinion ! So never steal it from people ! Never do that ! Otherwise, you look like a mean selfish person. You always write only and only for yourself, as an independent individual, living on the planet Earth ! Every single person has their own and independent and unique opinion. Respect it !

**Comment by deatrys** [comment] 2021-12-16 20:09
Sure enough.
I have not worked on OSS for years.
The "youtube-dl" program's instructions upon encountering the error said to report the bug here, there is no indication of a template etc.

deatrys

**Comment by aliostad** [comment] 2021-12-16 20:16
Anyway, thanks to maintainers who have released the fix in less than 24 hours. 👏👏👏

**Comment by deatrys** [comment] 2021-12-16 20:19
> Anyway, thanks to maintainers who have released the fix in less than 24 hours. clapclapclap


Oh. Didn't notice.  Version 2012.12.17 works for me for it now.  Thanks.

**Comment by deatrys** [comment] 2021-12-16 20:24
> Sure enough. I have not worked on OSS for years. The "youtube-dl" program's instructions upon encountering the error said to report the bug here, there is no indication of a template etc.
> 
> deatrys

Also to clarify about templates, I did just now check what happens when Opening a New Issue, and it gives a list of types of issues, one of which is Bug Report which includes a template.  I did not encounter that list when I opened this thread, not sure how I did, but I never saw a template or list when I did it.
