### ISSUE TITLE
Support Request: https://www.channel5.com/

### ISSUE THREAD

**Issue by RogerW17** [ytdl-org/youtube-dl#30242] opened 2021-11-16 00:07 UTC
Please add support for My5 (https://www.channel5.com/)

**Comment by 89z** [comment] 2021-11-16 00:12
Region restricted:

> We're sorry, you must be located in the UK to view this content.

**Comment by RogerW17** [comment] 2021-11-16 00:13
I am located in the UK.

**Comment by 89z** [comment] 2021-11-16 00:18
... the comment was not for you. Obviously you are in UK, else you wouldnt have posted the issue to begin with. The comment is for anyone who may visit this page, and now they know they can only (easily) help if they are in UK.

**Comment by dirkf** [comment] 2021-11-16 01:58
My5 and All4 both deliver encrypted videos that yt-dl can't decode (DRM), unless someone can show otherwise.

Duplicate of #11407.

**Comment by RogerW17** [comment] 2021-11-16 02:36
Thanks dirkf.

**Closed** 2021-11-16 02:37 UTC
