### ISSUE TITLE
Download youtube playlist

### ISSUE THREAD

**Issue by sfxhewitt** [ytdl-org/youtube-dl#29838] opened 2021-08-21 15:11 UTC
I have a weird issue where if you download a playlist it will sometimes get to a video and the speed will just drop to where it's going to take like hours but if I kill the command and re-run it skips all downloaded ones and the one that was slow will download at normal speed. is there any way to detect that the speed has dropped and re try the video?

**Comment by dirkf** [comment] 2021-08-22 00:48
Not at the moment.

Duplicate of #29790, and see also #29326.

**Comment by dirkf** [comment] 2022-01-31 00:37
Closed in af9e72507.

**Closed by dirkf** 2022-01-31 00:37 UTC
Labels: duplicate
