### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by Uthsoxyz** [ytdl-org/youtube-dl#23577] opened 2019-12-31 02:31 UTC
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by tianon** [comment] 2019-12-31 05:24
This is very likely a duplicate of #23516 / #23558 (although not being able to even do the minimum included in the error message and include the full output with `--verbose` makes it a bit hard to tell :wink:).

Likely already fixed via https://github.com/ytdl-org/youtube-dl/commit/d1b27220959921c8c96bfd92c946edb52c78c39b, although that doesn't appear to be in a released build yet.

**Closed** 2019-12-31 06:07 UTC
