### ISSUE TITLE
[YouTube] ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by dsp-stap** [ytdl-org/youtube-dl#26397] opened 2020-08-21 04:59 UTC
Note: This works with option --format 18
Note: This fails with no such --format option
Note: This fails with option --format 22
Note: Works on Chromium | 84.0.4147.105 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

There are many issues with error message 'ERROR: Did not get any data blocks', but none of them seem to match this one I am reporting.

Please send me an email if a solution becomes available.

## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
139 King$ youtube-dl -v https://www.youtube.com/watch?v=r9EvWz34DRk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=r9EvWz34DRk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] r9EvWz34DRk: Downloading webpage
[youtube] r9EvWz34DRk: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-5ualdn7s.googlevideo.com/videoplayback?expire=1598006289&ei=sU8_X7LkG6qPzLUPrrqI0AQ&ip=24.170.167.222&id=o-AKoJVOr5GRptcBFftMGTXIeokej12JyjZfaz8zVr3YOQ&itag=22&source=youtube&requiressl=yes&mh=aC&mm=31%2C29&mn=sn-5ualdn7s%2Csn-5uaezn6y&ms=au%2Crdu&mv=m&mvi=5&pl=18&initcwndbps=2292500&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=112.732&lmt=1521072029464285&mt=1597984596&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdrIatA8-JbRVTREWbw9d7UIBL1SKQ06AkE0d8Gh7AKoCIQDjhPT5OEmshOyD45GMgvC3YZi-o6GaumK-YLEVCDv_Bw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgB0qS9SvBUvE_PMWZpGr3a_6-D7Blhv1FAmgwf0yEZ7kCIQCOnHVWJa6wHfKUJPmD-0KORH6xmemVCG6SkHP1xBrHvw%3D%3D'
[download] Destination: Yaesu ft 950 mars mod-r9EvWz34DRk.mp4
[download]  22.9% of 27.69MiB at  3.29MiB/s ETA 00:06[download] Got server HTTP error: Downloaded 6641720 bytes, expected 29039552 bytes. Retrying (attempt 1 of 10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

140 King$ youtube-dl -v https://www.youtube.com/watch?v=r9EvWz34DRk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=r9EvWz34DRk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] r9EvWz34DRk: Downloading webpage
[youtube] r9EvWz34DRk: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-5uaezn6y.googlevideo.com/videoplayback?expire=1598006306&ei=wk8_X_WsC9GHkAT53angCA&ip=24.170.167.222&id=o-AHNQ5hiS2sPusUlAxBIEuoVeebnqD_MiLieQQ4PoKVeg&itag=22&source=youtube&requiressl=yes&mh=aC&mm=31%2C26&mn=sn-5uaezn6y%2Csn-q4flrnek&ms=au%2Conr&mv=m&mvi=5&pl=18&initcwndbps=2173750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=112.732&lmt=1521072029464285&mt=1597984596&fvip=5&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgR32HHlBS46m-PQlO8lDAQZTZHS9MLJFVTGaLgXOMI_8CIQCwtHwRuRw0P4Z0DPhlS59gVtONIVlOuKlStQotYYcV_A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgCbNFzXayJz6yNnqOXw80bzPRMtm8VfXpjnn_ZEz4sOMCIQCB29Mr3FRCJPHYu3MKetkK5uLCaOewdUxDH_Q5ORSQTg%3D%3D'
[download] Resuming download at byte 6641720
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found


```

## Description

Cannot download video.
Error message is:
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by Zlopez** [comment] 2021-06-04 10:31
I'm now having the same issue for one video, but the traceback is different.
```
$ youtube-dl -v "https://www.youtube.com/watch?v=z0yMN9H9NbY"
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=z0yMN9H9NbY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.05.16
[debug] Python version 3.9.5 (CPython) - Linux-5.12.8-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] z0yMN9H9NbY: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-2gb7sn7z.googlevideo.com/videoplayback?expire=1622824170&ei=igC6YM2CKYT8gAfi-6HQCg&ip=91.225.86.145&id=o-AP6Of2qvkOXUt4DuEgPC8MQwv5d0vvn8RAGn2gZcK2dH&itag=22&source=youtube&requiressl=yes&mh=as&mm=31%2C26&mn=sn-2gb7sn7z%2Csn-c0q7lnly&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=1385000&vprv=1&mime=video%2Fmp4&ns=-4qBX8d3vl6ubNAjOJukAfgF&cnr=14&ratebypass=yes&dur=77.136&lmt=1622722010993177&mt=1622802286&fvip=3&fexp=24001373%2C24007246&beids=9466586&c=WEB&txp=6211224&n=c61go2Scf2XWyMs9b&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJ5cvX6-Zbwy1iA7f7RDXjoOrA9AzsKO9TIAj3LVkaCQAiEA6ljGu80onIsIz_smllceSIN4BUkJo7cjqZ9U4ebtM6k%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgFmRZnV1NB4l7dvP_ESoWd4ch4Ue0dZXqdPp5fZoW2a0CIASvooPCQcFOpKld8DPjgyvZDhh6p89ycL7qdedHqAOe'


ERROR: Did not get any data blocks
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.5.16', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/usr/lib/python3.9/site-packages/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 2067, in download
    res = self.extract_info(
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 814, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 846, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 880, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1691, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1975, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 1914, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 352, in real_download
    return download()
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/http.py", line 322, in download
    self.report_error('Did not get any data blocks')
  File "/usr/lib/python3.9/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 627, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 589, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

```

The video URL is playable without issues in my browser.

**Comment by tonyxiao** [comment] 2023-10-03 18:42
Running into the same issue on a different video too. Anyone has a workaround?

**Comment by dirkf** [comment] 2023-10-03 19:38
Try different format selections. If the problem persists post your verbose log.

**Comment by dirkf** [comment] 2023-10-18 04:35
The original report was `ERROR: unable to download video data: HTTP Error 404: Not Found`, duplicate of #29404.

If anyone gets `ERROR: Did not get any data blocks`, consider raising a new issue according to #30839.

**Closed by dirkf** 2023-10-18 04:35 UTC
