### ISSUE TITLE
Music.Yandex | ERROR: Unable to download JSON metadata: HTTP Error 413

### ISSUE THREAD

**Issue by Arksault** [ytdl-org/youtube-dl#28184] opened 2021-02-16 20:35 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.02.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\yaM>youtube-dl -v https://music.yandex.ru/users/web-aison/playlists/1043
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://music.yandex.ru/users/web-aison/playl
ists/1043']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2021.02.10
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:playlist] 1043: Downloading playlist JSON
[yandexmusic:playlist] 1043: Downloading missing tracks JSON
WARNING: Unable to download JSON metadata: HTTP Error 413: Request entity too la
rge
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\__init__.py", line 465, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\YoutubeDL.py", line 2056, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\YoutubeDL.py", line 806, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\YoutubeDL.py", line 827, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\yandexmusic.py", line 349, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\yandexmusic.py", line 219, in _extract_tracks
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\yandexmusic.py", line 61, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\yandexmusic.py", line 47, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\common.py", line 897, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\common.py", line 875, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp5n2jym
44\build\youtube_dl\extractor\yandexmusic.py", line 42, in _download_webpage_han
dle
TypeError: argument of type 'bool' is not iterable
```

## Description

Hello. I'm trying to download audio from the music service https://music.yandex.ru/ but the program refers to the http error 413. I believe this is due to the large amount of audio in the playlist of 3000+ pieces. I checked it out. If there are 100 audios in the playlist, the program loads them without any problems.

p.s. please help me. I apologize for my english)

**Comment by dstftw** [comment] 2021-02-16 20:37
Duplicate of #27355.

**Closed by dstftw** 2021-02-16 20:37 UTC
