### ISSUE TITLE
Unable to recognize tab page

### ISSUE THREAD

**Issue by BEWARETHEDEAD** [ytdl-org/youtube-dl#31589] opened 2023-02-19 00:04 UTC
how to fix this?

`ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by dirkf** [comment] 2023-02-19 00:21
#30839
But as a hint, duplicate of #30269.

**Closed by dirkf** 2023-02-19 00:21 UTC
