### ISSUE TITLE
[CeskaTelevize] domain update for last version od youtube-dl

### ISSUE THREAD

**Issue by bluenitepk** [ytdl-org/youtube-dl#30966] opened 2022-05-20 22:37 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
Hello,
please can you update your program for the domain of ceskatelevize.cz?

This reports 2021.12.17
C: \ ctdownload> youtube-dl https://www.ceskatelevize.cz/porady/10805121298-gejzir/22256235000011/
[Czech CatelestiaPoras] 222562235000011: Downloading WebPage
Error: Unable to Extract iFrame Player URL; Please report this Issue on https://yt-dl.org/bug. Make Sue You Are Using The Latest Version; Type YouTube -DL -u to update. Be Sure to Call Youtube-Dl with the-Verbose Flag and Include Its Complete Output.

This version of DLG 0.4:
![ss111](https://user-images.githubusercontent.com/85237706/169620878-aff6e865-d89e-4ed0-9dca-99b3efb3c3c0.jpg)

thx a lot
Peter

**Comment by dirkf** [comment] 2022-05-21 12:27
Pending a release build, install the PR #30713 or use yt-dlp.

Duplicate of #30406.

**Closed by dirkf** 2022-05-21 12:27 UTC
Labels: duplicate, question

**Comment by bluenitepk** [comment] 2022-05-21 19:21
> Pending a release build, install the PR #30713 or use yt-dlp.
> 
> Duplicate of #30406.

yt-dlp resolved that problem. thx a lot.
BUT other one arose:
...
[download] Downloading video 1 of 1
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
ERROR: [CeskaTelevize] 61924494877884676: This video is DRM protected
[download] Finished downloading playlist: Queen - A Night At The Opera - Slavná alba | Česká televize

Can yt-dlp download DRM protected video?

**Comment by dirkf** [comment] 2022-05-21 22:08
There's an option to **download** DRM (==encrypted) media. This can be useful if you have too much free space on your disk, or if you need a source of pseudo-random data. Maybe someone on the internet has worked out how to decrypt such files, though.
