### ISSUE TITLE
Unable to Download Video from France.Tv

### ISSUE THREAD

**Issue by Gnomish1** [ytdl-org/youtube-dl#31394] opened 2022-12-03 05:27 UTC
As it says, though it gives the same error whether or not I'm just simulating, it isn't giving me the JSON data. Running a VPN (Mullvad) to Paris. Here's the error:

C:\Users\XXXX\Downloads>youtube-dl.exe -v -g https://www.france.tv/slash/lastman/saison-2/4273474-richard.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-g', 'https://www.france.tv/slash/lastman/saison-2/4273474-richard.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment] 2022-12-03 12:34
Duplicate of #29956.

**Closed by dirkf** 2022-12-03 12:34 UTC
