### ISSUE TITLE
tv.youtube.com doesn't work, or 2fa isn't working quite right, or both

### ISSUE THREAD

**Issue by coldwaterq** [ytdl-org/youtube-dl#13998] opened 2017-08-23 04:17 UTC
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
python -m youtube_dl --verbose -u REDACTED@gmail.com -w --ffmpeg-location ffmpeg -f worst -o %(upload_date)s.%(uploader)s.%(title)s.%(ext)s "https://tv.youtube.com/?v=VQ4H33iIPWY"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-w', '--ffmpeg-location', 'ffmpeg', '-f', 'worst', '-o', '%(upload_date)s.%(uploader)s.%(title)s.%(ext)s', 'https://tv.youtube.com/?v=VQ4H33iIPWY']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-76526-ga5202bc, ffprobe N-76526-ga5202bc
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
WARNING: Unable to extract CheckCookie URL
[youtube] VQ4H33iIPWY: Downloading webpage
[youtube] VQ4H33iIPWY: Downloading video info webpage
ERROR: VQ4H33iIPWY: YouTube said: This video is not available.
Traceback (most recent call last):
  File "C:\Users\ColdwaterQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\ColdwaterQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\ColdwaterQ\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1537, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: VQ4H33iIPWY: YouTube said: This video is not available.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://tv.youtube.com/?v=VQ4H33iIPWY
- Show: https://tv.youtube.com/?browse=UCspnjcbufE7wey4CHTFrwmw

I don't think the show necessarily should be included because of the copy right issue, but for the videos I would like to be able to grab news clips now and then. This time I was hoping to get some of the footage of the eclipse

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I am not sure if this is a bug in 2fa, because google does the prompt on my phone, then I enter the code from authenticator, and in the verbose output I see  500 ERROR. So that could be it, or it could be trying to get the video on youtube.com instead of tv.youtube.com, which isn't the same even though the links use the same parameters.

If you need me to try anything else or look up anything just let me know and I will try to help.

**Comment by dstftw** [comment] 2017-08-23 14:59
Post the output with `--dump-pages`.

**Comment by yan12125** [comment] 2017-08-23 15:20
Most likely a duplicate of #13759, https://github.com/rg3/youtube-dl/issues/1336#issuecomment-312462483 and #9857. Google Prompt is not supported yet.

**Comment by coldwaterq** [comment] 2017-08-23 16:46
I created a new account without 2fa and I still get "youtube_dl.utils.ExtractorError: VQ4H33iIPWY: YouTube said: This video is not available." I can do --dump-pages, but I prefer to not submit my account information, is there a way to dump pages without disclosing anything personal?

**Comment by coldwaterq** [comment] 2017-08-23 16:51
But looking at the --dump-pages output I get the line. "[youtube] Dumping request to https://www.youtube.com/watch?v=VQ4H33iIPWY&gl=US&hl=en&has_verified=1&bpctr=9999999999". And since TV content can't be loaded on the standard youtube domain I think that the problem is just that www.youtube.com/watch?v=VQ4H33iIPWY != tv.youtube.com/watch?v=VQ4H33iIPWY

**Comment by coldwaterq** [comment] 2017-08-23 17:17
I hacked the youtube.py extractor on my computer to force it to use tv.youtube.com instead of www.youtube.com and it is getting the unauthenticated tv.youtube.com page instead of the video when it goes to https://tv.youtube.com/watch?v=VQ4H33iIPWY&gl=US&hl=en&has_verified=1&bpctr=9999999999 and https://tv.youtube.com/get_video_info. So I think something with the authentication may need to be modified along with detecting tv vs not tv youtube links

**Comment by coldwaterq** [comment] 2017-08-23 22:53
Is there a way I can help with the geo-restriction since I am in the area it is restricted to?

**Comment by yan12125** [comment] 2017-08-24 04:15
The fastest way should be dumped files. There won't be passwords but your username and personal preferences may be leaked.

**Comment by coldwaterq** [comment] 2017-08-24 21:28
I created a gist because it was too long to be a comment, this is also not with the modification to make it go to tv.youtube.com. https://gist.github.com/coldwaterq/edcf3c0a2a6e435749730e34e90085dc
And this is with the first request for the video hacked to go to tv.youtube.com https://gist.github.com/coldwaterq/29238836e1c0acca14d83c0d1419378e

**Comment by coldwaterq** [comment] 2017-08-26 01:54
This is the youtube.py that works for me on tv.youtube.com. https://gist.github.com/coldwaterq/0462b9411c72bea49883cbd8e9c1c72a

**Comment by judge2020** [comment] 2017-10-25 03:34
I can confirm the above youtube.py works for making a connection to tv.youtube.com (without 2fa), however, there are issues with the content you download (possibly related to DRM).

Content issue: 

![](https://judge2020.me/LpLZXl.png)

The first 10 seconds, where the USA logo appears, are fine, however, after that, it's likely DRM kicks in for the actual content and displays this

 ![](https://judge2020.me/xPffkh.png)

Diff of the youtube.py files: https://www.diffchecker.com/TwxSZzvI


download output
```
[debug] System config: []
[debug] User config: [u'--netrc']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://tv.youtube.com/?v=Bq6ug91Qeoc']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.14 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-88042-g72c3d9ae45, ffprobe N-88042-g72c3d9ae45
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] Bq6ug91Qeoc: Downloading webpage
[youtube] Bq6ug91Qeoc: Downloading video info webpage
[youtube] Bq6ug91Qeoc: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] Bq6ug91Qeoc: Downloading embed webpage
[youtube] {146} signature length 40.41, html5 player vflN-B5oM
[youtube] {145} signature length 40.41, html5 player vflN-B5oM
[youtube] {224} signature length 40.41, html5 player vflN-B5oM
[youtube] {144} signature length 40.41, html5 player vflN-B5oM
[youtube] {222} signature length 40.41, html5 player vflN-B5oM
[youtube] {223} signature length 40.41, html5 player vflN-B5oM
[youtube] {143} signature length 40.41, html5 player vflN-B5oM
[youtube] {142} signature length 40.41, html5 player vflN-B5oM
[youtube] {161} signature length 40.41, html5 player vflN-B5oM
[youtube] {148} signature length 40.41, html5 player vflN-B5oM
[youtube] {149} signature length 40.41, html5 player vflN-B5oM
[youtube] {150} signature length 40.41, html5 player vflN-B5oM
[youtube] Bq6ug91Qeoc: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r5---sn-5uaeznde.googlevideo.com/videoplayback?gcr=us&gir=yes&initcwndbps=1283750&pl=14&source=youtube&ms=auh&clen=908248452&mv=m&pfa=5&mt=1508902087&expire=1508923799&hightc=yes&requiressl=yes&ipbits=0&mn=sn-5uaeznde&mm=27&id=o-AHYFq3aZY0n-Jr-aLDMCVuf3P_UEHXAlXjv8V0oHxEYM&itag=146&ei=NwXwWZ_7A9bzqQXqlagg&ip=174.108.35.211&key=yt6&keepalive=yes&dur=2857.954&lmt=1508399865663141&cmbypass=yes&aitags=142%2C143%2C144%2C145%2C146%2C161%2C222%2C223%2C224&ctier=UD&mime=video%2Fmp4&sparams=aitags%2Cclen%2Ccmbypass%2Cctier%2Cdur%2Cei%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=CFE6BFD804B1D9ECC050C0A24BF21B271FA544B5.59102D4A934EA8E46253C9E9E9D56CF68B12CEE0&ratebypass=yes'
[download] Destination: Eps3.1undo.gz-Bq6ug91Qeoc.f146.mp4
[download] 100% of 866.17MiB in 01:06
[debug] Invoking downloader on u'https://r5---sn-5uaeznde.googlevideo.com/videoplayback?gcr=us&gir=yes&initcwndbps=1283750&pl=14&source=youtube&ms=auh&clen=92917250&mv=m&pfa=5&mt=1508902087&expire=1508923799&hightc=yes&requiressl=yes&ipbits=0&mn=sn-5uaeznde&mm=27&id=o-AHYFq3aZY0n-Jr-aLDMCVuf3P_UEHXAlXjv8V0oHxEYM&itag=150&ei=NwXwWZ_7A9bzqQXqlagg&ip=174.108.35.211&key=yt6&keepalive=yes&dur=2858.004&lmt=1508400112643637&cmbypass=yes&ctier=UD&mime=audio%2Fmp4&sparams=clen%2Ccmbypass%2Cctier%2Cdur%2Cei%2Cgcr%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpfa%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=35125FA2AE8ED73B5BEB63A05F6D8A8EBD40AC3B.6134463D593F25C492190B1EE448D661023A9EAD&ratebypass=yes'
[download] Destination: Eps3.1undo.gz-Bq6ug91Qeoc.f150.m4a
[download] 100% of 88.61MiB in 00:06
[ffmpeg] Merging formats into "Eps3.1undo.gz-Bq6ug91Qeoc.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Eps3.1undo.gz-Bq6ug91Qeoc.f146.mp4" -i "file:Eps3.1undo.gz-Bq6ug91Qeoc.f150.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Eps3.1undo.gz-Bq6ug91Qeoc.temp.mp4"
Deleting original file Eps3.1undo.gz-Bq6ug91Qeoc.f146.mp4 (pass -k to keep)
Deleting original file Eps3.1undo.gz-Bq6ug91Qeoc.f150.m4a (pass -k to keep)
```

**Comment by austinarchibald** [comment] 2017-11-11 06:16
Any update on this? Anyone figure out how to download tv.youtube.com videos?

**Comment by judge2020** [comment] 2017-11-11 14:49
It's likely proprietary DRM protected, preventing many shows from being downloaded. That would explain why youtube TV recommends not to use the original, slower chromecast (buffers for longer since it takes longer decrypt the stream).

**Comment by yan12125** [comment] 2017-11-11 15:07
@judge2020: Could you add --write-pages and see what's in the MPD manifests (*.mpd)? youtube-dl already filters out [ContentProtection-based DRM manifests](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L1773).

Judging from your screenshot, I guess that's similar to HLS's SAMPLE-AES - decrypt after demux.

**Comment by remitamine** [comment] 2017-11-11 15:25
i guess that it's `.wvm` video as the files has been downloaded with the builtin `http downloader`.

**Comment by judge2020** [comment] 2017-11-11 16:32
@yan12125 Here's the mpd manifest: https://ghostbin.com/paste/btj36 I removed the links containing my IP and whatnot, if needed I can provide the unedited dump.

**Comment by yan12125** [comment] 2017-11-11 16:57
Thanks! That's indeed DRM, and Google's open-sourced shaka-player can handle them (via close-sourced CDMs I guess) [1]. IIRC codes for calling CDMs are open-sourced. I remembered I've seen them in Chromium and Firefox's source trees.

[1] https://github.com/google/shaka-player/issues/358

**Comment by lastb0isct** [comment] 2018-03-21 18:37
Any movement on this issue?

**Comment by treesap32** [comment] 2018-08-04 19:32
@coldwaterq @judge2020  I'm pretty new at this stuff but would like to test on additional programming on tv.youtube.com with the updated python script youtube.py.  Any chance either of you could compile a new windows executable with tv.youtube.com support that I could test with?

**Comment by 89z** [comment] 2022-04-23 17:54
Issue should be closed, URL is dead

**Comment by judge2020** [comment] 2022-04-23 19:50
If someone wants to test this it won’t be hard to find another show to download, but regardless: I doubt this ever will happen since YouTube TV doesn’t even work with software-based CDM/widevine level 3 (likely at the request of their TV channel content providers), precisely to prevent anyone from downloading the channels. Unless yt-dl is interested in embedding a 0-day widevine bypass or L1 decryption key, this isn’t going to happen.

**Comment by 89z** [comment] 2022-04-23 19:56
I am able to decrypt Widevine content, from at least two different sites. So perhaps you should just provide an example, and let people decide if they can help or not.

**Comment by judge2020** [comment] 2022-04-23 22:43
https://tv.youtube.com/watch/TnPb_XFxuyo - Saturday Night Live, S47 E1= - Owen Wilson; Kacey Musgraves

YouTube TV is a paid service, but feel free.

**Comment by 89z** [comment] 2022-04-23 22:48
> Saturday Night Live, S47 E1= - Owen Wilson; Kacey Musgraves

I don't think that's a great example, as you can already get that from NBC:

~~~
PS C:\> nbc -b 9000199358
POST http://access-cloudpath.media.nbcuni.com/access/vod/nbcuniversal/9000199358
GET https://east.manifest.na.theplatform.com/m/NnzsPC/P3SxIJ4UKaJ7,x_U_3FRM6_mL,E8eDNLskrRwg,74sfimEHVQvk,ThnunlAOwYup,EfiqbgG8AVZ8.m3u8?sid=acfbf1d0-b158-43ad-ab2e-8c6ca76c9816&policy=189081367&date=1650754043148&ip=72.181.23.38&schema=1.1&manifest=M3U&tracking=true&switch=HLSServiceSecure&am_sdkv=null&p2=null&_fw_did=&nw=169843&f1=&am_extmp=default&uuid=optout-926144728383214&am_appv=null&mode=on-demand&uoo=1&sfid=9244572&s3=null&am_buildv=null&am_abvrtd=null&s4=poc&_fw_ae=&debug=false&csid=oneapp_phone_android_app_ondemand&metr=1023&am_cpsv=4.0.0-2&bundleId=&userAgent=Go-http-client%2F1.1&e1=default&afid=200265138&prof=nbcu_android_cts_bl&c3=null&a2=4.0.0-2&a3=null&a5=null&a6=0&am_crmid=null&rdid=android&am_playerv=null&did=optout&am_stitcherv=poc&am_abtestid=null&sig=d23ded547ce9af3a2e9361d47b0b7aa6c61fe7b7c81040782aec4a68d9b47516
POST https://friendship.nbc.co/v2/graphql
GET https://east.manifest.na.theplatform.com/m/NnzsPC/P3SxIJ4UKaJ7,x_U_3FRM6_mL,E8eDNLskrRwg,74sfimEHVQvk,ThnunlAOwYup,EfiqbgG8AVZ8/3.m3u8?sid=acfbf1d0-b158-43ad-ab2e-8c6ca76c9816&policy=189081367&date=1650754043662&ip=72.181.23.38&schema=1.1&cid=0ff67e57-025a-4ac5-b91b-225f33cf53af&host=vod-lf-oneapp-prd.akamaized.net&meta=false&manifest=M3U&switch=HLSServiceSecure&am_sdkv=null&p2=null&_fw_did=&nw=169843&f1=&am_extmp=default&tracking=true&uuid=optout-926144728383214&am_appv=null&mode=on-demand&uoo=1&sfid=9244572&s3=null&am_buildv=null&am_abvrtd=null&s4=poc&_fw_ae=&csid=oneapp_phone_android_app_ondemand&metr=1023&am_cpsv=4.0.0-2&bundleId=&userAgent=Go-http-client%2F1.1&e1=default&afid=200265138&prof=nbcu_android_cts_bl&c3=null&a2=4.0.0-2&a3=null&a5=null&a6=0&am_crmid=null&rdid=android&am_playerv=null&did=optout&am_stitcherv=poc&am_abtestid=null&sig=d2c0b9ca33a5ce80b3aa2927a5b12da3f1e6c3292c31de59548aea40874dfec3
0.2%    3.856 MB        5.624 MB/s
~~~

Do you have any other examples?

**Closed** 2022-04-27 12:50 UTC
Labels: geo-restricted, DRM, account-needed, cant-reproduce
