### ISSUE TITLE
[Udemy] Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError())

### ISSUE THREAD

**Issue by amitsharma4hld** [ytdl-org/youtube-dl#31047] opened 2022-06-23 06:58 UTC
E:\>youtube-dl -u himanshu@cvinfotech.com -o "~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" https://www.udemy.com/course/solid-principles-object-oriented-design-architecture --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/course/solid-principles-object-oriented-design-architecture', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by dirkf** [comment] 2022-06-23 09:46
Today we learn that GitHub MarkDown uses `~...~` to indicate ~strikeout text~, which is why the template asks you to post the log inside triple backquotes:

\`\`\`\
...
\`\`\`\.

As to the issue, [duplicate of #29410](https://github.com/ytdl-org/youtube-dl/issues/29410#issuecomment-1110882032) (and also the further comments there).

**Closed** 2023-01-09 03:31 UTC
Labels: duplicate
