### ISSUE TITLE
Unable to DL vids from Rumble.com

### ISSUE THREAD

**Issue by jd1008** [ytdl-org/youtube-dl#31036] opened 2022-06-18 20:51 UTC
## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

ERROR: Unsupported URL: https://rumble.com/v18czhg-cia-operation-crimson-mist.html?mref=6zof&mrefc=2

**Comment by dirkf** [comment] 2022-06-19 11:47
Duplicate of #10785.

See https://github.com/ytdl-org/youtube-dl/issues/30717#issuecomment-1059886141.

**Closed by dirkf** 2022-06-19 11:47 UTC
