### ISSUE TITLE
Soundcloud 401 Unauthorized error

### ISSUE THREAD

**Issue by ppkozlowski** [ytdl-org/youtube-dl#23161] opened 2019-11-21 11:10 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://soundcloud.com/dannaxtheprinz/dannax-me-pega-prod-young-records']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.6.8 (CPython) - Linux-4.19.79-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud] dannaxtheprinz/dannax-me-pega-prod-young-records: Downloading info JSON
[soundcloud] 231281665: Downloading JSON metadata
[soundcloud] 231281665: Downloading JSON metadata
[soundcloud] 231281665: Downloading JSON metadata
[soundcloud] 231281665: Downloading JSON metadata
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/231281665/download?client_id=BeGVhOrGmfboy1LtiHTQF6Ejpt9ULJCI'
ERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/pkozlowski/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

## Description

Hi,

When I try to download some songs from Soundcloud I get 401 Unauthorized error. Occurred not for all songs but only for some of them.

Example song: https://soundcloud.com/dannaxtheprinz/dannax-me-pega-prod-young-records

Probably it's related to wrong CLIENT_ID for  Soundcloud?

Regards
Piotr

**Comment by megascrapper** [comment] 2019-11-21 12:00
Possible duplicate of #23045

**Closed** 2019-11-21 15:48 UTC
