### ISSUE TITLE
Cannot download from Discovery+

### ISSUE THREAD

**Issue by CHJ85** [ytdl-org/youtube-dl#28403] opened 2021-03-10 18:49 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Description

Videos that require me to be logged in doesn't seem to be working.
Using `--cookies` does solve the problem. However, I have to save a new cookies file ever so often (just like with the Funimation extractor).
Would be nice if somebody could look into this.
Thanks in advance.

```
❯ youtube-dl -u "email" -p "password" https://www.discoveryplus.com/video/unraveled-the-long-island-serial-killer/the-long-island-serial-killer
[DiscoveryPlus] unraveled-the-long-island-serial-killer/the-long-island-serial-killer: Downloading JSON metadata
ERROR: This video is only available for registered users. You may want to use --cookies.
```

## Verbose log

```
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.02.22
[debug] Python version 3.8.6 (CPython) - Linux-5.8.0-44-generic-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 6.48.41.4 (US) as X-Forwarded-For.
[DiscoveryPlus] unraveled-the-long-island-serial-killer/the-long-island-serial-killer: Downloading JSON metadata
ERROR: This video is only available for registered users. You may want to use --cookies.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/dplay.py", line 198, in _get_disco_api_info
    video = self._download_json(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/dplay.py", line 198, in _get_disco_api_info
    video = self._download_json(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/dplay.py", line 338, in _real_extract
    return self._get_disco_api_info(
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/dplay.py", line 210, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/dplay.py", line 164, in _process_errors
    raise ExtractorError(
youtube_dl.utils.ExtractorError: This video is only available for registered users. You may want to use --cookies.

```

**Comment by 89z** [comment] 2022-04-24 02:13
Issue should be closed, account required

**Comment by dirkf** [comment] 2023-05-25 17:14
If this show is still valid, use cookies from your logged-in browser session where you can play the show with DRM disabled.

Otherwise, duplicate of #28160. Continue there.

**Closed by dirkf** 2023-05-25 17:14 UTC
