### ISSUE TITLE
FranceTV replay web site

### ISSUE THREAD

**Issue by Boby1717** [ytdl-org/youtube-dl#31280] opened 2022-10-05 09:35 UTC
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.france.tv/france-2/les-pouvoirs-extraordinaires-du-corps-humain/2196075-fatigue-insomnies-ronflements-comment-mieux-dormir.html

## Description

I would like to download this video cause it's very interseting but youtube-dl does not work for this website.

**Comment by dirkf** [comment] 2022-10-05 12:19
It's supposed to work but the extractor needs to be updated.

>[ x] I've searched the bugtracker for similar site support requests including closed ones

https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+france.tv:

> 9 Open 29 Closed

Duplicate of #29956.

**Closed by dirkf** 2022-10-05 12:19 UTC
Labels: site-support-request
