### ISSUE TITLE
/usr/bin/env: «python»: no such file or directory found (linux) [easy to solve]

### ISSUE THREAD

**Issue by byoso** [ytdl-org/youtube-dl#31868] opened 2023-03-17 14:03 UTC
Using the app on linux mint 21 (=Ubuntu 22.04) I got this error:

```console
$ youtube-dl --verbose https://www.youtube.com/watch?v=_pZ0rLdcQSc
/usr/bin/env: «python»: Aucun fichier ou dossier de ce type # = no such file or directory found
```

At the head of your python files, you write:
```python
#! /usr/bin/env python
```
Which on linux refers to python 2, not 3, that is not used anymore, and then not found.
It should work on macOs (because macOs wil take the highest version of python, which is 3), but not on linux, I guess you could fix it by simply change this in the \_\_main__.py file (and in all *.py files to be cleaner) by:

```python
#! /usr/bin/env python3
```
Than it should work on both macOs and linux, as the aim of `/usr/bin/env python3` (instead of just `/usr/bin/python3`) is precisely to solve this OS issue, by 'routing' the version to the good python executable depending on the OS. Of course it will break the compatibility with python2, well, python2 is deprecated anyway.

I wont make a pull request for just adding a "3" in a file... (I solved it for myself, that works)

**Comment by dirkf** [comment] 2023-03-17 14:59
In Debian/Ubuntu/etc, install _python-is-python3_.

Duplicate of #30129: follow #30839 properly.

**Closed by dirkf** 2023-03-17 14:59 UTC

**Comment by tilemoon** [comment] 2023-05-20 15:30
> python-is-python3

get other error when change to python3, `can not find `__main__` module`
