### ISSUE TITLE
Error: Unable to extract uploader id

### ISSUE THREAD

**Issue by AsHfIEXE** [ytdl-org/youtube-dl#32823] opened 2024-06-23 07:51 UTC
when I tried to download youtube video as mp3 using savify.exe it giving me this error

[ERROR] ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
![Screenshot_23](https://github.com/ytdl-org/youtube-dl/assets/124058914/fbe85869-cc4b-4490-a0d6-567bd90b167f)

**Comment by dirkf** [comment] 2024-06-23 12:55
Feel free to review #30839 **as asked** where the solution to your **known issue** is given.

As you are using a package with _yt-dl_ embedded, follow up the issue there: duplicate of https://github.com/LaurenceRawlings/savify/issues/98; see also https://github.com/LaurenceRawlings/savify/issues/99.

**Closed by dirkf** 2024-06-23 12:55 UTC
