### ISSUE TITLE
Download speed is crippling - I can download 100x faster with another method

### ISSUE THREAD

**Issue by FurkanGozukara** [ytdl-org/youtube-dl#30221] opened 2021-11-10 10:29 UTC
Hello. When I download a video with latest youtube-dl it is extremely slow. Like 50 KB per second

With another method I follow I am able to download with 5000 KB per second

I go to en.savefrom . net

It generates some video save-as-able links

Then I copy and paste that link into uGet with 16 connections

How can I achieve same speed with youtube-dl?

Because this process is annoying

**Comment by dirkf** [comment] 2021-11-10 11:32
Duplicate of #29326, where solutions are provided. Also duplicate of at least 15 other issues that OP might have found by **following the [Broken site support](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=&template=1_broken_site.md&title=) template**.

**Comment by unityconstruct** [comment] 2021-11-13 08:52
Confirming the 'drop in' youtube.py is working like a beast:
 71.2% of 1.99GiB at 13.80MiB/s ETA 00:42

Was sobbing over 56K speeds after checking main page for new release, found this ticket, and did the following:
- git clone repo
- rm'd extractor/youtube.py
- wget copy from above in its place
- apt-get pandoc
- make clean
- make

Hardest part was following the damn instructions instead of hacking the youtube-dl directly to replace the file. Was much easier to do what I would normally do at work & pull repo, replace file, build per instructions.   (8-P

Just leaving a note that performance is crazy good with 'drop in' and offer some encouragement to other lazy a$$es that were on the fence whether to wait for another release.

Thx to the team for this utility!!! It has literally changed my life after adding a bash front end. 20TB+ deep into saving the planet from the scourge of L1BT@RD censorhip.

**Closed** 2022-01-31 00:31 UTC
Labels: duplicate
