### ISSUE TITLE
SVT Play is broken 

### ISSUE THREAD

**Issue by ijbh** [ytdl-org/youtube-dl#26428] opened 2020-08-24 17:42 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.svtplay.se/video/27782111/en-andra-chans', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Darwin-19.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 78.74.182.000 (SE) as X-Forwarded-For.
[SVTPlay] 27782111: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/svt.py", line 229, in _real_extract
webpage, 'video id')
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Just moments ago youtube-dl stopped working for svtplay.se. It has been working all morning but suddenly stopped this afternoon.

**Comment by Sopor** [comment] 2020-08-24 17:59
- Finally, put x into all relevant boxes (like this [x]) not like this [ x]

**Comment by hakanw** [comment] 2020-08-25 08:30
I can confirm this, the latest version of youtube-dl, and started happening just the last 24 hours.

**Comment by Surkal** [comment] 2020-08-25 10:53
In `extractor/svt.py`, line 227, replace :
```python
svt_id = self._search_regex(
            r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
            webpage, 'video id')
```
by
```python
svt_id = self._search_regex(
            (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
             r'"content":\{"id":"([\da-zA-Z-]+)'),
            webpage, 'video id')
```

**Comment by ijbh** [comment] 2020-08-25 11:02
> In `extractor/svt.py`, line 227, replace :
> 
> ```python
> svt_id = self._search_regex(
>             r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>             webpage, 'video id')
> ```
> 
> by
> 
> ```python
> svt_id = self._search_regex(
>             (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>              r'"content":\{"id":"([\da-zA-Z-]+)'),
>             webpage, 'video id')
> ```

How would I go about doing this if I'm using brew in Terminal on Mac OS?

**Comment by beteetzen** [comment] 2020-08-25 12:30
Thank you for the patch, Surkal

@ijbh: it's not that difficult. Just download the source code, edit the file as Surkal said and call "make" from the main directory of the youtube-dl source. Copy the new youtube-dl to /usr/local/bin and you're done.

I only had to install pandoc using 'brew install pandoc' before make run through.

**Comment by ijbh** [comment] 2020-08-25 15:05
Hm, I will try but I don't really understand any of what you just said.

Will it be in vain waiting for youtube-dl to be updated in brew to reflect these new changes?

**Comment by ijbh** [comment] 2020-08-25 15:18
@beteetzen Can I ask you two questions?

1. I think I managed to download the source code and edit it. But please explain what you mean by "call "make" from the main directory of the youtube-dl source"? I don't understand that part at all.

2. The source code I downloaded is in a folder with lots of files within it. The youtube-dl file in /usr/local/bin is different. It has a shortcut icon and won't let me explore it as a folder. Do I just exchange one for the other?

**Comment by hakanw** [comment] 2020-08-25 15:22
I added a pull request for the above fix. Please someone with knowhow about this, take a look at it.

**Comment by beteetzen** [comment] 2020-08-25 15:32
@ijbh: 
If you have unzipped the archive with the sourcecode to t.ex. ~/Downloads, you have a directory ~/Downloads/youtube-dl

In the Terminal you just go into that directory
cd ~/Downloads/youtube-dl
and then type
make youtube-dl

This will create a new executable file youtube-dl in that directory which you'll have to copy to /usr/local/bin

But I think it will not take too long until the fix will be released if I understand Håkan right.

**Comment by TheNorwegian** [comment] 2020-08-25 15:35
Sorry for not actually contributing; I just want to say thanks to anyone who works on adding a fix to the DL core. Eagerly waiting for the SVT fix (as well as a NRK regionblock fix).

**Comment by ijbh** [comment] 2020-08-25 15:43
@beteetzen That's great. But I like learning how to do this :) I think I understand your explanation! 

@TheNorwegian that has been a problem for long no? It stopped working for me months ago :(

**Comment by TheNorwegian** [comment] 2020-08-25 15:57
@ijbh The last successfull playlist download from NRK that I did was on August 4th (regionblocked content). I think sometime between mid May and July, single episodes started to fail. Now in mid and late August, even playlists fail. 

However, nonregionblocked content still works for me (when downloading from Sweden, I have not tried downloading from a Norwegian computer.)

**Comment by ijbh** [comment] 2020-08-25 16:14
@beteetzen Thanks for your explanation. It worked :)

So what you said about Pandoc is just optional? I didn't seem to need it.

**Comment by HenrikElofsson** [comment] 2020-08-26 06:50
I can confirm that the fix from Surkal is working, thanks a lot!

**Comment by Tileann** [comment] 2020-08-28 02:29
Is there a fix for windows?
I tried updating but it still won't work.

**Comment by Sopor** [comment] 2020-08-28 03:21
@Tileann If you can't wait for an update you can always clone youtube-dl (or [download](https://github.com/ytdl-org/youtube-dl/archive/master.zip) it),
edit `youtube-dl\youtube_dl\extractor\svt.py` and do the [above](https://github.com/ytdl-org/youtube-dl/issues/26428#issuecomment-679956522) changes.
In the folder `youtube-dl\youtube_dl` (if you downloaded it the first folder is called youtube-dl-master) you can run it by entering `python __main__.py`, but you need to install [python](https://www.python.org) first if you don't have it installed already.

**Comment by Tileann** [comment] 2020-08-28 05:35
@Sopor All I have is a stand alone youtube-dl.exe file.
No other files or folders.

**Comment by Sopor** [comment] 2020-08-28 18:51
@Tileann I understand, but i explained in my previous comment how you should do it. I assume you have some experience in how to use a command prompt when you are using youtube-dl? The only difference is how you run it.

**Comment by r0lle** [comment] 2020-08-30 18:19
> In `extractor/svt.py`, line 227, replace :
> 
> ```python
> svt_id = self._search_regex(
>             r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>             webpage, 'video id')
> ```
> 
> by
> 
> ```python
> svt_id = self._search_regex(
>             (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>              r'"content":\{"id":"([\da-zA-Z-]+)'),
>             webpage, 'video id')
> ```

Works splendid,
Thanks!
R.

**Comment by Minherre** [comment] 2020-08-31 08:06
Hi!

I'm on a PC with Win10, I have Latest Python 3.8.5 installed, and it's in the System PATH.

I have picked up the youtube-dl-master.zip and unzipped it.
I have changed the file
 youtube-dl-master\youtube_dl\extractor\SVT.PY
according to the instructions above.

To what directory do I open a CMD Window (as Admin?!), and How do I then compile (what are the Command Line) a new youtube-dl.exe file?

/Cheers!

**Comment by Sopor** [comment] 2020-09-01 20:59
@Minherre Open the cmd window in the youtube_dl folder where you find `__main__.py`. You should not need to run it as an  Administrator if you have unpacked the `master.zip` on your Desktop or in Documents. Do remember that some python scripts don't like spaces in the path, so avoid that if you can.

Type in ` python __main__.py` and press enter and you should see:
```
>python __main__.py
Usage: __main__.py [OPTIONS] URL [URL...]

__main__.py: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

It you do, it works. You need to copy `ffmpeg.exe` to this folder too if it is not in your path already.

**Comment by Minherre** [comment] 2020-09-02 05:09
@Sopor:  Thank you, but that far I came myself, and it works perfectly well with SVTPLAY.SE now again.

But what I asked for was HOW to create the actual youtube-dl.EXE file ?!

**Comment by Sopor** [comment] 2020-09-03 16:11
@Minherre Why can't you run it with `python __main__.py` if that works for you? It is quite harder to compile it on Windows, so i leave that to the experts. I see no reason to compile it when it works with `python __main__.py`.

**Comment by Haykayz** [comment] 2020-09-03 16:20
> 
> 
> @Sopor: Thank you, but that far I came myself, and it works perfectly well with SVTPLAY.SE now again.
> 
> But what I asked for was HOW to create the actual youtube-dl.EXE file ?!

You don't need the .exe-file. Instead of writing `youtube-dl.exe YOUR-LINK` in the console you use `python __main__.py YOUR-LINK`.

**Comment by Minherre** [comment] 2020-09-05 05:10
Sopor> @Minherre Why can't you run it with `python __main__.py` if that works for you? It is quite harder to compile it on Windows, so i leave that to the experts. I see no reason to compile it (py2exe) when it works with `python __main__.py`.

@Sopor: I can't use your Commandline since that is so Primitive!

Instead I'm using Youtube-DLG on top of Youtube-dl.exe.

"A cross platform front-end GUI of the popular youtube-dl written in wxPython."

Pick it up and read more at:

https://github.com/MrS0m30n3/youtube-dl-gui

Just paste URL after URL into the top windows, then click ADD, and then GO, and it'll pick up URL after URL, three at the time.

If one wants Subs, just use >>Options>Download set on All Available Subs.

And then also >>Options>Extra and there you add:

--convert-subs srt

But this easy way doesn't work if one has to use commandline Python commands.

So unfortunately Youtube-DLG can't be used for certain sites (like Svtplay) until a new Youtube-dl.exe is compiled.

**Comment by Sopor** [comment] 2020-09-05 18:25
@Minherre I can't guarantee it is working, but try this [youtube-dl](https://gofile.io/d/yE4j7O)

**Closed** 2020-09-06 03:46 UTC

**Comment by Minherre** [comment] 2020-09-06 06:45
> @Minherre @Tileann
> I can't guarantee it is working, but try this [youtube-dl.exe]
> 
> It did worked for me:
> 


@Sopor: How nice of you to offer a download of a Trojan-INFECTED version of Youtube-dl.exe ... !

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.DA!ml&threatid=2147757789

https://howtofix.guide/trojanwin32-wacatac-dml/

The regular Youtube-dl.exe does not trigger any Anti-Virus programs, but your download triggers them all...
Suck... ( er! )

**Comment by Sopor** [comment] 2020-09-06 18:22
Trojan infected?! I have created the file by my own and i have no trojan in my system. It is of course a false positive.

**Comment by ijbh** [comment] 2020-09-09 19:07
Did anyone else just experience Svtplay stop working again? As if they changed their video path again? (or maybe went back?)

**Comment by TheNorwegian** [comment] 2020-09-09 19:27
ijbh, I experienced that SVTplay worked with YT-DLG yesterday - but not the day before and not today.  (Almost as if the functioning .exe was a glitch yesterday, and now back to "normal non functioning" status.)

**Comment by ijbh** [comment] 2020-09-09 19:36
@TheNorwegian For me it has worked without interruption since the above fix two weeks ago. So I think something changed now.

**Comment by TheNorwegian** [comment] 2020-09-09 20:44
Since I use Youtube-DLG only, the above fix was not relevant for me. I am not sure I would be able to apply the fix.

**Comment by Surkal** [comment] 2020-09-09 21:08
Here's a quick fix.
I don't guarantee that the downloaded video is the right one every time.

In `extractor/svt.py`, line 236, replace :
```python
svt_id = self._search_regex(
                (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
                 r'"content"\s*:\s*{.*?"id"\s*:\s*"([\da-zA-Z-]+)"'),
                webpage, 'video id')
```
by
```python
svt_id = self._search_regex(
                (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
                 r'"content"\s*:\s*{.*?"id"\s*:\s*"([\da-zA-Z-]+)"',
                 r'"videoSvtId"\s*:\s*"([\da-zA-Z-]+)"'),
                webpage, 'video id')
```

**Comment by ijbh** [comment] 2020-09-09 21:37
@Surkal Awesome. Thank you!

**Comment by TheNorwegian** [comment] 2020-09-09 22:31
Where would I find extractor/svt.py ?
I don't have a file or folder called that in my YT-DLG installation folder. (Told you I am not so technical :-) )

**Comment by ijbh** [comment] 2020-09-10 13:23
> Here's a quick fix.
> I don't guarantee that the downloaded video is the right one every time.
> 
> In `extractor/svt.py`, line 236, replace :
> 
> ```python
> svt_id = self._search_regex(
>                 (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>                  r'"content"\s*:\s*{.*?"id"\s*:\s*"([\da-zA-Z-]+)"'),
>                 webpage, 'video id')
> ```
> 
> by
> 
> ```python
> svt_id = self._search_regex(
>                 (r'<video[^>]+data-video-id=["\']([\da-zA-Z-]+)',
>                  r'"content"\s*:\s*{.*?"id"\s*:\s*"([\da-zA-Z-]+)"',
>                  r'"videoSvtId"\s*:\s*"([\da-zA-Z-]+)"'),
>                 webpage, 'video id')
> ```

I think it should be line 227!

Seems to be working now. Thank you!

**Comment by hakanw** [comment] 2020-09-10 13:28
This fix works! Can someone do a PR to be merged into master?

**Comment by blackjack4494** [comment] 2020-09-13 10:42
I could merge it into my fork if you want.

**Comment by Minherre** [comment] 2020-09-24 04:02
With youtube-dl 2020.09.20 this happens now.

Sept 23:

https://urplay.se/program/214580-nixon-och-skandalerna-nixon-den-enda

[09/23/20 07:23:04] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

Sept 24:

https://urplay.se/program/210205-fjaderlatt-och-superstark

[09/24/20 05:51:35] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

Perhaps this is the same problem as it was previous with Svtplay, that was fixed then ?!
The Urplay.se site belongs to the same company as Svtplay's site does.
