### ISSUE TITLE
Unable to recognize tab page (YT)

### ISSUE THREAD

**Issue by austux** [ytdl-org/youtube-dl#31166] opened 2022-08-13 00:58 UTC
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

$ youtube-dl -F --verbose https://www.youtube.com/shorts/WTNicVadi6k
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/shorts/WTNicVadi6k']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.4.0-124-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/user/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)
[VDH-20220813-details.pdf](https://github.com/ytdl-org/youtube-dl/files/9330479/VDH-20220813-details.pdf)

$

## Description

The URL plays in Firefox, does not download. Video Downloadhelper plugin shows (attached two-page A4 PDF) by way of details (no MP4 format available, only MP3 and WEBM). Gives exactly the same output sans the -F option.

**Comment by austux** [comment] 2022-08-13 01:04
I manually converted the supplied URL to https://www.youtube.com/watch?v=WTNicVadi6k and that downloaded just fine as a 720x1280 MP4 (with the video inlaid at what appears to be 480x854 resolution).

**Comment by dirkf** [comment] 2022-08-13 02:10
> I've searched the bugtracker for similar bug reports including closed ones

Obvs not.

Duplicate of #30269, fixed in git master by PR #30577.

Meanwhile you found the simple work-around.

**Closed by dirkf** 2022-08-13 02:10 UTC
