### ISSUE TITLE
[META] Please do not lock threads without a warning or explanation!

### ISSUE THREAD

**Issue by Mhowser** [ytdl-org/youtube-dl#26546] opened 2020-09-08 05:43 UTC
I have noticed several threads being locked with no explanation or warning.

#25687, #25684, #9337, #12724, #622, #17116, #20027, #9786

I can see that some conversations get off-topic and some are users not adding anything useful to the issue, but does that really require entirely shutting down collaboration like that? This kind of moderation is not a good thing for open source projects in my opinion. If the conversation is getting out of control, please let us know! **And only lock the thread if it is absolutely necessary.**

~With that said, I request issue #25687 to be unlocked as I need help with getting a patch updated, which is mentioned in the issue.~

**Comment by elyoas** [comment] 2020-09-08 07:11
Also this bug is locked without reason:

https://github.com/ytdl-org/youtube-dl/issues/23627

**Comment by jbruchon** [comment] 2020-09-18 04:35
You think that's bad? They not only locked my properly formed report, but **DELETED** my follow-up in the issue comments that explained what triggered the error, so anyone who finds my report will never learn why they were receiving `Error -22`.

**Comment by dstftw** [comment] 2020-09-20 04:20
Don't spam with useless +1 messages and they won't be closed.
@jbruchon no it wasn't properly formed, you haven't provided complete verbose log (removed header) as clearly requested by issue template thus resulted in issue closed as incomplete.
`Error number -22 occurred` may be caused by lots of things not only outdated ffmpeg in the first place and this is easily deducible from complete log you haven't provided. Thus your "explanation" will be wrong in most of the cases.

**Closed by dstftw** 2020-09-20 04:20 UTC
Labels: question
