### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by gabzsansev** [ytdl-org/youtube-dl#26938] opened 2020-10-19 17:34 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.09.20**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

This is the issue:

ERROR: query "Alan Walker Darkside feat AuRa and Tomine Harket": Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

It doesn't play the most of the songs,used with python and vlc,and prints this on the terminal

**Comment by tameTNT** [comment] 2020-10-19 19:02
This is a duplicate of #26937

**Closed** 2020-10-20 16:29 UTC
