### ISSUE TITLE
Unable to recognize tab page  Youtube Shorts

### ISSUE THREAD

**Issue by mx-yah** [ytdl-org/youtube-dl#30626] opened 2022-02-10 08:24 UTC
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/shorts/hwyXo0C3hjg

## Description

ERROR: Unable to recognize tab page;

**Comment by xgwhk** [comment] 2022-05-18 20:24
Can you clarify how the problem is marked fixed as I have the same issue with any #shorts video from Youtube?

Thanks

**Comment by danswett** [comment] 2022-06-06 05:07
Still having this problem using media_extractor in the latest version of Home Assistant, which wraps yt-dl.

**Comment by dirkf** [comment] 2022-06-06 10:21
Raise the issue [there](https://www.home-assistant.io/help/) quoting https://github.com/ytdl-org/youtube-dl/issues/30626#issuecomment-1035086171. They need to pull the latest git master.

**Comment by danswett** [comment] 2022-06-07 04:19
Going through this again, Home Assistant Core is referencing the most recently published version of youtube-dl (2021.12.17), and I think @dirkf you're saying that the issue was fixed post that release (merged on Feb 1).

I'm going to assume that the folks that own the HA Core repo will be reluctant to update to an "unreleased" version. Do you have an idea of when the next "official" release will be (or am I completely misinterpreting the state of things)?

**Comment by dirkf** [comment] 2022-06-07 09:24
Unfortunately the answer is "when it's ready".

FWIW, the git master isn't a "development" version or a "feature branch" that changes existing interfaces: only tested fixes and new extractors have been included. And it has exactly the same level of warranty as a release version (ie, none whatsoever).

HAC could equally switch to a release version of yt-dlp with some small wrapper changes.

**Closed** 2022-07-10 14:51 UTC
Labels: broken-IE, duplicate, fixed
