### ISSUE TITLE
ERROR: No video formats found

### ISSUE THREAD

**Issue by DanielTheGreat** [ytdl-org/youtube-dl#32055] opened 2023-04-18 07:33 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
E:\Videos\Temp>youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

E:\Videos\Temp>youtube-dl https://www.sbs.com.au/ondemand/watch/2186624579837 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.sbs.com.au/ondemand/watch/2186624579837', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 2021-09-11-git-3e127b595a-full_build-www.gyan.dev, ffprobe 2021-09-11-git-3e127b595a-full_build-www.gyan.dev
[debug] Proxy map: {}
[SBS] 2186624579837: Downloading JSON metadata
[ThePlatform] ew1pyO5uexuB: Downloading SMIL data
[ThePlatform] ew1pyO5uexuB: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\theplatform.py", line 309, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

[I didn't actually check the 'Bugtracker' because I couldn't find a link to it! :-( ]
Issue is simple: I can play the video from SBS OnDemand (in Firefox), but youtube-dl finds no video there.

**Comment by dirkf** [comment] 2023-04-18 14:35
Where did you open this from, if not https://github.com/ytdl-org/youtube-dl/issues?

Duplicate of #31841, with PR.

**Closed by dirkf** 2023-04-18 14:35 UTC

**Comment by DanielTheGreat** [comment] 2023-04-19 00:54
Yeah, that's where I opened it from.
OK, I see that others have reported this issue too.
Any ETA on when a version with a fix for it will be released?
(youtube-dl -U still returns 2021.12.17 as the latest!)

**Comment by dirkf** [comment] 2023-04-19 01:02
That **is** the bugtracker.

A yt-dlp equivalent PR has just been committed. In due course any features from that will be added to #38141 and when it passes its tests it'll be merged.

As to a yt-dl release, #31585. But you'll need to update according to #31530 anyway.
