### ISSUE TITLE
 Is there a way we can view the copyrighted works of YouTube and then download the copyrighted works with youtube_dl ? One person told me with Firefox Go to YouTube Do not go with Google he told me that a series of actions should be done, but did not help me !

### ISSUE THREAD

**Issue by ebrahimhoseini433433** [ytdl-org/youtube-dl#30293] opened 2021-11-30 08:08 UTC
Hello, I am an Iranian. My English is not good Why YouTube_dl does not download copyrighted works such as deleted YouTube videos in the playlist, except that the software does downloads copyrighted works such as copyrighted music videos but can not be downloaded So how to go to YouTube through Firefox Chrome Edge browsers that we can also see them and then download them through YouTube_dl ?

**Comment by gamer191** [comment] 2021-11-30 09:05
Youtube-dl can't download deleted videos, because they have been deleted and you can't download something that has been deleted

**Comment by kikuyan** [comment] 2021-11-30 09:36
You opened #30232.
Don't make new one.

**Comment by dirkf** [comment] 2021-11-30 11:21
In fact:

duplicate of #30232.

**Comment by rautamiekka** [comment] 2021-11-30 20:49
OP, I already explained you twice: doing this is impossible !

**Comment by mrwicks** [comment] 2021-12-01 04:03
Copyrighted works often make use of DRM - no point in breaking that.

Notably: DRM is stupid, because you can basically get it by using a virtual machine, and recording the video as it plays.  DRM just makes it a LITTLE more difficult to duplicate content, and only by making it a tiny bit lossy.

Allowing DRM material to be copied would likely to get the authors of this program in some trouble.  I don't recommend they attempt to ever support it.  This program I think is most properly used for archival of what gets banned or memory holed.

**Closed** 2022-01-29 17:19 UTC
Labels: duplicate
