### ISSUE TITLE
Likes and Dislikes both return as None.

### ISSUE THREAD

**Issue by Lemon-Hacking** [ytdl-org/youtube-dl#25977] opened 2020-07-12 04:22 UTC
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
When attempting to get info from a video, like_count and dislike_count both return as None.
Output of a program to get info from a video:
Views : 159370    Likes : None    Dislikes : None    Length : 90

**Comment by nastia-diaphan** [comment] 2020-07-12 10:06
This is a new bug that affect probably all YT videos. It started 4 days ago and concerns metadata like https://github.com/ytdl-org/youtube-dl/issues/25945 and https://github.com/ytdl-org/youtube-dl/issues/25937 that remain unsolved since 4 days

**Comment by RomanEmelyanov** [comment] 2020-07-12 13:46
Try to use this patch for file youtube.py:

```
def _extract_count(count_name):
            return str_to_int(self._search_regex(
                r'([0-9,]+) %ss"}}' # this line fixed
                % re.escape(count_name),
                video_webpage, count_name, default=None))
```

**Comment by nastia-diaphan** [comment] 2020-07-12 16:04
> Try to use this patch for file youtube.py:
> 
> ```
> def _extract_count(count_name):
>             return str_to_int(self._search_regex(
>                 r'([0-9,]+) %ss"}}' # this line fixed
>                 % re.escape(count_name),
>                 video_webpage, count_name, default=None))
> ```

short and it work. Thank you RomanEmelyanov

I will be happy if you solve this way https://github.com/ytdl-org/youtube-dl/issues/25945

The div is of class "reason"
`<div class="reason style-scope yt-player-error-message-renderer">This video has been removed for violating YouTube's Terms of Service.</div>`

**Comment by Marques-Desenv** [comment] 2020-07-13 00:51
> Try to use this patch for file youtube.py:
> 
> ```
> def _extract_count(count_name):
>             return str_to_int(self._search_regex(
>                 r'([0-9,]+) %ss"}}' # this line fixed
>                 % re.escape(count_name),
>                 video_webpage, count_name, default=None))
> ```

Thanks for replaying this helped a lot!

**Comment by Marques-Desenv** [comment] 2020-07-13 01:05
The comment_count has the same problem, it always give 0 as output. Do you have a patch for this?

**Comment by RomanEmelyanov** [comment] 2020-07-13 06:06
> > Try to use this patch for file youtube.py:
> > ```
> > def _extract_count(count_name):
> >             return str_to_int(self._search_regex(
> >                 r'([0-9,]+) %ss"}}' # this line fixed
> >                 % re.escape(count_name),
> >                 video_webpage, count_name, default=None))
> > ```
> 
> short and it work. Thank you RomanEmelyanov
> 
> I will be happy if you solve this way #25945
> 
> The div is of class "reason"
> `<div class="reason style-scope yt-player-error-message-renderer">This video has been removed for violating YouTube's Terms of Service.</div>`

Just replace this function in file youtube.py:
```
        def extract_unavailable_message():
            return self._html_search_regex(
                r',"reason":"(.*?)"',
                video_webpage, 'unavailable message', default=None)
```

**Comment by nastia-diaphan** [comment] 2020-07-13 20:05
> > > Try to use this patch for file youtube.py:
> > > ```
> > > def _extract_count(count_name):
> > >             return str_to_int(self._search_regex(
> > >                 r'([0-9,]+) %ss"}}' # this line fixed
> > >                 % re.escape(count_name),
> > >                 video_webpage, count_name, default=None))
> > > ```
> > 
> > 
> > short and it work. Thank you RomanEmelyanov
> > I will be happy if you solve this way #25945
> > The div is of class "reason"
> > `<div class="reason style-scope yt-player-error-message-renderer">This video has been removed for violating YouTube's Terms of Service.</div>`
> 
> Just replace this function in file youtube.py:
> 
> ```
>         def extract_unavailable_message():
>             return self._html_search_regex(
>                 r',"reason":"(.*?)"',
>                 video_webpage, 'unavailable message', default=None)
> ```

Marvelous, you are my savior RomanEmelyanov. One more time, it work and your code look so simple.

One question: why a new version of youtube-dl is so long to come after you have published a solution ?

**Comment by GlassedSilver** [comment] 2020-07-13 21:42
> 
> 
> > > > Try to use this patch for file youtube.py:
> > > > ```
> > > > def _extract_count(count_name):
> > > >             return str_to_int(self._search_regex(
> > > >                 r'([0-9,]+) %ss"}}' # this line fixed
> > > >                 % re.escape(count_name),
> > > >                 video_webpage, count_name, default=None))
> > > > ```
> > > 
> > > 
> > > short and it work. Thank you RomanEmelyanov
> > > I will be happy if you solve this way #25945
> > > The div is of class "reason"
> > > `<div class="reason style-scope yt-player-error-message-renderer">This video has been removed for violating YouTube's Terms of Service.</div>`
> > 
> > 
> > Just replace this function in file youtube.py:
> > ```
> >         def extract_unavailable_message():
> >             return self._html_search_regex(
> >                 r',"reason":"(.*?)"',
> >                 video_webpage, 'unavailable message', default=None)
> > ```
> 
> Marvelous, you are my savior RomanEmelyanov. One more time, it work and your code look so simple.
> 
> One question: why a new version of youtube-dl is so long to come after you have published a solution ?

Taking a wild guess here, it may be because no maintainer of the repo who'd be authorized to merge the PRs has seen the tickets or experienced this bug in their own usage yet.

The urgency of this issue is of course pretty drastic, but also means we experience the lack of an official fix as even slower I take it. :) 

I mean, it's not like it's hard to "bury" important things in this repo:

![Anmerkung 2020-07-13 234159](https://user-images.githubusercontent.com/1912133/87356497-76dec800-c562-11ea-89cb-dcbe72ce7ce6.png)

**Comment by nastia-diaphan** [comment] 2020-07-13 22:07
> > > Try to use this patch for file youtube.py:
> > > ```
> > > def _extract_count(count_name):
> > >             return str_to_int(self._search_regex(
> > >                 r'([0-9,]+) %ss"}}' # this line fixed
> > >                 % re.escape(count_name),
> > >                 video_webpage, count_name, default=None))
> > > ```
> > 
> > 
> > short and it work. Thank you RomanEmelyanov
> > I will be happy if you solve this way #25945
> > The div is of class "reason"
> > `<div class="reason style-scope yt-player-error-message-renderer">This video has been removed for violating YouTube's Terms of Service.</div>`
> 
> Just replace this function in file youtube.py:
> 
> ```
>         def extract_unavailable_message():
>             return self._html_search_regex(
>                 r',"reason":"(.*?)"',
>                 video_webpage, 'unavailable message', default=None)
> ```

Thanks again RomanEmelyanov, but your code need some more work.
Some unavailable messages are dispatched in two fields. by example for duplicated video.
Here is the video_webpage fragment
`..."playabilityStatus":{"status":"ERROR","reason":"Video unavailable","errorScreen":{"playerErrorMessageRenderer":{"subreason":{"simpleText":"This video is a duplicate of another YouTube video"},"reason":{"simpleText":"Video unavailable"}...`
and of course, the only information your code return is "Video unavailable"

I have tried to solve it by myself, but in vain. Here is my code
 ```
        def extract_unavailable_message():
            messages = []
            for tag in ('"reason":', '"subreason":\{"simpleText":'):
                msg = self._html_search_regex(
                    r',{tag}"(.*?)"'.format(tag=tag),
                    video_webpage, 'unavailable message', default=None)
                if msg:
                    messages.append(msg)
            if messages:
                return '\n'.join(messages)
 ```
Unfortunately this code return only  "Video unavailable" just as yours. I'm lost.

**Comment by RomanEmelyanov** [comment] 2020-07-14 12:59
Code not perfect but works for me:
```
        def extract_unavailable_message():
            reason = self._html_search_regex(
                    r'"subreason":{"simpleText":"(.*?)"',
                    video_webpage, 'unavailable message', default=None)
            if reason is None:
                reason = self._html_search_regex(
                    r',"reason":"(.*?)"',
                    video_webpage, 'unavailable message', default=None)
            return reason
```

**Comment by nastia-diaphan** [comment] 2020-07-14 16:05
> Code not perfect but works for me:
> 
> ```
>         def extract_unavailable_message():
>             reason = self._html_search_regex(
>                 r'"subreason":{"runs":(\[.*?\])',
>                 video_webpage, 'unavailable message', default=None)
>             try:
>                 reason_array = json.loads(reason); reason = ''
>                 for item in reason_array:
>                     reason += item['text']
>             except:
>                 pass
>             if reason is None:
>                 reason = self._html_search_regex(
>                     r'"subreason":{"simpleText":"(.*?)"',
>                     video_webpage, 'unavailable message', default=None)
>             if reason is None:
>                 reason = self._html_search_regex(
>                     r',"reason":"(.*?)"',
>                     video_webpage, 'unavailable message', default=None)
>             return reason```
> ```

Your code work for me too (before you edited it), Thank you RomanEmelyanov

I rewrote it like this to keep the carriage return of current youtube-dl code
```
        def extract_unavailable_message():
            reason = self._html_search_regex(
                    r',"reason":"(.*?)"',
                    video_webpage, 'unavailable message', default=None)
            subreason = self._html_search_regex(
                    r'"subreason":{"simpleText":"(.*?)"',
                    video_webpage, 'unavailable message', default=None)
            if subreason:
                reason = reason + '\n' + subreason
            return reason
```
Not a nice code, but readable and it work like expected... for now

**Closed** 2020-11-21 13:51 UTC
Labels: question
