### ISSUE TITLE
CLI youtube-dl fails in LINUX

### ISSUE THREAD

**Issue by phynster11** [ytdl-org/youtube-dl#20762] opened 2019-04-24 00:17 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.04.17*. If it's not, read [this FAQ entry](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/ytdl-org/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/ytdl-org/youtube-dl#faq) and [BUGS](https://github.com/ytdl-org/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/ytdl-org/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by phynster11** [comment] 2019-04-24 00:18
I use the CLI youtube-dl script daily but today it failed with the following :+1: 
Downloads /usr/local/bin/youtube-dl -xv --audio-format mp3 https://www.youtube.com/watch\?v\=Xq_xOibJBDc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-xv', u'--audio-format', u'mp3', u'https://www.youtube.com/watch?v=Xq_xOibJBDc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.15rc1 (CPython) - Linux-5.0.0-050000-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[youtube] Xq_xOibJBDc: Downloading webpage
[youtube] Xq_xOibJBDc: Downloading video info webpage
ERROR: Xq_xOibJBDc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: Xq_xOibJBDc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by J2D22** [comment] 2019-04-24 00:22
having the same issue on youtube on linux mint 

`youtube-dl -f 18 --simulate -v http://www.youtube.com/watch?v=pBPPLu2x3lI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'18', u'--simulate', u'-v', u'http://www.youtube.com/watch?v=pBPPLu2x3lI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.17
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.18.0-17-generic-x86_64-with-LinuxMint-19.1-tessa
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] pBPPLu2x3lI: Downloading webpage
[youtube] pBPPLu2x3lI: Downloading video info webpage
ERROR: pBPPLu2x3lI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
ExtractorError: pBPPLu2x3lI: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

`

**Comment by hulyom** [comment] 2019-04-24 00:26
Exactly the same error, I downloaded a video yesterday, today I wasn't able to download the same video.

```
$ youtube-dl qDW-g5kVsIA
[youtube] qDW-g5kVsIA: Downloading webpage
[youtube] qDW-g5kVsIA: Downloading video info webpage
ERROR: qDW-g5kVsIA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[hulyom@aspire Downloads]$ youtube-dl qDW-g5kVsIA --verbose
[hulyom@aspire Downloads]$ youtube-dl qDW-g5kVsIA --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['qDW-g5kVsIA', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.3 (CPython) - Linux-5.0.8-arch1-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] qDW-g5kVsIA: Downloading webpage
[youtube] qDW-g5kVsIA: Downloading video info webpage
ERROR: qDW-g5kVsIA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1693, in _real_extract
    video_id=video_id)
youtube_dl.utils.ExtractorError: qDW-g5kVsIA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by WemansG90** [comment] 2019-04-24 00:28
Ditto here on Windows 10, tried to continue backing up a playlist, suddenly stopped working.

```[debug] System config: []
[debug] User config: ['-v', '-o', 'D:\\Media_enz\\Downloads\\%(playlist)s\\%(playlist_index)s_%(title)s.%(ext)s', '--external-downloader', 'ffmpeg', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLh-QhuPQouNfxekQdx4YL6c0FtPzGvJap', '--playlist-start', '65', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f
[debug] Proxy map: {}
[youtube:playlist] PLh-QhuPQouNfxekQdx4YL6c0FtPzGvJap: Downloading webpage
[download] Downloading playlist: MAMAMOO 4season FW Concert April 2019
[youtube:playlist] playlist MAMAMOO 4season FW Concert April 2019: Downloading 27 videos
[download] Downloading video 1 of 27
[youtube] eoZh25VD06I: Downloading webpage
[youtube] eoZh25VD06I: Downloading video info webpage
ERROR: eoZh25VD06I: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 1693, in _real_extract
youtube_dl.utils.ExtractorError: eoZh25VD06I: "token" parameter not in video info for unknown reason```

**Comment by cinereous** [comment] 2019-04-24 00:31
Dupe of: https://github.com/ytdl-org/youtube-dl/issues/20758
(Temp?) Fix: https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882

**Closed** 2019-04-24 03:00 UTC
