### ISSUE TITLE
enable to extract uploader id

### ISSUE THREAD

**Issue by vovanshil95** [ytdl-org/youtube-dl#31558] opened 2023-02-17 20:34 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE
I can't download video with url https://www.youtube.com/watch?v=wWJAE3gZIvM
log: ERROR: Unable to extract uploader id;

**Comment by dirkf** [comment] 2023-02-17 20:37
Complete the template fully.

Then find that this is ...

Duplicate of #31530.

**Closed by dirkf** 2023-02-17 20:37 UTC
