### ISSUE TITLE
Download all videos from the "@channel/shorts" page

### ISSUE THREAD

**Issue by erikfiala** [ytdl-org/youtube-dl#31528] opened 2023-02-13 14:49 UTC
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Any plans on being able to bulk-download shorts from "https://https://www.youtube.com/@channelname/shorts"?

I think this would be super useful. Couldn't find a duplicate of this, sorry in case I suck at searching lol

**Comment by october262** [comment] 2023-02-14 01:41
your test link is broken.

**Comment by erikfiala** [comment] 2023-02-14 01:42
That was an example (insert any channel name)

**Comment by dirkf** [comment] 2023-02-14 02:28
Yes, [you suck at searching](https://github.com/ytdl-org/youtube-dl/issues?q=is%3Aissue+shorts+-label%3Aduplicate).

Duplicate of #31336, fixed in git master by PR #3419:
```shellsession
$ python -m youtube_dl -v --flat-playlist  'https://www.youtube.com/@JakeCeja/shorts'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--flat-playlist', u'https://www.youtube.com/@JakeCeja/shorts']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 6f8c2635a
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube:tab] @JakeCeja: Downloading webpage
[download] Downloading playlist: Jake Ceja - Shorts
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
[youtube:tab] Downloading page 3
[youtube:tab] Downloading page 4
[youtube:tab] Downloading page 5
[youtube:tab] playlist Jake Ceja - Shorts: Downloading 266 videos
[download] Downloading video 1 of 266
[download] Downloading video 2 of 266
...
[download] Downloading video 266 of 266
[download] Finished downloading playlist: Jake Ceja - Shorts
$
```

**Closed by dirkf** 2023-02-14 02:28 UTC

**Comment by erikfiala** [comment] 2023-02-14 02:29
Thank you!

**Comment by jonijee7** [comment] 2023-12-19 10:49
That was an example (insert any channel name)

Example of non-broken link: https://www.youtube.com/@Bhaiyajikfacts/shorts
