### ISSUE TITLE
dailymotion - ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by WoodpeckerBaby** [ytdl-org/youtube-dl#26019] opened 2020-07-16 08:45 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl https://www.dailymotion.com/video/x7u7219 --ignore-config -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.dailymotion.com/video/x7u7219', u'--ignore-config', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 2.7.16 (CPython) - Darwin-19.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] Downloading Access Token
[dailymotion] x7u7219: Downloading media JSON metadata
[dailymotion] x7u7219: Downloading metadata JSON
[dailymotion] x7u7219: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://proxy-05.ty4.dailymotion.com/sec(u0jljuz7LYYKNTAusZhSBtPjtGhMqTQk7tPxtNxUpNTv1P-AEM7xxL3c6l5k4oBH5GMNQaqbKAd0zHGe5TEf2w)/video/149/089/473980941_mp4_h264_aac_fhd.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

## Description

https://www.dailymotion.com/video/x7u7219

It's just for this video, other videos all work fine.

**Comment by PuppyPi** [comment] 2020-10-22 11:19
I'm running version 2020.09.20 and the same exact thing happens for me for these browser-playable videos:

https://www.dailymotion.com/video/xklb33
https://www.dailymotion.com/video/xklcyv
https://www.dailymotion.com/video/xklgty
https://www.dailymotion.com/video/xklgur
https://www.dailymotion.com/video/xklgxj

(But most videos from that very channel downloaded fine!)

**Comment by bersbersbers** [comment] 2020-11-22 08:29
I can repro the issue with the links above on `2020.11.21.1`. First analysis shows that videos play fine in browser, but let's look at them in detail.

1. https://www.dailymotion.com/video/x7u7219 autoplays in 720p quality, but not when you switch to 1080p quality:
> Sorry! An unexpected error has occured.

So the error is on the side of dailymotion for this video.

To fix it, download in 720p. First check the format names using `-F`, then download the best available one with `--format`:

```
>youtube-dl -F https://www.dailymotion.com/video/x7u7219
[dailymotion] Downloading Access Token
[dailymotion] x7u7219: Downloading media JSON metadata
[dailymotion] x7u7219: Downloading metadata JSON
[dailymotion] x7u7219: Downloading m3u8 information
[info] Available formats for x7u7219:
format code  extension  resolution note
hls-144-0    mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-144-1    mp4        192x112     105k , avc1.42000b, mp4a.40.5
http-144-0   mp4        192x112     105k , avc1.42000b, mp4a.40.5
http-144-1   mp4        192x112     105k , avc1.42000b, mp4a.40.5
hls-240-0    mp4        320x184     246k , avc1.4d000d, mp4a.40.5
hls-240-1    mp4        320x184     246k , avc1.4d000d, mp4a.40.5
http-240-0   mp4        320x184     246k , avc1.4d000d, mp4a.40.5
http-240-1   mp4        320x184     246k , avc1.4d000d, mp4a.40.5
hls-380-0    mp4        512x288     460k , avc1.4d0016, mp4a.40.5
hls-380-1    mp4        512x288     460k , avc1.4d0016, mp4a.40.5
http-380-0   mp4        512x288     460k , avc1.4d0016, mp4a.40.5
http-380-1   mp4        512x288     460k , avc1.4d0016, mp4a.40.5
hls-480-0    mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-480-1    mp4        848x480     836k , avc1.64001f, mp4a.40.2
http-480-0   mp4        848x480     836k , avc1.64001f, mp4a.40.2
http-480-1   mp4        848x480     836k , avc1.64001f, mp4a.40.2
hls-720-0    mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
hls-720-1    mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
http-720-0   mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
http-720-1   mp4        1280x720   2149k , avc1.64001f, mp4a.40.2
hls-1080-0   mp4        1920x1080  6221k , avc1.640028, mp4a.40.2
hls-1080-1   mp4        1920x1080  6221k , avc1.640028, mp4a.40.2
http-1080-0  mp4        1920x1080  6221k , avc1.640028, mp4a.40.2
http-1080-1  mp4        1920x1080  6221k , avc1.640028, mp4a.40.2 (best)

>youtube-dl --format http-720-0 https://www.dailymotion.com/video/x7u7219
[dailymotion] Downloading Access Token
[dailymotion] x7u7219: Downloading media JSON metadata
[dailymotion] x7u7219: Downloading metadata JSON
[dailymotion] x7u7219: Downloading m3u8 information
[download] Destination: 腾飞五千年之两晋南北朝 第二十三集 变态皇帝接二连三-x7u7219.mp4
[download]   1.4% of 285.70MiB at  5.45MiB/s ETA 00:51
```

2. Same thing for https://www.dailymotion.com/video/xklb33 and the other videos by @PuppyPi: autoplay in 480p, fail in 720p.

Fix:
```
>youtube-dl --format http-480-0 https://www.dailymotion.com/video/xklb33
[dailymotion] Downloading Access Token
[dailymotion] xklb33: Downloading media JSON metadata
[dailymotion] xklb33: Downloading metadata JSON
[dailymotion] xklb33: Downloading m3u8 information
[download] Destination: (Thermal Expansion, Calorimetry, Heat Transfer) - Thermal Expansion(Linear)-xklb33.mp4
[download]  35.0% of 5.72MiB at  4.44MiB/s ETA 00:00
```

**Comment by bersbersbers** [comment] 2020-11-22 08:31
What `youtube-dl` could do is to switch to another format when one is unavailable. So this looks like a duplicate of #3721.

**Comment by bersbersbers** [comment] 2020-11-22 08:48
Interestingly, dailymotion seems to offer each format several times, using separate mirrors I assume.

So for some videos (e.g., `x5luang`), you may find that `http-720-1` is not available, but `http-720-0` is. (This must be the case when the browser plays 720p.)

For other videos (e.g., `x5m3g74`), you may find that the 404 error appears mid-video, which may again be solved by choosing a different format for the same resolution. My guess is that you can even resume downloads started at one mirror with the data from a second mirror (if bitrate etc. is the same), but do verify that.

**Comment by PuppyPi** [comment] 2020-11-22 08:58
I can confirm exactly what bersbersbers said—I can download the videos now!
Two of them downloaded stochastically (xklgty and xklcyv) but the other
three never succeeded, despite several hundred (automated) attempts, but
using the --format selector for a 480 instead of any of the four 720's,
they downloaded immediately :)
Perhaps the reproducibility problem is that DailyMotion uses geoip on the
client's IP address and makes some formats completely unavailable by
cutting off all mirrors for it.  But that wouldn't explain why it's
stochastic.  Perhaps it's based on ping instead?

**Closed** 2020-11-22 12:40 UTC
Labels: duplicate
