### ISSUE TITLE
[bilibili] how to download a item in a list

### ISSUE THREAD

**Issue by Xueqc** [ytdl-org/youtube-dl#31217] opened 2022-09-01 12:38 UTC
## Checklist

- [ how to download:  https://www.bilibili.com/video/BV1V54y1B7K3?p=17] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by 89z** [comment] 2022-09-01 12:49
Here is clickable URL:

https://www.bilibili.com/video/BV1V54y1B7K3?p=17

**Comment by dirkf** [comment] 2022-09-01 13:21
`--playlist-items ...` [RTFM](https://github.com/ytdl-org/youtube-dl#user-content-video-selection)

**Comment by Vangelis66** [comment] 2022-09-02 01:37
... This is probably a duplicate of https://github.com/ytdl-org/youtube-dl/issues/31051 ...

Indeed, 
https://www.bilibili.com/video/BV1V54y1B7K3
is a playlist consisting of **18** items (parts), but when that URI is fed to `youtube-dl`, it is not treated as such: 
```cmd
youtube-dl -v -F "https://www.bilibili.com/video/BV1V54y1B7K3" => 

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bilibili.com/video/BV1V54y1B7K3']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2022.09.01.19419
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python version 3.4.4 (CPython) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BiliBili] 1V54y1B7K3: Downloading webpage
[BiliBili] 1V54y1B7K3: Downloading video info page
[info] Available formats for 1V54y1B7K3:
format code  extension  resolution note
0            flv        unknown    230.13MiB
```
and even when issuing
```
youtube-dl -v -F "https://www.bilibili.com/video/BV1V54y1B7K3?p=17"
```
or (as suggested)
```
youtube-dl -v -F "https://www.bilibili.com/video/BV1V54y1B7K3" --playlist-items 17
```
the outcome is identical: 
```cmd
[debug] Proxy map: {}
[BiliBili] 1V54y1B7K3: Downloading webpage
[BiliBili] 1V54y1B7K3: Downloading video info page
[info] Available formats for 1V54y1B7K3:
format code  extension  resolution note
0            flv        unknown    230.13MiB
```
According to testimony in #31051, I expect the 230MiB file to correspond to the **1st item** of that playlist (while OP wants **item/part 17**); out of curiosity, I DLed that file and it's a 1080p30 encode, with a duration of ca. 1h31m.

Contrast all the above with how (latest) `yt-dlp` handles those URIs: 
```cmd
yt-dlp "https://www.bilibili.com/video/BV1V54y1B7K3" --flat-playlist => 

BiliBili] 1V54y1B7K3: Grabbing original ID via API
BiliBili] 840983192: Downloading webpage
BiliBili] 840983192: Extracting videos in anthology
BiliBili] Downloading anthology 840983192 - add --no-playlist to just download video
download] Downloading playlist: ?????????? ?????? ?? ?????(???)
BiliBili] Playlist ?????????? ?????? ?? ?????(???): Downloading 18 videos of 18

download] Downloading video 1 of 18
download] Downloading video 2 of 18
download] Downloading video 3 of 18
download] Downloading video 4 of 18
download] Downloading video 5 of 18
download] Downloading video 6 of 18
download] Downloading video 7 of 18
download] Downloading video 8 of 18
download] Downloading video 9 of 18
download] Downloading video 10 of 18
download] Downloading video 11 of 18
download] Downloading video 12 of 18
download] Downloading video 13 of 18
download] Downloading video 14 of 18
download] Downloading video 15 of 18
download] Downloading video 16 of 18
download] Downloading video 17 of 18
download] Downloading video 18 of 18
download] Finished downloading playlist: ?????????? ?????? ?? ?????(???)
```
and 
```cmd
yt-dlp -v -F "https://www.bilibili.com/video/BV1V54y1B7K3?p=17" => 

[BiliBili] 1V54y1B7K3: Grabbing original ID via API
[BiliBili] 840983192: Downloading webpage
[BiliBili] 840983192: Extracting videos in anthology
[BiliBili] 840983192: Downloading tags
[info] Available formats for 840983192_part17:
ID EXT RESOLUTION |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR
------------------------------------------------------------------------------
0  m4a audio only | ~ 46.22MiB  67k https | audio only         mp4a.40.2   67k
1  m4a audio only | ~ 87.59MiB 127k https | audio only         mp4a.40.2  127k
2  m4a audio only | ~ 87.59MiB 127k https | audio only         mp4a.40.2  127k
3  mp4 640x360    | ~ 33.21MiB  48k https | av01.0.01M.08  48k video only
4  mp4 640x360    | ~ 36.15MiB  52k https | avc1.64001E    52k video only
5  mp4 852x480    | ~ 42.70MiB  62k https | av01.0.04M.08  62k video only
6  mp4 852x480    | ~ 49.83MiB  72k https | avc1.64001F    72k video only
7  mp4 1280x720   | ~ 67.65MiB  98k https | av01.0.05M.08  98k video only
8  mp4 1280x720   | ~ 82.54MiB 120k https | avc1.640028   120k video only
9  mp4 1920x1080  | ~109.79MiB 159k https | av01.0.08M.08 159k video only
10 mp4 1920x1080  | ~126.64MiB 184k https | avc1.640032   184k video only
```
or
```cmd
yt-dlp -F "https://www.bilibili.com/video/BV1V54y1B7K3" -I 17 => 

[BiliBili] 1V54y1B7K3: Grabbing original ID via API
[BiliBili] 840983192: Downloading webpage
[BiliBili] 840983192: Extracting videos in anthology
[BiliBili] Downloading anthology 840983192 - add --no-playlist to just download
video
[download] Downloading playlist: ?????????? ?????? ?? ?????(???)
[BiliBili] Playlist ?????????? ?????? ?? ?????(???): Downloading 1 videos
[download] Downloading video 1 of 1
[BiliBili] 1V54y1B7K3: Grabbing original ID via API
[BiliBili] 840983192: Downloading webpage
[BiliBili] 840983192: Extracting videos in anthology
[BiliBili] 840983192: Downloading tags
[info] Available formats for 840983192_part17:
ID EXT RESOLUTION |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR
------------------------------------------------------------------------------
0  m4a audio only | ~ 46.22MiB  67k https | audio only         mp4a.40.2   67k
1  m4a audio only | ~ 87.59MiB 127k https | audio only         mp4a.40.2  127k
2  m4a audio only | ~ 87.59MiB 127k https | audio only         mp4a.40.2  127k
3  mp4 640x360    | ~ 33.21MiB  48k https | av01.0.01M.08  48k video only
4  mp4 640x360    | ~ 36.15MiB  52k https | avc1.64001E    52k video only
5  mp4 852x480    | ~ 42.70MiB  62k https | av01.0.04M.08  62k video only
6  mp4 852x480    | ~ 49.83MiB  72k https | avc1.64001F    72k video only
7  mp4 1280x720   | ~ 67.65MiB  98k https | av01.0.05M.08  98k video only
8  mp4 1280x720   | ~ 82.54MiB 120k https | avc1.640028   120k video only
9  mp4 1920x1080  | ~109.79MiB 159k https | av01.0.08M.08 159k video only
10 mp4 1920x1080  | ~126.64MiB 184k https | avc1.640032   184k video only
[download] Finished downloading playlist: ?????????? ?????? ?? ?????(???)
```
I used `-f 10+2` to fetch item/part **17** (1080p30 encode again, ca. 1h34m) and it's different to the video file `yt-dl` fetched... 

So, unless I'm missing something obvious (I know it has happened before 😜 ), the answer to OP's question would be (i.e. if **I** were to supply it) that **it's impossible to download referenced video via** `youtube-dl` in its current state, because its `bilibiliIE` is not up to that task (requires an update) ...

**Comment by dirkf** [comment] 2022-09-02 13:57
yt-dlp works out that the page with ID 1V54y1B7K3 is actually 840983192; but that page also gets just the single 230MB flv.


Apparently a yt-dlp back-port would be good.

**Comment by dirkf** [comment] 2022-09-04 11:20
Duplicate of #30151.

**Closed by dirkf** 2022-09-04 11:20 UTC
Labels: question

**Comment by Vangelis66** [comment] 2022-09-04 15:28
> Duplicate of https://github.com/ytdl-org/youtube-dl/issues/30151.

Actually, as I wrote: 

> duplicate of https://github.com/ytdl-org/youtube-dl/issues/31051

😜
