### ISSUE TITLE
I request a re-publish of the latest version for pip, or just increase the version number and publish.

### ISSUE THREAD

**Issue by AntiMoron** [ytdl-org/youtube-dl#32686] opened 2024-01-09 09:36 UTC
## Verbose log

Provided in the follow section.

## Description

I think the **source code is not aligned** between binaries from homebrew(MacOS) and pip3.
Test command is as following:

```
youtube-dl -v  --skip-download --write-auto-sub --sub-lang=en -o test "https://www.youtube.com/watch?v=wAzYnx1J7YE"
```

Check the behavior:
![image](https://github.com/ytdl-org/youtube-dl/assets/6587734/2660336e-6122-44c4-9c36-ca3dfa3948a4)
Check the versions and envs:
![image](https://github.com/ytdl-org/youtube-dl/assets/6587734/6f38abb9-e12a-4529-a153-a2d4e2a889c6)
Check verbose logs:
![image](https://github.com/ytdl-org/youtube-dl/assets/6587734/68feba01-f575-44b9-a78b-633aba45c0f7)

# Verbose logs
Docker pip installed version:

```bash
root@help-desk-dev:/usr/local/bin# youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.2 (CPython) - Linux-5.15.0-1047-aws-x86_64-with-glibc2.36
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

MacOS homebrew version:

```bash
➜  ~ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 705d2564d
[debug] Python version 3.12.1 (CPython) - macOS-13.0-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'socks': 'http://127.0.0.1:7890'}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

> Also I've tried to run "pip installed" youtbe-dl in the same python version as that from homebrew (python 3.12) , it remains the same, so I'm quiet sure that the binary published to pip is somehow not correct.

**Comment by AntiMoron** [comment] 2024-01-09 09:47
Hi core members, please take some time reviewing this, this can be fixed within 5 minutes.

@dstftw @phihag

**Comment by dirkf** [comment] 2024-01-09 14:26
Review #30839.

The version in pypi is the [same as the official last release](https://github.com/ytdl-org/youtube-dl/issues/30837#issuecomment-1295842585), ie 2021.12.17.

You can install the nightly release use _pip_ or _pip3_. Suitable command lines are shown in the discussion of #31530, as linked from #32069.

Otherwise duplicate of #31585.

**Comment by AntiMoron** [comment] 2024-01-10 02:28
@dirkf First of all, thank you for being patiently maintaining such a great repo, most of the repos I proposed issues/merge requests they don't respond at all. 
Cut off the digression, I'm pretty sure I've read those threads before I submited this issue. I want to ask if it is possible that two same version's binaries from different package manager have different behaviors, because as you can see from above, I'm using ver. 2021.12.17 too. I'm willing to use the pip installed one, but the errors blocked my purpose of downloading some subtitles.

**Comment by ReenigneArcher** [comment] 2024-01-10 03:28
As a workaround you can install latest git version using pip.

`python -m pip install git+https://github.com/ytdl-org/youtube-dl.git`

OR if you don't have git

`python -m pip install https://github.com/ytdl-org/youtube-dl/archive/master.zip`

You can also put that in a requirements.txt file if needed.

```txt
git+https://github.com/ytdl-org/youtube-dl.git
```

But FYI, the version will be the "same" because it comes from here: https://github.com/ytdl-org/youtube-dl/blob/be008e657d79832642e2158557c899249c9e31cd/youtube_dl/version.py#L3

**Comment by dirkf** [comment] 2024-01-10 04:05
Or, as I suggested, install from the nightly repo, which will give you an accurate version display.

**Comment by AntiMoron** [comment] 2024-01-10 07:02
Get it, thanks folks. The workaround works.
---
If we can republish to have the latest accurate binary that'll solve issues like mine. For version is reflected by the code mentioned before, there're still possibilities that the code that turns error to warning were not merged before 2021.12.17 being published to pip.

**Comment by bashonly** [comment] 2024-01-10 17:15
Homebrew applies their own patch to youtube-dl resulting in the warning

**Comment by dirkf** [comment] 2024-01-11 00:08
Indeed, the issue from #31530 is only fixed in nightly versions, in the main repo or builds derived from it (such as the nightly versions), or where some other packager, such as Homebrew, has patched the 2021.12.17 version. Some older versions may not have the bug, but will fail in other ways, with YT or other sites.

**Closed by dirkf** 2024-01-11 00:08 UTC

**Comment by ArthurFerreiraRodrigues** [comment] 2024-11-23 22:02
> As a workaround you can install latest git version using pip.
> 
> `python -m pip install git+https://github.com/ytdl-org/youtube-dl.git`
> 
> OR if you don't have git
> 
> `python -m pip install https://github.com/ytdl-org/youtube-dl/archive/master.zip`
> 
> You can also put that in a requirements.txt file if needed.
> 
> ```
> git+https://github.com/ytdl-org/youtube-dl.git
> ```
> 
> But FYI, the version will be the "same" because it comes from here:
> 
> https://github.com/ytdl-org/youtube-dl/blob/be008e657d79832642e2158557c899249c9e31cd/youtube_dl/version.py#L3

Developers should add this to the README. Only instalation method that worked.

**Comment by dirkf** [comment] 2024-11-24 00:31
As mentioned several times before:

>You can install the nightly release use pip or pip3. Suitable command lines are shown in the discussion of #31530, as linked from #32069.

>Or, as I suggested, install from the nightly repo, which will give you an accurate version display.

Just change the URLs appropriately. The linked "suitable command lines" to change were later reposted above. Then this
>But FYI, the version will be the "same" because it comes from here:
...

is not a problem.
