### ISSUE TITLE
ABC TV Show - HTTP Error 400: Bad Request (caused by HTTPError())

### ISSUE THREAD

**Issue by SPDurkee** [ytdl-org/youtube-dl#15366] opened 2018-01-20 05:30 UTC
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ap-mso', 'TWC', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://abc.go.com/shows/american-housewife/episode-guide/season-02/2-boar-dain']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-89395-g71421f382f, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 2-boar-dain: Downloading webpage
[Go] VDKA4095507: Downloading JSON metadata
[Go] VDKA4095507: Downloading Provider Redirect Page
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 517, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Attempting to download "http://abc.go.com/shows/american-housewife/episode-guide/season-02/2-boar-dain" using valid TWC credentials that work for other videos.

**Comment by Rick7C2** [comment] 2018-01-27 15:57
I am having the same issue for every video I tried on abc.go.com

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ap-mso', u'TWC', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'http://abc.go.com/shows/scandal/episode-guide/season-07/9-good-people', u'--dump-json', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.12 (CPython) - Linux-3.10.102-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`

**Comment by SPDurkee** [comment] 2018-01-27 17:57
No, some videos work: http://abc.go.com/shows/child-support/episode-guide/season-01/2-episode-2

**Comment by Rick7C2** [comment] 2018-01-27 19:15
Ok, so maybe it only works for videos that don't need a cable sub login.

**Comment by Rick7C2** [comment] 2018-01-27 19:21
Confirmed. It's a problem with videos that need login --mso --ap-username --ap-password.

Non of those videos work.

Videos not requiring login work fine.

**Comment by Rick7C2** [comment] 2018-01-31 02:45
I would like to add that I am using TWC for mso just like OP. Could I get someone with a different provider to try?

Maybe it's TWC specific?

**Comment by remitamine** [comment] 2018-01-31 08:22
> Maybe it's TWC specific?

yes, it is.
```
python __main__.py --netrc --ap-mso DTV http://channel.nationalgeographic.com/videos/treasures-rediscovered/
[natgeo] treasures-rediscovered: Downloading webpage
[natgeo] Dx8qLlHX_Mto: Downloading Provider Redirect Page
[natgeo] Dx8qLlHX_Mto: Downloading Provider Login Page
[natgeo] Dx8qLlHX_Mto: Logging in
[natgeo] Dx8qLlHX_Mto: Confirming Login
[natgeo] Dx8qLlHX_Mto: Retrieving Session
[natgeo] Dx8qLlHX_Mto: Retrieving Authorization Token
[natgeo] Dx8qLlHX_Mto: Retrieving Media Token
[natgeo] Dx8qLlHX_Mto: Downloading http SMIL data
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Checking video URL
[natgeo] Dx8qLlHX_Mto: Downloading m3u SMIL data
[natgeo] Dx8qLlHX_Mto: Downloading m3u8 information
[natgeo] treasures-rediscovered: Downloading JSON metadata
[info] Writing video subtitles to: Treasures Rediscovered-Dx8qLlHX_Mto.un.scc
[info] Writing video subtitles to: Treasures Rediscovered-Dx8qLlHX_Mto.en.dfxp
[download] Destination: Treasures Rediscovered-Dx8qLlHX_Mto.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  837M    0 1261k    0     0  97037      0  2:30:49  0:00:13  2:30:36  178k
```

**Comment by Rick7C2** [comment] 2018-01-31 19:00
I think I may have found the problem but I don't know how to build youtube-dl from source to test.

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/adobepass.py

Line 43 to 46 are as follows...

```
    'TWC': {
        'name': 'Time Warner Cable | Spectrum',
        'username_field': 'Ecom_User_ID',
        'password_field': 'Ecom_Password',
```

Should be...

```
    'TWC': {
        'name': 'Time Warner Cable | Spectrum',
        'username_field': 'IDToken1',
        'password_field': 'IDToken2',
```

This will make TWC match Brighthouse and Charter_Direct which have all been merged to create Spectrum.

**Comment by Rick7C2** [comment] 2018-01-31 19:05
@SPDurkee @remitamine 

Just for shits and giggles I tried setting --ap-mso from TWC to Charter_Direct using my TWC login info since they have merged and it works!

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'http://abc.go.com/shows/scandal/episode-guide/season-07/9-good-people', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.12 (CPython) - Linux-3.10.102-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
[Go] 9-good-people: Downloading webpage
[Go] VDKA4261838: Downloading JSON metadata
[Go] VDKA4261838: Retrieving Media Token
[Go] VDKA4261838: Downloading JSON metadata
[Go] VDKA4261838: Downloading m3u8 information
[info] Available formats for VDKA4261838:
format code  extension  resolution note
ULNK-130     mp4        192x108     130k , avc1.42000b, 15.0fps, mp4a.40.5
ULNK-239     mp4        288x162     239k , avc1.42000c, 15.0fps, mp4a.40.5
ULNK-444     mp4        448x252     444k , avc1.420015, 30.0fps, mp4a.40.5
ULNK-754     mp4        768x432     754k , avc1.4d001e, 30.0fps, mp4a.40.5
ULNK-1199    mp4        992x558    1199k , avc1.4d001f, 30.0fps, mp4a.40.5
ULNK-1670    mp4        1056x594   1670k , avc1.4d001f, 30.0fps, mp4a.40.5
ULNK-2057    mp4        1088x612   2057k , avc1.4d001f, 30.0fps, mp4a.40.5
ULNK-2549    mp4        1152x648   2549k , avc1.4d001f, 30.0fps, mp4a.40.5
ULNK-3540    mp4        1280x720   3540k , avc1.64001f, 30.0fps, mp4a.40.5 (best)
```

**Closed** 2019-04-27 19:30 UTC
Labels: tv-provider-account-needed
