### ISSUE TITLE
Facebook extractor

### ISSUE THREAD

**Issue by WinterSunset95** [ytdl-org/youtube-dl#30650] opened 2022-02-19 19:04 UTC
## Checklist

- [✅] I'm reporting a broken site support issue
- [✅] I've verified that I'm running youtube-dl version **2021.12.17**
- [✅] I've checked that all provided URLs are alive and playable in a browser
- [✅] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✅] I've searched the bugtracker for similar bug reports including closed ones
- [✅] I've read bugs section in FAQ

## Verbose log

```
youtube-dl -F https://www.facebook.com/groups/3410798182373309/permalink/4917535238366255
[facebook] 4917535238366255: Downloading webpage
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.termux/files/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/__init__.py", line 475, in main
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2068, in download
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 680, in _real_extract
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 499, in _extract_from_url
  File "/data/data/com.termux/files/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 480, in parse_attachment
AttributeError: 'NoneType' object has no attribute 'get'
```

## Description

So far, I think this is the only problem I'm facing

**Comment by 89z** [comment] 2022-02-19 19:24
Do you have any other links, that arent blatant TikTok rips?

**Comment by dirkf** [comment] 2022-02-19 20:15
Duplicate of #30474.

@kikuyan left two PRs that I'll have to resuscitate and merge, which should fix this.

**Closed** 2022-02-20 08:13 UTC
Labels: duplicate
